erDiagram
    total ||--o{ opportunity : really
    total {
        DATE really
        TEXT break
        VARCHAR(50) do
    }
    opportunity ||--o{ peace : into
    opportunity {
        VARCHAR(50) into
        DATE evening
    }
    peace ||--o{ fear : food
    peace {
        DATE food
        TEXT door
        VARCHAR(50) policy
    }
    fear ||--o{ movie : president
    fear {
        VARCHAR(50) president
        DATE camera
    }
    movie ||--o{ customer : month
    movie {
        DATE month
        TEXT option
        VARCHAR(50) suggest
    }
    customer ||--o{ mind : news
    customer {
        VARCHAR(50) news
        DATE goal
    }
    mind ||--o{ stage : culture
    mind {
        DATE culture
        TEXT son
        VARCHAR(50) not
    }
    stage ||--o{ middle : enough
    stage {
        VARCHAR(50) enough
        DATE other
    }
    middle ||--o{ institution : likely
    middle {
        DATE likely
        TEXT letter
        VARCHAR(50) then
    }
    institution ||--o{ total : machine
    institution {
        VARCHAR(50) machine
        DATE fall
    }