erDiagram
    number ||--o{ threat : federal
    number {
        DATE federal
        TEXT without
        VARCHAR(50) even
    }
    threat ||--o{ ten : color
    threat {
        VARCHAR(50) color
        DATE lay
    }
    ten ||--o{ natural : relate
    ten {
        DATE relate
        TEXT wind
        VARCHAR(50) future
    }
    natural ||--o{ involve : may
    natural {
        VARCHAR(50) may
        DATE trouble
    }
    involve ||--o{ early : choose
    involve {
        DATE choose
        TEXT air
        VARCHAR(50) character
    }
    early ||--o{ perhaps : point
    early {
        VARCHAR(50) point
        DATE north
    }
    perhaps ||--o{ natural : early
    perhaps {
        DATE early
        TEXT until
        VARCHAR(50) prepare
    }
    natural ||--o{ myself : need
    natural {
        VARCHAR(50) need
        DATE do
    }
    myself ||--o{ TV : item
    myself {
        DATE item
        TEXT account
        VARCHAR(50) poor
    }
    TV ||--o{ number : painting
    TV {
        VARCHAR(50) painting
        DATE rate
    }