erDiagram
    about ||--o{ show : seven
    about {
        DATE seven
        TEXT fear
        VARCHAR(50) training
    }
    show ||--o{ involve : across
    show {
        VARCHAR(50) across
        DATE student
    }
    involve ||--o{ on : ever
    involve {
        DATE ever
        TEXT language
        VARCHAR(50) just
    }
    on ||--o{ evidence : point
    on {
        VARCHAR(50) point
        DATE serious
    }
    evidence ||--o{ leader : style
    evidence {
        DATE style
        TEXT throw
        VARCHAR(50) after
    }
    leader ||--o{ food : leader
    leader {
        VARCHAR(50) leader
        DATE him
    }
    food ||--o{ drug : artist
    food {
        DATE artist
        TEXT throughout
        VARCHAR(50) investment
    }
    drug ||--o{ school : order
    drug {
        VARCHAR(50) order
        DATE certain
    }
    school ||--o{ break : concern
    school {
        DATE concern
        TEXT leader
        VARCHAR(50) adult
    }
    break ||--o{ boy : two
    break {
        VARCHAR(50) two
        DATE physical
    }
    boy ||--o{ about : collection
    boy {
        DATE collection
        TEXT me
        VARCHAR(50) debate
    }