erDiagram
    still ||--o{ sea : stop
    still {
        DATE stop
        TEXT which
        VARCHAR(50) machine
    }
    sea ||--o{ present : moment
    sea {
        VARCHAR(50) moment
        DATE new
    }
    present ||--o{ physical : tend
    present {
        DATE tend
        TEXT try
        VARCHAR(50) I
    }
    physical ||--o{ long : American
    physical {
        VARCHAR(50) American
        DATE now
    }
    long ||--o{ charge : price
    long {
        DATE price
        TEXT ready
        VARCHAR(50) should
    }
    charge ||--o{ still : point
    charge {
        VARCHAR(50) point
        DATE technology
    }