erDiagram
    particularly ||--o{ opportunity : local
    particularly {
        DATE local
        TEXT expect
        VARCHAR(50) information
    }
    opportunity ||--o{ job : region
    opportunity {
        VARCHAR(50) region
        DATE know
    }
    job ||--o{ smile : tough
    job {
        DATE tough
        TEXT energy
        VARCHAR(50) call
    }
    smile ||--o{ government : meeting
    smile {
        VARCHAR(50) meeting
        DATE board
    }
    government ||--o{ day : way
    government {
        DATE way
        TEXT nature
        VARCHAR(50) mouth
    }
    day ||--o{ first : cup
    day {
        VARCHAR(50) cup
        DATE month
    }
    first ||--o{ during : significant
    first {
        DATE significant
        TEXT eye
        VARCHAR(50) expect
    }
    during ||--o{ but : finally
    during {
        VARCHAR(50) finally
        DATE across
    }
    but ||--o{ particularly : trouble
    but {
        DATE trouble
        TEXT Republican
        VARCHAR(50) certain
    }