erDiagram
    music ||--o{ ahead : central
    music {
        DATE central
        TEXT dog
        VARCHAR(50) dark
    }
    ahead ||--o{ either : color
    ahead {
        VARCHAR(50) color
        DATE statement
    }
    either ||--o{ note : another
    either {
        DATE another
        TEXT side
        VARCHAR(50) too
    }
    note ||--o{ sure : woman
    note {
        VARCHAR(50) woman
        DATE think
    }
    sure ||--o{ per : area
    sure {
        DATE area
        TEXT final
        VARCHAR(50) write
    }
    per ||--o{ energy : want
    per {
        VARCHAR(50) want
        DATE car
    }
    energy ||--o{ drug : them
    energy {
        DATE them
        TEXT as
        VARCHAR(50) daughter
    }
    drug ||--o{ Democrat : opportunity
    drug {
        VARCHAR(50) opportunity
        DATE professor
    }
    Democrat ||--o{ music : agent
    Democrat {
        DATE agent
        TEXT standard
        VARCHAR(50) color
    }