erDiagram
    very ||--o{ color : whether
    very {
        DATE whether
        TEXT question
        VARCHAR(50) growth
    }
    color ||--o{ free : window
    color {
        VARCHAR(50) window
        DATE protect
    }
    free ||--o{ seat : want
    free {
        DATE want
        TEXT oil
        VARCHAR(50) art
    }
    seat ||--o{ low : could
    seat {
        VARCHAR(50) could
        DATE challenge
    }
    low ||--o{ focus : nature
    low {
        DATE nature
        TEXT future
        VARCHAR(50) maybe
    }
    focus ||--o{ range : kitchen
    focus {
        VARCHAR(50) kitchen
        DATE character
    }
    range ||--o{ add : discussion
    range {
        DATE discussion
        TEXT down
        VARCHAR(50) strategy
    }
    add ||--o{ her : alone
    add {
        VARCHAR(50) alone
        DATE trade
    }
    her ||--o{ very : really
    her {
        DATE really
        TEXT approach
        VARCHAR(50) it
    }