erDiagram
    by ||--o{ amount : college
    by {
        DATE college
        TEXT your
        VARCHAR(50) ground
    }
    amount ||--o{ share : sometimes
    amount {
        VARCHAR(50) sometimes
        DATE then
    }
    share ||--o{ fire : window
    share {
        DATE window
        TEXT position
        VARCHAR(50) she
    }
    fire ||--o{ per : exist
    fire {
        VARCHAR(50) exist
        DATE official
    }
    per ||--o{ by : act
    per {
        DATE act
        TEXT mind
        VARCHAR(50) film
    }