erDiagram
    response ||--o{ act : far
    response {
        DATE far
        TEXT source
        VARCHAR(50) social
    }
    act ||--o{ hair : feeling
    act {
        VARCHAR(50) feeling
        DATE assume
    }
    hair ||--o{ someone : quite
    hair {
        DATE quite
        TEXT project
        VARCHAR(50) cost
    }
    someone ||--o{ thus : their
    someone {
        VARCHAR(50) their
        DATE expert
    }
    thus ||--o{ pressure : see
    thus {
        DATE see
        TEXT wear
        VARCHAR(50) fight
    }
    pressure ||--o{ short : than
    pressure {
        VARCHAR(50) than
        DATE control
    }
    short ||--o{ subject : sister
    short {
        DATE sister
        TEXT fill
        VARCHAR(50) fish
    }
    subject ||--o{ response : culture
    subject {
        VARCHAR(50) culture
        DATE capital
    }