erDiagram
    how ||--o{ structure : loss
    how {
        DATE loss
        TEXT agent
        VARCHAR(50) very
    }
    structure ||--o{ laugh : religious
    structure {
        VARCHAR(50) religious
        DATE since
    }
    laugh ||--o{ fine : see
    laugh {
        DATE see
        TEXT without
        VARCHAR(50) culture
    }
    fine ||--o{ special : common
    fine {
        VARCHAR(50) common
        DATE knowledge
    }
    special ||--o{ wish : operation
    special {
        DATE operation
        TEXT hour
        VARCHAR(50) our
    }
    wish ||--o{ dog : put
    wish {
        VARCHAR(50) put
        DATE responsibility
    }
    dog ||--o{ serious : character
    dog {
        DATE character
        TEXT wait
        VARCHAR(50) gun
    }
    serious ||--o{ follow : degree
    serious {
        VARCHAR(50) degree
        DATE member
    }
    follow ||--o{ history : per
    follow {
        DATE per
        TEXT from
        VARCHAR(50) thought
    }
    history ||--o{ task : sense
    history {
        VARCHAR(50) sense
        DATE space
    }
    task ||--o{ score : sense
    task {
        DATE sense
        TEXT else
        VARCHAR(50) only
    }
    score ||--o{ how : body
    score {
        VARCHAR(50) body
        DATE my
    }