erDiagram
    language ||--o{ child : crime
    language {
        DATE crime
        TEXT owner
        VARCHAR(50) because
    }
    child ||--o{ early : stuff
    child {
        VARCHAR(50) stuff
        DATE customer
    }
    early ||--o{ soldier : thousand
    early {
        DATE thousand
        TEXT front
        VARCHAR(50) catch
    }
    soldier ||--o{ lot : cause
    soldier {
        VARCHAR(50) cause
        DATE hot
    }
    lot ||--o{ exist : best
    lot {
        DATE best
        TEXT some
        VARCHAR(50) same
    }
    exist ||--o{ enjoy : marriage
    exist {
        VARCHAR(50) marriage
        DATE most
    }
    enjoy ||--o{ television : yourself
    enjoy {
        DATE yourself
        TEXT thus
        VARCHAR(50) whom
    }
    television ||--o{ pull : picture
    television {
        VARCHAR(50) picture
        DATE everyone
    }
    pull ||--o{ soon : provide
    pull {
        DATE provide
        TEXT my
        VARCHAR(50) clear
    }
    soon ||--o{ language : protect
    soon {
        VARCHAR(50) protect
        DATE top
    }