erDiagram
    billion ||--o{ discussion : sense
    billion {
        DATE sense
        TEXT trial
        VARCHAR(50) financial
    }
    discussion ||--o{ lot : beautiful
    discussion {
        VARCHAR(50) beautiful
        DATE mind
    }
    lot ||--o{ seat : blood
    lot {
        DATE blood
        TEXT son
        VARCHAR(50) market
    }
    seat ||--o{ wonder : moment
    seat {
        VARCHAR(50) moment
        DATE though
    }
    wonder ||--o{ skill : remain
    wonder {
        DATE remain
        TEXT seat
        VARCHAR(50) sell
    }
    skill ||--o{ significant : sense
    skill {
        VARCHAR(50) sense
        DATE decade
    }
    significant ||--o{ several : as
    significant {
        DATE as
        TEXT get
        VARCHAR(50) card
    }
    several ||--o{ his : well
    several {
        VARCHAR(50) well
        DATE movie
    }
    his ||--o{ far : hair
    his {
        DATE hair
        TEXT scientist
        VARCHAR(50) former
    }
    far ||--o{ network : land
    far {
        VARCHAR(50) land
        DATE treatment
    }
    network ||--o{ billion : discover
    network {
        DATE discover
        TEXT small
        VARCHAR(50) allow
    }