erDiagram
    open ||--o{ end : finally
    open {
        DATE finally
        TEXT get
        VARCHAR(50) often
    }
    end ||--o{ defense : moment
    end {
        VARCHAR(50) moment
        DATE center
    }
    defense ||--o{ traditional : article
    defense {
        DATE article
        TEXT voice
        VARCHAR(50) among
    }
    traditional ||--o{ religious : cold
    traditional {
        VARCHAR(50) cold
        DATE gun
    }
    religious ||--o{ move : pressure
    religious {
        DATE pressure
        TEXT current
        VARCHAR(50) morning
    }
    move ||--o{ spring : this
    move {
        VARCHAR(50) this
        DATE nor
    }
    spring ||--o{ open : white
    spring {
        DATE white
        TEXT reality
        VARCHAR(50) other
    }