erDiagram
    article ||--o{ open : rule
    article {
        DATE rule
        TEXT happy
        VARCHAR(50) may
    }
    open ||--o{ fill : cut
    open {
        VARCHAR(50) cut
        DATE music
    }
    fill ||--o{ sell : budget
    fill {
        DATE budget
        TEXT social
        VARCHAR(50) pick
    }
    sell ||--o{ participant : artist
    sell {
        VARCHAR(50) artist
        DATE two
    }
    participant ||--o{ article : while
    participant {
        DATE while
        TEXT outside
        VARCHAR(50) month
    }