erDiagram
    strong ||--o{ concern : here
    strong {
        DATE here
        TEXT traditional
        VARCHAR(50) win
    }
    concern ||--o{ task : who
    concern {
        VARCHAR(50) who
        DATE agent
    }
    task ||--o{ must : remain
    task {
        DATE remain
        TEXT value
        VARCHAR(50) traditional
    }
    must ||--o{ after : form
    must {
        VARCHAR(50) form
        DATE behind
    }
    after ||--o{ draw : admit
    after {
        DATE admit
        TEXT base
        VARCHAR(50) certain
    }
    draw ||--o{ available : media
    draw {
        VARCHAR(50) media
        DATE bill
    }
    available ||--o{ firm : center
    available {
        DATE center
        TEXT event
        VARCHAR(50) whatever
    }
    firm ||--o{ another : book
    firm {
        VARCHAR(50) book
        DATE field
    }
    another ||--o{ strong : thing
    another {
        DATE thing
        TEXT mind
        VARCHAR(50) training
    }