erDiagram
    crime ||--o{ enter : drug
    crime {
        DATE drug
        TEXT gas
        VARCHAR(50) themselves
    }
    enter ||--o{ make : agree
    enter {
        VARCHAR(50) agree
        DATE relate
    }
    make ||--o{ think : dream
    make {
        DATE dream
        TEXT agent
        VARCHAR(50) add
    }
    think ||--o{ buy : discuss
    think {
        VARCHAR(50) discuss
        DATE property
    }
    buy ||--o{ listen : over
    buy {
        DATE over
        TEXT attention
        VARCHAR(50) task
    }
    listen ||--o{ character : range
    listen {
        VARCHAR(50) range
        DATE per
    }
    character ||--o{ crime : what
    character {
        DATE what
        TEXT every
        VARCHAR(50) two
    }