erDiagram
    about ||--o{ country : heart
    about {
        DATE heart
        TEXT feel
        VARCHAR(50) attention
    }
    country ||--o{ church : baby
    country {
        VARCHAR(50) baby
        DATE price
    }
    church ||--o{ hotel : whom
    church {
        DATE whom
        TEXT war
        VARCHAR(50) wear
    }
    hotel ||--o{ forget : purpose
    hotel {
        VARCHAR(50) purpose
        DATE set
    }
    forget ||--o{ throw : probably
    forget {
        DATE probably
        TEXT source
        VARCHAR(50) religious
    }
    throw ||--o{ system : us
    throw {
        VARCHAR(50) us
        DATE method
    }
    system ||--o{ blood : final
    system {
        DATE final
        TEXT relationship
        VARCHAR(50) market
    }
    blood ||--o{ be : sister
    blood {
        VARCHAR(50) sister
        DATE fire
    }
    be ||--o{ us : tonight
    be {
        DATE tonight
        TEXT understand
        VARCHAR(50) else
    }
    us ||--o{ man : measure
    us {
        VARCHAR(50) measure
        DATE bill
    }
    man ||--o{ about : arrive
    man {
        DATE arrive
        TEXT adult
        VARCHAR(50) represent
    }