erDiagram
    century ||--o{ might : worry
    century {
        DATE worry
        TEXT reality
        VARCHAR(50) avoid
    }
    might ||--o{ customer : economic
    might {
        VARCHAR(50) economic
        DATE city
    }
    customer ||--o{ task : situation
    customer {
        DATE situation
        TEXT begin
        VARCHAR(50) just
    }
    task ||--o{ that : coach
    task {
        VARCHAR(50) coach
        DATE political
    }
    that ||--o{ table : science
    that {
        DATE science
        TEXT national
        VARCHAR(50) quite
    }
    table ||--o{ since : various
    table {
        VARCHAR(50) various
        DATE particular
    }
    since ||--o{ win : want
    since {
        DATE want
        TEXT pay
        VARCHAR(50) PM
    }
    win ||--o{ human : nothing
    win {
        VARCHAR(50) nothing
        DATE that
    }
    human ||--o{ collection : involve
    human {
        DATE involve
        TEXT plan
        VARCHAR(50) assume
    }
    collection ||--o{ cold : TV
    collection {
        VARCHAR(50) TV
        DATE right
    }
    cold ||--o{ building : toward
    cold {
        DATE toward
        TEXT record
        VARCHAR(50) indicate
    }
    building ||--o{ century : political
    building {
        VARCHAR(50) political
        DATE turn
    }