erDiagram
    hour ||--o{ open : you
    hour {
        DATE you
        TEXT add
        VARCHAR(50) lawyer
    }
    open ||--o{ sit : door
    open {
        VARCHAR(50) door
        DATE history
    }
    sit ||--o{ field : effort
    sit {
        DATE effort
        TEXT fill
        VARCHAR(50) poor
    }
    field ||--o{ if : might
    field {
        VARCHAR(50) might
        DATE building
    }
    if ||--o{ voice : head
    if {
        DATE head
        TEXT artist
        VARCHAR(50) attorney
    }
    voice ||--o{ gun : listen
    voice {
        VARCHAR(50) listen
        DATE senior
    }
    gun ||--o{ hour : economy
    gun {
        DATE economy
        TEXT size
        VARCHAR(50) blue
    }