erDiagram
    possible ||--o{ responsibility : east
    possible {
        DATE east
        TEXT drug
        VARCHAR(50) safe
    }
    responsibility ||--o{ glass : bit
    responsibility {
        VARCHAR(50) bit
        DATE tough
    }
    glass ||--o{ drive : weight
    glass {
        DATE weight
        TEXT glass
        VARCHAR(50) future
    }
    drive ||--o{ art : reflect
    drive {
        VARCHAR(50) reflect
        DATE interview
    }
    art ||--o{ lot : all
    art {
        DATE all
        TEXT information
        VARCHAR(50) participant
    }
    lot ||--o{ red : everybody
    lot {
        VARCHAR(50) everybody
        DATE deep
    }
    red ||--o{ soon : evening
    red {
        DATE evening
        TEXT almost
        VARCHAR(50) develop
    }
    soon ||--o{ culture : four
    soon {
        VARCHAR(50) four
        DATE employee
    }
    culture ||--o{ couple : study
    culture {
        DATE study
        TEXT game
        VARCHAR(50) understand
    }
    couple ||--o{ social : their
    couple {
        VARCHAR(50) their
        DATE statement
    }
    social ||--o{ run : occur
    social {
        DATE occur
        TEXT school
        VARCHAR(50) then
    }
    run ||--o{ possible : watch
    run {
        VARCHAR(50) watch
        DATE court
    }