erDiagram
    hair ||--o{ nearly : apply
    hair {
        DATE apply
        TEXT success
        VARCHAR(50) public
    }
    nearly ||--o{ score : appear
    nearly {
        VARCHAR(50) appear
        DATE them
    }
    score ||--o{ fast : reason
    score {
        DATE reason
        TEXT director
        VARCHAR(50) back
    }
    fast ||--o{ professional : morning
    fast {
        VARCHAR(50) morning
        DATE vote
    }
    professional ||--o{ public : former
    professional {
        DATE former
        TEXT well
        VARCHAR(50) artist
    }
    public ||--o{ no : lay
    public {
        VARCHAR(50) lay
        DATE picture
    }
    no ||--o{ industry : tree
    no {
        DATE tree
        TEXT leg
        VARCHAR(50) man
    }
    industry ||--o{ decision : treatment
    industry {
        VARCHAR(50) treatment
        DATE civil
    }
    decision ||--o{ report : despite
    decision {
        DATE despite
        TEXT including
        VARCHAR(50) draw
    }
    report ||--o{ behavior : data
    report {
        VARCHAR(50) data
        DATE return
    }
    behavior ||--o{ hair : still
    behavior {
        DATE still
        TEXT song
        VARCHAR(50) even
    }