erDiagram
    wrong ||--o{ sister : religious
    wrong {
        DATE religious
        TEXT quite
        VARCHAR(50) article
    }
    sister ||--o{ radio : always
    sister {
        VARCHAR(50) always
        DATE born
    }
    radio ||--o{ food : report
    radio {
        DATE report
        TEXT remember
        VARCHAR(50) significant
    }
    food ||--o{ center : see
    food {
        VARCHAR(50) see
        DATE toward
    }
    center ||--o{ material : ask
    center {
        DATE ask
        TEXT apply
        VARCHAR(50) kind
    }
    material ||--o{ director : goal
    material {
        VARCHAR(50) goal
        DATE fight
    }
    director ||--o{ explain : shake
    director {
        DATE shake
        TEXT rock
        VARCHAR(50) as
    }
    explain ||--o{ add : part
    explain {
        VARCHAR(50) part
        DATE light
    }
    add ||--o{ trouble : charge
    add {
        DATE charge
        TEXT common
        VARCHAR(50) throughout
    }
    trouble ||--o{ able : minute
    trouble {
        VARCHAR(50) minute
        DATE know
    }
    able ||--o{ wrong : we
    able {
        DATE we
        TEXT identify
        VARCHAR(50) plan
    }