erDiagram
    first ||--o{ assume : sound
    first {
        DATE sound
        TEXT especially
        VARCHAR(50) someone
    }
    assume ||--o{ your : mouth
    assume {
        VARCHAR(50) mouth
        DATE poor
    }
    your ||--o{ one : reveal
    your {
        DATE reveal
        TEXT near
        VARCHAR(50) soldier
    }
    one ||--o{ clearly : make
    one {
        VARCHAR(50) make
        DATE way
    }
    clearly ||--o{ international : long
    clearly {
        DATE long
        TEXT window
        VARCHAR(50) eight
    }
    international ||--o{ pick : face
    international {
        VARCHAR(50) face
        DATE opportunity
    }
    pick ||--o{ development : worry
    pick {
        DATE worry
        TEXT allow
        VARCHAR(50) prevent
    }
    development ||--o{ amount : late
    development {
        VARCHAR(50) late
        DATE worry
    }
    amount ||--o{ community : debate
    amount {
        DATE debate
        TEXT white
        VARCHAR(50) team
    }
    community ||--o{ office : affect
    community {
        VARCHAR(50) affect
        DATE open
    }
    office ||--o{ first : sing
    office {
        DATE sing
        TEXT usually
        VARCHAR(50) idea
    }