erDiagram
    public ||--o{ half : record
    public {
        DATE record
        TEXT pass
        VARCHAR(50) table
    }
    half ||--o{ finish : big
    half {
        VARCHAR(50) big
        DATE think
    }
    finish ||--o{ upon : religious
    finish {
        DATE religious
        TEXT yes
        VARCHAR(50) million
    }
    upon ||--o{ memory : message
    upon {
        VARCHAR(50) message
        DATE what
    }
    memory ||--o{ for : data
    memory {
        DATE data
        TEXT investment
        VARCHAR(50) sing
    }
    for ||--o{ two : term
    for {
        VARCHAR(50) term
        DATE wrong
    }
    two ||--o{ idea : brother
    two {
        DATE brother
        TEXT campaign
        VARCHAR(50) glass
    }
    idea ||--o{ late : similar
    idea {
        VARCHAR(50) similar
        DATE job
    }
    late ||--o{ door : present
    late {
        DATE present
        TEXT production
        VARCHAR(50) billion
    }
    door ||--o{ public : anything
    door {
        VARCHAR(50) anything
        DATE list
    }