erDiagram
    tough ||--o{ think : up
    tough {
        DATE up
        TEXT week
        VARCHAR(50) agreement
    }
    think ||--o{ idea : over
    think {
        VARCHAR(50) over
        DATE respond
    }
    idea ||--o{ special : Democrat
    idea {
        DATE Democrat
        TEXT structure
        VARCHAR(50) common
    }
    special ||--o{ several : how
    special {
        VARCHAR(50) how
        DATE common
    }
    several ||--o{ major : community
    several {
        DATE community
        TEXT popular
        VARCHAR(50) agent
    }
    major ||--o{ return : history
    major {
        VARCHAR(50) history
        DATE operation
    }
    return ||--o{ tough : cause
    return {
        DATE cause
        TEXT eight
        VARCHAR(50) manager
    }