erDiagram
    majority ||--o{ ahead : particular
    majority {
        DATE particular
        TEXT before
        VARCHAR(50) long
    }
    ahead ||--o{ worker : role
    ahead {
        VARCHAR(50) role
        DATE laugh
    }
    worker ||--o{ above : include
    worker {
        DATE include
        TEXT decade
        VARCHAR(50) little
    }
    above ||--o{ teacher : information
    above {
        VARCHAR(50) information
        DATE election
    }
    teacher ||--o{ majority : strategy
    teacher {
        DATE strategy
        TEXT reach
        VARCHAR(50) people
    }