erDiagram
    inside ||--o{ heavy : customer
    inside {
        DATE customer
        TEXT six
        VARCHAR(50) energy
    }
    heavy ||--o{ plan : than
    heavy {
        VARCHAR(50) than
        DATE right
    }
    plan ||--o{ report : compare
    plan {
        DATE compare
        TEXT data
        VARCHAR(50) staff
    }
    report ||--o{ section : paper
    report {
        VARCHAR(50) paper
        DATE finally
    }
    section ||--o{ coach : pressure
    section {
        DATE pressure
        TEXT step
        VARCHAR(50) prove
    }
    coach ||--o{ perform : fact
    coach {
        VARCHAR(50) fact
        DATE market
    }
    perform ||--o{ inside : campaign
    perform {
        DATE campaign
        TEXT likely
        VARCHAR(50) event
    }