erDiagram
    new ||--o{ note : author
    new {
        DATE author
        TEXT return
        VARCHAR(50) tell
    }
    note ||--o{ brother : former
    note {
        VARCHAR(50) former
        DATE door
    }
    brother ||--o{ media : over
    brother {
        DATE over
        TEXT against
        VARCHAR(50) other
    }
    media ||--o{ thus : our
    media {
        VARCHAR(50) our
        DATE song
    }
    thus ||--o{ seem : off
    thus {
        DATE off
        TEXT property
        VARCHAR(50) pick
    }
    seem ||--o{ new : smile
    seem {
        VARCHAR(50) smile
        DATE tax
    }