erDiagram
    theory ||--o{ cut : arrive
    theory {
        DATE arrive
        TEXT mind
        VARCHAR(50) ground
    }
    cut ||--o{ collection : add
    cut {
        VARCHAR(50) add
        DATE law
    }
    collection ||--o{ fight : open
    collection {
        DATE open
        TEXT kid
        VARCHAR(50) teach
    }
    fight ||--o{ budget : easy
    fight {
        VARCHAR(50) easy
        DATE us
    }
    budget ||--o{ theory : energy
    budget {
        DATE energy
        TEXT arrive
        VARCHAR(50) among
    }