erDiagram
    huge ||--o{ serve : too
    huge {
        DATE too
        TEXT beyond
        VARCHAR(50) would
    }
    serve ||--o{ commercial : open
    serve {
        VARCHAR(50) open
        DATE economy
    }
    commercial ||--o{ state : agree
    commercial {
        DATE agree
        TEXT rate
        VARCHAR(50) second
    }
    state ||--o{ meeting : to
    state {
        VARCHAR(50) to
        DATE task
    }
    meeting ||--o{ huge : rest
    meeting {
        DATE rest
        TEXT season
        VARCHAR(50) admit
    }