erDiagram
    other ||--o{ theory : economic
    other {
        DATE economic
        TEXT beat
        VARCHAR(50) consider
    }
    theory ||--o{ situation : modern
    theory {
        VARCHAR(50) modern
        DATE food
    }
    situation ||--o{ letter : exist
    situation {
        DATE exist
        TEXT significant
        VARCHAR(50) either
    }
    letter ||--o{ shake : central
    letter {
        VARCHAR(50) central
        DATE their
    }
    shake ||--o{ boy : through
    shake {
        DATE through
        TEXT reduce
        VARCHAR(50) PM
    }
    boy ||--o{ other : easy
    boy {
        VARCHAR(50) easy
        DATE house
    }