erDiagram
    store ||--o{ remember : about
    store {
        DATE about
        TEXT mother
        VARCHAR(50) letter
    }
    remember ||--o{ fine : situation
    remember {
        VARCHAR(50) situation
        DATE skin
    }
    fine ||--o{ certain : cultural
    fine {
        DATE cultural
        TEXT face
        VARCHAR(50) every
    }
    certain ||--o{ answer : per
    certain {
        VARCHAR(50) per
        DATE attack
    }
    answer ||--o{ century : design
    answer {
        DATE design
        TEXT official
        VARCHAR(50) kind
    }
    century ||--o{ police : place
    century {
        VARCHAR(50) place
        DATE network
    }
    police ||--o{ arm : impact
    police {
        DATE impact
        TEXT although
        VARCHAR(50) father
    }
    arm ||--o{ professor : toward
    arm {
        VARCHAR(50) toward
        DATE four
    }
    professor ||--o{ store : region
    professor {
        DATE region
        TEXT meeting
        VARCHAR(50) agent
    }