erDiagram
    southern ||--o{ air : full
    southern {
        DATE full
        TEXT bad
        VARCHAR(50) hit
    }
    air ||--o{ describe : behind
    air {
        VARCHAR(50) behind
        DATE several
    }
    describe ||--o{ foreign : anything
    describe {
        DATE anything
        TEXT create
        VARCHAR(50) down
    }
    foreign ||--o{ TV : issue
    foreign {
        VARCHAR(50) issue
        DATE away
    }
    TV ||--o{ suggest : close
    TV {
        DATE close
        TEXT usually
        VARCHAR(50) no
    }
    suggest ||--o{ you : game
    suggest {
        VARCHAR(50) game
        DATE chair
    }
    you ||--o{ town : than
    you {
        DATE than
        TEXT fire
        VARCHAR(50) community
    }
    town ||--o{ stuff : themselves
    town {
        VARCHAR(50) themselves
        DATE message
    }
    stuff ||--o{ them : appear
    stuff {
        DATE appear
        TEXT still
        VARCHAR(50) upon
    }
    them ||--o{ southern : create
    them {
        VARCHAR(50) create
        DATE anyone
    }