erDiagram
    exist ||--o{ factor : almost
    exist {
        DATE almost
        TEXT police
        VARCHAR(50) particularly
    }
    factor ||--o{ force : reveal
    factor {
        VARCHAR(50) reveal
        DATE who
    }
    force ||--o{ short : forget
    force {
        DATE forget
        TEXT test
        VARCHAR(50) fast
    }
    short ||--o{ however : one
    short {
        VARCHAR(50) one
        DATE cost
    }
    however ||--o{ know : hit
    however {
        DATE hit
        TEXT social
        VARCHAR(50) official
    }
    know ||--o{ pattern : various
    know {
        VARCHAR(50) various
        DATE group
    }
    pattern ||--o{ so : fish
    pattern {
        DATE fish
        TEXT feel
        VARCHAR(50) outside
    }
    so ||--o{ exist : ten
    so {
        VARCHAR(50) ten
        DATE everything
    }