erDiagram
    paper ||--o{ class : right
    paper {
        DATE right
        TEXT simple
        VARCHAR(50) wonder
    }
    class ||--o{ too : board
    class {
        VARCHAR(50) board
        DATE lot
    }
    too ||--o{ impact : now
    too {
        DATE now
        TEXT think
        VARCHAR(50) day
    }
    impact ||--o{ fight : take
    impact {
        VARCHAR(50) take
        DATE senior
    }
    fight ||--o{ during : about
    fight {
        DATE about
        TEXT authority
        VARCHAR(50) still
    }
    during ||--o{ much : political
    during {
        VARCHAR(50) political
        DATE which
    }
    much ||--o{ current : experience
    much {
        DATE experience
        TEXT others
        VARCHAR(50) contain
    }
    current ||--o{ paper : quickly
    current {
        VARCHAR(50) quickly
        DATE there
    }