erDiagram
    attorney ||--o{ perhaps : word
    attorney {
        DATE word
        TEXT nation
        VARCHAR(50) sure
    }
    perhaps ||--o{ PM : poor
    perhaps {
        VARCHAR(50) poor
        DATE time
    }
    PM ||--o{ safe : thing
    PM {
        DATE thing
        TEXT suddenly
        VARCHAR(50) wait
    }
    safe ||--o{ western : church
    safe {
        VARCHAR(50) church
        DATE sport
    }
    western ||--o{ attorney : tend
    western {
        DATE tend
        TEXT few
        VARCHAR(50) choice
    }