erDiagram
    old ||--o{ address : least
    old {
        DATE least
        TEXT western
        VARCHAR(50) three
    }
    address ||--o{ project : federal
    address {
        VARCHAR(50) federal
        DATE quality
    }
    project ||--o{ health : take
    project {
        DATE take
        TEXT maybe
        VARCHAR(50) very
    }
    health ||--o{ tell : operation
    health {
        VARCHAR(50) operation
        DATE former
    }
    tell ||--o{ time : remain
    tell {
        DATE remain
        TEXT themselves
        VARCHAR(50) American
    }
    time ||--o{ strategy : above
    time {
        VARCHAR(50) above
        DATE may
    }
    strategy ||--o{ old : best
    strategy {
        DATE best
        TEXT occur
        VARCHAR(50) price
    }