erDiagram
    relate ||--o{ per : staff
    relate {
        DATE staff
        TEXT miss
        VARCHAR(50) describe
    }
    per ||--o{ nation : reach
    per {
        VARCHAR(50) reach
        DATE its
    }
    nation ||--o{ Democrat : light
    nation {
        DATE light
        TEXT similar
        VARCHAR(50) eye
    }
    Democrat ||--o{ though : student
    Democrat {
        VARCHAR(50) student
        DATE media
    }
    though ||--o{ right : maintain
    though {
        DATE maintain
        TEXT any
        VARCHAR(50) dinner
    }
    right ||--o{ scene : few
    right {
        VARCHAR(50) few
        DATE after
    }
    scene ||--o{ during : fill
    scene {
        DATE fill
        TEXT produce
        VARCHAR(50) art
    }
    during ||--o{ do : message
    during {
        VARCHAR(50) message
        DATE mind
    }
    do ||--o{ a : forget
    do {
        DATE forget
        TEXT process
        VARCHAR(50) article
    }
    a ||--o{ relate : buy
    a {
        VARCHAR(50) buy
        DATE eye
    }