erDiagram
    seven ||--o{ science : ability
    seven {
        DATE ability
        TEXT decade
        VARCHAR(50) social
    }
    science ||--o{ blood : task
    science {
        VARCHAR(50) task
        DATE play
    }
    blood ||--o{ would : thousand
    blood {
        DATE thousand
        TEXT let
        VARCHAR(50) take
    }
    would ||--o{ wall : manager
    would {
        VARCHAR(50) manager
        DATE security
    }
    wall ||--o{ physical : section
    wall {
        DATE section
        TEXT safe
        VARCHAR(50) experience
    }
    physical ||--o{ usually : skill
    physical {
        VARCHAR(50) skill
        DATE move
    }
    usually ||--o{ necessary : compare
    usually {
        DATE compare
        TEXT rest
        VARCHAR(50) standard
    }
    necessary ||--o{ degree : job
    necessary {
        VARCHAR(50) job
        DATE herself
    }
    degree ||--o{ specific : player
    degree {
        DATE player
        TEXT major
        VARCHAR(50) once
    }
    specific ||--o{ wear : box
    specific {
        VARCHAR(50) box
        DATE only
    }
    wear ||--o{ seven : ball
    wear {
        DATE ball
        TEXT language
        VARCHAR(50) class
    }