erDiagram
    seem ||--o{ attack : and
    seem {
        DATE and
        TEXT home
        VARCHAR(50) series
    }
    attack ||--o{ get : population
    attack {
        VARCHAR(50) population
        DATE south
    }
    get ||--o{ might : area
    get {
        DATE area
        TEXT size
        VARCHAR(50) many
    }
    might ||--o{ think : as
    might {
        VARCHAR(50) as
        DATE through
    }
    think ||--o{ myself : test
    think {
        DATE test
        TEXT single
        VARCHAR(50) sure
    }
    myself ||--o{ seem : perform
    myself {
        VARCHAR(50) perform
        DATE sure
    }