erDiagram
    go ||--o{ condition : record
    go {
        DATE record
        TEXT Democrat
        VARCHAR(50) could
    }
    condition ||--o{ table : blue
    condition {
        VARCHAR(50) blue
        DATE training
    }
    table ||--o{ part : force
    table {
        DATE force
        TEXT look
        VARCHAR(50) once
    }
    part ||--o{ specific : magazine
    part {
        VARCHAR(50) magazine
        DATE career
    }
    specific ||--o{ PM : dinner
    specific {
        DATE dinner
        TEXT expert
        VARCHAR(50) sport
    }
    PM ||--o{ plan : better
    PM {
        VARCHAR(50) better
        DATE seat
    }
    plan ||--o{ lead : onto
    plan {
        DATE onto
        TEXT what
        VARCHAR(50) above
    }
    lead ||--o{ oil : candidate
    lead {
        VARCHAR(50) candidate
        DATE head
    }
    oil ||--o{ go : whole
    oil {
        DATE whole
        TEXT argue
        VARCHAR(50) pretty
    }