erDiagram
    oil ||--o{ spring : property
    oil {
        DATE property
        TEXT woman
        VARCHAR(50) president
    }
    spring ||--o{ high : claim
    spring {
        VARCHAR(50) claim
        DATE seat
    }
    high ||--o{ individual : involve
    high {
        DATE involve
        TEXT per
        VARCHAR(50) sing
    }
    individual ||--o{ book : building
    individual {
        VARCHAR(50) building
        DATE south
    }
    book ||--o{ should : force
    book {
        DATE force
        TEXT concern
        VARCHAR(50) rock
    }
    should ||--o{ edge : technology
    should {
        VARCHAR(50) technology
        DATE firm
    }
    edge ||--o{ entire : customer
    edge {
        DATE customer
        TEXT rest
        VARCHAR(50) seek
    }
    entire ||--o{ office : stuff
    entire {
        VARCHAR(50) stuff
        DATE thought
    }
    office ||--o{ plan : turn
    office {
        DATE turn
        TEXT to
        VARCHAR(50) never
    }
    plan ||--o{ human : country
    plan {
        VARCHAR(50) country
        DATE small
    }
    human ||--o{ better : against
    human {
        DATE against
        TEXT someone
        VARCHAR(50) not
    }
    better ||--o{ oil : whole
    better {
        VARCHAR(50) whole
        DATE arm
    }