erDiagram
    plan ||--o{ out : teacher
    plan {
        DATE teacher
        TEXT near
        VARCHAR(50) establish
    }
    out ||--o{ land : trip
    out {
        VARCHAR(50) trip
        DATE per
    }
    land ||--o{ imagine : could
    land {
        DATE could
        TEXT seem
        VARCHAR(50) resource
    }
    imagine ||--o{ wife : image
    imagine {
        VARCHAR(50) image
        DATE rich
    }
    wife ||--o{ plan : nation
    wife {
        DATE nation
        TEXT plant
        VARCHAR(50) behind
    }