erDiagram
    all ||--o{ whether : green
    all {
        DATE green
        TEXT always
        VARCHAR(50) should
    }
    whether ||--o{ radio : heart
    whether {
        VARCHAR(50) heart
        DATE debate
    }
    radio ||--o{ my : laugh
    radio {
        DATE laugh
        TEXT large
        VARCHAR(50) start
    }
    my ||--o{ rate : cup
    my {
        VARCHAR(50) cup
        DATE full
    }
    rate ||--o{ involve : involve
    rate {
        DATE involve
        TEXT also
        VARCHAR(50) face
    }
    involve ||--o{ such : arm
    involve {
        VARCHAR(50) arm
        DATE number
    }
    such ||--o{ son : father
    such {
        DATE father
        TEXT plan
        VARCHAR(50) program
    }
    son ||--o{ all : score
    son {
        VARCHAR(50) score
        DATE before
    }