erDiagram
    onto ||--o{ food : ten
    onto {
        DATE ten
        TEXT represent
        VARCHAR(50) market
    }
    food ||--o{ among : decade
    food {
        VARCHAR(50) decade
        DATE discussion
    }
    among ||--o{ article : car
    among {
        DATE car
        TEXT concern
        VARCHAR(50) company
    }
    article ||--o{ man : sort
    article {
        VARCHAR(50) sort
        DATE effort
    }
    man ||--o{ fast : image
    man {
        DATE image
        TEXT six
        VARCHAR(50) which
    }
    fast ||--o{ point : performance
    fast {
        VARCHAR(50) performance
        DATE oil
    }
    point ||--o{ beat : occur
    point {
        DATE occur
        TEXT trouble
        VARCHAR(50) parent
    }
    beat ||--o{ effect : art
    beat {
        VARCHAR(50) art
        DATE professional
    }
    effect ||--o{ assume : enjoy
    effect {
        DATE enjoy
        TEXT war
        VARCHAR(50) adult
    }
    assume ||--o{ everybody : create
    assume {
        VARCHAR(50) create
        DATE itself
    }
    everybody ||--o{ onto : chance
    everybody {
        DATE chance
        TEXT difference
        VARCHAR(50) local
    }