erDiagram
    during ||--o{ someone : family
    during {
        DATE family
        TEXT individual
        VARCHAR(50) threat
    }
    someone ||--o{ lawyer : bad
    someone {
        VARCHAR(50) bad
        DATE technology
    }
    lawyer ||--o{ lose : Congress
    lawyer {
        DATE Congress
        TEXT price
        VARCHAR(50) realize
    }
    lose ||--o{ tax : onto
    lose {
        VARCHAR(50) onto
        DATE fear
    }
    tax ||--o{ during : design
    tax {
        DATE design
        TEXT those
        VARCHAR(50) indeed
    }