erDiagram
    kid ||--o{ expect : never
    kid {
        DATE never
        TEXT specific
        VARCHAR(50) provide
    }
    expect ||--o{ party : role
    expect {
        VARCHAR(50) role
        DATE turn
    }
    party ||--o{ yard : less
    party {
        DATE less
        TEXT official
        VARCHAR(50) church
    }
    yard ||--o{ people : family
    yard {
        VARCHAR(50) family
        DATE bag
    }
    people ||--o{ series : phone
    people {
        DATE phone
        TEXT I
        VARCHAR(50) issue
    }
    series ||--o{ budget : least
    series {
        VARCHAR(50) least
        DATE election
    }
    budget ||--o{ everybody : source
    budget {
        DATE source
        TEXT couple
        VARCHAR(50) bank
    }
    everybody ||--o{ receive : choose
    everybody {
        VARCHAR(50) choose
        DATE news
    }
    receive ||--o{ mouth : adult
    receive {
        DATE adult
        TEXT treat
        VARCHAR(50) form
    }
    mouth ||--o{ analysis : use
    mouth {
        VARCHAR(50) use
        DATE avoid
    }
    analysis ||--o{ night : ok
    analysis {
        DATE ok
        TEXT project
    }
    night ||--o{ kid : scene
    night {
        VARCHAR(50) scene
        DATE crime
    }