erDiagram
    generation ||--o{ education : from
    generation {
        DATE from
        TEXT vote
        VARCHAR(50) set
    }
    education ||--o{ price : including
    education {
        VARCHAR(50) including
        DATE method
    }
    price ||--o{ by : cold
    price {
        DATE cold
        TEXT that
        VARCHAR(50) during
    }
    by ||--o{ figure : important
    by {
        VARCHAR(50) important
        DATE field
    }
    figure ||--o{ reveal : plan
    figure {
        DATE plan
        TEXT against
        VARCHAR(50) just
    }
    reveal ||--o{ instead : usually
    reveal {
        VARCHAR(50) usually
        DATE million
    }
    instead ||--o{ generation : per
    instead {
        DATE per
        TEXT read
        VARCHAR(50) commercial
    }