erDiagram
    majority ||--o{ man : health
    majority {
        DATE health
        TEXT ten
        VARCHAR(50) worker
    }
    man ||--o{ mother : stock
    man {
        VARCHAR(50) stock
        DATE such
    }
    mother ||--o{ whatever : sing
    mother {
        DATE sing
        TEXT half
        VARCHAR(50) general
    }
    whatever ||--o{ throughout : party
    whatever {
        VARCHAR(50) party
        DATE contain
    }
    throughout ||--o{ majority : yet
    throughout {
        DATE yet
        TEXT kitchen
        VARCHAR(50) west
    }