erDiagram
    color ||--o{ officer : affect
    color {
        DATE affect
        TEXT difficult
        VARCHAR(50) state
    }
    officer ||--o{ tend : away
    officer {
        VARCHAR(50) away
        DATE six
    }
    tend ||--o{ similar : clear
    tend {
        DATE clear
        TEXT dog
        VARCHAR(50) late
    }
    similar ||--o{ move : cultural
    similar {
        VARCHAR(50) cultural
        DATE offer
    }
    move ||--o{ study : total
    move {
        DATE total
        TEXT hotel
        VARCHAR(50) think
    }
    study ||--o{ color : after
    study {
        VARCHAR(50) after
        DATE weight
    }