erDiagram
    defense ||--o{ financial : subject
    defense {
        DATE subject
        TEXT chair
        VARCHAR(50) training
    }
    financial ||--o{ never : seem
    financial {
        VARCHAR(50) seem
        DATE task
    }
    never ||--o{ approach : suggest
    never {
        DATE suggest
        TEXT audience
        VARCHAR(50) foot
    }
    approach ||--o{ today : whether
    approach {
        VARCHAR(50) whether
        DATE raise
    }
    today ||--o{ defense : information
    today {
        DATE information
        TEXT second
        VARCHAR(50) account
    }