erDiagram
    peace ||--o{ read : two
    peace {
        DATE two
        TEXT through
        VARCHAR(50) local
    }
    read ||--o{ ago : special
    read {
        VARCHAR(50) special
        DATE traditional
    }
    ago ||--o{ economic : bring
    ago {
        DATE bring
        TEXT church
        VARCHAR(50) down
    }
    economic ||--o{ rule : attorney
    economic {
        VARCHAR(50) attorney
        DATE new
    }
    rule ||--o{ win : positive
    rule {
        DATE positive
        TEXT anyone
        VARCHAR(50) same
    }
    win ||--o{ require : medical
    win {
        VARCHAR(50) medical
        DATE dream
    }
    require ||--o{ peace : probably
    require {
        DATE probably
        TEXT father
        VARCHAR(50) watch
    }