erDiagram
    stand ||--o{ nor : television
    stand {
        DATE television
        TEXT edge
        VARCHAR(50) recent
    }
    nor ||--o{ player : any
    nor {
        VARCHAR(50) any
        DATE student
    }
    player ||--o{ media : lose
    player {
        DATE lose
        TEXT traditional
        VARCHAR(50) word
    }
    media ||--o{ factor : indeed
    media {
        VARCHAR(50) indeed
        DATE conference
    }
    factor ||--o{ type : billion
    factor {
        DATE billion
        TEXT week
        VARCHAR(50) edge
    }
    type ||--o{ myself : third
    type {
        VARCHAR(50) third
        DATE ever
    }
    myself ||--o{ structure : message
    myself {
        DATE message
        TEXT score
        VARCHAR(50) traditional
    }
    structure ||--o{ agree : any
    structure {
        VARCHAR(50) any
        DATE Congress
    }
    agree ||--o{ risk : career
    agree {
        DATE career
        TEXT money
        VARCHAR(50) later
    }
    risk ||--o{ stand : three
    risk {
        VARCHAR(50) three
        DATE think
    }