erDiagram
    TV ||--o{ bit : field
    TV {
        DATE field
        TEXT care
        VARCHAR(50) near
    }
    bit ||--o{ idea : never
    bit {
        VARCHAR(50) never
        DATE understand
    }
    idea ||--o{ mean : economy
    idea {
        DATE economy
        TEXT space
        VARCHAR(50) stuff
    }
    mean ||--o{ reflect : result
    mean {
        VARCHAR(50) result
        DATE gun
    }
    reflect ||--o{ instead : myself
    reflect {
        DATE myself
        TEXT real
        VARCHAR(50) so
    }
    instead ||--o{ brother : throw
    instead {
        VARCHAR(50) throw
        DATE side
    }
    brother ||--o{ agency : common
    brother {
        DATE common
        TEXT evidence
        VARCHAR(50) still
    }
    agency ||--o{ southern : ten
    agency {
        VARCHAR(50) ten
        DATE even
    }
    southern ||--o{ budget : energy
    southern {
        DATE energy
        TEXT meeting
        VARCHAR(50) dog
    }
    budget ||--o{ us : seem
    budget {
        VARCHAR(50) seem
        DATE amount
    }
    us ||--o{ TV : wide
    us {
        DATE wide
        TEXT claim
        VARCHAR(50) pass
    }