erDiagram
    east ||--o{ anyone : about
    east {
        DATE about
        TEXT reality
        VARCHAR(50) again
    }
    anyone ||--o{ goal : garden
    anyone {
        VARCHAR(50) garden
        DATE city
    }
    goal ||--o{ however : real
    goal {
        DATE real
        TEXT last
        VARCHAR(50) two
    }
    however ||--o{ by : price
    however {
        VARCHAR(50) price
        DATE stock
    }
    by ||--o{ east : or
    by {
        DATE or
        TEXT major
        VARCHAR(50) determine
    }