erDiagram
    seven ||--o{ even : bed
    seven {
        DATE bed
        TEXT set
        VARCHAR(50) approach
    }
    even ||--o{ tend : herself
    even {
        VARCHAR(50) herself
        DATE now
    }
    tend ||--o{ father : accept
    tend {
        DATE accept
        TEXT develop
        VARCHAR(50) million
    }
    father ||--o{ owner : how
    father {
        VARCHAR(50) how
        DATE successful
    }
    owner ||--o{ away : executive
    owner {
        DATE executive
        TEXT mouth
        VARCHAR(50) trial
    }
    away ||--o{ will : ready
    away {
        VARCHAR(50) ready
        DATE factor
    }
    will ||--o{ reach : something
    will {
        DATE something
        TEXT standard
        VARCHAR(50) dark
    }
    reach ||--o{ nothing : hold
    reach {
        VARCHAR(50) hold
        DATE we
    }
    nothing ||--o{ wide : low
    nothing {
        DATE low
        TEXT win
        VARCHAR(50) ball
    }
    wide ||--o{ someone : probably
    wide {
        VARCHAR(50) probably
        DATE avoid
    }
    someone ||--o{ heavy : way
    someone {
        DATE way
        TEXT fact
        VARCHAR(50) mean
    }
    heavy ||--o{ seven : vote
    heavy {
        VARCHAR(50) vote
        DATE serve
    }