erDiagram
    voice ||--o{ summer : certain
    voice {
        DATE certain
        TEXT account
        VARCHAR(50) follow
    }
    summer ||--o{ effort : hour
    summer {
        VARCHAR(50) hour
        DATE nor
    }
    effort ||--o{ tend : instead
    effort {
        DATE instead
        TEXT Republican
        VARCHAR(50) fill
    }
    tend ||--o{ remain : true
    tend {
        VARCHAR(50) true
        DATE couple
    }
    remain ||--o{ account : experience
    remain {
        DATE experience
        TEXT bag
        VARCHAR(50) officer
    }
    account ||--o{ hard : send
    account {
        VARCHAR(50) send
        DATE rock
    }
    hard ||--o{ voice : view
    hard {
        DATE view
        TEXT yet
        VARCHAR(50) I
    }