erDiagram
    everything ||--o{ company : community
    everything {
        DATE community
        TEXT stop
        VARCHAR(50) community
    }
    company ||--o{ customer : trial
    company {
        VARCHAR(50) trial
        DATE deal
    }
    customer ||--o{ color : upon
    customer {
        DATE upon
        TEXT until
        VARCHAR(50) part
    }
    color ||--o{ tree : hard
    color {
        VARCHAR(50) hard
        DATE mother
    }
    tree ||--o{ others : rule
    tree {
        DATE rule
        TEXT ok
        VARCHAR(50) because
    }
    others ||--o{ modern : economy
    others {
        VARCHAR(50) economy
        DATE rich
    }
    modern ||--o{ free : lawyer
    modern {
        DATE lawyer
        TEXT until
        VARCHAR(50) development
    }
    free ||--o{ want : system
    free {
        VARCHAR(50) system
        DATE black
    }
    want ||--o{ everything : son
    want {
        DATE son
        TEXT measure
        VARCHAR(50) arm
    }