erDiagram
    interview ||--o{ foot : just
    interview {
        DATE just
        TEXT sure
        VARCHAR(50) party
    }
    foot ||--o{ work : writer
    foot {
        VARCHAR(50) writer
        DATE PM
    }
    work ||--o{ professor : movie
    work {
        DATE movie
        TEXT rise
        VARCHAR(50) station
    }
    professor ||--o{ move : forward
    professor {
        VARCHAR(50) forward
        DATE identify
    }
    move ||--o{ per : old
    move {
        DATE old
        TEXT defense
        VARCHAR(50) music
    }
    per ||--o{ wife : small
    per {
        VARCHAR(50) small
        DATE none
    }
    wife ||--o{ modern : cold
    wife {
        DATE cold
        TEXT score
        VARCHAR(50) speech
    }
    modern ||--o{ allow : back
    modern {
        VARCHAR(50) back
        DATE group
    }
    allow ||--o{ heart : country
    allow {
        DATE country
        TEXT with
        VARCHAR(50) need
    }
    heart ||--o{ second : activity
    heart {
        VARCHAR(50) activity
        DATE tend
    }
    second ||--o{ past : purpose
    second {
        DATE purpose
        TEXT test
        VARCHAR(50) mean
    }
    past ||--o{ interview : modern
    past {
        VARCHAR(50) modern
        DATE wrong
    }