erDiagram
    interview ||--o{ bank : PM
    interview {
        DATE PM
        TEXT tonight
        VARCHAR(50) hundred
    }
    bank ||--o{ reach : surface
    bank {
        VARCHAR(50) surface
        DATE particularly
    }
    reach ||--o{ single : child
    reach {
        DATE child
        TEXT cut
        VARCHAR(50) add
    }
    single ||--o{ situation : group
    single {
        VARCHAR(50) group
        DATE door
    }
    situation ||--o{ all : right
    situation {
        DATE right
        TEXT occur
        VARCHAR(50) free
    }
    all ||--o{ generation : general
    all {
        VARCHAR(50) general
        DATE wear
    }
    generation ||--o{ interview : price
    generation {
        DATE price
        TEXT sense
        VARCHAR(50) quite
    }