erDiagram
    everything ||--o{ voice : film
    everything {
        DATE film
        TEXT when
        VARCHAR(50) reveal
    }
    voice ||--o{ star : water
    voice {
        VARCHAR(50) water
        DATE little
    }
    star ||--o{ computer : training
    star {
        DATE training
        TEXT painting
        VARCHAR(50) law
    }
    computer ||--o{ arrive : adult
    computer {
        VARCHAR(50) adult
        DATE start
    }
    arrive ||--o{ movie : political
    arrive {
        DATE political
        TEXT sometimes
        VARCHAR(50) firm
    }
    movie ||--o{ little : all
    movie {
        VARCHAR(50) all
        DATE add
    }
    little ||--o{ someone : home
    little {
        DATE home
        TEXT real
        VARCHAR(50) little
    }
    someone ||--o{ magazine : study
    someone {
        VARCHAR(50) study
        DATE somebody
    }
    magazine ||--o{ everything : little
    magazine {
        DATE little
        TEXT person
        VARCHAR(50) across
    }