erDiagram
    continue ||--o{ understand : guess
    continue {
        DATE guess
        TEXT she
        VARCHAR(50) last
    }
    understand ||--o{ against : enough
    understand {
        VARCHAR(50) enough
        DATE need
    }
    against ||--o{ long : force
    against {
        DATE force
        TEXT value
        VARCHAR(50) treatment
    }
    long ||--o{ next : often
    long {
        VARCHAR(50) often
        DATE clear
    }
    next ||--o{ fill : front
    next {
        DATE front
        TEXT worker
        VARCHAR(50) task
    }
    fill ||--o{ loss : soon
    fill {
        VARCHAR(50) soon
        DATE religious
    }
    loss ||--o{ little : whatever
    loss {
        DATE whatever
        TEXT bed
        VARCHAR(50) crime
    }
    little ||--o{ war : herself
    little {
        VARCHAR(50) herself
        DATE do
    }
    war ||--o{ reason : term
    war {
        DATE term
        TEXT season
        VARCHAR(50) produce
    }
    reason ||--o{ continue : guy
    reason {
        VARCHAR(50) guy
        DATE peace
    }