erDiagram
    blue ||--o{ hear : throw
    blue {
        DATE throw
        TEXT early
        VARCHAR(50) wide
    }
    hear ||--o{ space : yourself
    hear {
        VARCHAR(50) yourself
        DATE none
    }
    space ||--o{ simply : anyone
    space {
        DATE anyone
        TEXT word
        VARCHAR(50) these
    }
    simply ||--o{ factor : possible
    simply {
        VARCHAR(50) possible
        DATE avoid
    }
    factor ||--o{ sit : glass
    factor {
        DATE glass
        TEXT wall
        VARCHAR(50) character
    }
    sit ||--o{ including : across
    sit {
        VARCHAR(50) across
        DATE kind
    }
    including ||--o{ travel : tree
    including {
        DATE tree
        TEXT charge
        VARCHAR(50) board
    }
    travel ||--o{ small : five
    travel {
        VARCHAR(50) five
        DATE rise
    }
    small ||--o{ commercial : consumer
    small {
        DATE consumer
        TEXT safe
        VARCHAR(50) fund
    }
    commercial ||--o{ table : person
    commercial {
        VARCHAR(50) person
        DATE heavy
    }
    table ||--o{ blue : toward
    table {
        DATE toward
        TEXT lose
        VARCHAR(50) detail
    }