erDiagram
    page ||--o{ imagine : suggest
    page {
        DATE suggest
        TEXT area
        VARCHAR(50) treat
    }
    imagine ||--o{ onto : teach
    imagine {
        VARCHAR(50) teach
        DATE them
    }
    onto ||--o{ for : debate
    onto {
        DATE debate
        TEXT although
        VARCHAR(50) image
    }
    for ||--o{ between : who
    for {
        VARCHAR(50) who
        DATE serious
    }
    between ||--o{ page : level
    between {
        DATE level
        TEXT agent
        VARCHAR(50) foot
    }