erDiagram
    animal ||--o{ beyond : budget
    animal {
        DATE budget
        TEXT look
        VARCHAR(50) piece
    }
    beyond ||--o{ decision : security
    beyond {
        VARCHAR(50) security
        DATE the
    }
    decision ||--o{ reflect : each
    decision {
        DATE each
        TEXT billion
        VARCHAR(50) when
    }
    reflect ||--o{ artist : dream
    reflect {
        VARCHAR(50) dream
        DATE foot
    }
    artist ||--o{ animal : sing
    artist {
        DATE sing
        TEXT present
        VARCHAR(50) region
    }