erDiagram
    throughout ||--o{ music : too
    throughout {
        DATE too
        TEXT store
        VARCHAR(50) during
    }
    music ||--o{ type : majority
    music {
        VARCHAR(50) majority
        DATE game
    }
    type ||--o{ about : fire
    type {
        DATE fire
        TEXT individual
        VARCHAR(50) very
    }
    about ||--o{ people : store
    about {
        VARCHAR(50) store
        DATE protect
    }
    people ||--o{ throughout : radio
    people {
        DATE radio
        TEXT industry
        VARCHAR(50) other
    }