erDiagram
    where ||--o{ window : wish
    where {
        DATE wish
        TEXT travel
        VARCHAR(50) give
    }
    window ||--o{ bit : leave
    window {
        VARCHAR(50) leave
        DATE heavy
    }
    bit ||--o{ responsibility : movement
    bit {
        DATE movement
        TEXT indeed
        VARCHAR(50) plan
    }
    responsibility ||--o{ begin : entire
    responsibility {
        VARCHAR(50) entire
        DATE mention
    }
    begin ||--o{ seem : everyone
    begin {
        DATE everyone
        TEXT southern
        VARCHAR(50) newspaper
    }
    seem ||--o{ help : glass
    seem {
        VARCHAR(50) glass
        DATE despite
    }
    help ||--o{ wall : year
    help {
        DATE year
        TEXT home
        VARCHAR(50) firm
    }
    wall ||--o{ where : TV
    wall {
        VARCHAR(50) TV
        DATE quite
    }