erDiagram
    fire ||--o{ early : admit
    fire {
        DATE admit
        TEXT section
        VARCHAR(50) often
    }
    early ||--o{ here : imagine
    early {
        VARCHAR(50) imagine
        DATE out
    }
    here ||--o{ new : if
    here {
        DATE if
        TEXT capital
        VARCHAR(50) option
    }
    new ||--o{ each : myself
    new {
        VARCHAR(50) myself
        DATE ball
    }
    each ||--o{ notice : concern
    each {
        DATE concern
        TEXT two
        VARCHAR(50) run
    }
    notice ||--o{ page : plan
    notice {
        VARCHAR(50) plan
        DATE exactly
    }
    page ||--o{ fire : nation
    page {
        DATE nation
        TEXT structure
        VARCHAR(50) type
    }