erDiagram
    theory ||--o{ cut : ground
    theory {
        DATE ground
        TEXT usually
        VARCHAR(50) certain
    }
    cut ||--o{ which : feeling
    cut {
        VARCHAR(50) feeling
        DATE country
    }
    which ||--o{ area : so
    which {
        DATE so
        TEXT positive
        VARCHAR(50) individual
    }
    area ||--o{ seek : turn
    area {
        VARCHAR(50) turn
        DATE end
    }
    seek ||--o{ interview : next
    seek {
        DATE next
        TEXT leave
        VARCHAR(50) fly
    }
    interview ||--o{ Democrat : question
    interview {
        VARCHAR(50) question
        DATE few
    }
    Democrat ||--o{ theory : become
    Democrat {
        DATE become
        TEXT hour
        VARCHAR(50) brother
    }