erDiagram
    former ||--o{ green : admit
    former {
        DATE admit
        TEXT side
        VARCHAR(50) establish
    }
    green ||--o{ task : argue
    green {
        VARCHAR(50) argue
        DATE weight
    }
    task ||--o{ nearly : various
    task {
        DATE various
        TEXT TV
        VARCHAR(50) national
    }
    nearly ||--o{ join : remember
    nearly {
        VARCHAR(50) remember
        DATE occur
    }
    join ||--o{ discuss : big
    join {
        DATE big
        TEXT member
        VARCHAR(50) something
    }
    discuss ||--o{ unit : truth
    discuss {
        VARCHAR(50) truth
        DATE rich
    }
    unit ||--o{ yeah : certain
    unit {
        DATE certain
        TEXT center
        VARCHAR(50) wish
    }
    yeah ||--o{ each : help
    yeah {
        VARCHAR(50) help
        DATE suddenly
    }
    each ||--o{ later : drop
    each {
        DATE drop
        TEXT case
        VARCHAR(50) campaign
    }
    later ||--o{ to : exactly
    later {
        VARCHAR(50) exactly
        DATE share
    }
    to ||--o{ discussion : save
    to {
        DATE save
        TEXT appear
        VARCHAR(50) just
    }
    discussion ||--o{ former : operation
    discussion {
        VARCHAR(50) operation
        DATE such
    }