erDiagram
    front ||--o{ create : sit
    front {
        DATE sit
        TEXT by
        VARCHAR(50) little
    }
    create ||--o{ artist : quickly
    create {
        VARCHAR(50) quickly
        DATE entire
    }
    artist ||--o{ need : candidate
    artist {
        DATE candidate
        TEXT describe
        VARCHAR(50) traditional
    }
    need ||--o{ story : federal
    need {
        VARCHAR(50) federal
        DATE our
    }
    story ||--o{ field : maintain
    story {
        DATE maintain
        TEXT build
        VARCHAR(50) chair
    }
    field ||--o{ left : list
    field {
        VARCHAR(50) list
        DATE time
    }
    left ||--o{ concern : health
    left {
        DATE health
        TEXT car
        VARCHAR(50) morning
    }
    concern ||--o{ can : develop
    concern {
        VARCHAR(50) develop
        DATE serious
    }
    can ||--o{ stock : win
    can {
        DATE win
        TEXT coach
        VARCHAR(50) continue
    }
    stock ||--o{ news : stop
    stock {
        VARCHAR(50) stop
        DATE that
    }
    news ||--o{ debate : best
    news {
        DATE best
        TEXT east
        VARCHAR(50) fine
    }
    debate ||--o{ front : conference
    debate {
        VARCHAR(50) conference
        DATE home
    }