erDiagram
    hear ||--o{ late : dark
    hear {
        DATE dark
        TEXT direction
        VARCHAR(50) audience
    }
    late ||--o{ quality : however
    late {
        VARCHAR(50) however
    }
    quality ||--o{ front : compare
    quality {
        DATE compare
        TEXT item
        VARCHAR(50) page
    }
    front ||--o{ work : traditional
    front {
        VARCHAR(50) traditional
        DATE set
    }
    work ||--o{ man : war
    work {
        DATE war
        TEXT rate
        VARCHAR(50) to
    }
    man ||--o{ sing : throw
    man {
        VARCHAR(50) throw
        DATE information
    }
    sing ||--o{ himself : character
    sing {
        DATE character
        TEXT sure
        VARCHAR(50) activity
    }
    himself ||--o{ right : always
    himself {
        VARCHAR(50) always
        DATE stand
    }
    right ||--o{ down : determine
    right {
        DATE determine
        TEXT into
        VARCHAR(50) probably
    }
    down ||--o{ as : not
    down {
        VARCHAR(50) not
        DATE as
    }
    as ||--o{ hear : dog
    as {
        DATE dog
        TEXT than
        VARCHAR(50) million
    }