erDiagram
    nor ||--o{ hard : toward
    nor {
        DATE toward
        TEXT even
        VARCHAR(50) hope
    }
    hard ||--o{ large : measure
    hard {
        VARCHAR(50) measure
        DATE reach
    }
    large ||--o{ less : business
    large {
        DATE business
        TEXT Mrs
        VARCHAR(50) green
    }
    less ||--o{ cause : structure
    less {
        VARCHAR(50) structure
        DATE prepare
    }
    cause ||--o{ song : right
    cause {
        DATE right
        TEXT style
        VARCHAR(50) owner
    }
    song ||--o{ single : record
    song {
        VARCHAR(50) record
        DATE treat
    }
    single ||--o{ would : air
    single {
        DATE air
        TEXT stock
        VARCHAR(50) wrong
    }
    would ||--o{ house : foot
    would {
        VARCHAR(50) foot
        DATE knowledge
    }
    house ||--o{ education : assume
    house {
        DATE assume
        TEXT need
        VARCHAR(50) moment
    }
    education ||--o{ value : seem
    education {
        VARCHAR(50) seem
        DATE mean
    }
    value ||--o{ unit : others
    value {
        DATE others
        TEXT page
        VARCHAR(50) remain
    }
    unit ||--o{ nor : food
    unit {
        VARCHAR(50) food
        DATE meet
    }