erDiagram
    close ||--o{ environmental : word
    close {
        DATE word
        TEXT else
        VARCHAR(50) rate
    }
    environmental ||--o{ worry : better
    environmental {
        VARCHAR(50) better
        DATE serve
    }
    worry ||--o{ few : risk
    worry {
        DATE risk
        TEXT send
        VARCHAR(50) appear
    }
    few ||--o{ appear : north
    few {
        VARCHAR(50) north
        DATE present
    }
    appear ||--o{ several : where
    appear {
        DATE where
        TEXT history
        VARCHAR(50) under
    }
    several ||--o{ still : set
    several {
        VARCHAR(50) set
        DATE century
    }
    still ||--o{ deal : quickly
    still {
        DATE quickly
        TEXT sign
        VARCHAR(50) of
    }
    deal ||--o{ teach : space
    deal {
        VARCHAR(50) space
        DATE city
    }
    teach ||--o{ close : public
    teach {
        DATE public
        TEXT spend
        VARCHAR(50) court
    }