erDiagram
    middle ||--o{ hold : bag
    middle {
        DATE bag
        TEXT begin
        VARCHAR(50) do
    }
    hold ||--o{ suddenly : few
    hold {
        VARCHAR(50) few
        DATE charge
    }
    suddenly ||--o{ rather : why
    suddenly {
        DATE why
        TEXT actually
        VARCHAR(50) light
    }
    rather ||--o{ hair : each
    rather {
        VARCHAR(50) each
        DATE fear
    }
    hair ||--o{ city : speak
    hair {
        DATE speak
        TEXT recent
        VARCHAR(50) human
    }
    city ||--o{ network : follow
    city {
        VARCHAR(50) follow
        DATE goal
    }
    network ||--o{ middle : agent
    network {
        DATE agent
        TEXT many
        VARCHAR(50) agency
    }