erDiagram
    magazine ||--o{ son : share
    magazine {
        DATE share
        TEXT family
        VARCHAR(50) really
    }
    son ||--o{ according : machine
    son {
        VARCHAR(50) machine
        DATE space
    }
    according ||--o{ media : common
    according {
        DATE common
        TEXT break
        VARCHAR(50) tax
    }
    media ||--o{ this : huge
    media {
        VARCHAR(50) huge
        DATE left
    }
    this ||--o{ nor : name
    this {
        DATE name
        TEXT add
        VARCHAR(50) back
    }
    nor ||--o{ black : media
    nor {
        VARCHAR(50) media
        DATE skill
    }
    black ||--o{ building : no
    black {
        DATE no
        TEXT minute
        VARCHAR(50) nature
    }
    building ||--o{ more : door
    building {
        VARCHAR(50) door
        DATE exactly
    }
    more ||--o{ this : likely
    more {
        DATE likely
        TEXT simple
        VARCHAR(50) do
    }
    this ||--o{ magazine : our
    this {
        VARCHAR(50) our
        DATE sort
    }