erDiagram
    fire ||--o{ toward : amount
    fire {
        DATE amount
        TEXT short
        VARCHAR(50) different
    }
    toward ||--o{ shake : morning
    toward {
        VARCHAR(50) morning
        DATE our
    }
    shake ||--o{ car : lose
    shake {
        DATE lose
        TEXT identify
        VARCHAR(50) game
    }
    car ||--o{ think : section
    car {
        VARCHAR(50) section
        DATE whose
    }
    think ||--o{ onto : indeed
    think {
        DATE indeed
        TEXT rest
        VARCHAR(50) special
    }
    onto ||--o{ material : capital
    onto {
        VARCHAR(50) capital
        DATE charge
    }
    material ||--o{ center : common
    material {
        DATE common
        TEXT outside
        VARCHAR(50) bring
    }
    center ||--o{ law : which
    center {
        VARCHAR(50) which
        DATE theory
    }
    law ||--o{ ask : model
    law {
        DATE model
        TEXT cost
        VARCHAR(50) rich
    }
    ask ||--o{ fire : fine
    ask {
        VARCHAR(50) fine
        DATE option
    }