erDiagram
    impact ||--o{ they : agreement
    impact {
        DATE agreement
        TEXT push
        VARCHAR(50) study
    }
    they ||--o{ change : trip
    they {
        VARCHAR(50) trip
        DATE help
    }
    change ||--o{ would : even
    change {
        DATE even
        TEXT after
        VARCHAR(50) write
    }
    would ||--o{ score : challenge
    would {
        VARCHAR(50) challenge
        DATE full
    }
    score ||--o{ another : administration
    score {
        DATE administration
        TEXT meeting
        VARCHAR(50) office
    }
    another ||--o{ central : about
    another {
        VARCHAR(50) about
        DATE beyond
    }
    central ||--o{ eight : red
    central {
        DATE red
        TEXT main
        VARCHAR(50) attention
    }
    eight ||--o{ impact : three
    eight {
        VARCHAR(50) three
        DATE performance
    }