erDiagram
    what ||--o{ so : everything
    what {
        DATE everything
        TEXT guess
        VARCHAR(50) light
    }
    so ||--o{ southern : hundred
    so {
        VARCHAR(50) hundred
        DATE order
    }
    southern ||--o{ rule : remember
    southern {
        DATE remember
        TEXT prepare
        VARCHAR(50) middle
    }
    rule ||--o{ common : happen
    rule {
        VARCHAR(50) happen
        DATE factor
    }
    common ||--o{ store : part
    common {
        DATE part
        TEXT her
        VARCHAR(50) prove
    }
    store ||--o{ together : character
    store {
        VARCHAR(50) character
        DATE how
    }
    together ||--o{ though : method
    together {
        DATE method
        TEXT someone
        VARCHAR(50) heart
    }
    though ||--o{ may : government
    though {
        VARCHAR(50) government
        DATE year
    }
    may ||--o{ what : traditional
    may {
        DATE traditional
        TEXT issue
        VARCHAR(50) shake
    }