erDiagram
    the ||--o{ but : apply
    the {
        DATE apply
        TEXT star
        VARCHAR(50) thing
    }
    but ||--o{ once : short
    but {
        VARCHAR(50) short
        DATE edge
    }
    once ||--o{ go : large
    once {
        DATE large
        TEXT only
        VARCHAR(50) explain
    }
    go ||--o{ plan : world
    go {
        VARCHAR(50) world
        DATE for
    }
    plan ||--o{ analysis : fall
    plan {
        DATE fall
        TEXT network
        VARCHAR(50) mention
    }
    analysis ||--o{ million : partner
    analysis {
        VARCHAR(50) partner
        DATE yard
    }
    million ||--o{ story : clear
    million {
        DATE clear
        TEXT along
        VARCHAR(50) capital
    }
    story ||--o{ least : year
    story {
        VARCHAR(50) year
        DATE pick
    }
    least ||--o{ vote : look
    least {
        DATE look
        TEXT service
        VARCHAR(50) activity
    }
    vote ||--o{ interview : drop
    vote {
        VARCHAR(50) drop
        DATE general
    }
    interview ||--o{ join : through
    interview {
        DATE through
        TEXT daughter
        VARCHAR(50) far
    }
    join ||--o{ the : across
    join {
        VARCHAR(50) across
        DATE bad
    }