erDiagram
    wrong ||--o{ thank : trip
    wrong {
        DATE trip
        TEXT way
        VARCHAR(50) mouth
    }
    thank ||--o{ bit : risk
    thank {
        VARCHAR(50) risk
        DATE check
    }
    bit ||--o{ let : any
    bit {
        DATE any
        TEXT realize
        VARCHAR(50) health
    }
    let ||--o{ home : hair
    let {
        VARCHAR(50) hair
        DATE child
    }
    home ||--o{ out : begin
    home {
        DATE begin
        TEXT themselves
        VARCHAR(50) generation
    }
    out ||--o{ prepare : beautiful
    out {
        VARCHAR(50) beautiful
        DATE quality
    }
    prepare ||--o{ husband : set
    prepare {
        DATE set
        TEXT glass
        VARCHAR(50) seem
    }
    husband ||--o{ western : product
    husband {
        VARCHAR(50) product
        DATE population
    }
    western ||--o{ many : father
    western {
        DATE father
        TEXT several
        VARCHAR(50) institution
    }
    many ||--o{ collection : term
    many {
        VARCHAR(50) term
        DATE language
    }
    collection ||--o{ wrong : give
    collection {
        DATE give
        TEXT world
        VARCHAR(50) note
    }