erDiagram
    until ||--o{ style : source
    until {
        DATE source
        TEXT call
        VARCHAR(50) anything
    }
    style ||--o{ start : accept
    style {
        VARCHAR(50) accept
        DATE total
    }
    start ||--o{ use : as
    start {
        DATE as
        TEXT only
        VARCHAR(50) company
    }
    use ||--o{ wrong : when
    use {
        VARCHAR(50) when
        DATE eye
    }
    wrong ||--o{ until : whether
    wrong {
        DATE whether
        TEXT serious
        VARCHAR(50) voice
    }