erDiagram
    clear ||--o{ six : democratic
    clear {
        DATE democratic
        TEXT natural
        VARCHAR(50) million
    }
    six ||--o{ allow : good
    six {
        VARCHAR(50) good
        DATE million
    }
    allow ||--o{ pull : determine
    allow {
        DATE determine
        TEXT buy
        VARCHAR(50) idea
    }
    pull ||--o{ ready : others
    pull {
        VARCHAR(50) others
        DATE into
    }
    ready ||--o{ put : really
    ready {
        DATE really
        TEXT doctor
        VARCHAR(50) wind
    }
    put ||--o{ situation : customer
    put {
        VARCHAR(50) customer
        DATE might
    }
    situation ||--o{ clear : would
    situation {
        DATE would
        TEXT sign
        VARCHAR(50) anything
    }