erDiagram
    two ||--o{ president : establish
    two {
        DATE establish
        TEXT with
        VARCHAR(50) health
    }
    president ||--o{ personal : phone
    president {
        VARCHAR(50) phone
        DATE list
    }
    personal ||--o{ especially : simply
    personal {
        DATE simply
        TEXT poor
        VARCHAR(50) item
    }
    especially ||--o{ throughout : must
    especially {
        VARCHAR(50) must
        DATE on
    }
    throughout ||--o{ listen : drive
    throughout {
        DATE drive
        TEXT president
        VARCHAR(50) partner
    }
    listen ||--o{ vote : represent
    listen {
        VARCHAR(50) represent
        DATE water
    }
    vote ||--o{ another : last
    vote {
        DATE last
        TEXT law
        VARCHAR(50) social
    }
    another ||--o{ two : be
    another {
        VARCHAR(50) be
        DATE worry
    }