erDiagram
    think ||--o{ father : his
    think {
        DATE his
        TEXT ok
        VARCHAR(50) call
    }
    father ||--o{ teacher : agree
    father {
        VARCHAR(50) agree
        DATE thing
    }
    teacher ||--o{ should : purpose
    teacher {
        DATE purpose
        TEXT especially
        VARCHAR(50) a
    }
    should ||--o{ smile : southern
    should {
        VARCHAR(50) southern
        DATE along
    }
    smile ||--o{ partner : central
    smile {
        DATE central
        TEXT take
        VARCHAR(50) difference
    }
    partner ||--o{ anything : officer
    partner {
        VARCHAR(50) officer
        DATE somebody
    }
    anything ||--o{ mother : minute
    anything {
        DATE minute
        TEXT never
        VARCHAR(50) song
    }
    mother ||--o{ table : service
    mother {
        VARCHAR(50) service
        DATE beat
    }
    table ||--o{ force : fish
    table {
        DATE fish
        TEXT my
        VARCHAR(50) at
    }
    force ||--o{ think : miss
    force {
        VARCHAR(50) miss
        DATE politics
    }