erDiagram
    news ||--o{ officer : apply
    news {
        DATE apply
        TEXT baby
        VARCHAR(50) husband
    }
    officer ||--o{ wind : somebody
    officer {
        VARCHAR(50) somebody
        DATE campaign
    }
    wind ||--o{ oil : young
    wind {
        DATE young
        TEXT especially
        VARCHAR(50) others
    }
    oil ||--o{ end : here
    oil {
        VARCHAR(50) here
        DATE able
    }
    end ||--o{ worry : plant
    end {
        DATE plant
        TEXT little
        VARCHAR(50) analysis
    }
    worry ||--o{ almost : camera
    worry {
        VARCHAR(50) camera
        DATE minute
    }
    almost ||--o{ news : various
    almost {
        DATE various
        TEXT indeed
        VARCHAR(50) major
    }