erDiagram
    ask ||--o{ ten : nice
    ask {
        DATE nice
        TEXT crime
        VARCHAR(50) within
    }
    ten ||--o{ partner : upon
    ten {
        VARCHAR(50) upon
        DATE think
    }
    partner ||--o{ while : night
    partner {
        DATE night
        TEXT well
        VARCHAR(50) throughout
    }
    while ||--o{ early : debate
    while {
        VARCHAR(50) debate
        DATE agent
    }
    early ||--o{ forget : door
    early {
        DATE door
        TEXT door
        VARCHAR(50) spring
    }
    forget ||--o{ sense : lead
    forget {
        VARCHAR(50) lead
        DATE still
    }
    sense ||--o{ ask : after
    sense {
        DATE after
        TEXT defense
        VARCHAR(50) water
    }