erDiagram
    indeed ||--o{ yard : through
    indeed {
        DATE through
        TEXT matter
        VARCHAR(50) pressure
    }
    yard ||--o{ agreement : everybody
    yard {
        VARCHAR(50) everybody
        DATE deep
    }
    agreement ||--o{ brother : when
    agreement {
        DATE when
        TEXT employee
        VARCHAR(50) thing
    }
    brother ||--o{ each : fact
    brother {
        VARCHAR(50) fact
        DATE eight
    }
    each ||--o{ with : policy
    each {
        DATE policy
        TEXT operation
        VARCHAR(50) community
    }
    with ||--o{ indeed : power
    with {
        VARCHAR(50) power
        DATE sea
    }