erDiagram
    age ||--o{ answer : both
    age {
        DATE both
        TEXT box
        VARCHAR(50) behavior
    }
    answer ||--o{ yet : case
    answer {
        VARCHAR(50) case
        DATE require
    }
    yet ||--o{ majority : hair
    yet {
        DATE hair
        TEXT blood
        VARCHAR(50) agent
    }
    majority ||--o{ no : yet
    majority {
        VARCHAR(50) yet
        DATE system
    }
    no ||--o{ one : position
    no {
        DATE position
        TEXT whether
        VARCHAR(50) do
    }
    one ||--o{ not : explain
    one {
        VARCHAR(50) explain
        DATE drug
    }
    not ||--o{ present : involve
    not {
        DATE involve
        TEXT standard
        VARCHAR(50) arrive
    }
    present ||--o{ team : box
    present {
        VARCHAR(50) box
        DATE kitchen
    }
    team ||--o{ style : exactly
    team {
        DATE exactly
        TEXT fish
        VARCHAR(50) follow
    }
    style ||--o{ age : feeling
    style {
        VARCHAR(50) feeling
        DATE music
    }