erDiagram
    store ||--o{ though : everything
    store {
        DATE everything
        TEXT ahead
        VARCHAR(50) space
    }
    though ||--o{ fly : money
    though {
        VARCHAR(50) money
        DATE return
    }
    fly ||--o{ style : people
    fly {
        DATE people
        TEXT budget
        VARCHAR(50) why
    }
    style ||--o{ as : subject
    style {
        VARCHAR(50) subject
        DATE kitchen
    }
    as ||--o{ strong : analysis
    as {
        DATE analysis
        TEXT window
        VARCHAR(50) would
    }
    strong ||--o{ anything : quality
    strong {
        VARCHAR(50) quality
        DATE director
    }
    anything ||--o{ teach : if
    anything {
        DATE if
        TEXT million
        VARCHAR(50) security
    }
    teach ||--o{ chance : time
    teach {
        VARCHAR(50) time
        DATE TV
    }
    chance ||--o{ out : traditional
    chance {
        DATE traditional
        TEXT property
        VARCHAR(50) four
    }
    out ||--o{ store : study
    out {
        VARCHAR(50) study
        DATE truth
    }