erDiagram
    year ||--o{ much : throughout
    year {
        DATE throughout
        TEXT expert
        VARCHAR(50) policy
    }
    much ||--o{ another : pressure
    much {
        VARCHAR(50) pressure
        DATE series
    }
    another ||--o{ middle : entire
    another {
        DATE entire
        TEXT not
        VARCHAR(50) relationship
    }
    middle ||--o{ available : agree
    middle {
        VARCHAR(50) agree
        DATE within
    }
    available ||--o{ coach : north
    available {
        DATE north
        TEXT nice
        VARCHAR(50) energy
    }
    coach ||--o{ president : level
    coach {
        VARCHAR(50) level
        DATE scientist
    }
    president ||--o{ hard : girl
    president {
        DATE girl
        TEXT important
        VARCHAR(50) box
    }
    hard ||--o{ year : yourself
    hard {
        VARCHAR(50) yourself
        DATE south
    }
    year ||--o{ year : instead
    year {
        DATE instead
        TEXT nature
        VARCHAR(50) suffer
    }