erDiagram
    white ||--o{ its : garden
    white {
        DATE garden
        TEXT water
        VARCHAR(50) detail
    }
    its ||--o{ yet : here
    its {
        VARCHAR(50) here
        DATE office
    }
    yet ||--o{ back : civil
    yet {
        DATE civil
        TEXT world
        VARCHAR(50) also
    }
    back ||--o{ ago : full
    back {
        VARCHAR(50) full
        DATE may
    }
    ago ||--o{ white : available
    ago {
        DATE available
        TEXT company
        VARCHAR(50) fine
    }