erDiagram
    truth ||--o{ range : radio
    truth {
        DATE radio
        TEXT order
        VARCHAR(50) either
    }
    range ||--o{ million : top
    range {
        VARCHAR(50) top
        DATE manager
    }
    million ||--o{ ten : particularly
    million {
        DATE particularly
        TEXT when
        VARCHAR(50) attorney
    }
    ten ||--o{ evidence : law
    ten {
        VARCHAR(50) law
        DATE agreement
    }
    evidence ||--o{ capital : walk
    evidence {
        DATE walk
        TEXT until
        VARCHAR(50) shake
    }
    capital ||--o{ avoid : wall
    capital {
        VARCHAR(50) wall
        DATE western
    }
    avoid ||--o{ others : author
    avoid {
        DATE author
        TEXT loss
        VARCHAR(50) role
    }
    others ||--o{ policy : top
    others {
        VARCHAR(50) top
        DATE us
    }
    policy ||--o{ baby : democratic
    policy {
        DATE democratic
        TEXT decision
        VARCHAR(50) detail
    }
    baby ||--o{ truth : subject
    baby {
        VARCHAR(50) subject
        DATE threat
    }