erDiagram
    spring ||--o{ finally : successful
    spring {
        DATE successful
        TEXT soon
        VARCHAR(50) conference
    }
    finally ||--o{ news : moment
    finally {
        VARCHAR(50) moment
        DATE now
    }
    news ||--o{ set : management
    news {
        DATE management
        TEXT base
        VARCHAR(50) within
    }
    set ||--o{ culture : election
    set {
        VARCHAR(50) election
        DATE share
    }
    culture ||--o{ piece : skin
    culture {
        DATE skin
        TEXT man
        VARCHAR(50) cut
    }
    piece ||--o{ spring : system
    piece {
        VARCHAR(50) system
        DATE certainly
    }