erDiagram
    tough ||--o{ oil : approach
    tough {
        DATE approach
        TEXT now
        VARCHAR(50) relate
    }
    oil ||--o{ hear : race
    oil {
        VARCHAR(50) race
        DATE some
    }
    hear ||--o{ personal : expert
    hear {
        DATE expert
        TEXT for
        VARCHAR(50) control
    }
    personal ||--o{ last : early
    personal {
        VARCHAR(50) early
        DATE picture
    }
    last ||--o{ resource : ball
    last {
        DATE ball
        TEXT let
        VARCHAR(50) spend
    }
    resource ||--o{ tough : east
    resource {
        VARCHAR(50) east
        DATE common
    }