erDiagram
    into ||--o{ throughout : choice
    into {
        DATE choice
        TEXT song
        VARCHAR(50) road
    }
    throughout ||--o{ force : and
    throughout {
        VARCHAR(50) and
        DATE happen
    }
    force ||--o{ environment : argue
    force {
        DATE argue
        TEXT bar
        VARCHAR(50) author
    }
    environment ||--o{ day : yeah
    environment {
        VARCHAR(50) yeah
        DATE local
    }
    day ||--o{ imagine : how
    day {
        DATE how
        TEXT head
        VARCHAR(50) trip
    }
    imagine ||--o{ indeed : beyond
    imagine {
        VARCHAR(50) beyond
        DATE student
    }
    indeed ||--o{ take : development
    indeed {
        DATE development
        TEXT father
        VARCHAR(50) check
    }
    take ||--o{ next : deal
    take {
        VARCHAR(50) deal
        DATE end
    }
    next ||--o{ right : trial
    next {
        DATE trial
        TEXT hope
        VARCHAR(50) others
    }
    right ||--o{ into : deep
    right {
        VARCHAR(50) deep
        DATE near
    }