erDiagram
    spend ||--o{ matter : adult
    spend {
        DATE adult
        TEXT realize
        VARCHAR(50) respond
    }
    matter ||--o{ situation : can
    matter {
        VARCHAR(50) can
        DATE industry
    }
    situation ||--o{ since : pretty
    situation {
        DATE pretty
        TEXT today
        VARCHAR(50) because
    }
    since ||--o{ them : yard
    since {
        VARCHAR(50) yard
        DATE rock
    }
    them ||--o{ five : best
    them {
        DATE best
        TEXT audience
        VARCHAR(50) attention
    }
    five ||--o{ director : firm
    five {
        VARCHAR(50) firm
        DATE go
    }
    director ||--o{ for : increase
    director {
        DATE increase
        TEXT old
        VARCHAR(50) role
    }
    for ||--o{ spend : even
    for {
        VARCHAR(50) even
        DATE live
    }