erDiagram
    area ||--o{ voice : tend
    area {
        DATE tend
        TEXT word
        VARCHAR(50) mind
    }
    voice ||--o{ important : worker
    voice {
        VARCHAR(50) worker
        DATE body
    }
    important ||--o{ stage : walk
    important {
        DATE walk
        TEXT east
        VARCHAR(50) view
    }
    stage ||--o{ professional : bed
    stage {
        VARCHAR(50) bed
        DATE size
    }
    professional ||--o{ whole : by
    professional {
        DATE by
        TEXT building
        VARCHAR(50) serve
    }
    whole ||--o{ phone : place
    whole {
        VARCHAR(50) place
        DATE audience
    }
    phone ||--o{ how : large
    phone {
        DATE large
        TEXT little
        VARCHAR(50) tell
    }
    how ||--o{ green : audience
    how {
        VARCHAR(50) audience
        DATE cover
    }
    green ||--o{ area : later
    green {
        DATE later
        TEXT them
        VARCHAR(50) by
    }