erDiagram
    agent ||--o{ can : street
    agent {
        DATE street
        TEXT and
        VARCHAR(50) exist
    }
    can ||--o{ hope : poor
    can {
        VARCHAR(50) poor
        DATE action
    }
    hope ||--o{ during : relationship
    hope {
        DATE relationship
        TEXT along
        VARCHAR(50) assume
    }
    during ||--o{ feeling : expect
    during {
        VARCHAR(50) expect
        DATE study
    }
    feeling ||--o{ front : address
    feeling {
        DATE address
        TEXT society
        VARCHAR(50) Mr
    }
    front ||--o{ detail : fight
    front {
        VARCHAR(50) fight
        DATE happy
    }
    detail ||--o{ with : organization
    detail {
        DATE organization
        TEXT fine
        VARCHAR(50) TV
    }
    with ||--o{ board : none
    with {
        VARCHAR(50) none
        DATE place
    }
    board ||--o{ agent : eat
    board {
        DATE eat
        TEXT might
        VARCHAR(50) instead
    }