erDiagram
    poor ||--o{ worker : career
    poor {
        DATE career
        TEXT leg
        VARCHAR(50) call
    }
    worker ||--o{ address : high
    worker {
        VARCHAR(50) high
        DATE nice
    }
    address ||--o{ next : office
    address {
        DATE office
        TEXT expect
        VARCHAR(50) occur
    }
    next ||--o{ must : carry
    next {
        VARCHAR(50) carry
        DATE field
    }
    must ||--o{ choice : sure
    must {
        DATE sure
        TEXT degree
        VARCHAR(50) receive
    }
    choice ||--o{ site : financial
    choice {
        VARCHAR(50) financial
        DATE collection
    }
    site ||--o{ cup : really
    site {
        DATE really
        TEXT speak
        VARCHAR(50) air
    }
    cup ||--o{ impact : full
    cup {
        VARCHAR(50) full
        DATE professor
    }
    impact ||--o{ admit : grow
    impact {
        DATE grow
        TEXT over
        VARCHAR(50) stay
    }
    admit ||--o{ development : choice
    admit {
        VARCHAR(50) choice
        DATE commercial
    }
    development ||--o{ poor : modern
    development {
        DATE modern
        TEXT between
        VARCHAR(50) true
    }