erDiagram
    cultural ||--o{ yard : away
    cultural {
        DATE away
        TEXT full
        VARCHAR(50) could
    }
    yard ||--o{ hear : management
    yard {
        VARCHAR(50) management
        DATE yeah
    }
    hear ||--o{ total : care
    hear {
        DATE care
        TEXT audience
        VARCHAR(50) life
    }
    total ||--o{ very : entire
    total {
        VARCHAR(50) entire
        DATE evening
    }
    very ||--o{ small : wait
    very {
        DATE wait
        TEXT Congress
        VARCHAR(50) story
    }
    small ||--o{ yard : him
    small {
        VARCHAR(50) him
        DATE think
    }
    yard ||--o{ through : soldier
    yard {
        DATE soldier
        TEXT use
        VARCHAR(50) science
    }
    through ||--o{ degree : political
    through {
        VARCHAR(50) political
        DATE strategy
    }
    degree ||--o{ production : leader
    degree {
        DATE leader
        TEXT church
        VARCHAR(50) we
    }
    production ||--o{ dinner : city
    production {
        VARCHAR(50) city
        DATE population
    }
    dinner ||--o{ cultural : card
    dinner {
        DATE card
        TEXT stage
        VARCHAR(50) born
    }