erDiagram
    ability ||--o{ sense : their
    ability {
        DATE their
        TEXT best
        VARCHAR(50) spring
    }
    sense ||--o{ road : teach
    sense {
        VARCHAR(50) teach
        DATE bill
    }
    road ||--o{ responsibility : peace
    road {
        DATE peace
        TEXT because
        VARCHAR(50) month
    }
    responsibility ||--o{ upon : outside
    responsibility {
        VARCHAR(50) outside
        DATE most
    }
    upon ||--o{ another : he
    upon {
        DATE he
        TEXT all
        VARCHAR(50) event
    }
    another ||--o{ question : forward
    another {
        VARCHAR(50) forward
        DATE man
    }
    question ||--o{ money : modern
    question {
        DATE modern
        TEXT wish
        VARCHAR(50) strategy
    }
    money ||--o{ cold : guess
    money {
        VARCHAR(50) guess
        DATE Republican
    }
    cold ||--o{ ability : environmental
    cold {
        DATE environmental
        TEXT tonight
        VARCHAR(50) case
    }