erDiagram
    enough ||--o{ production : partner
    enough {
        DATE partner
        TEXT nor
        VARCHAR(50) travel
    }
    production ||--o{ all : set
    production {
        VARCHAR(50) set
        DATE other
    }
    all ||--o{ offer : somebody
    all {
        DATE somebody
        TEXT particularly
        VARCHAR(50) matter
    }
    offer ||--o{ body : parent
    offer {
        VARCHAR(50) parent
        DATE suddenly
    }
    body ||--o{ ok : material
    body {
        DATE material
        TEXT mean
        VARCHAR(50) state
    }
    ok ||--o{ enough : style
    ok {
        VARCHAR(50) style
        DATE allow
    }