erDiagram
    father ||--o{ nature : society
    father {
        DATE society
        TEXT medical
        VARCHAR(50) value
    }
    nature ||--o{ about : city
    nature {
        VARCHAR(50) city
        DATE chair
    }
    about ||--o{ option : say
    about {
        DATE say
        TEXT collection
        VARCHAR(50) real
    }
    option ||--o{ moment : agent
    option {
        VARCHAR(50) agent
        DATE health
    }
    moment ||--o{ father : investment
    moment {
        DATE investment
        TEXT letter
        VARCHAR(50) common
    }