erDiagram
    establish ||--o{ light : late
    establish {
        DATE late
        TEXT remember
        VARCHAR(50) probably
    }
    light ||--o{ away : security
    light {
        VARCHAR(50) security
        DATE me
    }
    away ||--o{ thing : development
    away {
        DATE development
        TEXT recognize
        VARCHAR(50) feeling
    }
    thing ||--o{ modern : player
    thing {
        VARCHAR(50) player
        DATE nation
    }
    modern ||--o{ herself : reason
    modern {
        DATE reason
        TEXT raise
        VARCHAR(50) forward
    }
    herself ||--o{ down : hundred
    herself {
        VARCHAR(50) hundred
        DATE event
    }
    down ||--o{ my : why
    down {
        DATE why
        TEXT audience
        VARCHAR(50) amount
    }
    my ||--o{ culture : who
    my {
        VARCHAR(50) who
        DATE book
    }
    culture ||--o{ pretty : prevent
    culture {
        DATE prevent
        TEXT minute
        VARCHAR(50) increase
    }
    pretty ||--o{ news : pick
    pretty {
        VARCHAR(50) pick
        DATE public
    }
    news ||--o{ establish : month
    news {
        DATE month
        TEXT entire
        VARCHAR(50) bad
    }