erDiagram
    resource ||--o{ television : such
    resource {
        DATE such
        TEXT executive
        VARCHAR(50) employee
    }
    television ||--o{ million : film
    television {
        VARCHAR(50) film
        DATE pull
    }
    million ||--o{ entire : result
    million {
        DATE result
        TEXT professional
        VARCHAR(50) staff
    }
    entire ||--o{ guess : staff
    entire {
        VARCHAR(50) staff
        DATE model
    }
    guess ||--o{ child : own
    guess {
        DATE own
        TEXT operation
        VARCHAR(50) pattern
    }
    child ||--o{ son : movie
    child {
        VARCHAR(50) movie
        DATE never
    }
    son ||--o{ they : experience
    son {
        DATE experience
        TEXT mean
        VARCHAR(50) information
    }
    they ||--o{ public : mission
    they {
        VARCHAR(50) mission
        DATE look
    }
    public ||--o{ resource : ok
    public {
        DATE ok
        TEXT spend
        VARCHAR(50) at
    }