erDiagram
    member ||--o{ media : continue
    member {
        DATE continue
        TEXT example
        VARCHAR(50) whole
    }
    media ||--o{ family : time
    media {
        VARCHAR(50) time
        DATE lose
    }
    family ||--o{ attorney : mother
    family {
        DATE mother
        TEXT data
        VARCHAR(50) economic
    }
    attorney ||--o{ read : there
    attorney {
        VARCHAR(50) there
        DATE want
    }
    read ||--o{ over : plan
    read {
        DATE plan
        TEXT anything
        VARCHAR(50) prepare
    }
    over ||--o{ wrong : over
    over {
        VARCHAR(50) over
        DATE focus
    }
    wrong ||--o{ manager : black
    wrong {
        DATE black
        TEXT article
        VARCHAR(50) decade
    }
    manager ||--o{ recognize : particularly
    manager {
        VARCHAR(50) particularly
        DATE water
    }
    recognize ||--o{ cup : develop
    recognize {
        DATE develop
        TEXT major
        VARCHAR(50) seem
    }
    cup ||--o{ member : already
    cup {
        VARCHAR(50) already
        DATE west
    }