erDiagram
    lay ||--o{ beat : call
    lay {
        DATE call
        TEXT blue
        VARCHAR(50) hand
    }
    beat ||--o{ tree : suddenly
    beat {
        VARCHAR(50) suddenly
        DATE cut
    }
    tree ||--o{ add : want
    tree {
        DATE want
        TEXT friend
        VARCHAR(50) way
    }
    add ||--o{ hand : show
    add {
        VARCHAR(50) show
        DATE throw
    }
    hand ||--o{ free : we
    hand {
        DATE we
        TEXT gas
        VARCHAR(50) simple
    }
    free ||--o{ account : current
    free {
        VARCHAR(50) current
        DATE result
    }
    account ||--o{ lay : price
    account {
        DATE price
        TEXT single
        VARCHAR(50) level
    }