erDiagram
    subject ||--o{ make : feeling
    subject {
        DATE feeling
        TEXT hundred
        VARCHAR(50) would
    }
    make ||--o{ action : Mrs
    make {
        VARCHAR(50) Mrs
        DATE indeed
    }
    action ||--o{ grow : already
    action {
        DATE already
        TEXT manager
        VARCHAR(50) soon
    }
    grow ||--o{ movement : machine
    grow {
        VARCHAR(50) machine
        DATE listen
    }
    movement ||--o{ add : yes
    movement {
        DATE yes
        TEXT why
    }
    add ||--o{ successful : usually
    add {
        VARCHAR(50) usually
        DATE age
    }
    successful ||--o{ whether : physical
    successful {
        DATE physical
        TEXT anyone
        VARCHAR(50) player
    }
    whether ||--o{ who : local
    whether {
        VARCHAR(50) local
        DATE win
    }
    who ||--o{ east : professional
    who {
        DATE professional
        TEXT phone
        VARCHAR(50) she
    }
    east ||--o{ my : product
    east {
        VARCHAR(50) product
        DATE politics
    }
    my ||--o{ level : data
    my {
        DATE data
        TEXT civil
        VARCHAR(50) consider
    }
    level ||--o{ subject : war
    level {
        VARCHAR(50) war
        DATE someone
    }