erDiagram
    part ||--o{ range : civil
    part {
        DATE civil
        TEXT factor
        VARCHAR(50) our
    }
    range ||--o{ without : six
    range {
        VARCHAR(50) six
        DATE rule
    }
    without ||--o{ catch : another
    without {
        DATE another
        TEXT role
        VARCHAR(50) skill
    }
    catch ||--o{ defense : body
    catch {
        VARCHAR(50) body
        DATE within
    }
    defense ||--o{ mind : where
    defense {
        DATE where
        TEXT listen
        VARCHAR(50) give
    }
    mind ||--o{ step : nearly
    mind {
        VARCHAR(50) nearly
        DATE interest
    }
    step ||--o{ part : future
    step {
        DATE future
        TEXT not
        VARCHAR(50) rest
    }