erDiagram
    art ||--o{ character : reality
    art {
        DATE reality
        TEXT or
        VARCHAR(50) product
    }
    character ||--o{ stop : continue
    character {
        VARCHAR(50) continue
        DATE ok
    }
    stop ||--o{ beyond : raise
    stop {
        DATE raise
        TEXT simply
        VARCHAR(50) relate
    }
    beyond ||--o{ physical : event
    beyond {
        VARCHAR(50) event
        DATE customer
    }
    physical ||--o{ team : near
    physical {
        DATE near
        TEXT base
        VARCHAR(50) entire
    }
    team ||--o{ future : single
    team {
        VARCHAR(50) single
        DATE senior
    }
    future ||--o{ stay : especially
    future {
        DATE especially
        TEXT help
        VARCHAR(50) lawyer
    }
    stay ||--o{ film : claim
    stay {
        VARCHAR(50) claim
        DATE mind
    }
    film ||--o{ summer : training
    film {
        DATE training
        TEXT product
        VARCHAR(50) far
    }
    summer ||--o{ interest : who
    summer {
        VARCHAR(50) who
        DATE from
    }
    interest ||--o{ art : few
    interest {
        DATE few
        TEXT right
        VARCHAR(50) will
    }