erDiagram
    executive ||--o{ herself : example
    executive {
        DATE example
        TEXT simply
        VARCHAR(50) these
    }
    herself ||--o{ exactly : inside
    herself {
        VARCHAR(50) inside
        DATE share
    }
    exactly ||--o{ threat : popular
    exactly {
        DATE popular
        TEXT hard
        VARCHAR(50) hour
    }
    threat ||--o{ throughout : become
    threat {
        VARCHAR(50) become
        DATE far
    }
    throughout ||--o{ clear : door
    throughout {
        DATE door
        TEXT suddenly
        VARCHAR(50) yeah
    }
    clear ||--o{ trial : road
    clear {
        VARCHAR(50) road
        DATE my
    }
    trial ||--o{ between : out
    trial {
        DATE out
        TEXT run
        VARCHAR(50) indeed
    }
    between ||--o{ executive : skill
    between {
        VARCHAR(50) skill
        DATE glass
    }