erDiagram
    any ||--o{ reason : network
    any {
        DATE network
        TEXT evening
        VARCHAR(50) past
    }
    reason ||--o{ law : policy
    reason {
        VARCHAR(50) policy
        DATE first
    }
    law ||--o{ blue : debate
    law {
        DATE debate
        TEXT try
        VARCHAR(50) outside
    }
    blue ||--o{ mission : star
    blue {
        VARCHAR(50) star
        DATE organization
    }
    mission ||--o{ any : summer
    mission {
        DATE summer
        TEXT family
        VARCHAR(50) add
    }