erDiagram
    community ||--o{ concern : many
    community {
        DATE many
        TEXT wide
        VARCHAR(50) pass
    }
    concern ||--o{ traditional : executive
    concern {
        VARCHAR(50) executive
        DATE together
    }
    traditional ||--o{ cell : moment
    traditional {
        DATE moment
        TEXT job
        VARCHAR(50) travel
    }
    cell ||--o{ recently : choice
    cell {
        VARCHAR(50) choice
        DATE somebody
    }
    recently ||--o{ agent : tend
    recently {
        DATE tend
        TEXT ground
        VARCHAR(50) market
    }
    agent ||--o{ girl : we
    agent {
        VARCHAR(50) we
        DATE yet
    }
    girl ||--o{ since : trip
    girl {
        DATE trip
        TEXT really
        VARCHAR(50) near
    }
    since ||--o{ early : black
    since {
        VARCHAR(50) black
        DATE treat
    }
    early ||--o{ exactly : whole
    early {
        DATE whole
        TEXT certainly
        VARCHAR(50) military
    }
    exactly ||--o{ lot : country
    exactly {
        VARCHAR(50) country
        DATE accept
    }
    lot ||--o{ fear : foreign
    lot {
        TEXT someone
        VARCHAR(50) season
    }
    fear ||--o{ community : yourself
    fear {
        VARCHAR(50) yourself
        DATE such
    }