erDiagram
    goal ||--o{ energy : describe
    goal {
        DATE describe
        TEXT nice
        VARCHAR(50) able
    }
    energy ||--o{ during : outside
    energy {
        VARCHAR(50) outside
        DATE science
    }
    during ||--o{ new : reason
    during {
        DATE reason
        TEXT service
        VARCHAR(50) research
    }
    new ||--o{ special : ready
    new {
        VARCHAR(50) ready
        DATE if
    }
    special ||--o{ goal : conference
    special {
        DATE conference
        TEXT politics
        VARCHAR(50) yeah
    }