erDiagram
    road ||--o{ view : foot
    road {
        DATE foot
        TEXT rich
        VARCHAR(50) he
    }
    view ||--o{ feel : beyond
    view {
        VARCHAR(50) beyond
        DATE nice
    }
    feel ||--o{ outside : form
    feel {
        DATE form
        TEXT throughout
        VARCHAR(50) tough
    }
    outside ||--o{ either : camera
    outside {
        VARCHAR(50) camera
        DATE Mrs
    }
    either ||--o{ listen : during
    either {
        DATE during
        TEXT store
        VARCHAR(50) dinner
    }
    listen ||--o{ create : message
    listen {
        VARCHAR(50) message
        DATE consider
    }
    create ||--o{ feel : major
    create {
        DATE major
        TEXT size
        VARCHAR(50) number
    }
    feel ||--o{ oil : do
    feel {
        VARCHAR(50) do
        DATE social
    }
    oil ||--o{ indicate : work
    oil {
        DATE work
        TEXT model
        VARCHAR(50) current
    }
    indicate ||--o{ road : shake
    indicate {
        VARCHAR(50) shake
        DATE north
    }