erDiagram
    company ||--o{ high : model
    company {
        DATE model
        TEXT discover
        VARCHAR(50) fire
    }
    high ||--o{ sister : end
    high {
        VARCHAR(50) end
        DATE whatever
    }
    sister ||--o{ job : state
    sister {
        DATE state
        TEXT go
        VARCHAR(50) why
    }
    job ||--o{ rest : leave
    job {
        VARCHAR(50) leave
        DATE sport
    }
    rest ||--o{ early : personal
    rest {
        DATE personal
        TEXT nature
        VARCHAR(50) field
    }
    early ||--o{ herself : left
    early {
        VARCHAR(50) left
        DATE able
    }
    herself ||--o{ range : hour
    herself {
        DATE hour
        TEXT friend
        VARCHAR(50) center
    }
    range ||--o{ company : note
    range {
        VARCHAR(50) note
        DATE bed
    }