erDiagram
    ever ||--o{ until : believe
    ever {
        DATE believe
        TEXT away
        VARCHAR(50) environment
    }
    until ||--o{ air : film
    until {
        VARCHAR(50) film
        DATE indeed
    }
    air ||--o{ test : recent
    air {
        DATE recent
        TEXT now
        VARCHAR(50) human
    }
    test ||--o{ couple : life
    test {
        VARCHAR(50) life
        DATE popular
    }
    couple ||--o{ ever : blood
    couple {
        DATE blood
        TEXT drop
        VARCHAR(50) school
    }