erDiagram
    rich ||--o{ over : responsibility
    rich {
        DATE responsibility
        TEXT memory
        VARCHAR(50) forward
    }
    over ||--o{ sometimes : nice
    over {
        VARCHAR(50) nice
        DATE bar
    }
    sometimes ||--o{ thing : for
    sometimes {
        DATE for
        TEXT money
        VARCHAR(50) leader
    }
    thing ||--o{ up : feeling
    thing {
        VARCHAR(50) feeling
        DATE table
    }
    up ||--o{ possible : red
    up {
        DATE red
        TEXT national
        VARCHAR(50) onto
    }
    possible ||--o{ phone : third
    possible {
        VARCHAR(50) third
        DATE could
    }
    phone ||--o{ system : sit
    phone {
        DATE sit
        TEXT phone
        VARCHAR(50) couple
    }
    system ||--o{ start : four
    system {
        VARCHAR(50) four
        DATE watch
    }
    start ||--o{ rich : support
    start {
        DATE support
        TEXT nor
        VARCHAR(50) real
    }