erDiagram
    discover ||--o{ break : onto
    discover {
        DATE onto
        TEXT road
        VARCHAR(50) pass
    }
    break ||--o{ in : summer
    break {
        VARCHAR(50) summer
        DATE side
    }
    in ||--o{ here : sure
    in {
        DATE sure
        TEXT bar
        VARCHAR(50) one
    }
    here ||--o{ three : recently
    here {
        VARCHAR(50) recently
        DATE me
    }
    three ||--o{ over : show
    three {
        DATE show
        TEXT budget
        VARCHAR(50) last
    }
    over ||--o{ box : six
    over {
        VARCHAR(50) six
        DATE election
    }
    box ||--o{ recognize : with
    box {
        DATE with
        TEXT would
        VARCHAR(50) travel
    }
    recognize ||--o{ authority : employee
    recognize {
        VARCHAR(50) employee
        DATE attorney
    }
    authority ||--o{ message : other
    authority {
        DATE other
        TEXT whom
        VARCHAR(50) something
    }
    message ||--o{ of : main
    message {
        VARCHAR(50) main
        DATE threat
    }
    of ||--o{ seven : so
    of {
        DATE so
        TEXT third
        VARCHAR(50) prevent
    }
    seven ||--o{ discover : issue
    seven {
        VARCHAR(50) issue
        DATE blood
    }