erDiagram
    gas ||--o{ economic : security
    gas {
        DATE security
        TEXT image
        VARCHAR(50) painting
    }
    economic ||--o{ sense : rich
    economic {
        VARCHAR(50) rich
        DATE usually
    }
    sense ||--o{ test : because
    sense {
        DATE because
        TEXT end
        VARCHAR(50) today
    }
    test ||--o{ president : certain
    test {
        VARCHAR(50) certain
        DATE hour
    }
    president ||--o{ respond : morning
    president {
        DATE morning
        TEXT series
        VARCHAR(50) mouth
    }
    respond ||--o{ form : east
    respond {
        VARCHAR(50) east
        DATE decide
    }
    form ||--o{ citizen : which
    form {
        DATE which
        TEXT art
        VARCHAR(50) away
    }
    citizen ||--o{ gas : nation
    citizen {
        VARCHAR(50) nation
        DATE health
    }