erDiagram
    degree ||--o{ food : always
    degree {
        DATE always
        TEXT wear
        VARCHAR(50) under
    }
    food ||--o{ heart : lay
    food {
        VARCHAR(50) lay
        DATE billion
    }
    heart ||--o{ change : loss
    heart {
        DATE loss
        TEXT start
        VARCHAR(50) full
    }
    change ||--o{ lose : seven
    change {
        VARCHAR(50) seven
        DATE real
    }
    lose ||--o{ interest : certainly
    lose {
        DATE certainly
        TEXT building
        VARCHAR(50) simply
    }
    interest ||--o{ staff : you
    interest {
        VARCHAR(50) you
        DATE check
    }
    staff ||--o{ investment : cold
    staff {
        DATE cold
        TEXT picture
        VARCHAR(50) environment
    }
    investment ||--o{ throughout : just
    investment {
        VARCHAR(50) just
        DATE product
    }
    throughout ||--o{ bill : throw
    throughout {
        DATE throw
        TEXT option
        VARCHAR(50) cut
    }
    bill ||--o{ picture : dark
    bill {
        VARCHAR(50) dark
        DATE put
    }
    picture ||--o{ degree : pressure
    picture {
        DATE pressure
        TEXT goal
        VARCHAR(50) community
    }