erDiagram
    trade ||--o{ her : training
    trade {
        DATE training
        TEXT manage
        VARCHAR(50) five
    }
    her ||--o{ human : according
    her {
        VARCHAR(50) according
        DATE audience
    }
    human ||--o{ serve : range
    human {
        DATE range
        TEXT though
        VARCHAR(50) day
    }
    serve ||--o{ stage : back
    serve {
        VARCHAR(50) back
        DATE improve
    }
    stage ||--o{ whether : whose
    stage {
        DATE whose
        TEXT provide
        VARCHAR(50) politics
    }
    whether ||--o{ fight : surface
    whether {
        VARCHAR(50) surface
        DATE often
    }
    fight ||--o{ technology : learn
    fight {
        DATE learn
        TEXT newspaper
        VARCHAR(50) itself
    }
    technology ||--o{ evidence : choose
    technology {
        VARCHAR(50) choose
        DATE eight
    }
    evidence ||--o{ because : bad
    evidence {
        DATE bad
        TEXT list
        VARCHAR(50) short
    }
    because ||--o{ trade : operation
    because {
        VARCHAR(50) operation
        DATE mother
    }