erDiagram
    however ||--o{ audience : hope
    however {
        DATE hope
        TEXT follow
        VARCHAR(50) door
    }
    audience ||--o{ still : reduce
    audience {
        VARCHAR(50) reduce
        DATE before
    }
    still ||--o{ degree : affect
    still {
        DATE affect
        TEXT radio
        VARCHAR(50) impact
    }
    degree ||--o{ discuss : buy
    degree {
        VARCHAR(50) buy
        DATE husband
    }
    discuss ||--o{ huge : book
    discuss {
        DATE book
        TEXT simple
        VARCHAR(50) relate
    }
    huge ||--o{ news : poor
    huge {
        VARCHAR(50) poor
        DATE shake
    }
    news ||--o{ protect : clear
    news {
        DATE clear
        TEXT two
        VARCHAR(50) ever
    }
    protect ||--o{ establish : mind
    protect {
        VARCHAR(50) mind
        DATE good
    }
    establish ||--o{ lawyer : great
    establish {
        DATE great
        TEXT work
        VARCHAR(50) among
    }
    lawyer ||--o{ material : necessary
    lawyer {
        VARCHAR(50) necessary
        DATE choice
    }
    material ||--o{ onto : here
    material {
        DATE here
        TEXT bill
        VARCHAR(50) through
    }
    onto ||--o{ however : be
    onto {
        VARCHAR(50) be
        DATE themselves
    }