erDiagram
    consider ||--o{ dream : goal
    consider {
        DATE goal
        TEXT agent
        VARCHAR(50) view
    }
    dream ||--o{ politics : play
    dream {
        VARCHAR(50) play
        DATE box
    }
    politics ||--o{ maintain : tend
    politics {
        DATE tend
        TEXT far
        VARCHAR(50) natural
    }
    maintain ||--o{ others : skin
    maintain {
        VARCHAR(50) skin
        DATE trial
    }
    others ||--o{ fire : ready
    others {
        DATE ready
        TEXT whole
        VARCHAR(50) now
    }
    fire ||--o{ consider : billion
    fire {
        VARCHAR(50) billion
        DATE dream
    }