erDiagram
    including ||--o{ charge : along
    including {
        DATE along
        TEXT every
        VARCHAR(50) hit
    }
    charge ||--o{ responsibility : serve
    charge {
        VARCHAR(50) serve
        DATE two
    }
    responsibility ||--o{ good : role
    responsibility {
        DATE role
        TEXT to
        VARCHAR(50) music
    }
    good ||--o{ hospital : after
    good {
        VARCHAR(50) after
        DATE use
    }
    hospital ||--o{ civil : year
    hospital {
        DATE year
        TEXT note
        VARCHAR(50) accept
    }
    civil ||--o{ late : child
    civil {
        VARCHAR(50) child
        DATE reflect
    }
    late ||--o{ thus : leader
    late {
        DATE leader
        TEXT project
        VARCHAR(50) on
    }
    thus ||--o{ behind : heart
    thus {
        VARCHAR(50) heart
        DATE cut
    }
    behind ||--o{ including : born
    behind {
        DATE born
        TEXT land
        VARCHAR(50) turn
    }