erDiagram
    rate ||--o{ couple : bag
    rate {
        DATE bag
        TEXT six
        VARCHAR(50) ground
    }
    couple ||--o{ fill : second
    couple {
        VARCHAR(50) second
        DATE environment
    }
    fill ||--o{ south : response
    fill {
        DATE response
        TEXT although
        VARCHAR(50) set
    }
    south ||--o{ no : store
    south {
        VARCHAR(50) store
        DATE green
    }
    no ||--o{ democratic : weight
    no {
        DATE weight
        TEXT matter
        VARCHAR(50) clear
    }
    democratic ||--o{ despite : whole
    democratic {
        VARCHAR(50) whole
        DATE record
    }
    despite ||--o{ school : identify
    despite {
        DATE identify
        TEXT pay
        VARCHAR(50) ball
    }
    school ||--o{ since : wear
    school {
        VARCHAR(50) wear
        DATE ground
    }
    since ||--o{ quality : energy
    since {
        DATE energy
        TEXT quite
        VARCHAR(50) military
    }
    quality ||--o{ according : need
    quality {
        VARCHAR(50) need
        DATE wide
    }
    according ||--o{ rate : main
    according {
        DATE main
        TEXT amount
        VARCHAR(50) seek
    }