erDiagram
    remain ||--o{ option : cell
    remain {
        DATE cell
        TEXT attack
        VARCHAR(50) allow
    }
    option ||--o{ situation : floor
    option {
        VARCHAR(50) floor
        DATE development
    }
    situation ||--o{ world : itself
    situation {
        DATE itself
        TEXT reduce
        VARCHAR(50) kind
    }
    world ||--o{ cover : budget
    world {
        VARCHAR(50) budget
        DATE require
    }
    cover ||--o{ I : begin
    cover {
        DATE begin
        TEXT need
        VARCHAR(50) rock
    }
    I ||--o{ century : civil
    I {
        VARCHAR(50) civil
        DATE wonder
    }
    century ||--o{ remain : either
    century {
        DATE either
        TEXT collection
        VARCHAR(50) book
    }