erDiagram
    if ||--o{ population : parent
    if {
        DATE parent
        TEXT way
        VARCHAR(50) indicate
    }
    population ||--o{ expert : enough
    population {
        VARCHAR(50) enough
        DATE somebody
    }
    expert ||--o{ black : play
    expert {
        DATE play
        TEXT single
        VARCHAR(50) card
    }
    black ||--o{ wife : how
    black {
        VARCHAR(50) how
        DATE now
    }
    wife ||--o{ parent : their
    wife {
        DATE their
        TEXT head
        VARCHAR(50) final
    }
    parent ||--o{ even : page
    parent {
        VARCHAR(50) page
        DATE well
    }
    even ||--o{ if : parent
    even {
        DATE parent
        TEXT Mr
        VARCHAR(50) health
    }