erDiagram
    name ||--o{ evidence : sign
    name {
        DATE sign
        TEXT follow
        VARCHAR(50) election
    }
    evidence ||--o{ training : hit
    evidence {
        VARCHAR(50) hit
        DATE involve
    }
    training ||--o{ peace : direction
    training {
        DATE direction
        TEXT American
        VARCHAR(50) remember
    }
    peace ||--o{ size : know
    peace {
        VARCHAR(50) know
        DATE arrive
    }
    size ||--o{ other : employee
    size {
        DATE employee
        TEXT system
        VARCHAR(50) hear
    }
    other ||--o{ part : company
    other {
        VARCHAR(50) company
        DATE time
    }
    part ||--o{ nature : wrong
    part {
        DATE wrong
        TEXT glass
        VARCHAR(50) owner
    }
    nature ||--o{ international : rate
    nature {
        VARCHAR(50) rate
        DATE bank
    }
    international ||--o{ name : seven
    international {
        DATE seven
        TEXT wonder
        VARCHAR(50) control
    }