erDiagram
    risk ||--o{ letter : debate
    risk {
        DATE debate
        TEXT analysis
        VARCHAR(50) heavy
    }
    letter ||--o{ old : still
    letter {
        VARCHAR(50) still
        DATE dinner
    }
    old ||--o{ want : now
    old {
        DATE now
        TEXT face
        VARCHAR(50) theory
    }
    want ||--o{ the : character
    want {
        VARCHAR(50) character
        DATE others
    }
    the ||--o{ evidence : about
    the {
        DATE about
        TEXT section
        VARCHAR(50) son
    }
    evidence ||--o{ how : bill
    evidence {
        VARCHAR(50) bill
        DATE receive
    }
    how ||--o{ create : manager
    how {
        DATE manager
        TEXT tonight
        VARCHAR(50) stock
    }
    create ||--o{ risk : husband
    create {
        VARCHAR(50) husband
        DATE cell
    }