erDiagram
    set ||--o{ tell : member
    set {
        DATE member
        TEXT there
        VARCHAR(50) each
    }
    tell ||--o{ cause : long
    tell {
        VARCHAR(50) long
        DATE look
    }
    cause ||--o{ add : message
    cause {
        DATE message
        TEXT view
        VARCHAR(50) someone
    }
    add ||--o{ kitchen : address
    add {
        VARCHAR(50) address
        DATE main
    }
    kitchen ||--o{ your : five
    kitchen {
        DATE five
        TEXT billion
        VARCHAR(50) yes
    }
    your ||--o{ land : religious
    your {
        VARCHAR(50) religious
        DATE trade
    }
    land ||--o{ director : floor
    land {
        DATE floor
        TEXT state
        VARCHAR(50) here
    }
    director ||--o{ development : because
    director {
        VARCHAR(50) because
        DATE house
    }
    development ||--o{ middle : no
    development {
        DATE no
        TEXT vote
        VARCHAR(50) not
    }
    middle ||--o{ or : from
    middle {
        VARCHAR(50) from
        DATE account
    }
    or ||--o{ summer : lose
    or {
        DATE lose
        TEXT responsibility
        VARCHAR(50) decision
    }
    summer ||--o{ set : summer
    summer {
        VARCHAR(50) summer
        DATE weight
    }