erDiagram
    alone ||--o{ century : raise
    alone {
        DATE raise
        TEXT factor
        VARCHAR(50) visit
    }
    century ||--o{ me : tough
    century {
        VARCHAR(50) tough
        DATE large
    }
    me ||--o{ child : security
    me {
        DATE security
        TEXT film
        VARCHAR(50) so
    }
    child ||--o{ technology : produce
    child {
        VARCHAR(50) produce
        DATE material
    }
    technology ||--o{ alone : meet
    technology {
        DATE meet
        TEXT democratic
        VARCHAR(50) step
    }