erDiagram
    watch ||--o{ position : animal
    watch {
        DATE animal
        TEXT article
        VARCHAR(50) water
    }
    position ||--o{ state : similar
    position {
        VARCHAR(50) similar
        DATE hospital
    }
    state ||--o{ then : laugh
    state {
        DATE laugh
        TEXT recognize
        VARCHAR(50) expect
    }
    then ||--o{ water : finally
    then {
        VARCHAR(50) finally
        DATE position
    }
    water ||--o{ cultural : maybe
    water {
        DATE maybe
        TEXT my
        VARCHAR(50) person
    }
    cultural ||--o{ participant : model
    cultural {
        VARCHAR(50) model
        DATE four
    }
    participant ||--o{ yet : break
    participant {
        DATE break
        TEXT fine
        VARCHAR(50) especially
    }
    yet ||--o{ science : pass
    yet {
        VARCHAR(50) pass
        DATE performance
    }
    science ||--o{ watch : wide
    science {
        DATE wide
        TEXT possible
        VARCHAR(50) suddenly
    }