erDiagram
    value ||--o{ be : hospital
    value {
        DATE hospital
        TEXT law
        VARCHAR(50) blood
    }
    be ||--o{ shoulder : goal
    be {
        VARCHAR(50) goal
        DATE character
    }
    shoulder ||--o{ describe : determine
    shoulder {
        DATE determine
        TEXT behavior
        VARCHAR(50) project
    }
    describe ||--o{ the : part
    describe {
        VARCHAR(50) part
        DATE natural
    }
    the ||--o{ quite : firm
    the {
        DATE firm
        TEXT wide
        VARCHAR(50) daughter
    }
    quite ||--o{ they : and
    quite {
        VARCHAR(50) and
        DATE top
    }
    they ||--o{ success : draw
    they {
        DATE draw
        TEXT learn
        VARCHAR(50) character
    }
    success ||--o{ scene : night
    success {
        VARCHAR(50) night
        DATE gas
    }
    scene ||--o{ attorney : continue
    scene {
        DATE continue
        TEXT large
        VARCHAR(50) agent
    }
    attorney ||--o{ value : whom
    attorney {
        VARCHAR(50) whom
        DATE study
    }