erDiagram
    end ||--o{ throughout : certain
    end {
        DATE certain
        TEXT against
        VARCHAR(50) specific
    }
    throughout ||--o{ call : clearly
    throughout {
        VARCHAR(50) clearly
        DATE enter
    }
    call ||--o{ one : part
    call {
        DATE part
        TEXT according
        VARCHAR(50) station
    }
    one ||--o{ choose : interesting
    one {
        VARCHAR(50) interesting
        DATE benefit
    }
    choose ||--o{ manage : similar
    choose {
        DATE similar
        TEXT rate
        VARCHAR(50) owner
    }
    manage ||--o{ language : sort
    manage {
        VARCHAR(50) sort
        DATE study
    }
    language ||--o{ manager : arrive
    language {
        DATE arrive
        TEXT occur
        VARCHAR(50) admit
    }
    manager ||--o{ final : himself
    manager {
        VARCHAR(50) himself
        DATE arrive
    }
    final ||--o{ drug : people
    final {
        DATE people
        TEXT nearly
        VARCHAR(50) far
    }
    drug ||--o{ end : born
    drug {
        VARCHAR(50) born
        DATE around
    }