erDiagram
    real ||--o{ other : successful
    real {
        DATE successful
        TEXT opportunity
        VARCHAR(50) environment
    }
    other ||--o{ speech : read
    other {
        VARCHAR(50) read
        DATE skin
    }
    speech ||--o{ role : seek
    speech {
        DATE seek
        TEXT television
        VARCHAR(50) concern
    }
    role ||--o{ two : center
    role {
        VARCHAR(50) center
        DATE benefit
    }
    two ||--o{ process : surface
    two {
        DATE surface
        TEXT front
        VARCHAR(50) common
    }
    process ||--o{ couple : health
    process {
        VARCHAR(50) health
        DATE wish
    }
    couple ||--o{ real : show
    couple {
        DATE show
        TEXT again
        VARCHAR(50) box
    }