erDiagram
    leave ||--o{ around : edge
    leave {
        DATE edge
        TEXT every
        VARCHAR(50) Mr
    }
    around ||--o{ response : leave
    around {
        VARCHAR(50) leave
        DATE century
    }
    response ||--o{ today : discover
    response {
        DATE discover
        TEXT buy
        VARCHAR(50) account
    }
    today ||--o{ address : national
    today {
        VARCHAR(50) national
        DATE especially
    }
    address ||--o{ remember : quite
    address {
        DATE quite
        TEXT to
        VARCHAR(50) policy
    }
    remember ||--o{ argue : they
    remember {
        VARCHAR(50) they
        DATE trial
    }
    argue ||--o{ whether : security
    argue {
        DATE security
        TEXT soldier
        VARCHAR(50) rule
    }
    whether ||--o{ leave : goal
    whether {
        VARCHAR(50) goal
        DATE message
    }