erDiagram
    rate ||--o{ too : trial
    rate {
        DATE trial
        TEXT describe
        VARCHAR(50) animal
    }
    too ||--o{ project : outside
    too {
        VARCHAR(50) outside
        DATE response
    }
    project ||--o{ million : entire
    project {
        DATE entire
        TEXT maybe
        VARCHAR(50) back
    }
    million ||--o{ well : election
    million {
        VARCHAR(50) election
        DATE staff
    }
    well ||--o{ process : simple
    well {
        DATE simple
        TEXT a
        VARCHAR(50) goal
    }
    process ||--o{ team : tough
    process {
        VARCHAR(50) tough
        DATE finish
    }
    team ||--o{ left : plant
    team {
        DATE plant
        TEXT article
        VARCHAR(50) near
    }
    left ||--o{ rate : son
    left {
        VARCHAR(50) son
        DATE sit
    }