erDiagram
    wall ||--o{ camera : agree
    wall {
        DATE agree
        TEXT stock
        VARCHAR(50) discover
    }
    camera ||--o{ improve : democratic
    camera {
        VARCHAR(50) democratic
        DATE in
    }
    improve ||--o{ light : decade
    improve {
        DATE decade
        TEXT picture
        VARCHAR(50) event
    }
    light ||--o{ soldier : majority
    light {
        VARCHAR(50) majority
        DATE behavior
    }
    soldier ||--o{ wall : street
    soldier {
        DATE street
        TEXT open
        VARCHAR(50) carry
    }