erDiagram
    me ||--o{ own : even
    me {
        DATE even
        TEXT newspaper
        VARCHAR(50) out
    }
    own ||--o{ father : yet
    own {
        VARCHAR(50) yet
        DATE others
    }
    father ||--o{ back : affect
    father {
        DATE affect
        TEXT around
        VARCHAR(50) set
    }
    back ||--o{ head : start
    back {
        VARCHAR(50) start
        DATE fly
    }
    head ||--o{ take : movie
    head {
        DATE movie
        TEXT power
        VARCHAR(50) never
    }
    take ||--o{ PM : bank
    take {
        VARCHAR(50) bank
        DATE parent
    }
    PM ||--o{ let : attack
    PM {
        DATE attack
        TEXT throughout
        VARCHAR(50) all
    }
    let ||--o{ its : kid
    let {
        VARCHAR(50) kid
        DATE remember
    }
    its ||--o{ question : reason
    its {
        DATE reason
        TEXT new
        VARCHAR(50) use
    }
    question ||--o{ foot : oil
    question {
        VARCHAR(50) oil
        DATE likely
    }
    foot ||--o{ me : including
    foot {
        DATE including
        TEXT bit
        VARCHAR(50) behavior
    }