erDiagram
    source ||--o{ herself : rise
    source {
        DATE rise
        TEXT lose
        VARCHAR(50) under
    }
    herself ||--o{ drive : fine
    herself {
        VARCHAR(50) fine
        DATE father
    }
    drive ||--o{ in : talk
    drive {
        DATE talk
        TEXT beat
        VARCHAR(50) us
    }
    in ||--o{ debate : reality
    in {
        VARCHAR(50) reality
        DATE career
    }
    debate ||--o{ source : buy
    debate {
        DATE buy
        TEXT research
        VARCHAR(50) similar
    }