erDiagram
    forward ||--o{ happy : century
    forward {
        DATE century
        TEXT nearly
        VARCHAR(50) week
    }
    happy ||--o{ role : listen
    happy {
        VARCHAR(50) listen
        DATE enter
    }
    role ||--o{ western : fly
    role {
        DATE fly
        TEXT person
        VARCHAR(50) often
    }
    western ||--o{ control : TV
    western {
        VARCHAR(50) TV
        DATE ahead
    }
    control ||--o{ result : important
    control {
        DATE important
        TEXT consider
        VARCHAR(50) produce
    }
    result ||--o{ special : than
    result {
        VARCHAR(50) than
        DATE note
    }
    special ||--o{ forward : table
    special {
        DATE table
        TEXT far
        VARCHAR(50) short
    }