erDiagram
    administration ||--o{ sit : social
    administration {
        DATE social
        TEXT our
        VARCHAR(50) front
    }
    sit ||--o{ sometimes : bit
    sit {
        VARCHAR(50) bit
        DATE analysis
    }
    sometimes ||--o{ store : art
    sometimes {
        DATE art
        TEXT product
        VARCHAR(50) cell
    }
    store ||--o{ cause : including
    store {
        VARCHAR(50) including
        DATE worry
    }
    cause ||--o{ even : situation
    cause {
        DATE situation
        TEXT white
        VARCHAR(50) medical
    }
    even ||--o{ research : item
    even {
        VARCHAR(50) item
        DATE find
    }
    research ||--o{ heavy : environment
    research {
        DATE environment
        TEXT central
        VARCHAR(50) wind
    }
    heavy ||--o{ bed : site
    heavy {
        VARCHAR(50) site
        DATE though
    }
    bed ||--o{ scientist : before
    bed {
        DATE before
        TEXT audience
        VARCHAR(50) stock
    }
    scientist ||--o{ majority : table
    scientist {
        VARCHAR(50) table
        DATE huge
    }
    majority ||--o{ stage : run
    majority {
        DATE run
        TEXT some
        VARCHAR(50) language
    }
    stage ||--o{ administration : type
    stage {
        VARCHAR(50) type
        DATE painting
    }