erDiagram
    tonight ||--o{ activity : manager
    tonight {
        DATE manager
        TEXT agree
        VARCHAR(50) get
    }
    activity ||--o{ business : upon
    activity {
        VARCHAR(50) upon
        DATE church
    }
    business ||--o{ several : point
    business {
        DATE point
        TEXT professional
        VARCHAR(50) dog
    }
    several ||--o{ former : easy
    several {
        VARCHAR(50) easy
        DATE and
    }
    former ||--o{ tonight : article
    former {
        DATE article
        TEXT standard
        VARCHAR(50) quality
    }