erDiagram
    price ||--o{ her : pay
    price {
        DATE pay
        TEXT southern
        VARCHAR(50) develop
    }
    her ||--o{ nature : describe
    her {
        VARCHAR(50) describe
        DATE possible
    }
    nature ||--o{ information : table
    nature {
        DATE table
        TEXT actually
        VARCHAR(50) business
    }
    information ||--o{ maybe : fall
    information {
        VARCHAR(50) fall
        DATE way
    }
    maybe ||--o{ building : participant
    maybe {
        DATE participant
        TEXT real
        VARCHAR(50) show
    }
    building ||--o{ somebody : crime
    building {
        VARCHAR(50) crime
        DATE painting
    }
    somebody ||--o{ price : ever
    somebody {
        DATE ever
        TEXT performance
        VARCHAR(50) response
    }