erDiagram
    simple ||--o{ strategy : water
    simple {
        DATE water
        TEXT card
        VARCHAR(50) ok
    }
    strategy ||--o{ animal : nor
    strategy {
        VARCHAR(50) nor
        DATE onto
    }
    animal ||--o{ Republican : industry
    animal {
        DATE industry
        TEXT decade
        VARCHAR(50) voice
    }
    Republican ||--o{ pretty : right
    Republican {
        VARCHAR(50) right
        DATE whose
    }
    pretty ||--o{ though : ten
    pretty {
        DATE ten
        TEXT usually
        VARCHAR(50) ahead
    }
    though ||--o{ statement : bar
    though {
        VARCHAR(50) bar
        DATE debate
    }
    statement ||--o{ foreign : cause
    statement {
        DATE cause
        TEXT nice
        VARCHAR(50) woman
    }
    foreign ||--o{ their : today
    foreign {
        VARCHAR(50) today
        DATE ever
    }
    their ||--o{ simple : choice
    their {
        DATE choice
        TEXT better
        VARCHAR(50) sense
    }