erDiagram
    check ||--o{ few : already
    check {
        DATE already
        TEXT music
        VARCHAR(50) health
    }
    few ||--o{ girl : say
    few {
        VARCHAR(50) say
        DATE already
    }
    girl ||--o{ cover : gas
    girl {
        DATE gas
        TEXT hear
        VARCHAR(50) part
    }
    cover ||--o{ order : type
    cover {
        VARCHAR(50) type
        DATE eight
    }
    order ||--o{ forget : another
    order {
        DATE another
        TEXT two
        VARCHAR(50) time
    }
    forget ||--o{ check : body
    forget {
        VARCHAR(50) body
        DATE although
    }