erDiagram
    fire ||--o{ two : argue
    fire {
        DATE argue
        TEXT inside
        VARCHAR(50) something
    }
    two ||--o{ drop : executive
    two {
        VARCHAR(50) executive
        DATE old
    }
    drop ||--o{ weight : understand
    drop {
        DATE understand
        TEXT buy
        VARCHAR(50) billion
    }
    weight ||--o{ open : Mr
    weight {
        VARCHAR(50) Mr
        DATE sense
    }
    open ||--o{ yard : up
    open {
        DATE up
        TEXT for
        VARCHAR(50) artist
    }
    yard ||--o{ seem : mission
    yard {
        VARCHAR(50) mission
        DATE staff
    }
    seem ||--o{ apply : song
    seem {
        DATE song
        TEXT forget
        VARCHAR(50) federal
    }
    apply ||--o{ business : data
    apply {
        VARCHAR(50) data
        DATE model
    }
    business ||--o{ activity : culture
    business {
        DATE culture
        TEXT mean
        VARCHAR(50) strategy
    }
    activity ||--o{ war : final
    activity {
        VARCHAR(50) final
        DATE of
    }
    war ||--o{ fire : cold
    war {
        DATE cold
        TEXT matter
        VARCHAR(50) option
    }