erDiagram
    hot ||--o{ summer : action
    hot {
        DATE action
        TEXT political
        VARCHAR(50) include
    }
    summer ||--o{ PM : citizen
    summer {
        VARCHAR(50) citizen
        DATE probably
    }
    PM ||--o{ buy : rich
    PM {
        DATE rich
        TEXT either
        VARCHAR(50) suddenly
    }
    buy ||--o{ establish : walk
    buy {
        VARCHAR(50) walk
        DATE positive
    }
    establish ||--o{ might : find
    establish {
        DATE find
        TEXT president
        VARCHAR(50) sea
    }
    might ||--o{ outside : according
    might {
        VARCHAR(50) according
        DATE act
    }
    outside ||--o{ get : remember
    outside {
        DATE remember
        TEXT area
        VARCHAR(50) big
    }
    get ||--o{ take : believe
    get {
        VARCHAR(50) believe
        DATE method
    }
    take ||--o{ for : everybody
    take {
        DATE everybody
        TEXT rock
        VARCHAR(50) career
    }
    for ||--o{ hot : some
    for {
        VARCHAR(50) some
        DATE product
    }