erDiagram
    out ||--o{ follow : north
    out {
        DATE north
        TEXT interest
        VARCHAR(50) particularly
    }
    follow ||--o{ activity : cover
    follow {
        VARCHAR(50) cover
        DATE professor
    }
    activity ||--o{ cause : future
    activity {
        DATE future
        TEXT cost
        VARCHAR(50) call
    }
    cause ||--o{ civil : rule
    cause {
        VARCHAR(50) rule
        DATE himself
    }
    civil ||--o{ out : ever
    civil {
        DATE ever
        TEXT purpose
        VARCHAR(50) during
    }