erDiagram
    fill ||--o{ point : choose
    fill {
        DATE choose
        TEXT you
        VARCHAR(50) sing
    }
    point ||--o{ scientist : room
    point {
        VARCHAR(50) room
        DATE level
    }
    scientist ||--o{ wrong : young
    scientist {
        DATE young
        TEXT grow
        VARCHAR(50) field
    }
    wrong ||--o{ matter : economy
    wrong {
        VARCHAR(50) economy
        DATE spend
    }
    matter ||--o{ candidate : sit
    matter {
        DATE sit
        TEXT specific
        VARCHAR(50) hotel
    }
    candidate ||--o{ upon : finish
    candidate {
        VARCHAR(50) finish
        DATE control
    }
    upon ||--o{ charge : program
    upon {
        DATE program
        TEXT according
        VARCHAR(50) born
    }
    charge ||--o{ agreement : issue
    charge {
        VARCHAR(50) issue
        DATE third
    }
    agreement ||--o{ employee : front
    agreement {
        DATE front
        TEXT building
        VARCHAR(50) movement
    }
    employee ||--o{ fill : western
    employee {
        VARCHAR(50) western
        DATE husband
    }