erDiagram
    when ||--o{ garden : production
    when {
        DATE production
        TEXT investment
        VARCHAR(50) article
    }
    garden ||--o{ out : seek
    garden {
        VARCHAR(50) seek
        DATE action
    }
    out ||--o{ society : available
    out {
        DATE available
        TEXT raise
        VARCHAR(50) material
    }
    society ||--o{ pay : once
    society {
        VARCHAR(50) once
        DATE face
    }
    pay ||--o{ physical : rich
    pay {
        DATE rich
        TEXT month
        VARCHAR(50) short
    }
    physical ||--o{ together : toward
    physical {
        VARCHAR(50) toward
        DATE control
    }
    together ||--o{ score : almost
    together {
        DATE almost
        TEXT direction
        VARCHAR(50) simply
    }
    score ||--o{ box : nearly
    score {
        VARCHAR(50) nearly
        DATE piece
    }
    box ||--o{ when : range
    box {
        DATE range
        TEXT Congress
        VARCHAR(50) great
    }