erDiagram
    on ||--o{ coach : field
    on {
        DATE field
        TEXT will
        VARCHAR(50) tend
    }
    coach ||--o{ yard : right
    coach {
        VARCHAR(50) right
        DATE shake
    }
    yard ||--o{ prove : available
    yard {
        DATE available
        TEXT situation
        VARCHAR(50) have
    }
    prove ||--o{ myself : deal
    prove {
        VARCHAR(50) deal
        DATE investment
    }
    myself ||--o{ training : almost
    myself {
        DATE almost
        TEXT push
        VARCHAR(50) save
    }
    training ||--o{ card : produce
    training {
        VARCHAR(50) produce
        DATE short
    }
    card ||--o{ place : father
    card {
        DATE father
        TEXT operation
        VARCHAR(50) sense
    }
    place ||--o{ student : hair
    place {
        VARCHAR(50) hair
        DATE think
    }
    student ||--o{ back : alone
    student {
        DATE alone
        TEXT minute
        VARCHAR(50) whatever
    }
    back ||--o{ mention : possible
    back {
        VARCHAR(50) possible
        DATE produce
    }
    mention ||--o{ on : necessary
    mention {
        DATE necessary
        TEXT because
        VARCHAR(50) traditional
    }