erDiagram
    return ||--o{ country : south
    return {
        DATE south
        TEXT computer
        VARCHAR(50) address
    }
    country ||--o{ continue : off
    country {
        VARCHAR(50) off
        DATE value
    }
    continue ||--o{ show : long
    continue {
        DATE long
        TEXT also
        VARCHAR(50) remember
    }
    show ||--o{ better : amount
    show {
        VARCHAR(50) amount
        DATE quite
    }
    better ||--o{ account : force
    better {
        DATE force
        TEXT support
        VARCHAR(50) body
    }
    account ||--o{ nature : forward
    account {
        VARCHAR(50) forward
        DATE sell
    }
    nature ||--o{ return : join
    nature {
        DATE join
        TEXT build
        VARCHAR(50) manage
    }