erDiagram
    three ||--o{ building : heart
    three {
        DATE heart
        TEXT guess
        VARCHAR(50) realize
    }
    building ||--o{ nice : town
    building {
        VARCHAR(50) town
        DATE occur
    }
    nice ||--o{ care : indicate
    nice {
        DATE indicate
        TEXT consumer
        VARCHAR(50) debate
    }
    care ||--o{ style : begin
    care {
        VARCHAR(50) begin
        DATE fast
    }
    style ||--o{ owner : though
    style {
        DATE though
        TEXT late
        VARCHAR(50) kind
    }
    owner ||--o{ rest : record
    owner {
        VARCHAR(50) record
        DATE any
    }
    rest ||--o{ three : table
    rest {
        DATE table
        TEXT individual
        VARCHAR(50) point
    }