erDiagram
    really ||--o{ cost : road
    really {
        DATE road
        TEXT different
        VARCHAR(50) many
    }
    cost ||--o{ important : chair
    cost {
        VARCHAR(50) chair
        DATE receive
    }
    important ||--o{ subject : give
    important {
        DATE give
        TEXT accept
        VARCHAR(50) rise
    }
    subject ||--o{ thought : actually
    subject {
        VARCHAR(50) actually
        DATE quite
    }
    thought ||--o{ within : even
    thought {
        DATE even
        TEXT mouth
        VARCHAR(50) minute
    }
    within ||--o{ really : skin
    within {
        VARCHAR(50) skin
        DATE them
    }