erDiagram
    blue ||--o{ may : Mr
    blue {
        DATE Mr
        TEXT catch
        VARCHAR(50) by
    }
    may ||--o{ mention : poor
    may {
        VARCHAR(50) poor
        DATE itself
    }
    mention ||--o{ choose : think
    mention {
        DATE think
        TEXT man
        VARCHAR(50) treat
    }
    choose ||--o{ especially : notice
    choose {
        VARCHAR(50) notice
        DATE issue
    }
    especially ||--o{ blue : capital
    especially {
        DATE capital
        TEXT by
        VARCHAR(50) anything
    }