erDiagram
    person ||--o{ perform : beyond
    person {
        DATE beyond
        TEXT attorney
        VARCHAR(50) spring
    }
    perform ||--o{ lawyer : coach
    perform {
        VARCHAR(50) coach
        DATE go
    }
    lawyer ||--o{ close : sport
    lawyer {
        DATE sport
        TEXT serious
        VARCHAR(50) nothing
    }
    close ||--o{ wall : build
    close {
        VARCHAR(50) build
        DATE deal
    }
    wall ||--o{ person : floor
    wall {
        DATE floor
        TEXT military
        VARCHAR(50) spend
    }