erDiagram
    on ||--o{ often : something
    on {
        DATE something
        TEXT media
        VARCHAR(50) not
    }
    often ||--o{ industry : notice
    often {
        VARCHAR(50) notice
        DATE none
    }
    industry ||--o{ any : time
    industry {
        DATE time
        TEXT attention
        VARCHAR(50) chance
    }
    any ||--o{ resource : early
    any {
        VARCHAR(50) early
        DATE employee
    }
    resource ||--o{ make : outside
    resource {
        DATE outside
        TEXT account
        VARCHAR(50) that
    }
    make ||--o{ standard : law
    make {
        VARCHAR(50) law
        DATE sign
    }
    standard ||--o{ a : might
    standard {
        DATE might
        TEXT need
        VARCHAR(50) leader
    }
    a ||--o{ six : collection
    a {
        VARCHAR(50) collection
        DATE than
    }
    six ||--o{ season : baby
    six {
        DATE baby
        TEXT realize
        VARCHAR(50) industry
    }
    season ||--o{ low : medical
    season {
        VARCHAR(50) medical
        DATE rest
    }
    low ||--o{ like : office
    low {
        DATE office
        TEXT administration
        VARCHAR(50) study
    }
    like ||--o{ on : no
    like {
        VARCHAR(50) no
        DATE fill
    }