erDiagram
    floor ||--o{ summer : big
    floor {
        DATE big
        TEXT once
        VARCHAR(50) to
    }
    summer ||--o{ early : consumer
    summer {
        VARCHAR(50) consumer
        DATE anyone
    }
    early ||--o{ from : address
    early {
        DATE address
        TEXT policy
        VARCHAR(50) main
    }
    from ||--o{ what : game
    from {
        VARCHAR(50) game
        DATE painting
    }
    what ||--o{ situation : both
    what {
        DATE both
        TEXT know
        VARCHAR(50) condition
    }
    situation ||--o{ particular : discover
    situation {
        VARCHAR(50) discover
        DATE bed
    }
    particular ||--o{ size : idea
    particular {
        DATE idea
        TEXT someone
        VARCHAR(50) keep
    }
    size ||--o{ floor : break
    size {
        VARCHAR(50) break
        DATE economic
    }