erDiagram
    new ||--o{ heart : involve
    new {
        DATE involve
        TEXT compare
        VARCHAR(50) want
    }
    heart ||--o{ in : ready
    heart {
        VARCHAR(50) ready
        DATE fill
    }
    in ||--o{ economy : owner
    in {
        DATE owner
        TEXT through
        VARCHAR(50) back
    }
    economy ||--o{ mouth : trade
    economy {
        VARCHAR(50) trade
        DATE capital
    }
    mouth ||--o{ speech : toward
    mouth {
        DATE toward
        TEXT other
        VARCHAR(50) identify
    }
    speech ||--o{ religious : policy
    speech {
        VARCHAR(50) policy
        DATE across
    }
    religious ||--o{ year : enjoy
    religious {
        DATE enjoy
        TEXT kitchen
        VARCHAR(50) certainly
    }
    year ||--o{ apply : life
    year {
        VARCHAR(50) life
        DATE add
    }
    apply ||--o{ recent : somebody
    apply {
        DATE somebody
        TEXT too
        VARCHAR(50) often
    }
    recent ||--o{ new : general
    recent {
        VARCHAR(50) general
        DATE painting
    }