erDiagram
    bit ||--o{ ten : campaign
    bit {
        DATE campaign
        TEXT enjoy
        VARCHAR(50) into
    }
    ten ||--o{ into : stage
    ten {
        VARCHAR(50) stage
        DATE police
    }
    into ||--o{ middle : anyone
    into {
        DATE anyone
        TEXT kid
        VARCHAR(50) our
    }
    middle ||--o{ deal : debate
    middle {
        VARCHAR(50) debate
        DATE deep
    }
    deal ||--o{ bit : central
    deal {
        DATE central
        TEXT reality
        VARCHAR(50) admit
    }