erDiagram
    class ||--o{ across : stuff
    class {
        DATE stuff
        TEXT contain
        VARCHAR(50) measure
    }
    across ||--o{ no : individual
    across {
        VARCHAR(50) individual
        DATE same
    }
    no ||--o{ total : number
    no {
        DATE number
        TEXT west
        VARCHAR(50) series
    }
    total ||--o{ for : explain
    total {
        VARCHAR(50) explain
        DATE building
    }
    for ||--o{ remain : individual
    for {
        DATE individual
        TEXT season
        VARCHAR(50) sing
    }
    remain ||--o{ fill : center
    remain {
        VARCHAR(50) center
        DATE institution
    }
    fill ||--o{ about : likely
    fill {
        DATE likely
        TEXT common
        VARCHAR(50) address
    }
    about ||--o{ none : window
    about {
        VARCHAR(50) window
        DATE identify
    }
    none ||--o{ close : recent
    none {
        DATE recent
        TEXT blue
        VARCHAR(50) radio
    }
    close ||--o{ matter : knowledge
    close {
        VARCHAR(50) knowledge
        DATE pick
    }
    matter ||--o{ name : teach
    matter {
        DATE teach
        TEXT east
        VARCHAR(50) gun
    }
    name ||--o{ class : member
    name {
        VARCHAR(50) member
        DATE contain
    }