erDiagram
    five ||--o{ debate : church
    five {
        DATE church
        TEXT behavior
        VARCHAR(50) suggest
    }
    debate ||--o{ newspaper : shake
    debate {
        VARCHAR(50) shake
        DATE though
    }
    newspaper ||--o{ development : just
    newspaper {
        DATE just
        TEXT statement
        VARCHAR(50) best
    }
    development ||--o{ article : indicate
    development {
        VARCHAR(50) indicate
        DATE quality
    }
    article ||--o{ act : recognize
    article {
        DATE recognize
        TEXT debate
        VARCHAR(50) receive
    }
    act ||--o{ five : woman
    act {
        VARCHAR(50) woman
        DATE kid
    }