erDiagram
    draw ||--o{ soldier : thought
    draw {
        DATE thought
        TEXT red
        VARCHAR(50) there
    }
    soldier ||--o{ culture : popular
    soldier {
        VARCHAR(50) popular
        DATE answer
    }
    culture ||--o{ senior : cut
    culture {
        DATE cut
        TEXT follow
        VARCHAR(50) rock
    }
    senior ||--o{ attack : exist
    senior {
        VARCHAR(50) exist
        DATE better
    }
    attack ||--o{ evidence : truth
    attack {
        DATE truth
        TEXT total
        VARCHAR(50) few
    }
    evidence ||--o{ draw : top
    evidence {
        VARCHAR(50) top
        DATE rule
    }
    draw ||--o{ artist : issue
    draw {
        DATE issue
        TEXT truth
        VARCHAR(50) set
    }
    artist ||--o{ defense : myself
    artist {
        VARCHAR(50) myself
        DATE tough
    }
    defense ||--o{ draw : high
    defense {
        DATE high
        TEXT light
        VARCHAR(50) final
    }