erDiagram
    entire ||--o{ sport : threat
    entire {
        DATE threat
        TEXT write
        VARCHAR(50) state
    }
    sport ||--o{ such : writer
    sport {
        VARCHAR(50) writer
        DATE something
    }
    such ||--o{ whom : six
    such {
        DATE six
        TEXT great
        VARCHAR(50) economic
    }
    whom ||--o{ dark : impact
    whom {
        VARCHAR(50) impact
        DATE especially
    }
    dark ||--o{ entire : green
    dark {
        DATE green
        TEXT year
        VARCHAR(50) sort
    }