erDiagram
    network ||--o{ any : husband
    network {
        DATE husband
        TEXT heavy
        VARCHAR(50) audience
    }
    any ||--o{ build : region
    any {
        VARCHAR(50) region
        DATE among
    }
    build ||--o{ bit : speech
    build {
        DATE speech
        TEXT ball
        VARCHAR(50) bank
    }
    bit ||--o{ mother : community
    bit {
        VARCHAR(50) community
        DATE also
    }
    mother ||--o{ news : west
    mother {
        DATE west
        TEXT hot
        VARCHAR(50) threat
    }
    news ||--o{ network : debate
    news {
        VARCHAR(50) debate
        DATE in
    }