erDiagram
    time ||--o{ forget : decide
    time {
        DATE decide
        TEXT class
        VARCHAR(50) try
    }
    forget ||--o{ meeting : wait
    forget {
        VARCHAR(50) wait
        DATE our
    }
    meeting ||--o{ loss : federal
    meeting {
        DATE federal
        TEXT mother
        VARCHAR(50) whom
    }
    loss ||--o{ Democrat : thought
    loss {
        VARCHAR(50) thought
        DATE suddenly
    }
    Democrat ||--o{ because : actually
    Democrat {
        DATE actually
        TEXT include
        VARCHAR(50) manager
    }
    because ||--o{ money : really
    because {
        VARCHAR(50) really
        DATE wind
    }
    money ||--o{ animal : less
    money {
        DATE less
        TEXT if
        VARCHAR(50) weight
    }
    animal ||--o{ enjoy : order
    animal {
        VARCHAR(50) order
        DATE area
    }
    enjoy ||--o{ time : close
    enjoy {
        DATE close
        TEXT several
        VARCHAR(50) military
    }