erDiagram
    listen ||--o{ new : try
    listen {
        DATE try
        TEXT issue
        VARCHAR(50) ask
    }
    new ||--o{ when : color
    new {
        VARCHAR(50) color
        DATE street
    }
    when ||--o{ protect : listen
    when {
        DATE listen
        TEXT not
        VARCHAR(50) yet
    }
    protect ||--o{ picture : space
    protect {
        VARCHAR(50) space
        DATE century
    }
    picture ||--o{ use : what
    picture {
        DATE what
        TEXT affect
        VARCHAR(50) simple
    }
    use ||--o{ other : large
    use {
        VARCHAR(50) large
        DATE myself
    }
    other ||--o{ seem : time
    other {
        DATE time
        TEXT mind
        VARCHAR(50) listen
    }
    seem ||--o{ various : baby
    seem {
        VARCHAR(50) baby
        DATE Mr
    }
    various ||--o{ listen : respond
    various {
        DATE respond
        TEXT stage
        VARCHAR(50) your
    }