erDiagram
    person ||--o{ radio : firm
    person {
        DATE firm
        TEXT American
        VARCHAR(50) green
    }
    radio ||--o{ respond : record
    radio {
        VARCHAR(50) record
        DATE talk
    }
    respond ||--o{ bar : age
    respond {
        DATE age
        TEXT still
        VARCHAR(50) positive
    }
    bar ||--o{ occur : stock
    bar {
        VARCHAR(50) stock
        DATE hair
    }
    occur ||--o{ safe : over
    occur {
        DATE over
        TEXT such
        VARCHAR(50) professor
    }
    safe ||--o{ person : according
    safe {
        VARCHAR(50) according
        DATE inside
    }