erDiagram
    often ||--o{ along : position
    often {
        DATE position
        TEXT actually
        VARCHAR(50) large
    }
    along ||--o{ dinner : seek
    along {
        VARCHAR(50) seek
        DATE arrive
    }
    dinner ||--o{ few : key
    dinner {
        DATE key
        TEXT will
        VARCHAR(50) better
    }
    few ||--o{ discussion : right
    few {
        VARCHAR(50) right
        DATE arm
    }
    discussion ||--o{ machine : thing
    discussion {
        DATE thing
        TEXT always
        VARCHAR(50) seat
    }
    machine ||--o{ even : two
    machine {
        VARCHAR(50) two
        DATE girl
    }
    even ||--o{ often : over
    even {
        DATE over
        TEXT usually
        VARCHAR(50) plan
    }