erDiagram
    seek ||--o{ body : suddenly
    seek {
        DATE suddenly
        TEXT than
        VARCHAR(50) see
    }
    body ||--o{ other : still
    body {
        VARCHAR(50) still
        DATE still
    }
    other ||--o{ benefit : station
    other {
        DATE station
        TEXT debate
        VARCHAR(50) class
    }
    benefit ||--o{ almost : politics
    benefit {
        VARCHAR(50) politics
        DATE better
    }
    almost ||--o{ end : apply
    almost {
        DATE apply
        TEXT clear
        VARCHAR(50) small
    }
    end ||--o{ prove : size
    end {
        VARCHAR(50) size
        DATE say
    }
    prove ||--o{ along : morning
    prove {
        DATE morning
        TEXT evening
        VARCHAR(50) contain
    }
    along ||--o{ concern : let
    along {
        VARCHAR(50) let
        DATE authority
    }
    concern ||--o{ which : image
    concern {
        DATE image
        TEXT city
        VARCHAR(50) pressure
    }
    which ||--o{ our : security
    which {
        VARCHAR(50) security
        DATE get
    }
    our ||--o{ administration : cost
    our {
        DATE cost
        TEXT local
        VARCHAR(50) southern
    }
    administration ||--o{ seek : remember
    administration {
        VARCHAR(50) remember
        DATE sea
    }