erDiagram
    offer ||--o{ develop : face
    offer {
        DATE face
        TEXT star
        VARCHAR(50) without
    }
    develop ||--o{ throw : theory
    develop {
        VARCHAR(50) theory
        DATE strategy
    }
    throw ||--o{ develop : bag
    throw {
        DATE bag
        TEXT happen
        VARCHAR(50) nor
    }
    develop ||--o{ main : real
    develop {
        VARCHAR(50) real
        DATE beautiful
    }
    main ||--o{ late : recent
    main {
        DATE recent
        TEXT whose
        VARCHAR(50) charge
    }
    late ||--o{ three : great
    late {
        VARCHAR(50) great
        DATE out
    }
    three ||--o{ offer : father
    three {
        DATE father
        TEXT job
        VARCHAR(50) reveal
    }