erDiagram
    easy ||--o{ age : citizen
    easy {
        DATE citizen
        TEXT smile
        VARCHAR(50) expect
    }
    age ||--o{ home : decision
    age {
        VARCHAR(50) decision
        DATE write
    }
    home ||--o{ south : yourself
    home {
        DATE yourself
        TEXT order
        VARCHAR(50) whatever
    }
    south ||--o{ part : animal
    south {
        VARCHAR(50) animal
        DATE between
    }
    part ||--o{ catch : reason
    part {
        DATE reason
        TEXT ground
        VARCHAR(50) beautiful
    }
    catch ||--o{ success : help
    catch {
        VARCHAR(50) help
        DATE itself
    }
    success ||--o{ race : person
    success {
        DATE person
        TEXT stuff
        VARCHAR(50) become
    }
    race ||--o{ sister : sometimes
    race {
        VARCHAR(50) sometimes
        DATE much
    }
    sister ||--o{ final : though
    sister {
        DATE though
        TEXT yourself
        VARCHAR(50) range
    }
    final ||--o{ easy : result
    final {
        VARCHAR(50) result
        DATE final
    }