erDiagram
    measure ||--o{ even : price
    measure {
        DATE price
        TEXT arm
        VARCHAR(50) serve
    }
    even ||--o{ trade : challenge
    even {
        VARCHAR(50) challenge
        DATE significant
    }
    trade ||--o{ performance : stay
    trade {
        DATE stay
        TEXT away
        VARCHAR(50) discuss
    }
    performance ||--o{ challenge : audience
    performance {
        VARCHAR(50) audience
        DATE table
    }
    challenge ||--o{ stay : area
    challenge {
        DATE area
        TEXT own
        VARCHAR(50) film
    }
    stay ||--o{ oil : majority
    stay {
        VARCHAR(50) majority
        DATE continue
    }
    oil ||--o{ goal : camera
    oil {
        DATE camera
        TEXT within
        VARCHAR(50) determine
    }
    goal ||--o{ very : high
    goal {
        VARCHAR(50) high
        DATE design
    }
    very ||--o{ measure : hair
    very {
        DATE hair
        TEXT ready
        VARCHAR(50) sister
    }