erDiagram
    thought ||--o{ animal : father
    thought {
        DATE father
        TEXT power
        VARCHAR(50) themselves
    }
    animal ||--o{ east : consider
    animal {
        VARCHAR(50) consider
        DATE begin
    }
    east ||--o{ per : officer
    east {
        DATE officer
        TEXT clear
        VARCHAR(50) street
    }
    per ||--o{ sure : commercial
    per {
        VARCHAR(50) commercial
        DATE resource
    }
    sure ||--o{ similar : hotel
    sure {
        DATE hotel
        TEXT court
        VARCHAR(50) professional
    }
    similar ||--o{ power : size
    similar {
        VARCHAR(50) size
        DATE even
    }
    power ||--o{ home : friend
    power {
        DATE friend
        TEXT family
        VARCHAR(50) hand
    }
    home ||--o{ also : trip
    home {
        VARCHAR(50) trip
        DATE present
    }
    also ||--o{ follow : relationship
    also {
        DATE relationship
        TEXT attention
        VARCHAR(50) right
    }
    follow ||--o{ write : policy
    follow {
        VARCHAR(50) policy
        DATE table
    }
    write ||--o{ view : wear
    write {
        DATE wear
        TEXT assume
        VARCHAR(50) owner
    }
    view ||--o{ thought : general
    view {
        VARCHAR(50) general
        DATE including
    }