erDiagram
    start ||--o{ reflect : garden
    start {
        DATE garden
        TEXT better
        VARCHAR(50) senior
    }
    reflect ||--o{ court : lead
    reflect {
        VARCHAR(50) lead
        DATE concern
    }
    court ||--o{ avoid : fast
    court {
        DATE fast
        TEXT economic
        VARCHAR(50) front
    }
    avoid ||--o{ risk : range
    avoid {
        VARCHAR(50) range
        DATE shoulder
    }
    risk ||--o{ form : experience
    risk {
        DATE experience
        TEXT several
        VARCHAR(50) again
    }
    form ||--o{ manage : condition
    form {
        VARCHAR(50) condition
        DATE page
    }
    manage ||--o{ city : worker
    manage {
        DATE worker
        TEXT tree
        VARCHAR(50) quickly
    }
    city ||--o{ economy : evening
    city {
        VARCHAR(50) evening
        DATE stay
    }
    economy ||--o{ feel : eye
    economy {
        DATE eye
        TEXT call
        VARCHAR(50) who
    }
    feel ||--o{ start : decide
    feel {
        VARCHAR(50) decide
        DATE center
    }