erDiagram
    bring ||--o{ thought : impact
    bring {
        DATE impact
        TEXT what
        VARCHAR(50) environmental
    }
    thought ||--o{ girl : group
    thought {
        VARCHAR(50) group
        DATE modern
    }
    girl ||--o{ simply : bill
    girl {
        DATE bill
        TEXT leg
        VARCHAR(50) adult
    }
    simply ||--o{ listen : camera
    simply {
        VARCHAR(50) camera
        DATE six
    }
    listen ||--o{ ever : film
    listen {
        DATE film
        TEXT list
        VARCHAR(50) ten
    }
    ever ||--o{ show : turn
    ever {
        VARCHAR(50) turn
        DATE heart
    }
    show ||--o{ bring : plan
    show {
        DATE plan
        TEXT run
        VARCHAR(50) citizen
    }