erDiagram
    subject ||--o{ paper : forget
    subject {
        DATE forget
        TEXT far
        VARCHAR(50) always
    }
    paper ||--o{ family : bank
    paper {
        VARCHAR(50) bank
        DATE popular
    }
    family ||--o{ project : culture
    family {
        DATE culture
        TEXT management
        VARCHAR(50) address
    }
    project ||--o{ letter : thousand
    project {
        VARCHAR(50) thousand
        DATE especially
    }
    letter ||--o{ enough : stay
    letter {
        DATE stay
        TEXT hope
        VARCHAR(50) by
    }
    enough ||--o{ right : since
    enough {
        VARCHAR(50) since
        DATE second
    }
    right ||--o{ total : check
    right {
        DATE check
        TEXT art
        VARCHAR(50) late
    }
    total ||--o{ behavior : pressure
    total {
        VARCHAR(50) pressure
        DATE rise
    }
    behavior ||--o{ happen : difference
    behavior {
        DATE difference
        TEXT hour
        VARCHAR(50) phone
    }
    happen ||--o{ challenge : wind
    happen {
        VARCHAR(50) wind
        DATE whom
    }
    challenge ||--o{ although : artist
    challenge {
        DATE artist
        TEXT total
        VARCHAR(50) hotel
    }
    although ||--o{ subject : order
    although {
        VARCHAR(50) order
        DATE growth
    }