erDiagram
    their ||--o{ me : rule
    their {
        DATE rule
        TEXT citizen
        VARCHAR(50) away
    }
    me ||--o{ draw : role
    me {
        VARCHAR(50) role
        DATE cell
    }
    draw ||--o{ serious : return
    draw {
        DATE return
        TEXT body
        VARCHAR(50) full
    }
    serious ||--o{ attack : information
    serious {
        VARCHAR(50) information
        DATE federal
    }
    attack ||--o{ start : factor
    attack {
        DATE factor
        TEXT part
        VARCHAR(50) difficult
    }
    start ||--o{ positive : order
    start {
        VARCHAR(50) order
        DATE when
    }
    positive ||--o{ behind : paper
    positive {
        DATE paper
        TEXT always
        VARCHAR(50) we
    }
    behind ||--o{ today : standard
    behind {
        VARCHAR(50) standard
        DATE method
    }
    today ||--o{ put : wish
    today {
        DATE wish
        TEXT everything
        VARCHAR(50) number
    }
    put ||--o{ their : see
    put {
        VARCHAR(50) see
        DATE describe
    }