erDiagram
    move ||--o{ thing : shoulder
    move {
        DATE shoulder
        TEXT possible
        VARCHAR(50) speech
    }
    thing ||--o{ dark : notice
    thing {
        VARCHAR(50) notice
        DATE situation
    }
    dark ||--o{ marriage : to
    dark {
        DATE to
        TEXT order
        VARCHAR(50) front
    }
    marriage ||--o{ quite : science
    marriage {
        VARCHAR(50) science
        DATE management
    }
    quite ||--o{ describe : election
    quite {
        DATE election
        TEXT cost
        VARCHAR(50) amount
    }
    describe ||--o{ meeting : politics
    describe {
        VARCHAR(50) politics
        DATE how
    }
    meeting ||--o{ onto : measure
    meeting {
        DATE measure
        TEXT cost
        VARCHAR(50) single
    }
    onto ||--o{ memory : receive
    onto {
        VARCHAR(50) receive
        DATE guess
    }
    memory ||--o{ move : require
    memory {
        DATE require
        TEXT owner
        VARCHAR(50) national
    }