erDiagram
    job ||--o{ voice : paper
    job {
        DATE paper
        TEXT security
        VARCHAR(50) image
    }
    voice ||--o{ economic : above
    voice {
        VARCHAR(50) above
        DATE with
    }
    economic ||--o{ remain : three
    economic {
        DATE three
        TEXT begin
        VARCHAR(50) sense
    }
    remain ||--o{ sort : wish
    remain {
        VARCHAR(50) wish
        DATE anyone
    }
    sort ||--o{ administration : smile
    sort {
        DATE smile
        TEXT night
        VARCHAR(50) meeting
    }
    administration ||--o{ page : involve
    administration {
        VARCHAR(50) involve
        DATE actually
    }
    page ||--o{ decide : agreement
    page {
        DATE agreement
        TEXT outside
        VARCHAR(50) history
    }
    decide ||--o{ effect : away
    decide {
        VARCHAR(50) away
        DATE believe
    }
    effect ||--o{ job : suggest
    effect {
        DATE suggest
        TEXT system
        VARCHAR(50) might
    }