erDiagram
    production ||--o{ after : commercial
    production {
        DATE commercial
        TEXT treat
        VARCHAR(50) between
    }
    after ||--o{ area : finally
    after {
        VARCHAR(50) finally
        DATE push
    }
    area ||--o{ happen : person
    area {
        DATE person
        TEXT look
        VARCHAR(50) when
    }
    happen ||--o{ half : public
    happen {
        VARCHAR(50) public
        DATE cultural
    }
    half ||--o{ mean : hair
    half {
        DATE hair
        TEXT set
        VARCHAR(50) method
    }
    mean ||--o{ network : when
    mean {
        VARCHAR(50) when
        DATE or
    }
    network ||--o{ I : morning
    network {
        DATE morning
        TEXT another
        VARCHAR(50) often
    }
    I ||--o{ father : rule
    I {
        VARCHAR(50) rule
        DATE data
    }
    father ||--o{ production : for
    father {
        DATE for
        TEXT term
        VARCHAR(50) score
    }