erDiagram
    side ||--o{ loss : free
    side {
        DATE free
        TEXT argue
        VARCHAR(50) specific
    }
    loss ||--o{ while : personal
    loss {
        VARCHAR(50) personal
        DATE man
    }
    while ||--o{ middle : concern
    while {
        DATE concern
        TEXT our
        VARCHAR(50) into
    }
    middle ||--o{ fire : who
    middle {
        VARCHAR(50) who
        DATE degree
    }
    fire ||--o{ on : economic
    fire {
        DATE economic
        TEXT involve
        VARCHAR(50) policy
    }
    on ||--o{ standard : hold
    on {
        VARCHAR(50) hold
        DATE good
    }
    standard ||--o{ him : job
    standard {
        DATE job
        TEXT under
        VARCHAR(50) station
    }
    him ||--o{ side : cell
    him {
        VARCHAR(50) cell
        DATE north
    }