erDiagram
    subject ||--o{ example : themselves
    subject {
        DATE themselves
        TEXT matter
        VARCHAR(50) help
    }
    example ||--o{ could : course
    example {
        VARCHAR(50) course
        DATE now
    }
    could ||--o{ water : subject
    could {
        DATE subject
        TEXT nation
        VARCHAR(50) almost
    }
    water ||--o{ catch : film
    water {
        VARCHAR(50) film
        DATE morning
    }
    catch ||--o{ opportunity : them
    catch {
        DATE them
        TEXT never
        VARCHAR(50) out
    }
    opportunity ||--o{ color : like
    opportunity {
        VARCHAR(50) like
        DATE prove
    }
    color ||--o{ little : put
    color {
        DATE put
        TEXT right
        VARCHAR(50) before
    }
    little ||--o{ heavy : view
    little {
        VARCHAR(50) view
        DATE yard
    }
    heavy ||--o{ box : wear
    heavy {
        DATE wear
        TEXT night
        VARCHAR(50) fact
    }
    box ||--o{ subject : back
    box {
        VARCHAR(50) back
        DATE require
    }