erDiagram
    identify ||--o{ spring : child
    identify {
        DATE child
        TEXT single
        VARCHAR(50) almost
    }
    spring ||--o{ teach : store
    spring {
        VARCHAR(50) store
        DATE admit
    }
    teach ||--o{ accept : consumer
    teach {
        DATE consumer
        TEXT easy
        VARCHAR(50) hold
    }
    accept ||--o{ trade : same
    accept {
        VARCHAR(50) same
        DATE also
    }
    trade ||--o{ explain : bed
    trade {
        DATE bed
        TEXT pick
        VARCHAR(50) indicate
    }
    explain ||--o{ treat : senior
    explain {
        VARCHAR(50) senior
        DATE involve
    }
    treat ||--o{ change : pretty
    treat {
        DATE pretty
        TEXT culture
        VARCHAR(50) born
    }
    change ||--o{ value : support
    change {
        VARCHAR(50) support
        DATE record
    }
    value ||--o{ threat : agree
    value {
        DATE agree
        TEXT voice
        VARCHAR(50) debate
    }
    threat ||--o{ identify : else
    threat {
        VARCHAR(50) else
        DATE challenge
    }