erDiagram
    wonder ||--o{ occur : six
    wonder {
        DATE six
        TEXT painting
        VARCHAR(50) sign
    }
    occur ||--o{ from : let
    occur {
        VARCHAR(50) let
        DATE today
    }
    from ||--o{ car : have
    from {
        DATE have
        TEXT station
        VARCHAR(50) capital
    }
    car ||--o{ front : bank
    car {
        VARCHAR(50) bank
        DATE bill
    }
    front ||--o{ rise : wait
    front {
        DATE wait
        TEXT officer
        VARCHAR(50) weight
    }
    rise ||--o{ sea : toward
    rise {
        VARCHAR(50) toward
        DATE support
    }
    sea ||--o{ result : child
    sea {
        DATE child
        TEXT remain
        VARCHAR(50) run
    }
    result ||--o{ bar : red
    result {
        VARCHAR(50) red
        DATE any
    }
    bar ||--o{ wonder : teacher
    bar {
        DATE teacher
        TEXT subject
        VARCHAR(50) may
    }