erDiagram
    behavior ||--o{ goal : risk
    behavior {
        DATE risk
        TEXT matter
        VARCHAR(50) notice
    }
    goal ||--o{ line : former
    goal {
        VARCHAR(50) former
        DATE case
    }
    line ||--o{ treat : yeah
    line {
        DATE yeah
        TEXT day
        VARCHAR(50) stock
    }
    treat ||--o{ carry : close
    treat {
        VARCHAR(50) close
        DATE sound
    }
    carry ||--o{ report : need
    carry {
        DATE need
        TEXT serious
        VARCHAR(50) dinner
    }
    report ||--o{ mouth : nice
    report {
        VARCHAR(50) nice
        DATE happen
    }
    mouth ||--o{ want : day
    mouth {
        DATE day
        TEXT everything
        VARCHAR(50) citizen
    }
    want ||--o{ lot : produce
    want {
        VARCHAR(50) produce
        DATE after
    }
    lot ||--o{ behavior : include
    lot {
        DATE include
        TEXT the
        VARCHAR(50) share
    }