erDiagram
    between ||--o{ quickly : everything
    between {
        DATE everything
        TEXT event
        VARCHAR(50) unit
    }
    quickly ||--o{ another : evening
    quickly {
        VARCHAR(50) evening
        DATE past
    }
    another ||--o{ station : hot
    another {
        DATE hot
        TEXT form
        VARCHAR(50) economic
    }
    station ||--o{ group : summer
    station {
        VARCHAR(50) summer
        DATE last
    }
    group ||--o{ between : surface
    group {
        DATE surface
        TEXT different
        VARCHAR(50) name
    }