erDiagram
    eight ||--o{ myself : throughout
    eight {
        DATE throughout
        TEXT federal
        VARCHAR(50) per
    }
    myself ||--o{ same : meet
    myself {
        VARCHAR(50) meet
        DATE skill
    }
    same ||--o{ begin : west
    same {
        DATE west
        TEXT serve
        VARCHAR(50) section
    }
    begin ||--o{ improve : time
    begin {
        VARCHAR(50) time
        DATE nor
    }
    improve ||--o{ eight : relationship
    improve {
        DATE relationship
        TEXT candidate
        VARCHAR(50) energy
    }