erDiagram
    until ||--o{ page : pay
    until {
        DATE pay
        TEXT present
        VARCHAR(50) foot
    }
    page ||--o{ assume : car
    page {
        VARCHAR(50) car
        DATE source
    }
    assume ||--o{ modern : yard
    assume {
        DATE yard
        TEXT we
        VARCHAR(50) music
    }
    modern ||--o{ if : likely
    modern {
        VARCHAR(50) likely
        DATE economy
    }
    if ||--o{ serve : movement
    if {
        DATE movement
        TEXT owner
        VARCHAR(50) less
    }
    serve ||--o{ natural : position
    serve {
        VARCHAR(50) position
        DATE vote
    }
    natural ||--o{ near : cut
    natural {
        DATE cut
        TEXT find
        VARCHAR(50) sort
    }
    near ||--o{ morning : apply
    near {
        VARCHAR(50) apply
        DATE morning
    }
    morning ||--o{ population : treatment
    morning {
        DATE treatment
        TEXT the
        VARCHAR(50) cover
    }
    population ||--o{ develop : because
    population {
        VARCHAR(50) because
        DATE chair
    }
    develop ||--o{ until : authority
    develop {
        DATE authority
        TEXT someone
        VARCHAR(50) leg
    }