erDiagram
    large ||--o{ option : truth
    large {
        DATE truth
        TEXT around
        VARCHAR(50) adult
    }
    option ||--o{ environmental : we
    option {
        VARCHAR(50) we
        DATE blue
    }
    environmental ||--o{ technology : very
    environmental {
        DATE very
        TEXT in
        VARCHAR(50) charge
    }
    technology ||--o{ although : really
    technology {
        VARCHAR(50) really
        DATE notice
    }
    although ||--o{ Mr : among
    although {
        DATE among
        TEXT information
        VARCHAR(50) step
    }
    Mr ||--o{ large : sell
    Mr {
        VARCHAR(50) sell
        DATE interest
    }