erDiagram
    perform ||--o{ single : assume
    perform {
        DATE assume
        TEXT president
        VARCHAR(50) follow
    }
    single ||--o{ data : customer
    single {
        VARCHAR(50) customer
        DATE continue
    }
    data ||--o{ respond : face
    data {
        DATE face
        TEXT garden
        VARCHAR(50) of
    }
    respond ||--o{ wrong : student
    respond {
        VARCHAR(50) student
        DATE alone
    }
    wrong ||--o{ church : customer
    wrong {
        DATE customer
        TEXT onto
        VARCHAR(50) air
    }
    church ||--o{ young : free
    church {
        VARCHAR(50) free
        DATE mind
    }
    young ||--o{ particular : environment
    young {
        DATE environment
        TEXT reveal
        VARCHAR(50) may
    }
    particular ||--o{ our : consider
    particular {
        VARCHAR(50) consider
        DATE cause
    }
    our ||--o{ send : team
    our {
        DATE team
        TEXT campaign
        VARCHAR(50) never
    }
    send ||--o{ law : class
    send {
        VARCHAR(50) class
        DATE one
    }
    law ||--o{ should : green
    law {
        DATE green
        TEXT rise
        VARCHAR(50) above
    }
    should ||--o{ perform : look
    should {
        VARCHAR(50) look
        DATE page
    }