erDiagram
    impact ||--o{ people : view
    impact {
        DATE view
        TEXT relationship
        VARCHAR(50) manage
    }
    people ||--o{ election : enjoy
    people {
        VARCHAR(50) enjoy
        DATE teach
    }
    election ||--o{ head : blood
    election {
        DATE blood
        TEXT friend
        VARCHAR(50) anyone
    }
    head ||--o{ population : word
    head {
        VARCHAR(50) word
        DATE community
    }
    population ||--o{ night : newspaper
    population {
        DATE newspaper
        TEXT help
        VARCHAR(50) apply
    }
    night ||--o{ early : house
    night {
        VARCHAR(50) house
        DATE source
    }
    early ||--o{ impact : anyone
    early {
        DATE anyone
        TEXT partner
        VARCHAR(50) future
    }