erDiagram
    successful ||--o{ idea : still
    successful {
        DATE still
        TEXT she
        VARCHAR(50) evidence
    }
    idea ||--o{ beat : explain
    idea {
        VARCHAR(50) explain
        DATE as
    }
    beat ||--o{ president : like
    beat {
        DATE like
        TEXT bring
        VARCHAR(50) scientist
    }
    president ||--o{ various : contain
    president {
        VARCHAR(50) contain
        DATE question
    }
    various ||--o{ west : send
    various {
        DATE send
        TEXT wide
        VARCHAR(50) whose
    }
    west ||--o{ face : provide
    west {
        VARCHAR(50) provide
        DATE medical
    }
    face ||--o{ theory : hot
    face {
        DATE hot
        TEXT few
        VARCHAR(50) just
    }
    theory ||--o{ pull : growth
    theory {
        VARCHAR(50) growth
        DATE more
    }
    pull ||--o{ side : lay
    pull {
        DATE lay
        TEXT brother
        VARCHAR(50) often
    }
    side ||--o{ game : business
    side {
        VARCHAR(50) business
        DATE office
    }
    game ||--o{ successful : drop
    game {
        DATE drop
        TEXT north
        VARCHAR(50) piece
    }