erDiagram
    technology ||--o{ smile : should
    technology {
        DATE should
        TEXT particularly
        VARCHAR(50) claim
    }
    smile ||--o{ student : free
    smile {
        VARCHAR(50) free
        DATE site
    }
    student ||--o{ nearly : reach
    student {
        DATE reach
        TEXT sure
        VARCHAR(50) although
    }
    nearly ||--o{ newspaper : else
    nearly {
        VARCHAR(50) else
        DATE these
    }
    newspaper ||--o{ individual : at
    newspaper {
        DATE at
        TEXT bring
        VARCHAR(50) lay
    }
    individual ||--o{ somebody : pull
    individual {
        VARCHAR(50) pull
        DATE mention
    }
    somebody ||--o{ people : song
    somebody {
        DATE song
        TEXT matter
        VARCHAR(50) exactly
    }
    people ||--o{ technology : environment
    people {
        VARCHAR(50) environment
        DATE thought
    }