erDiagram
    become ||--o{ right : run
    become {
        DATE run
        TEXT here
        VARCHAR(50) enjoy
    }
    right ||--o{ either : until
    right {
        VARCHAR(50) until
        DATE international
    }
    either ||--o{ benefit : southern
    either {
        DATE southern
        TEXT interview
        VARCHAR(50) time
    }
    benefit ||--o{ gas : forward
    benefit {
        VARCHAR(50) forward
        DATE possible
    }
    gas ||--o{ this : individual
    gas {
        DATE individual
        TEXT something
        VARCHAR(50) alone
    }
    this ||--o{ from : ask
    this {
        VARCHAR(50) ask
        DATE capital
    }
    from ||--o{ house : however
    from {
        DATE however
        TEXT expert
        VARCHAR(50) church
    }
    house ||--o{ early : prepare
    house {
        VARCHAR(50) prepare
        DATE actually
    }
    early ||--o{ rest : civil
    early {
        DATE civil
        TEXT new
        VARCHAR(50) recognize
    }
    rest ||--o{ become : some
    rest {
        VARCHAR(50) some
        DATE which
    }