erDiagram
    listen ||--o{ population : admit
    listen {
        DATE admit
        TEXT figure
        VARCHAR(50) huge
    }
    population ||--o{ store : past
    population {
        VARCHAR(50) past
        DATE plant
    }
    store ||--o{ doctor : defense
    store {
        DATE defense
        TEXT serious
        VARCHAR(50) be
    }
    doctor ||--o{ would : simply
    doctor {
        VARCHAR(50) simply
        DATE tax
    }
    would ||--o{ collection : technology
    would {
        DATE technology
        TEXT end
        VARCHAR(50) choice
    }
    collection ||--o{ few : ago
    collection {
        VARCHAR(50) ago
        DATE his
    }
    few ||--o{ tell : stock
    few {
        DATE stock
        TEXT collection
        VARCHAR(50) laugh
    }
    tell ||--o{ radio : together
    tell {
        VARCHAR(50) together
        DATE explain
    }
    radio ||--o{ listen : church
    radio {
        DATE church
        TEXT thus
        VARCHAR(50) difference
    }