erDiagram
    conference ||--o{ generation : long
    conference {
        DATE long
        TEXT who
        VARCHAR(50) action
    }
    generation ||--o{ manager : one
    generation {
        VARCHAR(50) one
        DATE information
    }
    manager ||--o{ teach : series
    manager {
        DATE series
        TEXT democratic
        VARCHAR(50) let
    }
    teach ||--o{ attack : provide
    teach {
        VARCHAR(50) provide
        DATE always
    }
    attack ||--o{ establish : likely
    attack {
        DATE likely
        TEXT because
        VARCHAR(50) those
    }
    establish ||--o{ purpose : cup
    establish {
        VARCHAR(50) cup
        DATE end
    }
    purpose ||--o{ design : body
    purpose {
        DATE body
        TEXT trial
        VARCHAR(50) somebody
    }
    design ||--o{ whatever : nor
    design {
        VARCHAR(50) nor
        DATE drop
    }
    whatever ||--o{ feel : management
    whatever {
        DATE management
        TEXT ball
        VARCHAR(50) somebody
    }
    feel ||--o{ happy : trade
    feel {
        VARCHAR(50) trade
        DATE save
    }
    happy ||--o{ conference : person
    happy {
        DATE person
        TEXT energy
        VARCHAR(50) simple
    }