erDiagram
    if ||--o{ score : phone
    if {
        DATE phone
        TEXT gas
        VARCHAR(50) seven
    }
    score ||--o{ role : help
    score {
        VARCHAR(50) help
        DATE technology
    }
    role ||--o{ full : soldier
    role {
        DATE soldier
        TEXT yourself
        VARCHAR(50) message
    }
    full ||--o{ eye : yourself
    full {
        VARCHAR(50) yourself
        DATE institution
    }
    eye ||--o{ career : language
    eye {
        DATE language
        TEXT term
        VARCHAR(50) wonder
    }
    career ||--o{ opportunity : example
    career {
        VARCHAR(50) example
        DATE task
    }
    opportunity ||--o{ budget : whom
    opportunity {
        DATE whom
        TEXT there
        VARCHAR(50) design
    }
    budget ||--o{ push : catch
    budget {
        VARCHAR(50) catch
        DATE position
    }
    push ||--o{ young : film
    push {
        DATE film
        TEXT school
        VARCHAR(50) paper
    }
    young ||--o{ help : five
    young {
        VARCHAR(50) five
        DATE decide
    }
    help ||--o{ region : affect
    help {
        DATE affect
        TEXT skill
        VARCHAR(50) since
    }
    region ||--o{ if : reach
    region {
        VARCHAR(50) reach
        DATE government
    }