erDiagram
    big ||--o{ their : check
    big {
        DATE check
        TEXT I
        VARCHAR(50) condition
    }
    their ||--o{ single : kitchen
    their {
        VARCHAR(50) kitchen
        DATE nearly
    }
    single ||--o{ usually : put
    single {
        DATE put
        TEXT road
        VARCHAR(50) politics
    }
    usually ||--o{ set : certain
    usually {
        VARCHAR(50) certain
        DATE wonder
    }
    set ||--o{ significant : change
    set {
        DATE change
        TEXT particularly
        VARCHAR(50) almost
    }
    significant ||--o{ boy : article
    significant {
        VARCHAR(50) article
        DATE huge
    }
    boy ||--o{ stay : require
    boy {
        DATE require
        TEXT improve
        VARCHAR(50) must
    }
    stay ||--o{ other : analysis
    stay {
        VARCHAR(50) analysis
        DATE traditional
    }
    other ||--o{ seven : contain
    other {
        DATE contain
        TEXT especially
        VARCHAR(50) subject
    }
    seven ||--o{ big : reduce
    seven {
        VARCHAR(50) reduce
        DATE church
    }