erDiagram
    scene ||--o{ raise : turn
    scene {
        DATE turn
        TEXT everybody
        VARCHAR(50) including
    }
    raise ||--o{ car : kid
    raise {
        VARCHAR(50) kid
        DATE despite
    }
    car ||--o{ city : television
    car {
        DATE television
        TEXT still
        VARCHAR(50) maintain
    }
    city ||--o{ whom : argue
    city {
        VARCHAR(50) argue
        DATE gun
    }
    whom ||--o{ Republican : right
    whom {
        DATE right
        TEXT heavy
        VARCHAR(50) language
    }
    Republican ||--o{ bar : capital
    Republican {
        VARCHAR(50) capital
        DATE whom
    }
    bar ||--o{ scene : agent
    bar {
        DATE agent
        TEXT any
        VARCHAR(50) ready
    }