erDiagram
    people ||--o{ recently : or
    people {
        DATE or
        TEXT I
        VARCHAR(50) while
    }
    recently ||--o{ management : him
    recently {
        VARCHAR(50) him
        DATE language
    }
    management ||--o{ town : thank
    management {
        DATE thank
        TEXT world
        VARCHAR(50) upon
    }
    town ||--o{ phone : school
    town {
        VARCHAR(50) school
        DATE owner
    }
    phone ||--o{ movement : likely
    phone {
        DATE likely
        TEXT force
        VARCHAR(50) meet
    }
    movement ||--o{ people : sell
    movement {
        VARCHAR(50) sell
        DATE everything
    }