erDiagram
    down ||--o{ arrive : court
    down {
        DATE court
        TEXT next
        VARCHAR(50) window
    }
    arrive ||--o{ nearly : ground
    arrive {
        VARCHAR(50) ground
        DATE more
    }
    nearly ||--o{ task : must
    nearly {
        DATE must
        TEXT sort
        VARCHAR(50) fall
    }
    task ||--o{ they : industry
    task {
        VARCHAR(50) industry
        DATE concern
    }
    they ||--o{ size : me
    they {
        DATE me
        TEXT film
        VARCHAR(50) body
    }
    size ||--o{ down : moment
    size {
        VARCHAR(50) moment
        DATE piece
    }