erDiagram
    air ||--o{ record : market
    air {
        DATE market
        TEXT idea
        VARCHAR(50) thousand
    }
    record ||--o{ than : teacher
    record {
        VARCHAR(50) teacher
        DATE effect
    }
    than ||--o{ great : approach
    than {
        DATE approach
        TEXT stand
        VARCHAR(50) him
    }
    great ||--o{ night : once
    great {
        VARCHAR(50) once
        DATE level
    }
    night ||--o{ send : impact
    night {
        DATE impact
        TEXT education
        VARCHAR(50) break
    }
    send ||--o{ send : industry
    send {
        VARCHAR(50) industry
        DATE give
    }
    send ||--o{ future : improve
    send {
        DATE improve
        TEXT today
        VARCHAR(50) energy
    }
    future ||--o{ week : area
    future {
        VARCHAR(50) area
        DATE serious
    }
    week ||--o{ into : since
    week {
        DATE since
        TEXT hear
        VARCHAR(50) girl
    }
    into ||--o{ air : hospital
    into {
        VARCHAR(50) hospital
        DATE move
    }