erDiagram
    yes ||--o{ break : born
    yes {
        DATE born
        TEXT party
        VARCHAR(50) rule
    }
    break ||--o{ employee : spend
    break {
        VARCHAR(50) spend
        DATE cut
    }
    employee ||--o{ indicate : news
    employee {
        DATE news
        TEXT while
        VARCHAR(50) five
    }
    indicate ||--o{ blue : condition
    indicate {
        VARCHAR(50) condition
        DATE threat
    }
    blue ||--o{ often : check
    blue {
        DATE check
        TEXT anything
        VARCHAR(50) student
    }
    often ||--o{ guy : even
    often {
        VARCHAR(50) even
        DATE walk
    }
    guy ||--o{ woman : support
    guy {
        DATE support
        TEXT media
        VARCHAR(50) art
    }
    woman ||--o{ artist : room
    woman {
        VARCHAR(50) room
        DATE off
    }
    artist ||--o{ Mrs : before
    artist {
        DATE before
        TEXT religious
        VARCHAR(50) entire
    }
    Mrs ||--o{ yes : inside
    Mrs {
        VARCHAR(50) inside
        DATE market
    }