erDiagram
    everybody ||--o{ bring : indicate
    everybody {
        DATE indicate
        TEXT follow
        VARCHAR(50) safe
    }
    bring ||--o{ national : nor
    bring {
        VARCHAR(50) nor
        DATE shake
    }
    national ||--o{ science : close
    national {
        DATE close
        TEXT leader
        VARCHAR(50) seek
    }
    science ||--o{ again : purpose
    science {
        VARCHAR(50) purpose
        DATE system
    }
    again ||--o{ everybody : professional
    again {
        DATE professional
        TEXT cover
        VARCHAR(50) debate
    }