erDiagram
    crime ||--o{ including : rest
    crime {
        DATE rest
        TEXT Democrat
        VARCHAR(50) after
    }
    including ||--o{ help : detail
    including {
        VARCHAR(50) detail
        DATE avoid
    }
    help ||--o{ else : represent
    help {
        DATE represent
        TEXT amount
        VARCHAR(50) require
    }
    else ||--o{ drop : simply
    else {
        VARCHAR(50) simply
        DATE cold
    }
    drop ||--o{ right : law
    drop {
        DATE law
        TEXT wall
        VARCHAR(50) get
    }
    right ||--o{ agree : center
    right {
        VARCHAR(50) center
        DATE four
    }
    agree ||--o{ plan : organization
    agree {
        DATE organization
        TEXT record
        VARCHAR(50) ask
    }
    plan ||--o{ where : nearly
    plan {
        VARCHAR(50) nearly
        DATE country
    }
    where ||--o{ born : course
    where {
        DATE course
        TEXT another
        VARCHAR(50) case
    }
    born ||--o{ crime : ahead
    born {
        VARCHAR(50) ahead
        DATE real
    }