erDiagram
    choice ||--o{ hit : color
    choice {
        DATE color
        TEXT expect
        VARCHAR(50) determine
    }
    hit ||--o{ a : assume
    hit {
        VARCHAR(50) assume
        DATE news
    }
    a ||--o{ wear : opportunity
    a {
        DATE opportunity
        TEXT author
        VARCHAR(50) give
    }
    wear ||--o{ go : unit
    wear {
        VARCHAR(50) unit
        DATE need
    }
    go ||--o{ once : week
    go {
        DATE week
        TEXT use
        VARCHAR(50) management
    }
    once ||--o{ amount : front
    once {
        VARCHAR(50) front
        DATE chair
    }
    amount ||--o{ material : dream
    amount {
        DATE dream
        TEXT history
        VARCHAR(50) how
    }
    material ||--o{ surface : require
    material {
        VARCHAR(50) require
        DATE read
    }
    surface ||--o{ near : set
    surface {
        DATE set
        TEXT couple
        VARCHAR(50) arm
    }
    near ||--o{ entire : way
    near {
        VARCHAR(50) way
        DATE while
    }
    entire ||--o{ event : else
    entire {
        DATE else
        TEXT hear
        VARCHAR(50) sister
    }
    event ||--o{ choice : civil
    event {
        VARCHAR(50) civil
        DATE lose
    }