erDiagram
    ability ||--o{ mouth : many
    ability {
        DATE many
        TEXT resource
        VARCHAR(50) member
    }
    mouth ||--o{ worry : over
    mouth {
        VARCHAR(50) over
        DATE physical
    }
    worry ||--o{ record : city
    worry {
        DATE city
        TEXT economy
        VARCHAR(50) prove
    }
    record ||--o{ hundred : another
    record {
        VARCHAR(50) another
        DATE receive
    }
    hundred ||--o{ better : certain
    hundred {
        DATE certain
        TEXT foot
        VARCHAR(50) as
    }
    better ||--o{ ability : close
    better {
        VARCHAR(50) close
        DATE herself
    }