erDiagram
    resource ||--o{ any : interest
    resource {
        DATE interest
        TEXT fall
        VARCHAR(50) stock
    }
    any ||--o{ board : star
    any {
        VARCHAR(50) star
        DATE certainly
    }
    board ||--o{ agency : budget
    board {
        DATE budget
        TEXT pick
        VARCHAR(50) board
    }
    agency ||--o{ country : total
    agency {
        VARCHAR(50) total
        DATE require
    }
    country ||--o{ if : involve
    country {
        DATE involve
        TEXT parent
        VARCHAR(50) history
    }
    if ||--o{ great : everybody
    if {
        VARCHAR(50) everybody
        DATE car
    }
    great ||--o{ fight : send
    great {
        DATE send
        TEXT almost
        VARCHAR(50) indeed
    }
    fight ||--o{ with : everybody
    fight {
        VARCHAR(50) everybody
        DATE head
    }
    with ||--o{ base : another
    with {
        DATE another
        TEXT information
        VARCHAR(50) part
    }
    base ||--o{ resource : answer
    base {
        VARCHAR(50) answer
        DATE quite
    }