erDiagram
    third ||--o{ nice : rest
    third {
        DATE rest
        TEXT hard
        VARCHAR(50) lead
    }
    nice ||--o{ stand : bed
    nice {
        VARCHAR(50) bed
        DATE development
    }
    stand ||--o{ structure : always
    stand {
        DATE always
        TEXT attack
        VARCHAR(50) or
    }
    structure ||--o{ order : simple
    structure {
        VARCHAR(50) simple
        DATE brother
    }
    order ||--o{ various : difficult
    order {
        DATE difficult
        TEXT final
        VARCHAR(50) begin
    }
    various ||--o{ will : stuff
    various {
        VARCHAR(50) stuff
        DATE foot
    }
    will ||--o{ member : direction
    will {
        DATE direction
        TEXT trial
        VARCHAR(50) fire
    }
    member ||--o{ third : or
    member {
        VARCHAR(50) or
        DATE camera
    }