erDiagram
    challenge ||--o{ hotel : heavy
    challenge {
        DATE heavy
        TEXT write
        VARCHAR(50) ok
    }
    hotel ||--o{ scene : until
    hotel {
        VARCHAR(50) until
        DATE subject
    }
    scene ||--o{ hand : billion
    scene {
        DATE billion
        TEXT politics
        VARCHAR(50) blue
    }
    hand ||--o{ ball : look
    hand {
        VARCHAR(50) look
        DATE would
    }
    ball ||--o{ physical : day
    ball {
        DATE day
        TEXT voice
        VARCHAR(50) product
    }
    physical ||--o{ beautiful : sister
    physical {
        VARCHAR(50) sister
        DATE today
    }
    beautiful ||--o{ challenge : performance
    beautiful {
        DATE performance
        TEXT leave
        VARCHAR(50) expect
    }