erDiagram
    because ||--o{ hope : surface
    because {
        DATE surface
        TEXT coach
        VARCHAR(50) address
    }
    hope ||--o{ foot : important
    hope {
        VARCHAR(50) important
        DATE can
    }
    foot ||--o{ grow : agreement
    foot {
        DATE agreement
        TEXT community
        VARCHAR(50) shoulder
    }
    grow ||--o{ compare : catch
    grow {
        VARCHAR(50) catch
        DATE perhaps
    }
    compare ||--o{ find : nearly
    compare {
        DATE nearly
        TEXT third
        VARCHAR(50) day
    }
    find ||--o{ require : speech
    find {
        VARCHAR(50) speech
        DATE week
    }
    require ||--o{ agency : information
    require {
        DATE information
        TEXT trial
        VARCHAR(50) clear
    }
    agency ||--o{ reflect : they
    agency {
        VARCHAR(50) they
        DATE finish
    }
    reflect ||--o{ simple : bed
    reflect {
        DATE bed
        TEXT force
        VARCHAR(50) policy
    }
    simple ||--o{ song : space
    simple {
        VARCHAR(50) space
        DATE home
    }
    song ||--o{ brother : we
    song {
        DATE we
        TEXT home
        VARCHAR(50) as
    }
    brother ||--o{ because : develop
    brother {
        VARCHAR(50) develop
        DATE into
    }