erDiagram
    need ||--o{ sit : trouble
    need {
        DATE trouble
        TEXT add
        VARCHAR(50) positive
    }
    sit ||--o{ play : firm
    sit {
        VARCHAR(50) firm
        DATE respond
    }
    play ||--o{ write : development
    play {
        DATE development
        TEXT reality
        VARCHAR(50) student
    }
    write ||--o{ kid : bed
    write {
        VARCHAR(50) bed
        DATE reality
    }
    kid ||--o{ only : generation
    kid {
        DATE generation
        TEXT would
        VARCHAR(50) employee
    }
    only ||--o{ commercial : position
    only {
        VARCHAR(50) position
        DATE shoulder
    }
    commercial ||--o{ should : each
    commercial {
        DATE each
        TEXT development
        VARCHAR(50) man
    }
    should ||--o{ medical : lot
    should {
        VARCHAR(50) lot
        DATE report
    }
    medical ||--o{ especially : young
    medical {
        DATE young
        TEXT seat
        VARCHAR(50) conference
    }
    especially ||--o{ media : kid
    especially {
        VARCHAR(50) kid
        DATE police
    }
    media ||--o{ need : American
    media {
        DATE American
        TEXT data
        VARCHAR(50) car
    }