erDiagram
    challenge ||--o{ only : himself
    challenge {
        DATE himself
        TEXT also
        VARCHAR(50) during
    }
    only ||--o{ how : general
    only {
        VARCHAR(50) general
        DATE shake
    }
    how ||--o{ lot : read
    how {
        DATE read
        TEXT consumer
        VARCHAR(50) foot
    }
    lot ||--o{ response : alone
    lot {
        VARCHAR(50) alone
        DATE firm
    }
    response ||--o{ price : protect
    response {
        DATE protect
        TEXT miss
        VARCHAR(50) election
    }
    price ||--o{ rich : media
    price {
        VARCHAR(50) media
        DATE future
    }
    rich ||--o{ father : choice
    rich {
        DATE choice
        TEXT production
        VARCHAR(50) open
    }
    father ||--o{ garden : whether
    father {
        VARCHAR(50) whether
        DATE citizen
    }
    garden ||--o{ senior : else
    garden {
        DATE else
        TEXT action
        VARCHAR(50) service
    }
    senior ||--o{ consider : kid
    senior {
        VARCHAR(50) kid
        DATE guess
    }
    consider ||--o{ capital : must
    consider {
        DATE must
        TEXT well
        VARCHAR(50) real
    }
    capital ||--o{ challenge : other
    capital {
        VARCHAR(50) other
        DATE modern
    }