erDiagram
    garden ||--o{ door : wait
    garden {
        DATE wait
        TEXT strong
        VARCHAR(50) pressure
    }
    door ||--o{ believe : reach
    door {
        VARCHAR(50) reach
        DATE he
    }
    believe ||--o{ check : change
    believe {
        DATE change
        TEXT special
        VARCHAR(50) seem
    }
    check ||--o{ source : finally
    check {
        VARCHAR(50) finally
        DATE simple
    }
    source ||--o{ surface : thousand
    source {
        DATE thousand
        TEXT energy
        VARCHAR(50) chance
    }
    surface ||--o{ so : serve
    surface {
        VARCHAR(50) serve
        DATE yes
    }
    so ||--o{ black : describe
    so {
        DATE describe
        TEXT energy
        VARCHAR(50) name
    }
    black ||--o{ garden : single
    black {
        VARCHAR(50) single
        DATE matter
    }