erDiagram
    hand ||--o{ front : early
    hand {
        DATE early
        TEXT toward
        VARCHAR(50) although
    }
    front ||--o{ receive : police
    front {
        VARCHAR(50) police
        DATE education
    }
    receive ||--o{ cover : international
    receive {
        DATE international
        TEXT before
        VARCHAR(50) whom
    }
    cover ||--o{ month : world
    cover {
        VARCHAR(50) world
        DATE article
    }
    month ||--o{ both : allow
    month {
        DATE allow
        TEXT add
        VARCHAR(50) crime
    }
    both ||--o{ out : most
    both {
        VARCHAR(50) most
        DATE form
    }
    out ||--o{ box : wish
    out {
        DATE wish
        TEXT type
        VARCHAR(50) education
    }
    box ||--o{ hand : tax
    box {
        VARCHAR(50) tax
        DATE fight
    }