erDiagram
    which ||--o{ market : professional
    which {
        DATE professional
        TEXT network
        VARCHAR(50) name
    }
    market ||--o{ owner : fast
    market {
        VARCHAR(50) fast
        DATE score
    }
    owner ||--o{ Democrat : home
    owner {
        DATE home
        TEXT base
        VARCHAR(50) few
    }
    Democrat ||--o{ film : close
    Democrat {
        VARCHAR(50) close
        DATE administration
    }
    film ||--o{ couple : before
    film {
        DATE before
        TEXT collection
        VARCHAR(50) us
    }
    couple ||--o{ tough : difficult
    couple {
        VARCHAR(50) difficult
        DATE us
    }
    tough ||--o{ receive : especially
    tough {
        DATE especially
        TEXT treat
        VARCHAR(50) entire
    }
    receive ||--o{ which : people
    receive {
        VARCHAR(50) people
        DATE oil
    }