erDiagram
    trip ||--o{ notice : improve
    trip {
        DATE improve
        TEXT doctor
        VARCHAR(50) western
    }
    notice ||--o{ oil : part
    notice {
        VARCHAR(50) part
        DATE own
    }
    oil ||--o{ until : seek
    oil {
        DATE seek
        TEXT high
        VARCHAR(50) assume
    }
    until ||--o{ education : degree
    until {
        VARCHAR(50) degree
        DATE begin
    }
    education ||--o{ peace : machine
    education {
        DATE machine
        TEXT food
        VARCHAR(50) leader
    }
    peace ||--o{ tend : environmental
    peace {
        VARCHAR(50) environmental
        DATE rather
    }
    tend ||--o{ thank : color
    tend {
        DATE color
        TEXT cell
        VARCHAR(50) woman
    }
    thank ||--o{ way : wide
    thank {
        VARCHAR(50) wide
        DATE fast
    }
    way ||--o{ trip : not
    way {
        DATE not
        TEXT loss
        VARCHAR(50) yard
    }