erDiagram
    though ||--o{ energy : fish
    though {
        DATE fish
        TEXT short
        VARCHAR(50) information
    }
    energy ||--o{ may : staff
    energy {
        VARCHAR(50) staff
        DATE knowledge
    }
    may ||--o{ agree : many
    may {
        DATE many
        TEXT market
        VARCHAR(50) course
    }
    agree ||--o{ century : dinner
    agree {
        VARCHAR(50) dinner
        DATE your
    }
    century ||--o{ agency : political
    century {
        DATE political
        TEXT get
        VARCHAR(50) produce
    }
    agency ||--o{ site : blue
    agency {
        VARCHAR(50) blue
        DATE behavior
    }
    site ||--o{ role : skill
    site {
        DATE skill
        TEXT right
        VARCHAR(50) else
    }
    role ||--o{ avoid : rest
    role {
        VARCHAR(50) rest
        DATE role
    }
    avoid ||--o{ though : democratic
    avoid {
        DATE democratic
        TEXT information
        VARCHAR(50) trip
    }