erDiagram
    buy ||--o{ benefit : reflect
    buy {
        DATE reflect
        TEXT plant
        VARCHAR(50) debate
    }
    benefit ||--o{ must : cost
    benefit {
        VARCHAR(50) cost
        DATE but
    }
    must ||--o{ get : involve
    must {
        DATE involve
        TEXT close
        VARCHAR(50) represent
    }
    get ||--o{ court : yourself
    get {
        VARCHAR(50) yourself
        DATE it
    }
    court ||--o{ investment : effect
    court {
        DATE effect
        TEXT air
        VARCHAR(50) keep
    }
    investment ||--o{ benefit : expert
    investment {
        VARCHAR(50) expert
        DATE new
    }
    benefit ||--o{ cut : follow
    benefit {
        DATE follow
        TEXT animal
        VARCHAR(50) race
    }
    cut ||--o{ buy : amount
    cut {
        VARCHAR(50) amount
        DATE college
    }