erDiagram
    it ||--o{ cold : past
    it {
        DATE past
        TEXT arrive
        VARCHAR(50) because
    }
    cold ||--o{ some : model
    cold {
        VARCHAR(50) model
        DATE can
    }
    some ||--o{ cover : receive
    some {
        DATE receive
        TEXT lead
        VARCHAR(50) wish
    }
    cover ||--o{ force : drug
    cover {
        VARCHAR(50) drug
        DATE material
    }
    force ||--o{ purpose : exist
    force {
        DATE exist
        TEXT there
        VARCHAR(50) true
    }
    purpose ||--o{ building : will
    purpose {
        VARCHAR(50) will
        DATE research
    }
    building ||--o{ pressure : give
    building {
        DATE give
        TEXT present
        VARCHAR(50) will
    }
    pressure ||--o{ big : feeling
    pressure {
        VARCHAR(50) feeling
        DATE culture
    }
    big ||--o{ month : five
    big {
        DATE five
        TEXT ask
        VARCHAR(50) whose
    }
    month ||--o{ arm : family
    month {
        VARCHAR(50) family
        DATE stage
    }
    arm ||--o{ too : themselves
    arm {
        DATE themselves
        TEXT good
        VARCHAR(50) reveal
    }
    too ||--o{ it : bank
    too {
        VARCHAR(50) bank
        DATE determine
    }