erDiagram
    small ||--o{ can : region
    small {
        DATE region
        TEXT hour
        VARCHAR(50) realize
    }
    can ||--o{ pay : teacher
    can {
        VARCHAR(50) teacher
        DATE increase
    }
    pay ||--o{ lay : move
    pay {
        DATE move
        TEXT purpose
        VARCHAR(50) star
    }
    lay ||--o{ will : sport
    lay {
        VARCHAR(50) sport
        DATE may
    }
    will ||--o{ nor : history
    will {
        DATE history
        TEXT writer
        VARCHAR(50) body
    }
    nor ||--o{ turn : road
    nor {
        VARCHAR(50) road
        DATE specific
    }
    turn ||--o{ drug : occur
    turn {
        DATE occur
        TEXT quality
        VARCHAR(50) bed
    }
    drug ||--o{ small : sort
    drug {
        VARCHAR(50) sort
        DATE professor
    }