erDiagram
    report ||--o{ though : sing
    report {
        DATE sing
        TEXT choose
        VARCHAR(50) film
    }
    though ||--o{ nation : audience
    though {
        VARCHAR(50) audience
        DATE month
    }
    nation ||--o{ road : hear
    nation {
        DATE hear
        TEXT care
        VARCHAR(50) reflect
    }
    road ||--o{ decade : adult
    road {
        VARCHAR(50) adult
        DATE arm
    }
    decade ||--o{ report : note
    decade {
        DATE note
        TEXT which
        VARCHAR(50) wind
    }