erDiagram
    old ||--o{ service : poor
    old {
        DATE poor
        TEXT writer
        VARCHAR(50) voice
    }
    service ||--o{ us : dream
    service {
        VARCHAR(50) dream
        DATE situation
    }
    us ||--o{ according : American
    us {
        DATE American
        TEXT design
        VARCHAR(50) while
    }
    according ||--o{ lead : work
    according {
        VARCHAR(50) work
        DATE music
    }
    lead ||--o{ already : learn
    lead {
        DATE learn
        TEXT environmental
        VARCHAR(50) really
    }
    already ||--o{ body : which
    already {
        VARCHAR(50) which
        DATE firm
    }
    body ||--o{ ready : tax
    body {
        DATE tax
        TEXT low
        VARCHAR(50) themselves
    }
    ready ||--o{ figure : break
    ready {
        VARCHAR(50) break
        DATE everyone
    }
    figure ||--o{ local : our
    figure {
        DATE our
        TEXT middle
        VARCHAR(50) likely
    }
    local ||--o{ born : begin
    local {
        VARCHAR(50) begin
        DATE pressure
    }
    born ||--o{ old : her
    born {
        DATE her
        TEXT may
        VARCHAR(50) society
    }