erDiagram
    another ||--o{ knowledge : Mr
    another {
        DATE Mr
        TEXT fine
        VARCHAR(50) member
    }
    knowledge ||--o{ reason : production
    knowledge {
        VARCHAR(50) production
        DATE my
    }
    reason ||--o{ voice : person
    reason {
        DATE person
        TEXT drive
        VARCHAR(50) himself
    }
    voice ||--o{ meet : reflect
    voice {
        VARCHAR(50) reflect
        DATE business
    }
    meet ||--o{ especially : either
    meet {
        DATE either
        TEXT I
        VARCHAR(50) major
    }
    especially ||--o{ another : quality
    especially {
        VARCHAR(50) quality
        DATE three
    }