erDiagram
    wall ||--o{ much : admit
    wall {
        DATE admit
        TEXT different
        VARCHAR(50) card
    }
    much ||--o{ laugh : sell
    much {
        VARCHAR(50) sell
        DATE loss
    }
    laugh ||--o{ check : give
    laugh {
        DATE give
        TEXT include
        VARCHAR(50) fine
    }
    check ||--o{ present : report
    check {
        VARCHAR(50) report
        DATE common
    }
    present ||--o{ which : future
    present {
        DATE future
        TEXT cold
        VARCHAR(50) model
    }
    which ||--o{ easy : paper
    which {
        VARCHAR(50) paper
        DATE country
    }
    easy ||--o{ short : partner
    easy {
        DATE partner
        TEXT table
        VARCHAR(50) executive
    }
    short ||--o{ wall : nearly
    short {
        VARCHAR(50) nearly
        DATE government
    }