erDiagram
    forget ||--o{ claim : teach
    forget {
        DATE teach
        TEXT really
        VARCHAR(50) without
    }
    claim ||--o{ prove : raise
    claim {
        VARCHAR(50) raise
        DATE wait
    }
    prove ||--o{ business : begin
    prove {
        DATE begin
        TEXT consumer
        VARCHAR(50) here
    }
    business ||--o{ ability : hair
    business {
        VARCHAR(50) hair
        DATE relationship
    }
    ability ||--o{ trade : garden
    ability {
        DATE garden
        TEXT cultural
        VARCHAR(50) task
    }
    trade ||--o{ bank : article
    trade {
        VARCHAR(50) article
        DATE region
    }
    bank ||--o{ sort : large
    bank {
        DATE large
        TEXT account
        VARCHAR(50) rather
    }
    sort ||--o{ college : force
    sort {
        VARCHAR(50) force
        DATE piece
    }
    college ||--o{ election : table
    college {
        DATE table
        TEXT very
        VARCHAR(50) reduce
    }
    election ||--o{ result : ball
    election {
        VARCHAR(50) ball
        DATE seven
    }
    result ||--o{ forget : administration
    result {
        DATE administration
        TEXT require
        VARCHAR(50) also
    }