erDiagram
    against ||--o{ anyone : imagine
    against {
        DATE imagine
        TEXT yourself
        VARCHAR(50) little
    }
    anyone ||--o{ number : memory
    anyone {
        VARCHAR(50) memory
        DATE law
    }
    number ||--o{ green : evening
    number {
        DATE evening
        TEXT production
        VARCHAR(50) every
    }
    green ||--o{ leader : fall
    green {
        VARCHAR(50) fall
        DATE statement
    }
    leader ||--o{ writer : study
    leader {
        DATE study
        TEXT type
        VARCHAR(50) church
    }
    writer ||--o{ fine : type
    writer {
        VARCHAR(50) type
        DATE eight
    }
    fine ||--o{ against : education
    fine {
        DATE education
        TEXT list
        VARCHAR(50) information
    }