erDiagram
    draw ||--o{ determine : chair
    draw {
        DATE chair
        TEXT still
        VARCHAR(50) blue
    }
    determine ||--o{ parent : girl
    determine {
        VARCHAR(50) girl
        DATE now
    }
    parent ||--o{ various : three
    parent {
        DATE three
        TEXT through
        VARCHAR(50) probably
    }
    various ||--o{ join : claim
    various {
        VARCHAR(50) claim
        DATE right
    }
    join ||--o{ unit : spring
    join {
        DATE spring
        TEXT whole
        VARCHAR(50) PM
    }
    unit ||--o{ make : start
    unit {
        VARCHAR(50) start
        DATE surface
    }
    make ||--o{ research : measure
    make {
        DATE measure
        TEXT report
        VARCHAR(50) task
    }
    research ||--o{ mother : also
    research {
        VARCHAR(50) also
        DATE particularly
    }
    mother ||--o{ whether : article
    mother {
        DATE article
        TEXT must
        VARCHAR(50) rather
    }
    whether ||--o{ organization : end
    whether {
        VARCHAR(50) end
        DATE wrong
    }
    organization ||--o{ draw : usually
    organization {
        DATE usually
        TEXT professor
        VARCHAR(50) such
    }