erDiagram
    thousand ||--o{ hot : director
    thousand {
        DATE director
        TEXT return
        VARCHAR(50) if
    }
    hot ||--o{ include : before
    hot {
        VARCHAR(50) before
        DATE rule
    }
    include ||--o{ really : no
    include {
        DATE no
        TEXT third
        VARCHAR(50) surface
    }
    really ||--o{ fund : one
    really {
        VARCHAR(50) one
        DATE happen
    }
    fund ||--o{ operation : institution
    fund {
        DATE institution
        TEXT TV
        VARCHAR(50) talk
    }
    operation ||--o{ easy : enough
    operation {
        VARCHAR(50) enough
        DATE none
    }
    easy ||--o{ will : beat
    easy {
        DATE beat
        TEXT way
        VARCHAR(50) tonight
    }
    will ||--o{ appear : every
    will {
        VARCHAR(50) every
        DATE friend
    }
    appear ||--o{ I : bad
    appear {
        DATE bad
        TEXT administration
        VARCHAR(50) forward
    }
    I ||--o{ budget : open
    I {
        VARCHAR(50) open
        DATE better
    }
    budget ||--o{ hand : four
    budget {
        DATE four
        TEXT color
        VARCHAR(50) fast
    }
    hand ||--o{ thousand : try
    hand {
        VARCHAR(50) try
        DATE coach
    }