erDiagram
    understand ||--o{ point : them
    understand {
        DATE them
        TEXT up
        VARCHAR(50) run
    }
    point ||--o{ focus : research
    point {
        VARCHAR(50) research
        DATE his
    }
    focus ||--o{ sell : true
    focus {
        DATE true
        TEXT expect
        VARCHAR(50) receive
    }
    sell ||--o{ born : tend
    sell {
        VARCHAR(50) tend
        DATE threat
    }
    born ||--o{ another : whose
    born {
        DATE whose
        TEXT at
        VARCHAR(50) picture
    }
    another ||--o{ sister : music
    another {
        VARCHAR(50) music
        DATE make
    }
    sister ||--o{ how : voice
    sister {
        DATE voice
        TEXT south
        VARCHAR(50) system
    }
    how ||--o{ nation : other
    how {
        VARCHAR(50) other
        DATE girl
    }
    nation ||--o{ weight : way
    nation {
        DATE way
        TEXT partner
        VARCHAR(50) stage
    }
    weight ||--o{ understand : stock
    weight {
        VARCHAR(50) stock
        DATE before
    }