erDiagram
    company ||--o{ opportunity : avoid
    company {
        DATE avoid
        TEXT goal
        VARCHAR(50) face
    }
    opportunity ||--o{ morning : task
    opportunity {
        VARCHAR(50) task
        DATE score
    }
    morning ||--o{ magazine : practice
    morning {
        DATE practice
        TEXT receive
        VARCHAR(50) act
    }
    magazine ||--o{ less : difficult
    magazine {
        VARCHAR(50) difficult
        DATE through
    }
    less ||--o{ admit : something
    less {
        DATE something
        TEXT adult
        VARCHAR(50) pull
    }
    admit ||--o{ but : remember
    admit {
        VARCHAR(50) remember
        DATE bad
    }
    but ||--o{ among : prepare
    but {
        DATE prepare
        TEXT development
        VARCHAR(50) clearly
    }
    among ||--o{ real : couple
    among {
        VARCHAR(50) couple
        DATE certain
    }
    real ||--o{ company : wall
    real {
        DATE wall
        TEXT together
        VARCHAR(50) sense
    }