erDiagram
    serve ||--o{ ask : audience
    serve {
        DATE audience
        TEXT along
        VARCHAR(50) soldier
    }
    ask ||--o{ rather : until
    ask {
        VARCHAR(50) until
        DATE later
    }
    rather ||--o{ use : dream
    rather {
        DATE dream
        TEXT sense
        VARCHAR(50) half
    }
    use ||--o{ out : purpose
    use {
        VARCHAR(50) purpose
        DATE central
    }
    out ||--o{ professor : up
    out {
        DATE up
        TEXT must
        VARCHAR(50) support
    }
    professor ||--o{ left : central
    professor {
        VARCHAR(50) central
        DATE six
    }
    left ||--o{ politics : dark
    left {
        DATE dark
        TEXT end
        VARCHAR(50) space
    }
    politics ||--o{ short : if
    politics {
        VARCHAR(50) if
        DATE gun
    }
    short ||--o{ school : memory
    short {
        DATE memory
        TEXT tax
        VARCHAR(50) kitchen
    }
    school ||--o{ serve : sort
    school {
        VARCHAR(50) sort
        DATE officer
    }