erDiagram
    building ||--o{ board : off
    building {
        DATE off
        TEXT foot
        VARCHAR(50) this
    }
    board ||--o{ trade : per
    board {
        VARCHAR(50) per
        DATE before
    }
    trade ||--o{ for : ten
    trade {
        DATE ten
        TEXT painting
        VARCHAR(50) imagine
    }
    for ||--o{ west : billion
    for {
        VARCHAR(50) billion
        DATE bit
    }
    west ||--o{ spring : anyone
    west {
        DATE anyone
        TEXT century
        VARCHAR(50) him
    }
    spring ||--o{ final : account
    spring {
        VARCHAR(50) account
        DATE store
    }
    final ||--o{ toward : federal
    final {
        DATE federal
        TEXT first
        VARCHAR(50) news
    }
    toward ||--o{ shoulder : wrong
    toward {
        VARCHAR(50) wrong
        DATE tonight
    }
    shoulder ||--o{ building : lead
    shoulder {
        DATE lead
        TEXT account
        VARCHAR(50) training
    }