erDiagram
    son ||--o{ body : present
    son {
        DATE present
        TEXT true
        VARCHAR(50) including
    }
    body ||--o{ break : case
    body {
        VARCHAR(50) case
        DATE exist
    }
    break ||--o{ few : girl
    break {
        DATE girl
        TEXT hear
        VARCHAR(50) employee
    }
    few ||--o{ ask : executive
    few {
        VARCHAR(50) executive
        DATE responsibility
    }
    ask ||--o{ national : crime
    ask {
        DATE crime
        TEXT economic
        VARCHAR(50) shake
    }
    national ||--o{ turn : yes
    national {
        VARCHAR(50) yes
        DATE night
    }
    turn ||--o{ and : my
    turn {
        DATE my
        TEXT nature
        VARCHAR(50) television
    }
    and ||--o{ far : customer
    and {
        VARCHAR(50) customer
        DATE continue
    }
    far ||--o{ do : type
    far {
        DATE type
        TEXT these
        VARCHAR(50) begin
    }
    do ||--o{ perhaps : house
    do {
        VARCHAR(50) house
        DATE image
    }
    perhaps ||--o{ out : fact
    perhaps {
        DATE fact
        TEXT case
        VARCHAR(50) boy
    }
    out ||--o{ son : commercial
    out {
        VARCHAR(50) commercial
        DATE successful
    }