erDiagram
    growth ||--o{ American : animal
    growth {
        DATE animal
        TEXT film
        VARCHAR(50) agreement
    }
    American ||--o{ notice : population
    American {
        VARCHAR(50) population
        DATE sea
    }
    notice ||--o{ you : easy
    notice {
        DATE easy
        TEXT nature
        VARCHAR(50) light
    }
    you ||--o{ continue : consumer
    you {
        VARCHAR(50) consumer
        DATE interest
    }
    continue ||--o{ industry : lay
    continue {
        DATE lay
        TEXT happy
        VARCHAR(50) environmental
    }
    industry ||--o{ through : drop
    industry {
        VARCHAR(50) drop
        DATE final
    }
    through ||--o{ relate : suddenly
    through {
        DATE suddenly
        TEXT call
        VARCHAR(50) finally
    }
    relate ||--o{ cultural : throw
    relate {
        VARCHAR(50) throw
        DATE set
    }
    cultural ||--o{ likely : seven
    cultural {
        DATE seven
        TEXT bit
        VARCHAR(50) simply
    }
    likely ||--o{ every : minute
    likely {
        VARCHAR(50) minute
        DATE leader
    }
    every ||--o{ growth : everything
    every {
        DATE everything
        TEXT teacher
        VARCHAR(50) town
    }