erDiagram
    get ||--o{ story : discussion
    get {
        DATE discussion
        TEXT senior
        VARCHAR(50) use
    }
    story ||--o{ history : feel
    story {
        VARCHAR(50) feel
        DATE lose
    }
    history ||--o{ reflect : cup
    history {
        DATE cup
        TEXT never
        VARCHAR(50) deal
    }
    reflect ||--o{ our : season
    reflect {
        VARCHAR(50) season
        DATE market
    }
    our ||--o{ few : six
    our {
        DATE six
        TEXT source
        VARCHAR(50) by
    }
    few ||--o{ opportunity : material
    few {
        VARCHAR(50) material
        DATE perhaps
    }
    opportunity ||--o{ everybody : great
    opportunity {
        DATE great
        TEXT future
        VARCHAR(50) mind
    }
    everybody ||--o{ Congress : home
    everybody {
        VARCHAR(50) home
        DATE give
    }
    Congress ||--o{ get : carry
    Congress {
        DATE carry
        TEXT newspaper
        VARCHAR(50) economic
    }