erDiagram
    information ||--o{ left : building
    information {
        DATE building
        TEXT make
        VARCHAR(50) radio
    }
    left ||--o{ to : describe
    left {
        VARCHAR(50) describe
        DATE hair
    }
    to ||--o{ theory : others
    to {
        DATE others
        TEXT probably
        VARCHAR(50) economy
    }
    theory ||--o{ single : simply
    theory {
        VARCHAR(50) simply
        DATE candidate
    }
    single ||--o{ resource : art
    single {
        DATE art
        TEXT gas
        VARCHAR(50) week
    }
    resource ||--o{ hair : produce
    resource {
        VARCHAR(50) produce
        DATE key
    }
    hair ||--o{ wonder : professional
    hair {
        DATE professional
        TEXT pattern
        VARCHAR(50) team
    }
    wonder ||--o{ culture : career
    wonder {
        VARCHAR(50) career
        DATE word
    }
    culture ||--o{ form : reality
    culture {
        DATE reality
        TEXT part
        VARCHAR(50) little
    }
    form ||--o{ ok : him
    form {
        VARCHAR(50) him
        DATE pressure
    }
    ok ||--o{ represent : thousand
    ok {
        DATE thousand
        TEXT such
        VARCHAR(50) me
    }
    represent ||--o{ information : yet
    represent {
        VARCHAR(50) yet
        DATE sell
    }