erDiagram
    support ||--o{ low : information
    support {
        DATE information
        TEXT new
        VARCHAR(50) crime
    }
    low ||--o{ what : red
    low {
        VARCHAR(50) red
        DATE attention
    }
    what ||--o{ however : stand
    what {
        DATE stand
        TEXT possible
        VARCHAR(50) realize
    }
    however ||--o{ marriage : dog
    however {
        VARCHAR(50) dog
        DATE nor
    }
    marriage ||--o{ carry : represent
    marriage {
        DATE represent
        TEXT which
        VARCHAR(50) including
    }
    carry ||--o{ speech : way
    carry {
        VARCHAR(50) way
        DATE threat
    }
    speech ||--o{ support : wide
    speech {
        DATE wide
        TEXT time
        VARCHAR(50) sort
    }