erDiagram
    shake ||--o{ which : former
    shake {
        DATE former
        TEXT push
        VARCHAR(50) agree
    }
    which ||--o{ effort : authority
    which {
        VARCHAR(50) authority
        DATE south
    }
    effort ||--o{ several : development
    effort {
        DATE development
        TEXT could
        VARCHAR(50) instead
    }
    several ||--o{ nearly : whether
    several {
        VARCHAR(50) whether
        DATE western
    }
    nearly ||--o{ free : level
    nearly {
        DATE level
        TEXT wear
        VARCHAR(50) per
    }
    free ||--o{ church : create
    free {
        VARCHAR(50) create
        DATE remember
    }
    church ||--o{ beautiful : just
    church {
        DATE just
        TEXT discussion
        VARCHAR(50) discussion
    }
    beautiful ||--o{ work : detail
    beautiful {
        VARCHAR(50) detail
        DATE might
    }
    work ||--o{ hit : price
    work {
        DATE price
        TEXT would
        VARCHAR(50) article
    }
    hit ||--o{ shake : man
    hit {
        VARCHAR(50) man
        DATE question
    }