erDiagram
    offer ||--o{ particular : author
    offer {
        DATE author
        TEXT style
        VARCHAR(50) modern
    }
    particular ||--o{ real : growth
    particular {
        VARCHAR(50) growth
        DATE want
    }
    real ||--o{ indeed : art
    real {
        DATE art
        TEXT relate
        VARCHAR(50) Congress
    }
    indeed ||--o{ else : material
    indeed {
        VARCHAR(50) material
        DATE reflect
    }
    else ||--o{ campaign : hope
    else {
        DATE hope
        TEXT the
        VARCHAR(50) senior
    }
    campaign ||--o{ arrive : glass
    campaign {
        VARCHAR(50) glass
        DATE range
    }
    arrive ||--o{ cell : sister
    arrive {
        DATE sister
        TEXT city
        VARCHAR(50) call
    }
    cell ||--o{ training : nice
    cell {
        VARCHAR(50) nice
        DATE share
    }
    training ||--o{ street : opportunity
    training {
        DATE opportunity
        TEXT center
        VARCHAR(50) animal
    }
    street ||--o{ offer : pull
    street {
        VARCHAR(50) pull
        DATE from
    }