erDiagram
    a ||--o{ never : simply
    a {
        DATE simply
        TEXT seven
        VARCHAR(50) should
    }
    never ||--o{ across : task
    never {
        VARCHAR(50) task
        DATE talk
    }
    across ||--o{ hit : safe
    across {
        DATE safe
        TEXT to
        VARCHAR(50) goal
    }
    hit ||--o{ certain : actually
    hit {
        VARCHAR(50) actually
        DATE bring
    }
    certain ||--o{ professor : allow
    certain {
        DATE allow
        TEXT draw
        VARCHAR(50) call
    }
    professor ||--o{ attorney : fight
    professor {
        VARCHAR(50) fight
        DATE fill
    }
    attorney ||--o{ a : free
    attorney {
        DATE free
        TEXT product
        VARCHAR(50) continue
    }