erDiagram
    reduce ||--o{ physical : thank
    reduce {
        DATE thank
        TEXT box
        VARCHAR(50) decide
    }
    physical ||--o{ himself : member
    physical {
        VARCHAR(50) member
        DATE become
    }
    himself ||--o{ whatever : director
    himself {
        DATE director
        TEXT heart
        VARCHAR(50) artist
    }
    whatever ||--o{ draw : building
    whatever {
        VARCHAR(50) building
        DATE message
    }
    draw ||--o{ home : at
    draw {
        DATE at
        TEXT task
        VARCHAR(50) black
    }
    home ||--o{ here : give
    home {
        VARCHAR(50) give
        DATE work
    }
    here ||--o{ benefit : no
    here {
        DATE no
        TEXT everyone
        VARCHAR(50) herself
    }
    benefit ||--o{ already : letter
    benefit {
        VARCHAR(50) letter
        DATE look
    }
    already ||--o{ letter : relate
    already {
        DATE relate
        TEXT happen
        VARCHAR(50) someone
    }
    letter ||--o{ reduce : explain
    letter {
        VARCHAR(50) explain
        DATE above
    }