erDiagram
    social ||--o{ respond : red
    social {
        DATE red
        TEXT quality
        VARCHAR(50) reduce
    }
    respond ||--o{ fly : crime
    respond {
        VARCHAR(50) crime
        DATE pull
    }
    fly ||--o{ finally : myself
    fly {
        DATE myself
        TEXT middle
        VARCHAR(50) start
    }
    finally ||--o{ special : enter
    finally {
        VARCHAR(50) enter
        DATE other
    }
    special ||--o{ recognize : skill
    special {
        DATE skill
        TEXT surface
        VARCHAR(50) modern
    }
    recognize ||--o{ price : again
    recognize {
        VARCHAR(50) again
        DATE organization
    }
    price ||--o{ section : pull
    price {
        DATE pull
        TEXT simple
        VARCHAR(50) whatever
    }
    section ||--o{ prove : catch
    section {
        VARCHAR(50) catch
        DATE opportunity
    }
    prove ||--o{ remain : near
    prove {
        DATE near
        TEXT about
        VARCHAR(50) record
    }
    remain ||--o{ interview : receive
    remain {
        VARCHAR(50) receive
        DATE cut
    }
    interview ||--o{ hit : maybe
    interview {
        DATE maybe
        TEXT back
        VARCHAR(50) series
    }
    hit ||--o{ social : light
    hit {
        VARCHAR(50) light
        DATE particular
    }