erDiagram
    hold ||--o{ fight : example
    hold {
        DATE example
        TEXT response
        VARCHAR(50) new
    }
    fight ||--o{ answer : site
    fight {
        VARCHAR(50) site
        DATE air
    }
    answer ||--o{ ok : necessary
    answer {
        DATE necessary
        TEXT just
        VARCHAR(50) Congress
    }
    ok ||--o{ with : economy
    ok {
        VARCHAR(50) economy
        DATE gun
    }
    with ||--o{ before : spring
    with {
        DATE spring
        TEXT world
        VARCHAR(50) visit
    }
    before ||--o{ believe : board
    before {
        VARCHAR(50) board
        DATE consider
    }
    believe ||--o{ smile : bed
    believe {
        DATE bed
        TEXT keep
        VARCHAR(50) arm
    }
    smile ||--o{ teacher : its
    smile {
        VARCHAR(50) its
        DATE understand
    }
    teacher ||--o{ social : five
    teacher {
        DATE five
        TEXT nation
        VARCHAR(50) game
    }
    social ||--o{ hold : Mr
    social {
        VARCHAR(50) Mr
        DATE happen
    }