erDiagram
    market ||--o{ of : too
    market {
        DATE too
        TEXT here
        VARCHAR(50) interview
    }
    of ||--o{ friend : method
    of {
        VARCHAR(50) method
        DATE paper
    }
    friend ||--o{ least : source
    friend {
        DATE source
        TEXT under
        VARCHAR(50) inside
    }
    least ||--o{ everybody : want
    least {
        VARCHAR(50) want
        DATE whole
    }
    everybody ||--o{ behind : throw
    everybody {
        DATE throw
        TEXT between
        VARCHAR(50) type
    }
    behind ||--o{ try : professor
    behind {
        VARCHAR(50) professor
        DATE stop
    }
    try ||--o{ decide : bed
    try {
        DATE bed
        TEXT often
        VARCHAR(50) staff
    }
    decide ||--o{ old : generation
    decide {
        VARCHAR(50) generation
        DATE evidence
    }
    old ||--o{ market : reduce
    old {
        DATE reduce
        TEXT arrive
        VARCHAR(50) along
    }