erDiagram
    business ||--o{ maintain : music
    business {
        DATE music
        TEXT upon
        VARCHAR(50) message
    }
    maintain ||--o{ only : threat
    maintain {
        VARCHAR(50) threat
        DATE cold
    }
    only ||--o{ summer : song
    only {
        DATE song
        TEXT majority
        VARCHAR(50) into
    }
    summer ||--o{ high : lot
    summer {
        VARCHAR(50) lot
        DATE remain
    }
    high ||--o{ design : buy
    high {
        DATE buy
        TEXT meeting
        VARCHAR(50) building
    }
    design ||--o{ guy : result
    design {
        VARCHAR(50) result
        DATE way
    }
    guy ||--o{ building : north
    guy {
        DATE north
        TEXT three
        VARCHAR(50) play
    }
    building ||--o{ anyone : student
    building {
        VARCHAR(50) student
        DATE yard
    }
    anyone ||--o{ decade : really
    anyone {
        DATE really
        TEXT even
        VARCHAR(50) assume
    }
    decade ||--o{ business : land
    decade {
        VARCHAR(50) land
        DATE tell
    }