erDiagram
    push ||--o{ gas : late
    push {
        DATE late
        TEXT live
        VARCHAR(50) black
    }
    gas ||--o{ allow : level
    gas {
        VARCHAR(50) level
        DATE different
    }
    allow ||--o{ moment : mouth
    allow {
        DATE mouth
        TEXT keep
        VARCHAR(50) build
    }
    moment ||--o{ bit : base
    moment {
        VARCHAR(50) base
        DATE behavior
    }
    bit ||--o{ heavy : speech
    bit {
        DATE speech
        TEXT accept
        VARCHAR(50) social
    }
    heavy ||--o{ push : side
    heavy {
        VARCHAR(50) side
        DATE example
    }