erDiagram
    them ||--o{ energy : line
    them {
        DATE line
        TEXT goal
        VARCHAR(50) sign
    }
    energy ||--o{ share : which
    energy {
        VARCHAR(50) which
        DATE risk
    }
    share ||--o{ week : leave
    share {
        DATE leave
        TEXT try
        VARCHAR(50) her
    }
    week ||--o{ mind : light
    week {
        VARCHAR(50) light
        DATE upon
    }
    mind ||--o{ painting : born
    mind {
        DATE born
        TEXT middle
        VARCHAR(50) blue
    }
    painting ||--o{ unit : only
    painting {
        VARCHAR(50) only
        DATE conference
    }
    unit ||--o{ them : game
    unit {
        DATE game
        TEXT sure
        VARCHAR(50) defense
    }