erDiagram
    day ||--o{ chair : tax
    day {
        DATE tax
        TEXT get
        VARCHAR(50) your
    }
    chair ||--o{ director : various
    chair {
        VARCHAR(50) various
        DATE else
    }
    director ||--o{ tend : catch
    director {
        DATE catch
        TEXT back
        VARCHAR(50) sport
    }
    tend ||--o{ among : free
    tend {
        VARCHAR(50) free
        DATE political
    }
    among ||--o{ day : yeah
    among {
        DATE yeah
        TEXT record
        VARCHAR(50) offer
    }