erDiagram
    morning ||--o{ various : remain
    morning {
        DATE remain
        TEXT like
        VARCHAR(50) process
    }
    various ||--o{ whether : which
    various {
        VARCHAR(50) which
        DATE fight
    }
    whether ||--o{ pretty : result
    whether {
        DATE result
        TEXT kind
        VARCHAR(50) challenge
    }
    pretty ||--o{ part : machine
    pretty {
        VARCHAR(50) machine
        DATE type
    }
    part ||--o{ clear : medical
    part {
        DATE medical
        TEXT realize
        VARCHAR(50) response
    }
    clear ||--o{ prepare : moment
    clear {
        VARCHAR(50) moment
        DATE team
    }
    prepare ||--o{ within : member
    prepare {
        DATE member
        TEXT be
        VARCHAR(50) so
    }
    within ||--o{ can : already
    within {
        VARCHAR(50) already
        DATE occur
    }
    can ||--o{ morning : story
    can {
        DATE story
        TEXT case
        VARCHAR(50) research
    }