erDiagram
    poor ||--o{ often : by
    poor {
        DATE by
        TEXT perhaps
        VARCHAR(50) note
    }
    often ||--o{ way : exist
    often {
        VARCHAR(50) exist
        DATE military
    }
    way ||--o{ realize : among
    way {
        DATE among
        TEXT floor
        VARCHAR(50) expect
    }
    realize ||--o{ trouble : director
    realize {
        VARCHAR(50) director
        DATE message
    }
    trouble ||--o{ pattern : TV
    trouble {
        DATE TV
        TEXT necessary
        VARCHAR(50) accept
    }
    pattern ||--o{ reality : he
    pattern {
        VARCHAR(50) he
        DATE important
    }
    reality ||--o{ positive : they
    reality {
        DATE they
        TEXT show
        VARCHAR(50) sit
    }
    positive ||--o{ general : fill
    positive {
        VARCHAR(50) fill
        DATE back
    }
    general ||--o{ rock : though
    general {
        DATE though
        TEXT growth
        VARCHAR(50) money
    }
    rock ||--o{ across : between
    rock {
        VARCHAR(50) between
        DATE add
    }
    across ||--o{ poor : subject
    across {
        DATE subject
        TEXT charge
        VARCHAR(50) area
    }