erDiagram
    pattern ||--o{ write : themselves
    pattern {
        DATE themselves
        TEXT age
        VARCHAR(50) score
    }
    write ||--o{ clearly : under
    write {
        VARCHAR(50) under
        DATE blood
    }
    clearly ||--o{ avoid : get
    clearly {
        DATE get
        TEXT young
        VARCHAR(50) involve
    }
    avoid ||--o{ conference : oil
    avoid {
        VARCHAR(50) oil
        DATE really
    }
    conference ||--o{ rest : game
    conference {
        DATE game
        TEXT little
        VARCHAR(50) sound
    }
    rest ||--o{ pattern : raise
    rest {
        VARCHAR(50) raise
        DATE full
    }