erDiagram
    similar ||--o{ how : body
    similar {
        DATE body
        TEXT attack
        VARCHAR(50) character
    }
    how ||--o{ season : Democrat
    how {
        VARCHAR(50) Democrat
        DATE bag
    }
    season ||--o{ sort : watch
    season {
        DATE watch
        TEXT responsibility
        VARCHAR(50) weight
    }
    sort ||--o{ maybe : husband
    sort {
        VARCHAR(50) husband
        DATE show
    }
    maybe ||--o{ still : attack
    maybe {
        DATE attack
        TEXT program
        VARCHAR(50) contain
    }
    still ||--o{ adult : against
    still {
        VARCHAR(50) against
        DATE film
    }
    adult ||--o{ similar : food
    adult {
        DATE food
        TEXT quite
        VARCHAR(50) market
    }