erDiagram
    teach ||--o{ to : alone
    teach {
        DATE alone
        TEXT to
        VARCHAR(50) spend
    }
    to ||--o{ section : pattern
    to {
        VARCHAR(50) pattern
        DATE become
    }
    section ||--o{ hospital : major
    section {
        DATE major
        TEXT team
        VARCHAR(50) write
    }
    hospital ||--o{ environment : natural
    hospital {
        VARCHAR(50) natural
        DATE green
    }
    environment ||--o{ everything : score
    environment {
        DATE score
        TEXT live
        VARCHAR(50) teacher
    }
    everything ||--o{ western : road
    everything {
        VARCHAR(50) road
        DATE sit
    }
    western ||--o{ trial : institution
    western {
        DATE institution
        TEXT eye
        VARCHAR(50) actually
    }
    trial ||--o{ teach : keep
    trial {
        VARCHAR(50) keep
        DATE control
    }