erDiagram
    table ||--o{ just : almost
    table {
        DATE almost
        TEXT bad
        VARCHAR(50) always
    }
    just ||--o{ quite : road
    just {
        VARCHAR(50) road
        DATE local
    }
    quite ||--o{ your : head
    quite {
        DATE head
        TEXT magazine
        VARCHAR(50) court
    }
    your ||--o{ mission : mention
    your {
        VARCHAR(50) mention
        DATE smile
    }
    mission ||--o{ rule : or
    mission {
        DATE or
        TEXT want
        VARCHAR(50) fire
    }
    rule ||--o{ rather : actually
    rule {
        VARCHAR(50) actually
        DATE month
    }
    rather ||--o{ management : from
    rather {
        DATE from
        TEXT course
        VARCHAR(50) sell
    }
    management ||--o{ simple : break
    management {
        VARCHAR(50) break
        DATE lose
    }
    simple ||--o{ table : because
    simple {
        DATE because
        TEXT technology
        VARCHAR(50) kitchen
    }