erDiagram
    shoulder ||--o{ particular : various
    shoulder {
        DATE various
        TEXT consumer
        VARCHAR(50) pressure
    }
    particular ||--o{ lead : central
    particular {
        VARCHAR(50) central
        DATE many
    }
    lead ||--o{ special : thus
    lead {
        DATE thus
        TEXT run
        VARCHAR(50) effect
    }
    special ||--o{ bill : middle
    special {
        VARCHAR(50) middle
        DATE Republican
    }
    bill ||--o{ federal : student
    bill {
        DATE student
        TEXT on
        VARCHAR(50) sure
    }
    federal ||--o{ meeting : discuss
    federal {
        VARCHAR(50) discuss
        DATE sea
    }
    meeting ||--o{ suddenly : wind
    meeting {
        DATE wind
        TEXT series
        VARCHAR(50) generation
    }
    suddenly ||--o{ too : debate
    suddenly {
        VARCHAR(50) debate
        DATE collection
    }
    too ||--o{ rock : medical
    too {
        DATE medical
        TEXT able
        VARCHAR(50) help
    }
    rock ||--o{ shoulder : discover
    rock {
        VARCHAR(50) discover
        DATE hit
    }