erDiagram
    operation ||--o{ seat : give
    operation {
        DATE give
        TEXT firm
        VARCHAR(50) follow
    }
    seat ||--o{ increase : military
    seat {
        VARCHAR(50) military
        DATE home
    }
    increase ||--o{ quite : hard
    increase {
        DATE hard
        TEXT necessary
        VARCHAR(50) argue
    }
    quite ||--o{ expert : financial
    quite {
        VARCHAR(50) financial
        DATE happy
    }
    expert ||--o{ yard : similar
    expert {
        DATE similar
        TEXT above
        VARCHAR(50) country
    }
    yard ||--o{ film : campaign
    yard {
        VARCHAR(50) campaign
        DATE entire
    }
    film ||--o{ hospital : arrive
    film {
        DATE arrive
        TEXT four
        VARCHAR(50) next
    }
    hospital ||--o{ measure : consider
    hospital {
        VARCHAR(50) consider
        DATE set
    }
    measure ||--o{ operation : old
    measure {
        DATE old
        TEXT black
        VARCHAR(50) fly
    }