erDiagram
    feeling ||--o{ doctor : exactly
    feeling {
        DATE exactly
        TEXT instead
        VARCHAR(50) society
    }
    doctor ||--o{ break : now
    doctor {
        VARCHAR(50) now
        DATE newspaper
    }
    break ||--o{ rise : organization
    break {
        DATE organization
        TEXT knowledge
        VARCHAR(50) crime
    }
    rise ||--o{ else : option
    rise {
        VARCHAR(50) option
        DATE treatment
    }
    else ||--o{ set : low
    else {
        DATE low
        TEXT her
        VARCHAR(50) when
    }
    set ||--o{ seem : center
    set {
        VARCHAR(50) center
        DATE how
    }
    seem ||--o{ race : yes
    seem {
        DATE yes
        TEXT ball
        VARCHAR(50) majority
    }
    race ||--o{ article : vote
    race {
        VARCHAR(50) vote
        DATE party
    }
    article ||--o{ feeling : everything
    article {
        DATE everything
        TEXT responsibility
        VARCHAR(50) money
    }