erDiagram
    indicate ||--o{ huge : morning
    indicate {
        DATE morning
        TEXT there
        VARCHAR(50) people
    }
    huge ||--o{ million : record
    huge {
        VARCHAR(50) record
        DATE million
    }
    million ||--o{ compare : present
    million {
        DATE present
        TEXT religious
        VARCHAR(50) sport
    }
    compare ||--o{ both : price
    compare {
        VARCHAR(50) price
        DATE everything
    }
    both ||--o{ together : minute
    both {
        DATE minute
        TEXT think
        VARCHAR(50) sometimes
    }
    together ||--o{ game : threat
    together {
        VARCHAR(50) threat
        DATE sit
    }
    game ||--o{ town : agency
    game {
        DATE agency
        TEXT development
        VARCHAR(50) hear
    }
    town ||--o{ bill : before
    town {
        VARCHAR(50) before
        DATE station
    }
    bill ||--o{ throughout : indicate
    bill {
        DATE indicate
        TEXT some
        VARCHAR(50) cold
    }
    throughout ||--o{ indicate : notice
    throughout {
        VARCHAR(50) notice
        DATE kid
    }