erDiagram
    good ||--o{ democratic : wife
    good {
        DATE wife
        TEXT movie
        VARCHAR(50) north
    }
    democratic ||--o{ focus : nice
    democratic {
        VARCHAR(50) nice
        DATE course
    }
    focus ||--o{ safe : baby
    focus {
        DATE baby
        TEXT worry
        VARCHAR(50) resource
    }
    safe ||--o{ wall : us
    safe {
        VARCHAR(50) us
        DATE upon
    }
    wall ||--o{ often : child
    wall {
        DATE child
        TEXT read
        VARCHAR(50) them
    }
    often ||--o{ Republican : protect
    often {
        VARCHAR(50) protect
        DATE character
    }
    Republican ||--o{ generation : sign
    Republican {
        DATE sign
        TEXT evidence
        VARCHAR(50) family
    }
    generation ||--o{ good : someone
    generation {
        VARCHAR(50) someone
        DATE charge
    }