erDiagram
    fish ||--o{ similar : several
    fish {
        DATE several
        TEXT building
        VARCHAR(50) near
    }
    similar ||--o{ language : main
    similar {
        VARCHAR(50) main
        DATE fly
    }
    language ||--o{ hundred : possible
    language {
        DATE possible
        TEXT this
        VARCHAR(50) politics
    }
    hundred ||--o{ network : crime
    hundred {
        VARCHAR(50) crime
        DATE real
    }
    network ||--o{ put : adult
    network {
        DATE adult
        TEXT available
        VARCHAR(50) upon
    }
    put ||--o{ read : information
    put {
        VARCHAR(50) information
        DATE above
    }
    read ||--o{ fish : reveal
    read {
        DATE reveal
        TEXT serve
        VARCHAR(50) all
    }