erDiagram
    evidence ||--o{ too : exist
    evidence {
        DATE exist
        TEXT event
        VARCHAR(50) base
    }
    too ||--o{ support : like
    too {
        VARCHAR(50) like
        DATE arm
    }
    support ||--o{ capital : eight
    support {
        DATE eight
        TEXT fear
        VARCHAR(50) month
    }
    capital ||--o{ nor : none
    capital {
        VARCHAR(50) none
        DATE wife
    }
    nor ||--o{ human : talk
    nor {
        DATE talk
        TEXT star
        VARCHAR(50) pretty
    }
    human ||--o{ indicate : loss
    human {
        VARCHAR(50) loss
        DATE hospital
    }
    indicate ||--o{ evidence : environment
    indicate {
        DATE environment
        TEXT shake
        VARCHAR(50) team
    }