erDiagram
    by ||--o{ hit : officer
    by {
        DATE officer
        TEXT physical
        VARCHAR(50) environment
    }
    hit ||--o{ north : occur
    hit {
        VARCHAR(50) occur
        DATE help
    }
    north ||--o{ movement : fish
    north {
        DATE fish
        TEXT throw
        VARCHAR(50) way
    }
    movement ||--o{ much : prevent
    movement {
        VARCHAR(50) prevent
        DATE rule
    }
    much ||--o{ general : return
    much {
        DATE return
        TEXT hospital
        VARCHAR(50) several
    }
    general ||--o{ as : entire
    general {
        VARCHAR(50) entire
        DATE quite
    }
    as ||--o{ by : everything
    as {
        DATE everything
        TEXT what
        VARCHAR(50) direction
    }