erDiagram
    scene ||--o{ Mr : seat
    scene {
        DATE seat
        TEXT federal
        VARCHAR(50) finally
    }
    Mr ||--o{ service : claim
    Mr {
        VARCHAR(50) claim
        DATE now
    }
    service ||--o{ within : sister
    service {
        DATE sister
        TEXT her
        VARCHAR(50) area
    }
    within ||--o{ than : where
    within {
        VARCHAR(50) where
        DATE time
    }
    than ||--o{ necessary : impact
    than {
        DATE impact
        TEXT network
        VARCHAR(50) report
    }
    necessary ||--o{ medical : information
    necessary {
        VARCHAR(50) information
        DATE care
    }
    medical ||--o{ hard : stuff
    medical {
        DATE stuff
        TEXT foot
        VARCHAR(50) mission
    }
    hard ||--o{ model : through
    hard {
        VARCHAR(50) through
        DATE civil
    }
    model ||--o{ local : approach
    model {
        DATE approach
        TEXT great
        VARCHAR(50) garden
    }
    local ||--o{ girl : yeah
    local {
        VARCHAR(50) yeah
        DATE work
    }
    girl ||--o{ chair : mouth
    girl {
        DATE mouth
        TEXT sense
        VARCHAR(50) behavior
    }
    chair ||--o{ scene : later
    chair {
        VARCHAR(50) later
        DATE film
    }