erDiagram
    line ||--o{ activity : push
    line {
        DATE push
        TEXT big
        VARCHAR(50) provide
    }
    activity ||--o{ front : figure
    activity {
        VARCHAR(50) figure
        DATE determine
    }
    front ||--o{ color : effect
    front {
        DATE effect
        TEXT so
        VARCHAR(50) animal
    }
    color ||--o{ determine : article
    color {
        VARCHAR(50) article
        DATE seat
    }
    determine ||--o{ line : although
    determine {
        DATE although
        TEXT however
        VARCHAR(50) whether
    }