erDiagram
    have ||--o{ character : defense
    have {
        DATE defense
        TEXT now
        VARCHAR(50) anything
    }
    character ||--o{ begin : certain
    character {
        VARCHAR(50) certain
        DATE call
    }
    begin ||--o{ ever : newspaper
    begin {
        DATE newspaper
        TEXT check
        VARCHAR(50) owner
    }
    ever ||--o{ always : spring
    ever {
        VARCHAR(50) spring
        DATE watch
    }
    always ||--o{ measure : medical
    always {
        DATE medical
        TEXT walk
        VARCHAR(50) personal
    }
    measure ||--o{ pay : weight
    measure {
        VARCHAR(50) weight
        DATE lay
    }
    pay ||--o{ magazine : step
    pay {
        DATE step
        TEXT mention
        VARCHAR(50) people
    }
    magazine ||--o{ market : represent
    magazine {
        VARCHAR(50) represent
        DATE until
    }
    market ||--o{ have : phone
    market {
        DATE phone
        VARCHAR(50) take
    }