erDiagram
    science ||--o{ until : easy
    science {
        DATE easy
        TEXT rest
        VARCHAR(50) case
    }
    until ||--o{ health : plant
    until {
        VARCHAR(50) plant
        DATE fight
    }
    health ||--o{ term : she
    health {
        DATE she
        TEXT city
        VARCHAR(50) movie
    }
    term ||--o{ fly : huge
    term {
        VARCHAR(50) huge
        DATE raise
    }
    fly ||--o{ provide : article
    fly {
        DATE article
        TEXT style
        VARCHAR(50) discussion
    }
    provide ||--o{ effect : Democrat
    provide {
        VARCHAR(50) Democrat
        DATE hope
    }
    effect ||--o{ state : plan
    effect {
        DATE plan
        TEXT keep
        VARCHAR(50) there
    }
    state ||--o{ forward : language
    state {
        VARCHAR(50) language
        DATE anything
    }
    forward ||--o{ parent : air
    forward {
        DATE air
        TEXT seem
        VARCHAR(50) single
    }
    parent ||--o{ service : but
    parent {
        VARCHAR(50) but
        DATE travel
    }
    service ||--o{ science : notice
    service {
        DATE notice
        TEXT whose
        VARCHAR(50) hit
    }