erDiagram
    might ||--o{ maybe : wind
    might {
        DATE wind
        TEXT impact
        VARCHAR(50) likely
    }
    maybe ||--o{ rather : forward
    maybe {
        VARCHAR(50) forward
        DATE yard
    }
    rather ||--o{ me : bar
    rather {
        DATE bar
        TEXT expect
        VARCHAR(50) question
    }
    me ||--o{ those : forget
    me {
        VARCHAR(50) forget
        DATE result
    }
    those ||--o{ blood : just
    those {
        DATE just
        TEXT sing
        VARCHAR(50) itself
    }
    blood ||--o{ history : time
    blood {
        VARCHAR(50) time
        DATE series
    }
    history ||--o{ law : board
    history {
        DATE board
        TEXT list
        VARCHAR(50) perform
    }
    law ||--o{ someone : many
    law {
        VARCHAR(50) many
        DATE indicate
    }
    someone ||--o{ sister : necessary
    someone {
        DATE necessary
        TEXT condition
        VARCHAR(50) war
    }
    sister ||--o{ might : investment
    sister {
        VARCHAR(50) investment
        DATE actually
    }