erDiagram
    federal ||--o{ thing : off
    federal {
        DATE off
        TEXT man
        VARCHAR(50) matter
    }
    thing ||--o{ evening : with
    thing {
        VARCHAR(50) with
        DATE feel
    }
    evening ||--o{ visit : study
    evening {
        DATE study
        TEXT organization
        VARCHAR(50) indeed
    }
    visit ||--o{ manager : less
    visit {
        VARCHAR(50) less
        DATE mother
    }
    manager ||--o{ radio : else
    manager {
        DATE else
        TEXT house
        VARCHAR(50) small
    }
    radio ||--o{ federal : first
    radio {
        VARCHAR(50) first
        DATE effect
    }