erDiagram
    rise ||--o{ ever : recently
    rise {
        DATE recently
        TEXT garden
        VARCHAR(50) help
    }
    ever ||--o{ key : try
    ever {
        VARCHAR(50) try
        DATE best
    }
    key ||--o{ until : prevent
    key {
        DATE prevent
        TEXT require
        VARCHAR(50) admit
    }
    until ||--o{ house : third
    until {
        VARCHAR(50) third
        DATE base
    }
    house ||--o{ rise : cell
    house {
        DATE cell
        TEXT certain
        VARCHAR(50) old
    }