erDiagram
    describe ||--o{ natural : right
    describe {
        DATE right
        TEXT teach
        VARCHAR(50) me
    }
    natural ||--o{ add : beat
    natural {
        VARCHAR(50) beat
        DATE tend
    }
    add ||--o{ accept : off
    add {
        DATE off
        TEXT likely
        VARCHAR(50) painting
    }
    accept ||--o{ security : deep
    accept {
        VARCHAR(50) deep
        DATE trade
    }
    security ||--o{ low : structure
    security {
        DATE structure
        TEXT history
        VARCHAR(50) authority
    }
    low ||--o{ firm : he
    low {
        VARCHAR(50) he
        DATE camera
    }
    firm ||--o{ describe : another
    firm {
        DATE another
        TEXT exist
        VARCHAR(50) summer
    }