erDiagram
    animal ||--o{ his : attack
    animal {
        DATE attack
        TEXT receive
        VARCHAR(50) sit
    }
    his ||--o{ different : purpose
    his {
        VARCHAR(50) purpose
        DATE daughter
    }
    different ||--o{ what : mind
    different {
        DATE mind
        TEXT control
        VARCHAR(50) enter
    }
    what ||--o{ late : bar
    what {
        VARCHAR(50) bar
        DATE team
    }
    late ||--o{ group : approach
    late {
        DATE approach
        TEXT think
        VARCHAR(50) bit
    }
    group ||--o{ animal : something
    group {
        VARCHAR(50) something
        DATE pick
    }