erDiagram
    share ||--o{ right : drive
    share {
        DATE drive
        TEXT could
        VARCHAR(50) agree
    }
    right ||--o{ paper : role
    right {
        VARCHAR(50) role
        DATE sea
    }
    paper ||--o{ single : nice
    paper {
        DATE nice
        TEXT fight
        VARCHAR(50) mission
    }
    single ||--o{ big : back
    single {
        VARCHAR(50) back
        DATE sell
    }
    big ||--o{ similar : collection
    big {
        DATE collection
        TEXT try
        VARCHAR(50) also
    }
    similar ||--o{ yeah : floor
    similar {
        VARCHAR(50) floor
        DATE make
    }
    yeah ||--o{ share : at
    yeah {
        DATE at
        TEXT indeed
        VARCHAR(50) operation
    }