erDiagram
    consider ||--o{ even : social
    consider {
        DATE social
        TEXT room
        VARCHAR(50) success
    }
    even ||--o{ not : report
    even {
        VARCHAR(50) report
        DATE example
    }
    not ||--o{ skin : glass
    not {
        DATE glass
        TEXT president
        VARCHAR(50) certainly
    }
    skin ||--o{ board : question
    skin {
        VARCHAR(50) question
        DATE sound
    }
    board ||--o{ consider : watch
    board {
        DATE watch
        TEXT speech
        VARCHAR(50) fall
    }