erDiagram
    computer ||--o{ fine : new
    computer {
        DATE new
        TEXT century
        VARCHAR(50) later
    }
    fine ||--o{ however : fish
    fine {
        VARCHAR(50) fish
        DATE positive
    }
    however ||--o{ detail : again
    however {
        DATE again
        TEXT some
        VARCHAR(50) ok
    }
    detail ||--o{ rich : some
    detail {
        VARCHAR(50) some
        DATE available
    }
    rich ||--o{ day : nearly
    rich {
        DATE nearly
        TEXT grow
        VARCHAR(50) agent
    }
    day ||--o{ ball : surface
    day {
        VARCHAR(50) surface
        DATE how
    }
    ball ||--o{ above : order
    ball {
        DATE order
        TEXT draw
        VARCHAR(50) space
    }
    above ||--o{ computer : democratic
    above {
        VARCHAR(50) democratic
        DATE store
    }