erDiagram
    must ||--o{ statement : before
    must {
        DATE before
        TEXT suffer
        VARCHAR(50) take
    }
    statement ||--o{ focus : food
    statement {
        VARCHAR(50) food
        DATE yourself
    }
    focus ||--o{ trip : degree
    focus {
        DATE degree
        TEXT write
        VARCHAR(50) evidence
    }
    trip ||--o{ daughter : write
    trip {
        VARCHAR(50) write
        DATE pull
    }
    daughter ||--o{ must : investment
    daughter {
        DATE investment
        TEXT fill
        VARCHAR(50) ask
    }