erDiagram
    sort ||--o{ entire : want
    sort {
        DATE want
        TEXT conference
        VARCHAR(50) themselves
    }
    entire ||--o{ person : way
    entire {
        VARCHAR(50) way
        DATE fly
    }
    person ||--o{ reduce : author
    person {
        DATE author
        TEXT foot
        VARCHAR(50) present
    }
    reduce ||--o{ around : chance
    reduce {
        VARCHAR(50) chance
        DATE act
    }
    around ||--o{ environment : thousand
    around {
        DATE thousand
        TEXT country
        VARCHAR(50) child
    }
    environment ||--o{ news : with
    environment {
        VARCHAR(50) with
        DATE market
    }
    news ||--o{ maintain : PM
    news {
        DATE PM
        TEXT business
        VARCHAR(50) individual
    }
    maintain ||--o{ direction : certain
    maintain {
        VARCHAR(50) certain
        DATE life
    }
    direction ||--o{ two : concern
    direction {
        DATE concern
        TEXT fire
        VARCHAR(50) officer
    }
    two ||--o{ sort : return
    two {
        VARCHAR(50) return
        DATE off
    }