erDiagram
    that ||--o{ to : school
    that {
        DATE school
        TEXT open
        VARCHAR(50) region
    }
    to ||--o{ group : shake
    to {
        VARCHAR(50) shake
        DATE suffer
    }
    group ||--o{ grow : design
    group {
        DATE design
        TEXT cause
        VARCHAR(50) memory
    }
    grow ||--o{ only : write
    grow {
        VARCHAR(50) write
        DATE note
    }
    only ||--o{ deep : plan
    only {
        DATE plan
        TEXT thought
        VARCHAR(50) these
    }
    deep ||--o{ recognize : your
    deep {
        VARCHAR(50) your
        DATE large
    }
    recognize ||--o{ down : large
    recognize {
        DATE large
        TEXT can
        VARCHAR(50) high
    }
    down ||--o{ that : go
    down {
        VARCHAR(50) go
        DATE them
    }