erDiagram
    behavior ||--o{ ball : after
    behavior {
        DATE after
        TEXT answer
        VARCHAR(50) policy
    }
    ball ||--o{ turn : money
    ball {
        VARCHAR(50) money
        DATE mission
    }
    turn ||--o{ long : compare
    turn {
        DATE compare
        TEXT fire
        VARCHAR(50) operation
    }
    long ||--o{ turn : hair
    long {
        VARCHAR(50) hair
        DATE create
    }
    turn ||--o{ doctor : onto
    turn {
        DATE onto
        TEXT economy
        VARCHAR(50) identify
    }
    doctor ||--o{ hit : resource
    doctor {
        VARCHAR(50) resource
        DATE claim
    }
    hit ||--o{ plan : relate
    hit {
        DATE relate
        TEXT industry
        VARCHAR(50) per
    }
    plan ||--o{ behavior : step
    plan {
        VARCHAR(50) step
        DATE yes
    }