erDiagram
    alone ||--o{ tough : tonight
    alone {
        DATE tonight
        TEXT anything
        VARCHAR(50) consumer
    }
    tough ||--o{ college : design
    tough {
        VARCHAR(50) design
        DATE several
    }
    college ||--o{ we : main
    college {
        DATE main
        TEXT yet
        VARCHAR(50) live
    }
    we ||--o{ worry : newspaper
    we {
        VARCHAR(50) newspaper
        DATE reflect
    }
    worry ||--o{ admit : final
    worry {
        DATE final
        TEXT together
        VARCHAR(50) dream
    }
    admit ||--o{ alone : bed
    admit {
        VARCHAR(50) bed
        DATE since
    }