erDiagram
    type ||--o{ party : attorney
    type {
        DATE attorney
        TEXT push
        VARCHAR(50) personal
    }
    party ||--o{ protect : million
    party {
        VARCHAR(50) million
        DATE employee
    }
    protect ||--o{ themselves : still
    protect {
        DATE still
        TEXT social
        VARCHAR(50) table
    }
    themselves ||--o{ according : western
    themselves {
        VARCHAR(50) western
        DATE specific
    }
    according ||--o{ edge : page
    according {
        DATE page
        TEXT teach
        VARCHAR(50) person
    }
    edge ||--o{ feeling : big
    edge {
        VARCHAR(50) big
        DATE whether
    }
    feeling ||--o{ throughout : enter
    feeling {
        DATE enter
        TEXT pull
        VARCHAR(50) city
    }
    throughout ||--o{ type : turn
    throughout {
        VARCHAR(50) turn
        DATE stock
    }