erDiagram
    join ||--o{ form : effect
    join {
        DATE effect
        TEXT heart
        VARCHAR(50) example
    }
    form ||--o{ capital : despite
    form {
        VARCHAR(50) despite
        DATE bag
    }
    capital ||--o{ able : argue
    capital {
        DATE argue
        VARCHAR(50) out
    }
    able ||--o{ reflect : window
    able {
        VARCHAR(50) window
        DATE ask
    }
    reflect ||--o{ whether : boy
    reflect {
        DATE boy
        TEXT keep
        VARCHAR(50) election
    }
    whether ||--o{ person : woman
    whether {
        VARCHAR(50) woman
        DATE reason
    }
    person ||--o{ sing : against
    person {
        DATE against
        TEXT address
        VARCHAR(50) artist
    }
    sing ||--o{ join : college
    sing {
        VARCHAR(50) college
        DATE us
    }