erDiagram
    stand ||--o{ evening : fast
    stand {
        DATE fast
        TEXT left
        VARCHAR(50) sort
    }
    evening ||--o{ time : sister
    evening {
        VARCHAR(50) sister
        DATE back
    }
    time ||--o{ call : political
    time {
        DATE political
        TEXT station
        VARCHAR(50) meeting
    }
    call ||--o{ education : lawyer
    call {
        VARCHAR(50) lawyer
        DATE prevent
    }
    education ||--o{ wife : set
    education {
        DATE set
        TEXT with
        VARCHAR(50) data
    }
    wife ||--o{ better : cover
    wife {
        VARCHAR(50) cover
        DATE attack
    }
    better ||--o{ goal : good
    better {
        DATE good
        TEXT low
        VARCHAR(50) guy
    }
    goal ||--o{ political : glass
    goal {
        VARCHAR(50) glass
        DATE what
    }
    political ||--o{ training : nor
    political {
        DATE nor
        TEXT arm
        VARCHAR(50) behavior
    }
    training ||--o{ teacher : eight
    training {
        VARCHAR(50) eight
        DATE live
    }
    teacher ||--o{ run : collection
    teacher {
        DATE collection
        TEXT with
        VARCHAR(50) read
    }
    run ||--o{ stand : exactly
    run {
        VARCHAR(50) exactly
        DATE worry
    }