erDiagram
    decide ||--o{ wife : worry
    decide {
        DATE worry
        TEXT fund
        VARCHAR(50) commercial
    }
    wife ||--o{ follow : game
    wife {
        VARCHAR(50) game
        DATE half
    }
    follow ||--o{ may : control
    follow {
        DATE control
        TEXT plant
        VARCHAR(50) level
    }
    may ||--o{ pretty : ask
    may {
        VARCHAR(50) ask
        DATE wonder
    }
    pretty ||--o{ success : same
    pretty {
        DATE same
        TEXT tonight
        VARCHAR(50) set
    }
    success ||--o{ writer : fund
    success {
        VARCHAR(50) fund
        DATE test
    }
    writer ||--o{ it : feeling
    writer {
        DATE feeling
        TEXT some
        VARCHAR(50) property
    }
    it ||--o{ trial : follow
    it {
        VARCHAR(50) follow
        DATE three
    }
    trial ||--o{ decide : three
    trial {
        DATE three
        TEXT though
        VARCHAR(50) government
    }