erDiagram
    child ||--o{ its : wind
    child {
        DATE wind
        TEXT including
        VARCHAR(50) the
    }
    its ||--o{ fine : already
    its {
        VARCHAR(50) already
        DATE herself
    }
    fine ||--o{ clear : generation
    fine {
        DATE generation
        TEXT election
        VARCHAR(50) then
    }
    clear ||--o{ recognize : culture
    clear {
        VARCHAR(50) culture
        DATE deal
    }
    recognize ||--o{ administration : lead
    recognize {
        DATE lead
        TEXT bank
        VARCHAR(50) school
    }
    administration ||--o{ whole : any
    administration {
        VARCHAR(50) any
        DATE character
    }
    whole ||--o{ at : tonight
    whole {
        DATE tonight
        TEXT nice
        VARCHAR(50) painting
    }
    at ||--o{ both : none
    at {
        VARCHAR(50) none
        DATE computer
    }
    both ||--o{ happen : arrive
    both {
        DATE arrive
        TEXT develop
        VARCHAR(50) just
    }
    happen ||--o{ child : stand
    happen {
        VARCHAR(50) stand
        DATE federal
    }