erDiagram
    animal ||--o{ direction : its
    animal {
        DATE its
        TEXT increase
        VARCHAR(50) city
    }
    direction ||--o{ water : like
    direction {
        VARCHAR(50) like
        DATE finally
    }
    water ||--o{ carry : table
    water {
        DATE table
        TEXT company
        VARCHAR(50) those
    }
    carry ||--o{ either : myself
    carry {
        VARCHAR(50) myself
        DATE mean
    }
    either ||--o{ large : art
    either {
        DATE art
        TEXT rate
        VARCHAR(50) information
    }
    large ||--o{ field : rather
    large {
        VARCHAR(50) rather
        DATE whether
    }
    field ||--o{ return : eat
    field {
        DATE eat
        TEXT itself
        VARCHAR(50) I
    }
    return ||--o{ laugh : suffer
    return {
        VARCHAR(50) suffer
        DATE avoid
    }
    laugh ||--o{ property : deep
    laugh {
        DATE deep
        TEXT be
        VARCHAR(50) good
    }
    property ||--o{ that : dream
    property {
        VARCHAR(50) dream
        DATE will
    }
    that ||--o{ animal : whose
    that {
        DATE whose
        TEXT stock
        VARCHAR(50) table
    }