erDiagram
    able ||--o{ reveal : economy
    able {
        DATE economy
        TEXT real
        VARCHAR(50) positive
    }
    reveal ||--o{ green : long
    reveal {
        VARCHAR(50) long
        DATE ten
    }
    green ||--o{ movement : green
    green {
        DATE green
        TEXT full
        VARCHAR(50) fight
    }
    movement ||--o{ begin : work
    movement {
        VARCHAR(50) work
        DATE opportunity
    }
    begin ||--o{ example : several
    begin {
        DATE several
        TEXT pass
        VARCHAR(50) school
    }
    example ||--o{ result : simply
    example {
        VARCHAR(50) simply
        DATE standard
    }
    result ||--o{ arm : sound
    result {
        DATE sound
        TEXT modern
        VARCHAR(50) nice
    }
    arm ||--o{ able : weight
    arm {
        VARCHAR(50) weight
        DATE place
    }