erDiagram
    off ||--o{ challenge : happen
    off {
        DATE happen
        TEXT girl
        VARCHAR(50) so
    }
    challenge ||--o{ skill : fine
    challenge {
        VARCHAR(50) fine
        DATE industry
    }
    skill ||--o{ hot : left
    skill {
        DATE left
        TEXT quality
        VARCHAR(50) field
    }
    hot ||--o{ upon : heart
    hot {
        VARCHAR(50) heart
        DATE player
    }
    upon ||--o{ off : investment
    upon {
        DATE investment
        TEXT foot
        VARCHAR(50) save
    }