erDiagram
    loss ||--o{ pass : rich
    loss {
        DATE rich
        TEXT hospital
        VARCHAR(50) ability
    }
    pass ||--o{ quite : listen
    pass {
        VARCHAR(50) listen
        DATE catch
    }
    quite ||--o{ staff : attorney
    quite {
        DATE attorney
        TEXT wonder
        VARCHAR(50) statement
    }
    staff ||--o{ notice : heart
    staff {
        VARCHAR(50) heart
        DATE citizen
    }
    notice ||--o{ simply : may
    notice {
        DATE may
        TEXT grow
        VARCHAR(50) manage
    }
    simply ||--o{ traditional : before
    simply {
        VARCHAR(50) before
        DATE join
    }
    traditional ||--o{ one : skill
    traditional {
        DATE skill
        TEXT this
        VARCHAR(50) either
    }
    one ||--o{ call : visit
    one {
        VARCHAR(50) visit
        DATE more
    }
    call ||--o{ explain : mean
    call {
        DATE mean
        TEXT successful
        VARCHAR(50) address
    }
    explain ||--o{ where : contain
    explain {
        VARCHAR(50) contain
        DATE thank
    }
    where ||--o{ loss : agent
    where {
        DATE agent
        TEXT information
        VARCHAR(50) important
    }