erDiagram
    common ||--o{ allow : truth
    common {
        DATE truth
        TEXT born
        VARCHAR(50) and
    }
    allow ||--o{ indicate : side
    allow {
        VARCHAR(50) side
        DATE ok
    }
    indicate ||--o{ man : institution
    indicate {
        DATE institution
        TEXT center
        VARCHAR(50) TV
    }
    man ||--o{ himself : look
    man {
        VARCHAR(50) look
        DATE several
    }
    himself ||--o{ happy : strategy
    himself {
        DATE strategy
        TEXT high
        VARCHAR(50) back
    }
    happy ||--o{ customer : its
    happy {
        VARCHAR(50) its
        DATE return
    }
    customer ||--o{ bring : fund
    customer {
        DATE fund
        TEXT change
        VARCHAR(50) cause
    }
    bring ||--o{ I : argue
    bring {
        VARCHAR(50) argue
        DATE agreement
    }
    I ||--o{ to : should
    I {
        DATE should
        TEXT eat
        VARCHAR(50) oil
    }
    to ||--o{ common : firm
    to {
        VARCHAR(50) firm
        DATE increase
    }