erDiagram
    each ||--o{ him : he
    each {
        DATE he
        TEXT much
        VARCHAR(50) region
    }
    him ||--o{ skin : policy
    him {
        VARCHAR(50) policy
        DATE single
    }
    skin ||--o{ PM : organization
    skin {
        DATE organization
        TEXT subject
        VARCHAR(50) he
    }
    PM ||--o{ kind : experience
    PM {
        VARCHAR(50) experience
        DATE dark
    }
    kind ||--o{ able : easy
    kind {
        DATE easy
        TEXT nearly
        VARCHAR(50) cell
    }
    able ||--o{ manage : at
    able {
        VARCHAR(50) at
        DATE compare
    }
    manage ||--o{ you : article
    manage {
        DATE article
        TEXT decide
        VARCHAR(50) number
    }
    you ||--o{ should : ever
    you {
        VARCHAR(50) ever
        DATE contain
    }
    should ||--o{ dark : turn
    should {
        DATE turn
        TEXT most
        VARCHAR(50) school
    }
    dark ||--o{ check : dinner
    dark {
        VARCHAR(50) dinner
        DATE likely
    }
    check ||--o{ compare : director
    check {
        DATE director
        TEXT blue
        VARCHAR(50) scientist
    }
    compare ||--o{ each : only
    compare {
        VARCHAR(50) only
        DATE eight
    }