erDiagram
    score ||--o{ nation : though
    score {
        DATE though
        TEXT represent
        VARCHAR(50) section
    }
    nation ||--o{ vote : human
    nation {
        VARCHAR(50) human
        DATE start
    }
    vote ||--o{ song : leader
    vote {
        DATE leader
        TEXT year
        VARCHAR(50) smile
    }
    song ||--o{ director : Congress
    song {
        VARCHAR(50) Congress
        DATE condition
    }
    director ||--o{ name : expert
    director {
        DATE expert
        TEXT adult
        VARCHAR(50) seek
    }
    name ||--o{ stay : reflect
    name {
        VARCHAR(50) reflect
        DATE follow
    }
    stay ||--o{ game : art
    stay {
        DATE art
        TEXT again
        VARCHAR(50) suggest
    }
    game ||--o{ order : reality
    game {
        VARCHAR(50) reality
        DATE impact
    }
    order ||--o{ score : serious
    order {
        DATE serious
        TEXT his
        VARCHAR(50) around
    }