erDiagram
    late ||--o{ fire : peace
    late {
        DATE peace
        TEXT begin
        VARCHAR(50) left
    }
    fire ||--o{ can : local
    fire {
        VARCHAR(50) local
        DATE age
    }
    can ||--o{ society : seek
    can {
        DATE seek
        TEXT short
        VARCHAR(50) capital
    }
    society ||--o{ on : entire
    society {
        VARCHAR(50) entire
        DATE officer
    }
    on ||--o{ produce : tough
    on {
        DATE tough
        TEXT drive
        VARCHAR(50) ahead
    }
    produce ||--o{ late : Mr
    produce {
        VARCHAR(50) Mr
        DATE image
    }