erDiagram
    senior ||--o{ money : artist
    senior {
        DATE artist
        TEXT size
        VARCHAR(50) interview
    }
    money ||--o{ we : fish
    money {
        VARCHAR(50) fish
        DATE discuss
    }
    we ||--o{ serious : experience
    we {
        DATE experience
        TEXT month
        VARCHAR(50) total
    }
    serious ||--o{ close : big
    serious {
        VARCHAR(50) big
        DATE consumer
    }
    close ||--o{ hand : very
    close {
        DATE very
        TEXT tell
        VARCHAR(50) Congress
    }
    hand ||--o{ price : main
    hand {
        VARCHAR(50) main
        DATE with
    }
    price ||--o{ director : stay
    price {
        DATE stay
        TEXT rate
        VARCHAR(50) control
    }
    director ||--o{ senior : season
    director {
        VARCHAR(50) season
        DATE determine
    }