erDiagram
    entire ||--o{ physical : information
    entire {
        DATE information
        TEXT necessary
        VARCHAR(50) they
    }
    physical ||--o{ station : indicate
    physical {
        VARCHAR(50) indicate
        DATE executive
    }
    station ||--o{ here : floor
    station {
        DATE floor
        TEXT science
        VARCHAR(50) I
    }
    here ||--o{ majority : development
    here {
        VARCHAR(50) development
        DATE rich
    }
    majority ||--o{ face : head
    majority {
        DATE head
        TEXT morning
        VARCHAR(50) end
    }
    face ||--o{ entire : policy
    face {
        VARCHAR(50) policy
        DATE challenge
    }
    entire ||--o{ often : film
    entire {
        DATE film
        TEXT those
        VARCHAR(50) culture
    }
    often ||--o{ meeting : seem
    often {
        VARCHAR(50) seem
        DATE might
    }
    meeting ||--o{ father : south
    meeting {
        DATE south
        TEXT wear
        VARCHAR(50) window
    }
    father ||--o{ phone : claim
    father {
        VARCHAR(50) claim
        DATE magazine
    }
    phone ||--o{ majority : political
    phone {
        DATE political
        TEXT instead
        VARCHAR(50) note
    }
    majority ||--o{ entire : guy
    majority {
        VARCHAR(50) guy
        DATE fish
    }