erDiagram
    boy ||--o{ avoid : white
    boy {
        DATE white
        TEXT catch
        VARCHAR(50) information
    }
    avoid ||--o{ finish : process
    avoid {
        VARCHAR(50) process
        DATE dinner
    }
    finish ||--o{ hand : lot
    finish {
        DATE lot
        TEXT tonight
        VARCHAR(50) quite
    }
    hand ||--o{ south : list
    hand {
        VARCHAR(50) list
        DATE when
    }
    south ||--o{ play : total
    south {
        DATE total
        TEXT television
        VARCHAR(50) forget
    }
    play ||--o{ assume : bad
    play {
        VARCHAR(50) bad
        DATE vote
    }
    assume ||--o{ boy : structure
    assume {
        DATE structure
        TEXT research
        VARCHAR(50) blood
    }