erDiagram
    authority ||--o{ test : may
    authority {
        DATE may
        TEXT very
        VARCHAR(50) degree
    }
    test ||--o{ indicate : around
    test {
        VARCHAR(50) around
        DATE oil
    }
    indicate ||--o{ only : child
    indicate {
        DATE child
        TEXT two
        VARCHAR(50) suddenly
    }
    only ||--o{ woman : prepare
    only {
        VARCHAR(50) prepare
        DATE allow
    }
    woman ||--o{ hot : office
    woman {
        DATE office
        TEXT party
        VARCHAR(50) usually
    }
    hot ||--o{ whole : cause
    hot {
        VARCHAR(50) cause
        DATE item
    }
    whole ||--o{ might : before
    whole {
        DATE before
        TEXT concern
        VARCHAR(50) capital
    }
    might ||--o{ language : eat
    might {
        VARCHAR(50) eat
        DATE there
    }
    language ||--o{ rich : effect
    language {
        DATE effect
        TEXT manager
        VARCHAR(50) short
    }
    rich ||--o{ common : hair
    rich {
        VARCHAR(50) hair
        DATE least
    }
    common ||--o{ authority : next
    common {
        DATE next
        TEXT many
        VARCHAR(50) suddenly
    }