erDiagram
    better ||--o{ often : world
    better {
        DATE world
        TEXT generation
        VARCHAR(50) us
    }
    often ||--o{ wish : draw
    often {
        VARCHAR(50) draw
        DATE coach
    }
    wish ||--o{ forward : grow
    wish {
        DATE grow
        TEXT talk
        VARCHAR(50) bag
    }
    forward ||--o{ window : leader
    forward {
        VARCHAR(50) leader
        DATE than
    }
    window ||--o{ three : memory
    window {
        DATE memory
        TEXT beat
        VARCHAR(50) lawyer
    }
    three ||--o{ better : toward
    three {
        VARCHAR(50) toward
        DATE skin
    }