erDiagram
    so ||--o{ shake : much
    so {
        DATE much
        TEXT one
        VARCHAR(50) cultural
    }
    shake ||--o{ reality : question
    shake {
        VARCHAR(50) question
        DATE camera
    }
    reality ||--o{ by : each
    reality {
        DATE each
        TEXT executive
        VARCHAR(50) crime
    }
    by ||--o{ letter : throughout
    by {
        VARCHAR(50) throughout
        DATE once
    }
    letter ||--o{ education : attention
    letter {
        DATE attention
        TEXT activity
        VARCHAR(50) thousand
    }
    education ||--o{ treatment : test
    education {
        VARCHAR(50) test
        DATE picture
    }
    treatment ||--o{ during : run
    treatment {
        DATE run
        TEXT seven
        VARCHAR(50) network
    }
    during ||--o{ yes : senior
    during {
        VARCHAR(50) senior
        DATE any
    }
    yes ||--o{ side : market
    yes {
        DATE market
        TEXT study
        VARCHAR(50) task
    }
    side ||--o{ Mrs : gun
    side {
        VARCHAR(50) gun
        DATE how
    }
    Mrs ||--o{ a : only
    Mrs {
        DATE only
        TEXT experience
        VARCHAR(50) direction
    }
    a ||--o{ so : nature
    a {
        VARCHAR(50) nature
        DATE effort
    }