erDiagram
    born ||--o{ direction : movie
    born {
        DATE movie
        TEXT size
        VARCHAR(50) course
    }
    direction ||--o{ difficult : much
    direction {
        VARCHAR(50) much
    }
    difficult ||--o{ front : television
    difficult {
        DATE television
        TEXT floor
        VARCHAR(50) PM
    }
    front ||--o{ could : individual
    front {
        VARCHAR(50) individual
        DATE us
    }
    could ||--o{ nearly : last
    could {
        DATE last
        TEXT north
        VARCHAR(50) stuff
    }
    nearly ||--o{ hope : father
    nearly {
        VARCHAR(50) father
        DATE set
    }
    hope ||--o{ none : age
    hope {
        DATE age
        TEXT real
        VARCHAR(50) item
    }
    none ||--o{ summer : person
    none {
        VARCHAR(50) person
        DATE world
    }
    summer ||--o{ level : see
    summer {
        DATE see
        TEXT throughout
        VARCHAR(50) report
    }
    level ||--o{ song : east
    level {
        VARCHAR(50) east
        DATE few
    }
    song ||--o{ born : state
    song {
        DATE state
        TEXT after
        VARCHAR(50) population
    }