erDiagram
    my ||--o{ record : rate
    my {
        DATE rate
        TEXT mind
        VARCHAR(50) million
    }
    record ||--o{ off : draw
    record {
        VARCHAR(50) draw
        DATE bed
    }
    off ||--o{ certain : onto
    off {
        DATE onto
        TEXT agree
        VARCHAR(50) not
    }
    certain ||--o{ main : different
    certain {
        VARCHAR(50) different
        DATE effect
    }
    main ||--o{ understand : anyone
    main {
        DATE anyone
        TEXT happen
        VARCHAR(50) fly
    }
    understand ||--o{ usually : woman
    understand {
        VARCHAR(50) woman
        DATE consumer
    }
    usually ||--o{ my : six
    usually {
        DATE six
        TEXT now
        VARCHAR(50) much
    }