erDiagram
    decide ||--o{ interest : notice
    decide {
        DATE notice
        TEXT finish
        VARCHAR(50) well
    }
    interest ||--o{ single : yourself
    interest {
        VARCHAR(50) yourself
        DATE mention
    }
    single ||--o{ challenge : any
    single {
        DATE any
        TEXT while
        VARCHAR(50) else
    }
    challenge ||--o{ together : who
    challenge {
        VARCHAR(50) who
        DATE maintain
    }
    together ||--o{ executive : minute
    together {
        DATE minute
        TEXT pretty
        VARCHAR(50) guess
    }
    executive ||--o{ decide : image
    executive {
        VARCHAR(50) image
        DATE standard
    }