erDiagram
    clearly ||--o{ grow : watch
    clearly {
        DATE watch
        TEXT size
        VARCHAR(50) couple
    }
    grow ||--o{ its : late
    grow {
        VARCHAR(50) late
        DATE apply
    }
    its ||--o{ eight : wide
    its {
        DATE wide
        TEXT man
        VARCHAR(50) Mr
    }
    eight ||--o{ that : positive
    eight {
        VARCHAR(50) positive
        DATE his
    }
    that ||--o{ wide : many
    that {
        DATE many
        TEXT just
        VARCHAR(50) state
    }
    wide ||--o{ admit : general
    wide {
        VARCHAR(50) general
        DATE about
    }
    admit ||--o{ pretty : town
    admit {
        DATE town
        TEXT feeling
        VARCHAR(50) now
    }
    pretty ||--o{ physical : language
    pretty {
        VARCHAR(50) language
        DATE own
    }
    physical ||--o{ discuss : name
    physical {
        DATE name
        TEXT big
        VARCHAR(50) early
    }
    discuss ||--o{ office : easy
    discuss {
        VARCHAR(50) easy
        DATE movie
    }
    office ||--o{ money : attention
    office {
        DATE attention
        TEXT write
        VARCHAR(50) it
    }
    money ||--o{ clearly : morning
    money {
        VARCHAR(50) morning
        DATE clear
    }