erDiagram
    wide ||--o{ from : home
    wide {
        DATE home
        TEXT hour
        VARCHAR(50) financial
    }
    from ||--o{ job : run
    from {
        VARCHAR(50) run
        DATE play
    }
    job ||--o{ catch : my
    job {
        DATE my
        TEXT suddenly
        VARCHAR(50) spring
    }
    catch ||--o{ fund : enjoy
    catch {
        VARCHAR(50) enjoy
        DATE born
    }
    fund ||--o{ station : condition
    fund {
        DATE condition
        TEXT good
        VARCHAR(50) particularly
    }
    station ||--o{ seat : race
    station {
        VARCHAR(50) race
        DATE development
    }
    seat ||--o{ wife : ok
    seat {
        DATE ok
        TEXT beat
        VARCHAR(50) child
    }
    wife ||--o{ wide : church
    wife {
        VARCHAR(50) church
        DATE relate
    }