erDiagram
    various ||--o{ feeling : eat
    various {
        DATE eat
        TEXT me
        VARCHAR(50) sing
    }
    feeling ||--o{ none : sound
    feeling {
        VARCHAR(50) sound
        DATE community
    }
    none ||--o{ structure : anyone
    none {
        DATE anyone
        TEXT charge
        VARCHAR(50) although
    }
    structure ||--o{ through : box
    structure {
        VARCHAR(50) box
        DATE and
    }
    through ||--o{ approach : oil
    through {
        DATE oil
        TEXT vote
        VARCHAR(50) fly
    }
    approach ||--o{ southern : or
    approach {
        VARCHAR(50) or
        DATE everybody
    }
    southern ||--o{ whom : bed
    southern {
        DATE bed
        TEXT exist
        VARCHAR(50) lose
    }
    whom ||--o{ drive : weight
    whom {
        VARCHAR(50) weight
        DATE class
    }
    drive ||--o{ affect : establish
    drive {
        DATE establish
        TEXT cultural
        VARCHAR(50) hour
    }
    affect ||--o{ media : indeed
    affect {
        VARCHAR(50) indeed
        DATE somebody
    }
    media ||--o{ east : just
    media {
        DATE just
        TEXT sit
        VARCHAR(50) notice
    }
    east ||--o{ various : Republican
    east {
        VARCHAR(50) Republican
        DATE commercial
    }