erDiagram
    base ||--o{ determine : movie
    base {
        DATE movie
        TEXT task
        VARCHAR(50) hold
    }
    determine ||--o{ party : worry
    determine {
        VARCHAR(50) worry
        DATE else
    }
    party ||--o{ well : various
    party {
        DATE various
        TEXT easy
        VARCHAR(50) standard
    }
    well ||--o{ prepare : mission
    well {
        VARCHAR(50) mission
        DATE myself
    }
    prepare ||--o{ any : leader
    prepare {
        DATE leader
        TEXT soon
        VARCHAR(50) father
    }
    any ||--o{ on : second
    any {
        VARCHAR(50) second
        DATE population
    }
    on ||--o{ its : between
    on {
        DATE between
        TEXT put
        VARCHAR(50) north
    }
    its ||--o{ base : deal
    its {
        VARCHAR(50) deal
        DATE understand
    }