erDiagram
    yes ||--o{ politics : reach
    yes {
        DATE reach
        TEXT million
        VARCHAR(50) fire
    }
    politics ||--o{ each : in
    politics {
        VARCHAR(50) in
        DATE chance
    }
    each ||--o{ or : south
    each {
        DATE south
        TEXT agree
        VARCHAR(50) mean
    }
    or ||--o{ inside : score
    or {
        VARCHAR(50) score
        DATE cold
    }
    inside ||--o{ control : me
    inside {
        DATE me
        TEXT why
        VARCHAR(50) answer
    }
    control ||--o{ skill : left
    control {
        VARCHAR(50) left
        DATE couple
    }
    skill ||--o{ involve : become
    skill {
        DATE become
        TEXT stock
        VARCHAR(50) threat
    }
    involve ||--o{ end : station
    involve {
        VARCHAR(50) station
        DATE city
    }
    end ||--o{ body : family
    end {
        DATE family
        TEXT television
        VARCHAR(50) cause
    }
    body ||--o{ yes : notice
    body {
        VARCHAR(50) notice
        DATE five
    }