erDiagram
    appear ||--o{ service : picture
    appear {
        DATE picture
        TEXT bill
        VARCHAR(50) court
    }
    service ||--o{ particularly : social
    service {
        VARCHAR(50) social
        DATE build
    }
    particularly ||--o{ ago : young
    particularly {
        DATE young
        TEXT garden
        VARCHAR(50) audience
    }
    ago ||--o{ control : threat
    ago {
        VARCHAR(50) threat
        DATE responsibility
    }
    control ||--o{ should : believe
    control {
        DATE believe
        TEXT accept
        VARCHAR(50) art
    }
    should ||--o{ trade : almost
    should {
        VARCHAR(50) almost
        DATE two
    }
    trade ||--o{ skill : officer
    trade {
        DATE officer
        TEXT chair
        VARCHAR(50) still
    }
    skill ||--o{ hard : six
    skill {
        VARCHAR(50) six
        DATE notice
    }
    hard ||--o{ knowledge : section
    hard {
        DATE section
        TEXT mind
        VARCHAR(50) American
    }
    knowledge ||--o{ necessary : individual
    knowledge {
        VARCHAR(50) individual
        DATE lose
    }
    necessary ||--o{ support : item
    necessary {
        DATE item
        TEXT add
        VARCHAR(50) while
    }
    support ||--o{ appear : reality
    support {
        VARCHAR(50) reality
        DATE more
    }