erDiagram
    central ||--o{ special : something
    central {
        DATE something
        TEXT style
        VARCHAR(50) charge
    }
    special ||--o{ company : difference
    special {
        VARCHAR(50) difference
        DATE body
    }
    company ||--o{ information : some
    company {
        DATE some
        TEXT today
        VARCHAR(50) the
    }
    information ||--o{ wear : already
    information {
        VARCHAR(50) already
        DATE interview
    }
    wear ||--o{ two : Republican
    wear {
        DATE Republican
        TEXT red
        VARCHAR(50) method
    }
    two ||--o{ career : camera
    two {
        VARCHAR(50) camera
        DATE agreement
    }
    career ||--o{ contain : professional
    career {
        DATE professional
        TEXT while
        VARCHAR(50) husband
    }
    contain ||--o{ central : huge
    contain {
        VARCHAR(50) huge
        DATE lead
    }