erDiagram
    certainly ||--o{ nothing : coach
    certainly {
        DATE coach
        TEXT behavior
        VARCHAR(50) manager
    }
    nothing ||--o{ mouth : long
    nothing {
        VARCHAR(50) long
        DATE significant
    }
    mouth ||--o{ finish : cost
    mouth {
        DATE cost
        TEXT military
        VARCHAR(50) whatever
    }
    finish ||--o{ approach : smile
    finish {
        VARCHAR(50) smile
        DATE mission
    }
    approach ||--o{ next : us
    approach {
        DATE us
        TEXT rate
        VARCHAR(50) visit
    }
    next ||--o{ start : sell
    next {
        VARCHAR(50) sell
        DATE from
    }
    start ||--o{ remember : power
    start {
        DATE power
        TEXT loss
        VARCHAR(50) great
    }
    remember ||--o{ statement : career
    remember {
        VARCHAR(50) career
        DATE first
    }
    statement ||--o{ political : model
    statement {
        DATE model
        TEXT store
        VARCHAR(50) seven
    }
    political ||--o{ certainly : guy
    political {
        VARCHAR(50) guy
        DATE this
    }