erDiagram
    tax ||--o{ sit : difficult
    tax {
        DATE difficult
        TEXT fish
        VARCHAR(50) garden
    }
    sit ||--o{ go : green
    sit {
        VARCHAR(50) green
        DATE too
    }
    go ||--o{ another : authority
    go {
        DATE authority
        TEXT clearly
        VARCHAR(50) security
    }
    another ||--o{ science : wife
    another {
        VARCHAR(50) wife
        DATE voice
    }
    science ||--o{ record : indeed
    science {
        DATE indeed
        TEXT method
        VARCHAR(50) agency
    }
    record ||--o{ base : the
    record {
        VARCHAR(50) the
        DATE her
    }
    base ||--o{ tax : her
    base {
        DATE her
        TEXT of
        VARCHAR(50) usually
    }