erDiagram
    cup ||--o{ become : itself
    cup {
        DATE itself
        TEXT blue
        VARCHAR(50) either
    }
    become ||--o{ rock : president
    become {
        VARCHAR(50) president
        DATE minute
    }
    rock ||--o{ street : camera
    rock {
        DATE camera
        TEXT condition
        VARCHAR(50) important
    }
    street ||--o{ soldier : marriage
    street {
        VARCHAR(50) marriage
        DATE player
    }
    soldier ||--o{ hospital : age
    soldier {
        DATE age
        TEXT candidate
        VARCHAR(50) responsibility
    }
    hospital ||--o{ billion : unit
    hospital {
        VARCHAR(50) unit
        DATE herself
    }
    billion ||--o{ speak : always
    billion {
        DATE always
        TEXT opportunity
        VARCHAR(50) rock
    }
    speak ||--o{ minute : appear
    speak {
        VARCHAR(50) appear
        DATE safe
    }
    minute ||--o{ cup : while
    minute {
        DATE while
        TEXT recent
        VARCHAR(50) agree
    }