erDiagram
    tax ||--o{ population : plan
    tax {
        DATE plan
        TEXT door
        VARCHAR(50) share
    }
    population ||--o{ agency : suddenly
    population {
        VARCHAR(50) suddenly
        DATE art
    }
    agency ||--o{ give : add
    agency {
        DATE add
        TEXT because
        VARCHAR(50) skin
    }
    give ||--o{ employee : hot
    give {
        VARCHAR(50) hot
        DATE seek
    }
    employee ||--o{ important : particularly
    employee {
        DATE particularly
        TEXT through
        VARCHAR(50) we
    }
    important ||--o{ as : Mr
    important {
        VARCHAR(50) Mr
        DATE season
    }
    as ||--o{ hospital : who
    as {
        DATE who
        TEXT amount
        VARCHAR(50) together
    }
    hospital ||--o{ drop : world
    hospital {
        VARCHAR(50) world
        DATE body
    }
    drop ||--o{ consider : attack
    drop {
        DATE attack
        TEXT home
        VARCHAR(50) common
    }
    consider ||--o{ perform : dinner
    consider {
        VARCHAR(50) dinner
        DATE much
    }
    perform ||--o{ tax : rock
    perform {
        DATE rock
        TEXT message
        VARCHAR(50) real
    }