erDiagram
    that ||--o{ east : morning
    that {
        DATE morning
        TEXT behavior
        VARCHAR(50) two
    }
    east ||--o{ new : nothing
    east {
        VARCHAR(50) nothing
        DATE structure
    }
    new ||--o{ dark : nothing
    new {
        DATE nothing
        TEXT view
        VARCHAR(50) bank
    }
    dark ||--o{ idea : outside
    dark {
        VARCHAR(50) outside
        DATE research
    }
    idea ||--o{ nothing : bring
    idea {
        DATE bring
        TEXT language
        VARCHAR(50) show
    }
    nothing ||--o{ that : brother
    nothing {
        VARCHAR(50) brother
        DATE process
    }