erDiagram
    save ||--o{ class : they
    save {
        DATE they
        TEXT very
        VARCHAR(50) pay
    }
    class ||--o{ certainly : another
    class {
        VARCHAR(50) another
        DATE until
    }
    certainly ||--o{ technology : expect
    certainly {
        DATE expect
        TEXT successful
        VARCHAR(50) way
    }
    technology ||--o{ may : stand
    technology {
        VARCHAR(50) stand
        DATE total
    }
    may ||--o{ force : agency
    may {
        DATE agency
        TEXT wonder
        VARCHAR(50) word
    }
    force ||--o{ nearly : behavior
    force {
        VARCHAR(50) behavior
        DATE involve
    }
    nearly ||--o{ side : hard
    nearly {
        DATE hard
        TEXT guess
        VARCHAR(50) discuss
    }
    side ||--o{ teach : off
    side {
        VARCHAR(50) off
        DATE forget
    }
    teach ||--o{ save : environmental
    teach {
        DATE environmental
        TEXT Mrs
        VARCHAR(50) return
    }