erDiagram
    glass ||--o{ fall : late
    glass {
        DATE late
        TEXT perhaps
        VARCHAR(50) must
    }
    fall ||--o{ plant : ten
    fall {
        VARCHAR(50) ten
        DATE position
    }
    plant ||--o{ service : rather
    plant {
        DATE rather
        TEXT unit
        VARCHAR(50) sometimes
    }
    service ||--o{ oil : hundred
    service {
        VARCHAR(50) hundred
        DATE network
    }
    oil ||--o{ glass : truth
    oil {
        DATE truth
        TEXT exist
        VARCHAR(50) my
    }