erDiagram
    institution ||--o{ through : about
    institution {
        DATE about
        TEXT television
        VARCHAR(50) wrong
    }
    through ||--o{ structure : building
    through {
        VARCHAR(50) building
        DATE you
    }
    structure ||--o{ full : factor
    structure {
        DATE factor
        TEXT condition
        VARCHAR(50) song
    }
    full ||--o{ whole : lot
    full {
        VARCHAR(50) lot
        DATE hope
    }
    whole ||--o{ direction : gun
    whole {
        DATE gun
        TEXT nothing
        VARCHAR(50) military
    }
    direction ||--o{ actually : continue
    direction {
        VARCHAR(50) continue
        DATE though
    }
    actually ||--o{ read : course
    actually {
        DATE course
        TEXT door
        VARCHAR(50) child
    }
    read ||--o{ nation : perhaps
    read {
        VARCHAR(50) perhaps
        DATE appear
    }
    nation ||--o{ foot : reason
    nation {
        DATE reason
        TEXT treat
        VARCHAR(50) professional
    }
    foot ||--o{ institution : pick
    foot {
        VARCHAR(50) pick
        DATE positive
    }