erDiagram
    act ||--o{ usually : majority
    act {
        DATE majority
        TEXT drop
        VARCHAR(50) born
    }
    usually ||--o{ rather : professor
    usually {
        VARCHAR(50) professor
        DATE black
    }
    rather ||--o{ leader : value
    rather {
        DATE value
        TEXT dream
        VARCHAR(50) idea
    }
    leader ||--o{ hotel : reflect
    leader {
        VARCHAR(50) reflect
        DATE actually
    }
    hotel ||--o{ American : national
    hotel {
        DATE national
        TEXT part
        VARCHAR(50) man
    }
    American ||--o{ knowledge : worry
    American {
        VARCHAR(50) worry
        DATE wear
    }
    knowledge ||--o{ make : seem
    knowledge {
        DATE seem
        TEXT fall
        VARCHAR(50) within
    }
    make ||--o{ truth : check
    make {
        VARCHAR(50) check
        DATE good
    }
    truth ||--o{ act : opportunity
    truth {
        DATE opportunity
        TEXT movement
        VARCHAR(50) baby
    }