erDiagram
    behavior ||--o{ wait : push
    behavior {
        DATE push
        TEXT ahead
        VARCHAR(50) inside
    }
    wait ||--o{ player : professor
    wait {
        VARCHAR(50) professor
        DATE moment
    }
    player ||--o{ summer : glass
    player {
        DATE glass
        TEXT recently
        VARCHAR(50) whole
    }
    summer ||--o{ these : task
    summer {
        VARCHAR(50) task
        DATE night
    }
    these ||--o{ already : soldier
    these {
        DATE soldier
        TEXT short
        VARCHAR(50) sometimes
    }
    already ||--o{ house : police
    already {
        VARCHAR(50) police
        DATE wrong
    }
    house ||--o{ mouth : enter
    house {
        DATE enter
        TEXT little
        VARCHAR(50) ok
    }
    mouth ||--o{ campaign : drug
    mouth {
        VARCHAR(50) drug
        DATE understand
    }
    campaign ||--o{ vote : much
    campaign {
        DATE much
        TEXT middle
        VARCHAR(50) onto
    }
    vote ||--o{ wear : receive
    vote {
        VARCHAR(50) receive
        DATE other
    }
    wear ||--o{ behavior : fund
    wear {
        DATE fund
        TEXT data
        VARCHAR(50) past
    }