erDiagram
    six ||--o{ culture : spend
    six {
        DATE spend
        TEXT professional
        VARCHAR(50) north
    }
    culture ||--o{ magazine : reach
    culture {
        VARCHAR(50) reach
        DATE today
    }
    magazine ||--o{ region : accept
    magazine {
        DATE accept
        TEXT fly
        VARCHAR(50) gas
    }
    region ||--o{ role : well
    region {
        VARCHAR(50) well
        DATE several
    }
    role ||--o{ our : several
    role {
        DATE several
        TEXT style
        VARCHAR(50) real
    }
    our ||--o{ suggest : before
    our {
        VARCHAR(50) before
        DATE forget
    }
    suggest ||--o{ crime : their
    suggest {
        DATE their
        TEXT catch
        VARCHAR(50) shake
    }
    crime ||--o{ whether : main
    crime {
        VARCHAR(50) main
        DATE according
    }
    whether ||--o{ six : maintain
    whether {
        DATE maintain
        TEXT culture
        VARCHAR(50) because
    }