erDiagram
    effect ||--o{ nice : strategy
    effect {
        DATE strategy
        TEXT deal
        VARCHAR(50) truth
    }
    nice ||--o{ goal : eat
    nice {
        VARCHAR(50) eat
        DATE man
    }
    goal ||--o{ price : others
    goal {
        DATE others
        TEXT heavy
        VARCHAR(50) lay
    }
    price ||--o{ action : occur
    price {
        VARCHAR(50) occur
        DATE state
    }
    action ||--o{ national : decision
    action {
        DATE decision
        TEXT production
        VARCHAR(50) place
    }
    national ||--o{ effect : number
    national {
        VARCHAR(50) number
        DATE family
    }