erDiagram
    may ||--o{ too : pick
    may {
        DATE pick
        TEXT level
        VARCHAR(50) in
    }
    too ||--o{ hour : left
    too {
        VARCHAR(50) left
        DATE lot
    }
    hour ||--o{ mission : animal
    hour {
        DATE animal
        TEXT since
        VARCHAR(50) nation
    }
    mission ||--o{ different : history
    mission {
        VARCHAR(50) history
        DATE health
    }
    different ||--o{ mother : play
    different {
        DATE play
        TEXT world
        VARCHAR(50) under
    }
    mother ||--o{ result : price
    mother {
        VARCHAR(50) price
        DATE land
    }
    result ||--o{ may : program
    result {
        DATE program
        TEXT gas
        VARCHAR(50) need
    }