erDiagram
    almost ||--o{ ever : control
    almost {
        DATE control
        TEXT ground
        VARCHAR(50) compare
    }
    ever ||--o{ attorney : too
    ever {
        VARCHAR(50) too
        DATE debate
    }
    attorney ||--o{ politics : another
    attorney {
        DATE another
        TEXT conference
        VARCHAR(50) experience
    }
    politics ||--o{ social : itself
    politics {
        VARCHAR(50) itself
        DATE reduce
    }
    social ||--o{ help : short
    social {
        DATE short
        TEXT for
        VARCHAR(50) professor
    }
    help ||--o{ shoulder : civil
    help {
        VARCHAR(50) civil
        DATE training
    }
    shoulder ||--o{ participant : your
    shoulder {
        DATE your
        TEXT sport
        VARCHAR(50) example
    }
    participant ||--o{ ago : entire
    participant {
        VARCHAR(50) entire
        DATE back
    }
    ago ||--o{ almost : family
    ago {
        DATE family
        TEXT quickly
        VARCHAR(50) line
    }