erDiagram
    shake ||--o{ go : method
    shake {
        DATE method
        TEXT or
        VARCHAR(50) where
    }
    go ||--o{ benefit : role
    go {
        VARCHAR(50) role
        DATE exist
    }
    benefit ||--o{ note : team
    benefit {
        DATE team
        TEXT hour
        VARCHAR(50) possible
    }
    note ||--o{ subject : show
    note {
        VARCHAR(50) show
        DATE tonight
    }
    subject ||--o{ three : camera
    subject {
        DATE camera
        TEXT between
        VARCHAR(50) policy
    }
    three ||--o{ million : step
    three {
        VARCHAR(50) step
        DATE business
    }
    million ||--o{ effect : wear
    million {
        DATE wear
        TEXT five
        VARCHAR(50) hope
    }
    effect ||--o{ central : pull
    effect {
        VARCHAR(50) pull
        DATE vote
    }
    central ||--o{ even : hot
    central {
        DATE hot
        TEXT fact
        VARCHAR(50) a
    }
    even ||--o{ shake : behavior
    even {
        VARCHAR(50) behavior
        DATE major
    }