erDiagram
    set ||--o{ step : prevent
    set {
        DATE prevent
        TEXT amount
        VARCHAR(50) attack
    }
    step ||--o{ small : pattern
    step {
        VARCHAR(50) pattern
        DATE everything
    }
    small ||--o{ learn : and
    small {
        DATE and
        TEXT trip
        VARCHAR(50) newspaper
    }
    learn ||--o{ set : much
    learn {
        VARCHAR(50) much
        DATE someone
    }
    set ||--o{ story : adult
    set {
        DATE adult
        TEXT call
        VARCHAR(50) realize
    }
    story ||--o{ set : school
    story {
        VARCHAR(50) school
        DATE art
    }