erDiagram
    significant ||--o{ let : low
    significant {
        DATE low
        TEXT information
        VARCHAR(50) opportunity
    }
    let ||--o{ save : smile
    let {
        VARCHAR(50) smile
        DATE check
    }
    save ||--o{ federal : why
    save {
        DATE why
        TEXT else
        VARCHAR(50) magazine
    }
    federal ||--o{ where : strong
    federal {
        VARCHAR(50) strong
        DATE major
    }
    where ||--o{ open : long
    where {
        DATE long
        TEXT doctor
        VARCHAR(50) be
    }
    open ||--o{ speak : beyond
    open {
        VARCHAR(50) beyond
        DATE allow
    }
    speak ||--o{ image : read
    speak {
        DATE read
        TEXT short
        VARCHAR(50) mind
    }
    image ||--o{ entire : reveal
    image {
        VARCHAR(50) reveal
        DATE among
    }
    entire ||--o{ sing : talk
    entire {
        DATE talk
        TEXT risk
        VARCHAR(50) life
    }
    sing ||--o{ significant : certain
    sing {
        VARCHAR(50) certain
        DATE machine
    }