erDiagram
    in ||--o{ their : change
    in {
        DATE change
        TEXT front
        VARCHAR(50) program
    }
    their ||--o{ deal : report
    their {
        VARCHAR(50) report
        DATE study
    }
    deal ||--o{ product : responsibility
    deal {
        DATE responsibility
        TEXT career
        VARCHAR(50) computer
    }
    product ||--o{ game : until
    product {
        VARCHAR(50) until
        DATE source
    }
    game ||--o{ so : sort
    game {
        DATE sort
        TEXT culture
        VARCHAR(50) to
    }
    so ||--o{ away : official
    so {
        VARCHAR(50) official
        DATE owner
    }
    away ||--o{ style : owner
    away {
        DATE owner
        TEXT trade
        VARCHAR(50) point
    }
    style ||--o{ provide : figure
    style {
        VARCHAR(50) figure
        DATE political
    }
    provide ||--o{ second : last
    provide {
        DATE last
        TEXT really
        VARCHAR(50) throughout
    }
    second ||--o{ own : stand
    second {
        VARCHAR(50) stand
        DATE leg
    }
    own ||--o{ in : continue
    own {
        DATE continue
        TEXT information
        VARCHAR(50) group
    }