erDiagram
    including ||--o{ case : box
    including {
        DATE box
        TEXT manager
        VARCHAR(50) effort
    }
    case ||--o{ not : future
    case {
        VARCHAR(50) future
        DATE too
    }
    not ||--o{ him : stay
    not {
        DATE stay
        TEXT rich
        VARCHAR(50) exactly
    }
    him ||--o{ bad : leader
    him {
        VARCHAR(50) leader
        DATE federal
    }
    bad ||--o{ treat : beautiful
    bad {
        DATE beautiful
        TEXT whether
        VARCHAR(50) also
    }
    treat ||--o{ program : force
    treat {
        VARCHAR(50) force
        DATE mean
    }
    program ||--o{ million : surface
    program {
        DATE surface
        TEXT put
        VARCHAR(50) tend
    }
    million ||--o{ hospital : season
    million {
        VARCHAR(50) season
        DATE force
    }
    hospital ||--o{ including : interesting
    hospital {
        DATE interesting
        TEXT three
        VARCHAR(50) well
    }