erDiagram
    although ||--o{ enough : letter
    although {
        DATE letter
        TEXT peace
        VARCHAR(50) try
    }
    enough ||--o{ arm : sometimes
    enough {
        VARCHAR(50) sometimes
        DATE service
    }
    arm ||--o{ age : why
    arm {
        DATE why
        TEXT court
        VARCHAR(50) where
    }
    age ||--o{ power : arrive
    age {
        VARCHAR(50) arrive
        DATE effect
    }
    power ||--o{ identify : quite
    power {
        DATE quite
        TEXT at
        VARCHAR(50) inside
    }
    identify ||--o{ staff : health
    identify {
        VARCHAR(50) health
        DATE use
    }
    staff ||--o{ already : certain
    staff {
        DATE certain
        TEXT easy
        VARCHAR(50) coach
    }
    already ||--o{ four : rate
    already {
        VARCHAR(50) rate
        DATE everyone
    }
    four ||--o{ specific : bed
    four {
        DATE bed
        TEXT short
        VARCHAR(50) during
    }
    specific ||--o{ population : reality
    specific {
        VARCHAR(50) reality
        DATE you
    }
    population ||--o{ realize : contain
    population {
        DATE contain
        TEXT do
        VARCHAR(50) him
    }
    realize ||--o{ although : chair
    realize {
        VARCHAR(50) chair
        DATE old
    }