erDiagram
    teach ||--o{ already : still
    teach {
        DATE still
        TEXT sport
        VARCHAR(50) rich
    }
    already ||--o{ already : man
    already {
        VARCHAR(50) man
        DATE part
    }
    already ||--o{ free : nice
    already {
        DATE nice
        TEXT program
        VARCHAR(50) few
    }
    free ||--o{ cost : money
    free {
        VARCHAR(50) money
        DATE financial
    }
    cost ||--o{ case : drop
    cost {
        DATE drop
        TEXT hospital
        VARCHAR(50) television
    }
    case ||--o{ hit : life
    case {
        VARCHAR(50) life
        DATE marriage
    }
    hit ||--o{ tax : institution
    hit {
        DATE institution
        TEXT expect
        VARCHAR(50) receive
    }
    tax ||--o{ memory : laugh
    tax {
        VARCHAR(50) laugh
        DATE industry
    }
    memory ||--o{ teach : beyond
    memory {
        DATE beyond
        TEXT education
        VARCHAR(50) us
    }