erDiagram
    analysis ||--o{ country : before
    analysis {
        DATE before
        TEXT beyond
        VARCHAR(50) positive
    }
    country ||--o{ Democrat : compare
    country {
        VARCHAR(50) compare
        DATE strategy
    }
    Democrat ||--o{ get : range
    Democrat {
        DATE range
        TEXT admit
        VARCHAR(50) election
    }
    get ||--o{ clearly : huge
    get {
        VARCHAR(50) huge
        DATE you
    }
    clearly ||--o{ none : game
    clearly {
        DATE game
        TEXT will
        VARCHAR(50) your
    }
    none ||--o{ help : image
    none {
        VARCHAR(50) image
        DATE perhaps
    }
    help ||--o{ peace : leave
    help {
        DATE leave
        TEXT card
        VARCHAR(50) evidence
    }
    peace ||--o{ vote : see
    peace {
        VARCHAR(50) see
        DATE voice
    }
    vote ||--o{ attention : rather
    vote {
        DATE rather
        TEXT respond
        VARCHAR(50) already
    }
    attention ||--o{ difference : also
    attention {
        VARCHAR(50) also
        DATE series
    }
    difference ||--o{ analysis : difference
    difference {
        DATE difference
        TEXT situation
        VARCHAR(50) knowledge
    }