erDiagram
    identify ||--o{ at : rate
    identify {
        DATE rate
        TEXT recently
        VARCHAR(50) radio
    }
    at ||--o{ size : answer
    at {
        VARCHAR(50) answer
        DATE field
    }
    size ||--o{ sit : magazine
    size {
        DATE magazine
        TEXT future
        VARCHAR(50) right
    }
    sit ||--o{ charge : yeah
    sit {
        VARCHAR(50) yeah
        DATE staff
    }
    charge ||--o{ beautiful : statement
    charge {
        DATE statement
        TEXT whole
        VARCHAR(50) prepare
    }
    beautiful ||--o{ whose : amount
    beautiful {
        VARCHAR(50) amount
        DATE single
    }
    whose ||--o{ identify : next
    whose {
        DATE next
        TEXT modern
        VARCHAR(50) practice
    }