erDiagram
    fine ||--o{ job : product
    fine {
        DATE product
        TEXT color
        VARCHAR(50) prevent
    }
    job ||--o{ chair : body
    job {
        VARCHAR(50) body
        DATE prevent
    }
    chair ||--o{ discussion : offer
    chair {
        DATE offer
        TEXT cultural
        VARCHAR(50) common
    }
    discussion ||--o{ last : big
    discussion {
        VARCHAR(50) big
        DATE fish
    }
    last ||--o{ generation : foreign
    last {
        TEXT four
        VARCHAR(50) table
    }
    generation ||--o{ fine : deep
    generation {
        VARCHAR(50) deep
        DATE yourself
    }