erDiagram
    energy ||--o{ assume : realize
    energy {
        DATE realize
        TEXT explain
        VARCHAR(50) Mr
    }
    assume ||--o{ especially : baby
    assume {
        VARCHAR(50) baby
        DATE live
    }
    especially ||--o{ new : plant
    especially {
        DATE plant
        TEXT use
        VARCHAR(50) party
    }
    new ||--o{ really : any
    new {
        VARCHAR(50) any
        DATE seven
    }
    really ||--o{ with : young
    really {
        DATE young
        TEXT total
        VARCHAR(50) travel
    }
    with ||--o{ more : foot
    with {
        VARCHAR(50) foot
        DATE same
    }
    more ||--o{ thus : affect
    more {
        DATE affect
        TEXT key
        VARCHAR(50) ball
    }
    thus ||--o{ product : the
    thus {
        VARCHAR(50) the
        DATE effect
    }
    product ||--o{ energy : civil
    product {
        DATE civil
        TEXT serve
        VARCHAR(50) data
    }