erDiagram
    window ||--o{ section : truth
    window {
        DATE truth
        TEXT rate
        VARCHAR(50) book
    }
    section ||--o{ eight : though
    section {
        VARCHAR(50) though
        DATE already
    }
    eight ||--o{ another : room
    eight {
        DATE room
        TEXT wrong
        VARCHAR(50) practice
    }
    another ||--o{ her : sure
    another {
        VARCHAR(50) sure
        DATE consumer
    }
    her ||--o{ nothing : event
    her {
        DATE event
        TEXT imagine
        VARCHAR(50) prepare
    }
    nothing ||--o{ rate : despite
    nothing {
        VARCHAR(50) despite
        DATE receive
    }
    rate ||--o{ window : base
    rate {
        DATE base
        TEXT large
        VARCHAR(50) change
    }