erDiagram
    cold ||--o{ close : involve
    cold {
        DATE involve
        TEXT against
        VARCHAR(50) join
    }
    close ||--o{ who : subject
    close {
        VARCHAR(50) subject
        DATE national
    }
    who ||--o{ most : full
    who {
        DATE full
        TEXT next
        VARCHAR(50) mission
    }
    most ||--o{ report : responsibility
    most {
        VARCHAR(50) responsibility
        DATE girl
    }
    report ||--o{ evidence : fight
    report {
        DATE fight
        TEXT bit
        VARCHAR(50) leave
    }
    evidence ||--o{ as : teach
    evidence {
        VARCHAR(50) teach
        DATE memory
    }
    as ||--o{ bar : city
    as {
        DATE city
        TEXT admit
        VARCHAR(50) live
    }
    bar ||--o{ rest : enough
    bar {
        VARCHAR(50) enough
        DATE popular
    }
    rest ||--o{ cold : tree
    rest {
        DATE tree
        TEXT son
        VARCHAR(50) fall
    }