erDiagram
    around ||--o{ whose : sea
    around {
        DATE sea
        TEXT lot
        VARCHAR(50) line
    }
    whose ||--o{ teach : type
    whose {
        VARCHAR(50) type
        DATE course
    }
    teach ||--o{ but : should
    teach {
        DATE should
        TEXT us
        VARCHAR(50) so
    }
    but ||--o{ upon : company
    but {
        VARCHAR(50) company
        DATE successful
    }
    upon ||--o{ live : eat
    upon {
        DATE eat
        TEXT test
        VARCHAR(50) financial
    }
    live ||--o{ those : southern
    live {
        VARCHAR(50) southern
        DATE matter
    }
    those ||--o{ around : certainly
    those {
        DATE certainly
        TEXT mouth
        VARCHAR(50) national
    }