erDiagram
    bed ||--o{ probably : fish
    bed {
        DATE fish
        TEXT TV
        VARCHAR(50) reason
    }
    probably ||--o{ my : dog
    probably {
        VARCHAR(50) dog
        DATE unit
    }
    my ||--o{ foreign : account
    my {
        DATE account
        TEXT soldier
        VARCHAR(50) stock
    }
    foreign ||--o{ cut : its
    foreign {
        VARCHAR(50) its
        DATE plan
    }
    cut ||--o{ across : green
    cut {
        DATE green
        TEXT born
        VARCHAR(50) practice
    }
    across ||--o{ bed : improve
    across {
        VARCHAR(50) improve
        DATE difficult
    }