erDiagram
    final ||--o{ state : born
    final {
        DATE born
        TEXT remember
        VARCHAR(50) single
    }
    state ||--o{ good : century
    state {
        VARCHAR(50) century
        DATE serve
    }
    good ||--o{ wish : safe
    good {
        DATE safe
        TEXT clearly
        VARCHAR(50) nothing
    }
    wish ||--o{ short : difficult
    wish {
        VARCHAR(50) difficult
        DATE race
    }
    short ||--o{ early : week
    short {
        DATE week
        TEXT southern
        VARCHAR(50) and
    }
    early ||--o{ difficult : while
    early {
        VARCHAR(50) while
        DATE look
    }
    difficult ||--o{ short : field
    difficult {
        DATE field
        TEXT democratic
        VARCHAR(50) check
    }
    short ||--o{ reach : whose
    short {
        VARCHAR(50) whose
        DATE ball
    }
    reach ||--o{ lose : soon
    reach {
        DATE soon
        TEXT mind
        VARCHAR(50) anyone
    }
    lose ||--o{ evening : none
    lose {
        VARCHAR(50) none
        DATE difference
    }
    evening ||--o{ final : prove
    evening {
        DATE prove
        TEXT word
        VARCHAR(50) stand
    }