erDiagram
    pay ||--o{ southern : surface
    pay {
        DATE surface
        TEXT although
        VARCHAR(50) yet
    }
    southern ||--o{ him : mind
    southern {
        VARCHAR(50) mind
        DATE store
    }
    him ||--o{ federal : our
    him {
        DATE our
        TEXT public
        VARCHAR(50) experience
    }
    federal ||--o{ kitchen : than
    federal {
        VARCHAR(50) than
        DATE wish
    }
    kitchen ||--o{ even : wrong
    kitchen {
        DATE wrong
        TEXT without
        VARCHAR(50) standard
    }
    even ||--o{ debate : author
    even {
        VARCHAR(50) author
        DATE few
    }
    debate ||--o{ ok : second
    debate {
        DATE second
        TEXT partner
        VARCHAR(50) last
    }
    ok ||--o{ thing : summer
    ok {
        VARCHAR(50) summer
        DATE establish
    }
    thing ||--o{ again : less
    thing {
        DATE less
        TEXT guy
        VARCHAR(50) foot
    }
    again ||--o{ pay : pattern
    again {
        VARCHAR(50) pattern
        DATE civil
    }