erDiagram
    story ||--o{ woman : speak
    story {
        DATE speak
        TEXT officer
        VARCHAR(50) sometimes
    }
    woman ||--o{ water : push
    woman {
        VARCHAR(50) push
        DATE let
    }
    water ||--o{ bag : part
    water {
        DATE part
        TEXT each
        VARCHAR(50) head
    }
    bag ||--o{ position : better
    bag {
        VARCHAR(50) better
        DATE increase
    }
    position ||--o{ business : war
    position {
        DATE war
        TEXT ago
        VARCHAR(50) sure
    }
    business ||--o{ positive : trade
    business {
        VARCHAR(50) trade
        DATE it
    }
    positive ||--o{ pattern : government
    positive {
        DATE government
        TEXT democratic
        VARCHAR(50) off
    }
    pattern ||--o{ story : better
    pattern {
        VARCHAR(50) better
        DATE order
    }