erDiagram
    can ||--o{ feel : better
    can {
        DATE better
        TEXT cup
        VARCHAR(50) open
    }
    feel ||--o{ well : stop
    feel {
        VARCHAR(50) stop
        DATE local
    }
    well ||--o{ court : participant
    well {
        DATE participant
        TEXT human
        VARCHAR(50) red
    }
    court ||--o{ catch : young
    court {
        VARCHAR(50) young
        DATE why
    }
    catch ||--o{ parent : ago
    catch {
        DATE ago
        TEXT upon
        VARCHAR(50) chance
    }
    parent ||--o{ have : most
    parent {
        VARCHAR(50) most
        DATE probably
    }
    have ||--o{ cold : standard
    have {
        DATE standard
        TEXT look
        VARCHAR(50) size
    }
    cold ||--o{ can : difficult
    cold {
        VARCHAR(50) difficult
        DATE ahead
    }