erDiagram
    read ||--o{ environmental : top
    read {
        DATE top
        TEXT manager
        VARCHAR(50) against
    }
    environmental ||--o{ director : give
    environmental {
        VARCHAR(50) give
        DATE war
    }
    director ||--o{ want : both
    director {
        DATE both
        TEXT hard
        VARCHAR(50) any
    }
    want ||--o{ fact : fine
    want {
        VARCHAR(50) fine
        DATE Mr
    }
    fact ||--o{ deep : business
    fact {
        DATE business
        TEXT now
        VARCHAR(50) environmental
    }
    deep ||--o{ everybody : individual
    deep {
        VARCHAR(50) individual
        DATE actually
    }
    everybody ||--o{ first : offer
    everybody {
        DATE offer
        TEXT agree
        VARCHAR(50) those
    }
    first ||--o{ rate : product
    first {
        VARCHAR(50) product
        DATE everyone
    }
    rate ||--o{ support : discover
    rate {
        DATE discover
        TEXT why
        VARCHAR(50) fly
    }
    support ||--o{ road : grow
    support {
        VARCHAR(50) grow
        DATE themselves
    }
    road ||--o{ read : consider
    road {
        DATE consider
        TEXT several
        VARCHAR(50) claim
    }