erDiagram
    save ||--o{ thank : score
    save {
        DATE score
        TEXT again
        VARCHAR(50) once
    }
    thank ||--o{ executive : single
    thank {
        VARCHAR(50) single
        DATE someone
    }
    executive ||--o{ agency : effect
    executive {
        DATE effect
        TEXT card
        VARCHAR(50) necessary
    }
    agency ||--o{ energy : buy
    agency {
        VARCHAR(50) buy
        DATE experience
    }
    energy ||--o{ player : try
    energy {
        DATE try
        TEXT nothing
        VARCHAR(50) professor
    }
    player ||--o{ within : college
    player {
        VARCHAR(50) college
        DATE feel
    }
    within ||--o{ role : sort
    within {
        DATE sort
        TEXT claim
        VARCHAR(50) drop
    }
    role ||--o{ suffer : almost
    role {
        VARCHAR(50) almost
        DATE test
    }
    suffer ||--o{ treat : hit
    suffer {
        DATE hit
        TEXT its
        VARCHAR(50) phone
    }
    treat ||--o{ building : drop
    treat {
        VARCHAR(50) drop
        DATE what
    }
    building ||--o{ save : southern
    building {
        DATE southern
        TEXT charge
        VARCHAR(50) happen
    }