erDiagram
    whatever ||--o{ hotel : television
    whatever {
        DATE television
        TEXT voice
        VARCHAR(50) million
    }
    hotel ||--o{ truth : movement
    hotel {
        VARCHAR(50) movement
        DATE event
    }
    truth ||--o{ ever : commercial
    truth {
        DATE commercial
        TEXT point
        VARCHAR(50) smile
    }
    ever ||--o{ claim : successful
    ever {
        VARCHAR(50) successful
        DATE mind
    }
    claim ||--o{ chair : investment
    claim {
        DATE investment
        TEXT section
        VARCHAR(50) friend
    }
    chair ||--o{ own : rather
    chair {
        VARCHAR(50) rather
        DATE spend
    }
    own ||--o{ whatever : daughter
    own {
        DATE daughter
        TEXT source
        VARCHAR(50) human
    }