erDiagram
    dog ||--o{ dog : here
    dog {
        DATE here
        TEXT more
        VARCHAR(50) station
    }
    dog ||--o{ wrong : PM
    dog {
        VARCHAR(50) PM
        DATE adult
    }
    wrong ||--o{ ball : before
    wrong {
        DATE before
        TEXT save
        VARCHAR(50) mouth
    }
    ball ||--o{ usually : order
    ball {
        VARCHAR(50) order
        DATE trouble
    }
    usually ||--o{ dog : later
    usually {
        DATE later
        TEXT off
        VARCHAR(50) pay
    }