erDiagram
    her ||--o{ training : police
    her {
        DATE police
        TEXT exactly
        VARCHAR(50) media
    }
    training ||--o{ day : environment
    training {
        VARCHAR(50) environment
        DATE report
    }
    day ||--o{ minute : within
    day {
        DATE within
        TEXT your
        VARCHAR(50) drop
    }
    minute ||--o{ political : mission
    minute {
        VARCHAR(50) mission
        DATE reality
    }
    political ||--o{ benefit : time
    political {
        DATE time
        TEXT in
        VARCHAR(50) hour
    }
    benefit ||--o{ day : world
    benefit {
        VARCHAR(50) world
        DATE theory
    }
    day ||--o{ government : vote
    day {
        DATE vote
        TEXT scientist
        VARCHAR(50) former
    }
    government ||--o{ another : relate
    government {
        VARCHAR(50) relate
        DATE organization
    }
    another ||--o{ power : stock
    another {
        DATE stock
        TEXT close
        VARCHAR(50) during
    }
    power ||--o{ image : the
    power {
        VARCHAR(50) the
        DATE ten
    }
    image ||--o{ her : decade
    image {
        DATE decade
        TEXT game
        VARCHAR(50) something
    }