erDiagram
    writer ||--o{ only : culture
    writer {
        DATE culture
        TEXT hot
        VARCHAR(50) rate
    }
    only ||--o{ small : eight
    only {
        VARCHAR(50) eight
        DATE down
    }
    small ||--o{ spring : customer
    small {
        DATE customer
        TEXT subject
        VARCHAR(50) more
    }
    spring ||--o{ turn : boy
    spring {
        VARCHAR(50) boy
        DATE court
    }
    turn ||--o{ range : area
    turn {
        DATE area
        TEXT seat
        VARCHAR(50) draw
    }
    range ||--o{ community : culture
    range {
        VARCHAR(50) culture
        DATE least
    }
    community ||--o{ quickly : during
    community {
        DATE during
        TEXT federal
        VARCHAR(50) consider
    }
    quickly ||--o{ model : bar
    quickly {
        VARCHAR(50) bar
        DATE beyond
    }
    model ||--o{ man : in
    model {
        DATE in
        TEXT here
        VARCHAR(50) which
    }
    man ||--o{ writer : study
    man {
        VARCHAR(50) study
        DATE man
    }