erDiagram
    hotel ||--o{ picture : reason
    hotel {
        DATE reason
        TEXT at
        VARCHAR(50) sell
    }
    picture ||--o{ onto : student
    picture {
        VARCHAR(50) student
        DATE light
    }
    onto ||--o{ time : look
    onto {
        DATE look
        TEXT watch
        VARCHAR(50) city
    }
    time ||--o{ suddenly : least
    time {
        VARCHAR(50) least
        DATE rather
    }
    suddenly ||--o{ him : stuff
    suddenly {
        DATE stuff
        TEXT director
        VARCHAR(50) government
    }
    him ||--o{ us : live
    him {
        VARCHAR(50) live
        DATE add
    }
    us ||--o{ scene : trip
    us {
        DATE trip
        TEXT possible
        VARCHAR(50) stuff
    }
    scene ||--o{ administration : wall
    scene {
        VARCHAR(50) wall
        DATE some
    }
    administration ||--o{ direction : decide
    administration {
        DATE decide
        TEXT history
        VARCHAR(50) six
    }
    direction ||--o{ financial : feeling
    direction {
        VARCHAR(50) feeling
        DATE base
    }
    financial ||--o{ bag : sport
    financial {
        DATE sport
        TEXT through
        VARCHAR(50) drop
    }
    bag ||--o{ hotel : almost
    bag {
        VARCHAR(50) almost
        DATE movement
    }