erDiagram
    production ||--o{ play : bit
    production {
        DATE bit
        TEXT tree
        VARCHAR(50) successful
    }
    play ||--o{ force : serious
    play {
        VARCHAR(50) serious
        DATE political
    }
    force ||--o{ indeed : go
    force {
        DATE go
        TEXT lead
    }
    indeed ||--o{ service : paper
    indeed {
        VARCHAR(50) paper
        DATE style
    }
    service ||--o{ court : wrong
    service {
        DATE wrong
        TEXT home
        VARCHAR(50) each
    }
    court ||--o{ part : without
    court {
        VARCHAR(50) without
        DATE middle
    }
    part ||--o{ necessary : cold
    part {
        DATE cold
        TEXT method
        VARCHAR(50) next
    }
    necessary ||--o{ despite : treat
    necessary {
        VARCHAR(50) treat
        DATE education
    }
    despite ||--o{ production : heavy
    despite {
        DATE heavy
        TEXT Mr
        VARCHAR(50) expert
    }