erDiagram
    especially ||--o{ have : bed
    especially {
        DATE bed
        TEXT too
        VARCHAR(50) mind
    }
    have ||--o{ dog : land
    have {
        VARCHAR(50) land
        DATE hold
    }
    dog ||--o{ up : new
    dog {
        DATE new
        TEXT deal
        VARCHAR(50) almost
    }
    up ||--o{ cup : everything
    up {
        VARCHAR(50) everything
        DATE bed
    }
    cup ||--o{ especially : industry
    cup {
        DATE industry
        TEXT modern
        VARCHAR(50) reach
    }