erDiagram
    bill ||--o{ prove : candidate
    bill {
        DATE candidate
        TEXT but
        VARCHAR(50) drug
    }
    prove ||--o{ onto : glass
    prove {
        VARCHAR(50) glass
        DATE single
    }
    onto ||--o{ defense : because
    onto {
        DATE because
        TEXT explain
        VARCHAR(50) democratic
    }
    defense ||--o{ such : Mrs
    defense {
        VARCHAR(50) Mrs
        DATE admit
    }
    such ||--o{ understand : fly
    such {
        DATE fly
        TEXT interesting
        VARCHAR(50) rather
    }
    understand ||--o{ research : management
    understand {
        VARCHAR(50) management
        DATE series
    }
    research ||--o{ reality : another
    research {
        DATE another
        TEXT our
        VARCHAR(50) never
    }
    reality ||--o{ arrive : before
    reality {
        VARCHAR(50) before
        DATE hit
    }
    arrive ||--o{ bill : exactly
    arrive {
        DATE exactly
        TEXT campaign
        VARCHAR(50) forget
    }