erDiagram
    skill ||--o{ low : range
    skill {
        DATE range
        TEXT general
        VARCHAR(50) me
    }
    low ||--o{ food : structure
    low {
        VARCHAR(50) structure
        DATE nor
    }
    food ||--o{ manage : store
    food {
        DATE store
        TEXT agent
        VARCHAR(50) media
    }
    manage ||--o{ however : citizen
    manage {
        VARCHAR(50) citizen
        DATE world
    }
    however ||--o{ window : high
    however {
        DATE high
        TEXT stay
        VARCHAR(50) never
    }
    window ||--o{ scientist : structure
    window {
        VARCHAR(50) structure
        DATE page
    }
    scientist ||--o{ development : woman
    scientist {
        DATE woman
        TEXT end
        VARCHAR(50) possible
    }
    development ||--o{ able : prepare
    development {
        VARCHAR(50) prepare
        DATE adult
    }
    able ||--o{ skill : nice
    able {
        DATE nice
        TEXT article
        VARCHAR(50) too
    }