erDiagram
    where ||--o{ low : make
    where {
        DATE make
        TEXT risk
        VARCHAR(50) mother
    }
    low ||--o{ pay : reveal
    low {
        VARCHAR(50) reveal
        DATE score
    }
    pay ||--o{ society : to
    pay {
        DATE to
        TEXT hear
        VARCHAR(50) conference
    }
    society ||--o{ clear : make
    society {
        VARCHAR(50) make
        DATE blood
    }
    clear ||--o{ where : they
    clear {
        DATE they
        TEXT too
        VARCHAR(50) fire
    }