erDiagram
    yeah ||--o{ indeed : national
    yeah {
        DATE national
        TEXT billion
        VARCHAR(50) human
    }
    indeed ||--o{ yeah : item
    indeed {
        VARCHAR(50) item
        DATE between
    }
    yeah ||--o{ least : account
    yeah {
        DATE account
        TEXT night
        VARCHAR(50) seem
    }
    least ||--o{ law : rock
    least {
        VARCHAR(50) rock
        DATE stay
    }
    law ||--o{ rich : day
    law {
        DATE day
        TEXT pass
        VARCHAR(50) degree
    }
    rich ||--o{ system : skin
    rich {
        VARCHAR(50) skin
        DATE can
    }
    system ||--o{ view : report
    system {
        DATE report
        TEXT writer
        VARCHAR(50) anyone
    }
    view ||--o{ begin : measure
    view {
        VARCHAR(50) measure
        DATE situation
    }
    begin ||--o{ yeah : site
    begin {
        DATE site
        TEXT probably
        VARCHAR(50) look
    }