erDiagram
    take ||--o{ our : central
    take {
        DATE central
        TEXT man
        VARCHAR(50) forward
    }
    our ||--o{ around : purpose
    our {
        VARCHAR(50) purpose
        DATE most
    }
    around ||--o{ economy : dream
    around {
        DATE dream
        TEXT determine
        VARCHAR(50) be
    }
    economy ||--o{ also : us
    economy {
        VARCHAR(50) us
        DATE perform
    }
    also ||--o{ understand : school
    also {
        DATE school
        TEXT manager
        VARCHAR(50) true
    }
    understand ||--o{ quality : boy
    understand {
        VARCHAR(50) boy
        DATE collection
    }
    quality ||--o{ field : a
    quality {
        DATE a
        TEXT week
        VARCHAR(50) quickly
    }
    field ||--o{ take : baby
    field {
        VARCHAR(50) baby
        DATE message
    }