erDiagram
    law ||--o{ wonder : however
    law {
        DATE however
        TEXT edge
        VARCHAR(50) however
    }
    wonder ||--o{ decide : wide
    wonder {
        VARCHAR(50) wide
        DATE change
    }
    decide ||--o{ his : finally
    decide {
        DATE finally
        TEXT next
        VARCHAR(50) trip
    }
    his ||--o{ direction : control
    his {
        VARCHAR(50) control
        DATE sell
    }
    direction ||--o{ lawyer : be
    direction {
        DATE be
        TEXT because
        VARCHAR(50) past
    }
    lawyer ||--o{ explain : organization
    lawyer {
        VARCHAR(50) organization
        DATE food
    }
    explain ||--o{ experience : catch
    explain {
        DATE catch
        TEXT these
        VARCHAR(50) suffer
    }
    experience ||--o{ too : window
    experience {
        VARCHAR(50) window
        DATE project
    }
    too ||--o{ rest : radio
    too {
        DATE radio
        TEXT left
        VARCHAR(50) shoulder
    }
    rest ||--o{ hard : could
    rest {
        VARCHAR(50) could
        DATE final
    }
    hard ||--o{ law : scene
    hard {
        DATE scene
        TEXT memory
        VARCHAR(50) others
    }