erDiagram
    debate ||--o{ practice : money
    debate {
        DATE money
        TEXT example
        VARCHAR(50) group
    }
    practice ||--o{ difficult : month
    practice {
        VARCHAR(50) month
        DATE society
    }
    difficult ||--o{ wife : so
    difficult {
        DATE so
        TEXT bring
        VARCHAR(50) ground
    }
    wife ||--o{ future : get
    wife {
        VARCHAR(50) get
        DATE inside
    }
    future ||--o{ among : test
    future {
        DATE test
        TEXT blood
        VARCHAR(50) though
    }
    among ||--o{ unit : since
    among {
        VARCHAR(50) since
        DATE safe
    }
    unit ||--o{ myself : spring
    unit {
        DATE spring
        TEXT piece
        VARCHAR(50) move
    }
    myself ||--o{ debate : natural
    myself {
        VARCHAR(50) natural
        DATE author
    }