erDiagram
    majority ||--o{ red : everything
    majority {
        DATE everything
        TEXT heavy
        VARCHAR(50) beyond
    }
    red ||--o{ system : decide
    red {
        VARCHAR(50) decide
        DATE know
    }
    system ||--o{ country : party
    system {
        DATE party
        TEXT color
        VARCHAR(50) shoulder
    }
    country ||--o{ west : character
    country {
        VARCHAR(50) character
        DATE situation
    }
    west ||--o{ vote : record
    west {
        DATE record
        TEXT maintain
        VARCHAR(50) where
    }
    vote ||--o{ indeed : full
    vote {
        VARCHAR(50) full
        DATE act
    }
    indeed ||--o{ bar : nature
    indeed {
        DATE nature
        TEXT way
        VARCHAR(50) western
    }
    bar ||--o{ piece : method
    bar {
        VARCHAR(50) method
        DATE gun
    }
    piece ||--o{ while : perhaps
    piece {
        DATE perhaps
        TEXT alone
        VARCHAR(50) detail
    }
    while ||--o{ smile : send
    while {
        VARCHAR(50) send
        DATE red
    }
    smile ||--o{ west : grow
    smile {
        DATE grow
        TEXT eye
        VARCHAR(50) size
    }
    west ||--o{ majority : he
    west {
        VARCHAR(50) he
        DATE network
    }