erDiagram
    window ||--o{ book : history
    window {
        DATE history
        TEXT collection
        VARCHAR(50) onto
    }
    book ||--o{ event : teacher
    book {
        VARCHAR(50) teacher
        DATE check
    }
    event ||--o{ shoulder : sit
    event {
        DATE sit
        TEXT price
        VARCHAR(50) him
    }
    shoulder ||--o{ city : need
    shoulder {
        VARCHAR(50) need
        DATE nothing
    }
    city ||--o{ window : tax
    city {
        DATE tax
        TEXT believe
        VARCHAR(50) west
    }