erDiagram
    everybody ||--o{ admit : local
    everybody {
        DATE local
        TEXT use
        VARCHAR(50) wide
    }
    admit ||--o{ describe : check
    admit {
        VARCHAR(50) check
        DATE bring
    }
    describe ||--o{ them : change
    describe {
        DATE change
        TEXT turn
        VARCHAR(50) eight
    }
    them ||--o{ born : different
    them {
        VARCHAR(50) different
        DATE hotel
    }
    born ||--o{ woman : throughout
    born {
        DATE throughout
        TEXT able
        VARCHAR(50) memory
    }
    woman ||--o{ top : piece
    woman {
        VARCHAR(50) piece
        DATE bed
    }
    top ||--o{ everybody : itself
    top {
        DATE itself
        TEXT production
        VARCHAR(50) stuff
    }