erDiagram
    suddenly ||--o{ financial : state
    suddenly {
        DATE state
        TEXT modern
        VARCHAR(50) old
    }
    financial ||--o{ others : then
    financial {
        VARCHAR(50) then
        DATE single
    }
    others ||--o{ four : establish
    others {
        DATE establish
        TEXT quality
        VARCHAR(50) box
    }
    four ||--o{ protect : off
    four {
        VARCHAR(50) off
        DATE physical
    }
    protect ||--o{ let : land
    protect {
        DATE land
        TEXT kitchen
        VARCHAR(50) response
    }
    let ||--o{ popular : soldier
    let {
        VARCHAR(50) soldier
        DATE spring
    }
    popular ||--o{ agent : fall
    popular {
        DATE fall
        TEXT wait
        VARCHAR(50) available
    }
    agent ||--o{ water : mention
    agent {
        VARCHAR(50) mention
        DATE develop
    }
    water ||--o{ culture : street
    water {
        DATE street
        TEXT big
        VARCHAR(50) police
    }
    culture ||--o{ realize : these
    culture {
        VARCHAR(50) these
        DATE direction
    }
    realize ||--o{ suddenly : create
    realize {
        DATE create
        TEXT ready
        VARCHAR(50) reflect
    }