erDiagram
    country ||--o{ parent : worry
    country {
        DATE worry
        TEXT different
        VARCHAR(50) long
    }
    parent ||--o{ book : north
    parent {
        VARCHAR(50) north
        DATE school
    }
    book ||--o{ measure : law
    book {
        DATE law
        TEXT great
        VARCHAR(50) food
    }
    measure ||--o{ old : everyone
    measure {
        VARCHAR(50) everyone
        DATE activity
    }
    old ||--o{ student : most
    old {
        DATE most
        TEXT occur
        VARCHAR(50) teacher
    }
    student ||--o{ open : nation
    student {
        VARCHAR(50) nation
        DATE herself
    }
    open ||--o{ political : coach
    open {
        DATE coach
        TEXT money
        VARCHAR(50) technology
    }
    political ||--o{ country : take
    political {
        VARCHAR(50) take
        DATE same
    }