erDiagram
    nature ||--o{ worker : author
    nature {
        DATE author
        TEXT fish
        VARCHAR(50) church
    }
    worker ||--o{ list : base
    worker {
        VARCHAR(50) base
        DATE someone
    }
    list ||--o{ only : foreign
    list {
        TEXT across
        VARCHAR(50) bank
    }
    only ||--o{ open : each
    only {
        VARCHAR(50) each
        DATE sell
    }
    open ||--o{ activity : small
    open {
        DATE small
        TEXT yourself
        VARCHAR(50) allow
    }
    activity ||--o{ attack : bag
    activity {
        VARCHAR(50) bag
        DATE throughout
    }
    attack ||--o{ since : loss
    attack {
        DATE loss
        TEXT other
        VARCHAR(50) deal
    }
    since ||--o{ option : unit
    since {
        VARCHAR(50) unit
        DATE who
    }
    option ||--o{ these : yard
    option {
        DATE yard
        TEXT defense
        VARCHAR(50) but
    }
    these ||--o{ stuff : I
    these {
        VARCHAR(50) I
        DATE catch
    }
    stuff ||--o{ nature : large
    stuff {
        DATE large
        TEXT popular
        VARCHAR(50) life
    }