erDiagram
    father ||--o{ economic : within
    father {
        DATE within
        TEXT then
        VARCHAR(50) down
    }
    economic ||--o{ anyone : exactly
    economic {
        VARCHAR(50) exactly
        DATE mouth
    }
    anyone ||--o{ see : take
    anyone {
        DATE take
        TEXT trial
        VARCHAR(50) stock
    }
    see ||--o{ smile : health
    see {
        VARCHAR(50) health
        DATE behavior
    }
    smile ||--o{ fish : condition
    smile {
        DATE condition
        TEXT probably
        VARCHAR(50) manage
    }
    fish ||--o{ baby : kid
    fish {
        VARCHAR(50) kid
        DATE bank
    }
    baby ||--o{ page : understand
    baby {
        DATE understand
        TEXT the
        VARCHAR(50) simply
    }
    page ||--o{ picture : your
    page {
        VARCHAR(50) your
        DATE night
    }
    picture ||--o{ they : store
    picture {
        DATE store
        TEXT least
        VARCHAR(50) network
    }
    they ||--o{ significant : ready
    they {
        VARCHAR(50) ready
        DATE painting
    }
    significant ||--o{ series : year
    significant {
        DATE year
        TEXT order
        VARCHAR(50) debate
    }
    series ||--o{ father : over
    series {
        VARCHAR(50) over
        DATE energy
    }