erDiagram
    benefit ||--o{ expert : senior
    benefit {
        DATE senior
        TEXT million
        VARCHAR(50) rule
    }
    expert ||--o{ give : production
    expert {
        VARCHAR(50) production
        DATE health
    }
    give ||--o{ somebody : learn
    give {
        DATE learn
        TEXT bar
        VARCHAR(50) art
    }
    somebody ||--o{ child : each
    somebody {
        VARCHAR(50) each
        DATE little
    }
    child ||--o{ lead : book
    child {
        DATE book
        TEXT collection
        VARCHAR(50) method
    }
    lead ||--o{ me : this
    lead {
        VARCHAR(50) this
        DATE life
    }
    me ||--o{ determine : name
    me {
        DATE name
        TEXT water
        VARCHAR(50) eat
    }
    determine ||--o{ benefit : despite
    determine {
        VARCHAR(50) despite
        DATE total
    }