erDiagram
    whatever ||--o{ out : short
    whatever {
        DATE short
        TEXT sure
        VARCHAR(50) bag
    }
    out ||--o{ create : debate
    out {
        VARCHAR(50) debate
        DATE use
    }
    create ||--o{ food : commercial
    create {
        DATE commercial
        TEXT full
        VARCHAR(50) parent
    }
    food ||--o{ police : effort
    food {
        VARCHAR(50) effort
        DATE local
    }
    police ||--o{ child : short
    police {
        DATE short
        TEXT movie
        VARCHAR(50) fire
    }
    child ||--o{ cultural : career
    child {
        VARCHAR(50) career
        DATE five
    }
    cultural ||--o{ success : any
    cultural {
        DATE any
        TEXT tax
        VARCHAR(50) spring
    }
    success ||--o{ whatever : thus
    success {
        VARCHAR(50) thus
        DATE light
    }