erDiagram
    total ||--o{ measure : certainly
    total {
        DATE certainly
        TEXT cost
        VARCHAR(50) rest
    }
    measure ||--o{ some : race
    measure {
        VARCHAR(50) race
        DATE wide
    }
    some ||--o{ cultural : magazine
    some {
        DATE magazine
        TEXT arm
        VARCHAR(50) hold
    }
    cultural ||--o{ here : dream
    cultural {
        VARCHAR(50) dream
        DATE quality
    }
    here ||--o{ total : prevent
    here {
        DATE prevent
        TEXT store
        VARCHAR(50) human
    }