erDiagram
    claim ||--o{ field : technology
    claim {
        DATE technology
        TEXT staff
        VARCHAR(50) relate
    }
    field ||--o{ look : dark
    field {
        VARCHAR(50) dark
        DATE national
    }
    look ||--o{ indicate : year
    look {
        DATE year
        TEXT walk
        VARCHAR(50) student
    }
    indicate ||--o{ next : west
    indicate {
        VARCHAR(50) west
        DATE cost
    }
    next ||--o{ actually : head
    next {
        DATE head
        TEXT specific
        VARCHAR(50) probably
    }
    actually ||--o{ to : scientist
    actually {
        VARCHAR(50) scientist
        DATE vote
    }
    to ||--o{ claim : life
    to {
        DATE life
        TEXT ability
        VARCHAR(50) military
    }