erDiagram
    teach ||--o{ like : bit
    teach {
        DATE bit
        TEXT another
        VARCHAR(50) result
    }
    like ||--o{ effort : call
    like {
        VARCHAR(50) call
        DATE fire
    }
    effort ||--o{ toward : including
    effort {
        DATE including
        TEXT light
        VARCHAR(50) writer
    }
    toward ||--o{ cultural : expert
    toward {
        VARCHAR(50) expert
        DATE oil
    }
    cultural ||--o{ special : rate
    cultural {
        DATE rate
        TEXT one
        VARCHAR(50) image
    }
    special ||--o{ purpose : public
    special {
        VARCHAR(50) public
        DATE politics
    }
    purpose ||--o{ teach : perhaps
    purpose {
        DATE perhaps
        TEXT talk
        VARCHAR(50) economy
    }