erDiagram
    trade ||--o{ bad : prepare
    trade {
        DATE prepare
        TEXT major
        VARCHAR(50) program
    }
    bad ||--o{ fear : your
    bad {
        VARCHAR(50) your
        DATE husband
    }
    fear ||--o{ make : trade
    fear {
        DATE trade
        TEXT talk
        VARCHAR(50) practice
    }
    make ||--o{ get : mention
    make {
        VARCHAR(50) mention
        DATE turn
    }
    get ||--o{ air : necessary
    get {
        DATE necessary
        TEXT attorney
        VARCHAR(50) well
    }
    air ||--o{ choice : answer
    air {
        VARCHAR(50) answer
        DATE too
    }
    choice ||--o{ window : establish
    choice {
        DATE establish
        TEXT large
        VARCHAR(50) hair
    }
    window ||--o{ guess : whole
    window {
        VARCHAR(50) whole
        DATE sound
    }
    guess ||--o{ sell : reason
    guess {
        DATE reason
        TEXT establish
        VARCHAR(50) score
    }
    sell ||--o{ security : establish
    sell {
        VARCHAR(50) establish
        DATE dream
    }
    security ||--o{ involve : police
    security {
        DATE police
        TEXT think
        VARCHAR(50) push
    }
    involve ||--o{ trade : play
    involve {
        VARCHAR(50) play
        DATE probably
    }