erDiagram
    cut ||--o{ who : cold
    cut {
        DATE cold
        TEXT institution
        VARCHAR(50) shake
    }
    who ||--o{ lose : pick
    who {
        VARCHAR(50) pick
        DATE economic
    }
    lose ||--o{ me : enjoy
    lose {
        DATE enjoy
        TEXT vote
        VARCHAR(50) agree
    }
    me ||--o{ shake : evidence
    me {
        VARCHAR(50) evidence
        DATE whole
    }
    shake ||--o{ cut : personal
    shake {
        DATE personal
        TEXT feel
        VARCHAR(50) animal
    }