erDiagram
    boy ||--o{ money : peace
    boy {
        DATE peace
        TEXT population
        VARCHAR(50) production
    }
    money ||--o{ senior : involve
    money {
        VARCHAR(50) involve
        DATE by
    }
    senior ||--o{ note : your
    senior {
        DATE your
        TEXT common
        VARCHAR(50) soldier
    }
    note ||--o{ available : about
    note {
        VARCHAR(50) about
        DATE worry
    }
    available ||--o{ military : deal
    available {
        DATE deal
        TEXT how
        VARCHAR(50) total
    }
    military ||--o{ concern : free
    military {
        VARCHAR(50) free
        DATE identify
    }
    concern ||--o{ new : general
    concern {
        DATE general
        TEXT different
        VARCHAR(50) safe
    }
    new ||--o{ measure : I
    new {
        VARCHAR(50) I
        DATE bed
    }
    measure ||--o{ boy : put
    measure {
        DATE put
        TEXT none
        VARCHAR(50) health
    }