erDiagram
    break ||--o{ low : similar
    break {
        DATE similar
        TEXT body
        VARCHAR(50) value
    }
    low ||--o{ near : provide
    low {
        VARCHAR(50) provide
        DATE here
    }
    near ||--o{ drug : him
    near {
        DATE him
        TEXT song
        VARCHAR(50) high
    }
    drug ||--o{ lose : image
    drug {
        VARCHAR(50) image
        DATE reduce
    }
    lose ||--o{ field : something
    lose {
        DATE something
        TEXT here
        VARCHAR(50) PM
    }
    field ||--o{ break : high
    field {
        VARCHAR(50) high
        DATE marriage
    }