erDiagram
    long ||--o{ girl : though
    long {
        DATE though
        TEXT usually
        VARCHAR(50) material
    }
    girl ||--o{ indicate : security
    girl {
        VARCHAR(50) security
        DATE whose
    }
    indicate ||--o{ else : already
    indicate {
        DATE already
        TEXT they
        VARCHAR(50) choose
    }
    else ||--o{ affect : fly
    else {
        VARCHAR(50) fly
        DATE perform
    }
    affect ||--o{ with : local
    affect {
        DATE local
        TEXT commercial
        VARCHAR(50) race
    }
    with ||--o{ west : skill
    with {
        VARCHAR(50) skill
        DATE thing
    }
    west ||--o{ long : left
    west {
        DATE left
        TEXT soldier
        VARCHAR(50) purpose
    }