erDiagram
    heavy ||--o{ movie : less
    heavy {
        DATE less
        TEXT up
        VARCHAR(50) race
    }
    movie ||--o{ evidence : reach
    movie {
        VARCHAR(50) reach
        DATE check
    }
    evidence ||--o{ happen : war
    evidence {
        DATE war
        TEXT style
        VARCHAR(50) dinner
    }
    happen ||--o{ line : resource
    happen {
        VARCHAR(50) resource
        DATE alone
    }
    line ||--o{ tend : small
    line {
        DATE small
        TEXT mind
        VARCHAR(50) material
    }
    tend ||--o{ mind : piece
    tend {
        VARCHAR(50) piece
        DATE wait
    }
    mind ||--o{ air : order
    mind {
        DATE order
        TEXT industry
        VARCHAR(50) together
    }
    air ||--o{ green : with
    air {
        VARCHAR(50) with
        DATE space
    }
    green ||--o{ five : lay
    green {
        DATE lay
        TEXT yourself
        VARCHAR(50) news
    }
    five ||--o{ ok : carry
    five {
        VARCHAR(50) carry
        DATE police
    }
    ok ||--o{ forward : radio
    ok {
        DATE radio
        TEXT hot
        VARCHAR(50) minute
    }
    forward ||--o{ heavy : tend
    forward {
        VARCHAR(50) tend
        DATE wind
    }