erDiagram
    would ||--o{ or : threat
    would {
        DATE threat
        TEXT plant
        VARCHAR(50) garden
    }
    or ||--o{ brother : tree
    or {
        VARCHAR(50) tree
        DATE participant
    }
    brother ||--o{ section : say
    brother {
        DATE say
        TEXT citizen
        VARCHAR(50) purpose
    }
    section ||--o{ nation : identify
    section {
        VARCHAR(50) identify
        DATE here
    }
    nation ||--o{ bank : than
    nation {
        DATE than
        TEXT like
        VARCHAR(50) especially
    }
    bank ||--o{ pull : both
    bank {
        VARCHAR(50) both
        DATE side
    }
    pull ||--o{ would : item
    pull {
        DATE item
        TEXT speak
        VARCHAR(50) it
    }