erDiagram
    weight ||--o{ simple : five
    weight {
        DATE five
        TEXT street
        VARCHAR(50) hard
    }
    simple ||--o{ treat : marriage
    simple {
        VARCHAR(50) marriage
        DATE blood
    }
    treat ||--o{ media : sometimes
    treat {
        DATE sometimes
        TEXT child
        VARCHAR(50) front
    }
    media ||--o{ art : hope
    media {
        VARCHAR(50) hope
        DATE perhaps
    }
    art ||--o{ police : mouth
    art {
        DATE mouth
        TEXT product
        VARCHAR(50) level
    }
    police ||--o{ artist : themselves
    police {
        VARCHAR(50) themselves
        DATE reason
    }
    artist ||--o{ education : trade
    artist {
        DATE trade
        TEXT power
        VARCHAR(50) character
    }
    education ||--o{ increase : question
    education {
        VARCHAR(50) question
        DATE professional
    }
    increase ||--o{ view : begin
    increase {
        DATE begin
        TEXT us
        VARCHAR(50) keep
    }
    view ||--o{ question : series
    view {
        VARCHAR(50) series
        DATE born
    }
    question ||--o{ weight : summer
    question {
        DATE summer
        TEXT team
        VARCHAR(50) argue
    }