erDiagram
    mind ||--o{ traditional : particularly
    mind {
        DATE particularly
        TEXT environment
        VARCHAR(50) part
    }
    traditional ||--o{ walk : final
    traditional {
        VARCHAR(50) final
        DATE above
    }
    walk ||--o{ trade : occur
    walk {
        DATE occur
        TEXT few
        VARCHAR(50) music
    }
    trade ||--o{ act : thus
    trade {
        VARCHAR(50) thus
        DATE guess
    }
    act ||--o{ seven : project
    act {
        DATE project
        TEXT moment
        VARCHAR(50) first
    }
    seven ||--o{ leg : from
    seven {
        VARCHAR(50) from
        DATE when
    }
    leg ||--o{ try : system
    leg {
        DATE system
        TEXT police
        VARCHAR(50) bad
    }
    try ||--o{ coach : tend
    try {
        VARCHAR(50) tend
        DATE American
    }
    coach ||--o{ mind : various
    coach {
        DATE various
        TEXT toward
        VARCHAR(50) out
    }