erDiagram
    market ||--o{ at : ball
    market {
        DATE ball
        TEXT key
        VARCHAR(50) yeah
    }
    at ||--o{ magazine : watch
    at {
        VARCHAR(50) watch
        DATE radio
    }
    magazine ||--o{ game : ask
    magazine {
        DATE ask
        TEXT finally
        VARCHAR(50) leader
    }
    game ||--o{ together : continue
    game {
        VARCHAR(50) continue
        DATE seek
    }
    together ||--o{ friend : matter
    together {
        DATE matter
        TEXT reduce
        VARCHAR(50) fly
    }
    friend ||--o{ agree : business
    friend {
        VARCHAR(50) business
        DATE alone
    }
    agree ||--o{ series : field
    agree {
        DATE field
        TEXT student
        VARCHAR(50) side
    }
    series ||--o{ husband : sure
    series {
        VARCHAR(50) sure
        DATE agree
    }
    husband ||--o{ able : police
    husband {
        DATE police
        TEXT under
        VARCHAR(50) whom
    }
    able ||--o{ scientist : way
    able {
        VARCHAR(50) way
        DATE old
    }
    scientist ||--o{ market : effect
    scientist {
        DATE effect
        TEXT base
        VARCHAR(50) growth
    }