erDiagram
    notice ||--o{ leader : network
    notice {
        DATE network
        TEXT poor
        VARCHAR(50) whose
    }
    leader ||--o{ choice : new
    leader {
        VARCHAR(50) new
        DATE ball
    }
    choice ||--o{ moment : already
    choice {
        DATE already
        TEXT entire
        VARCHAR(50) probably
    }
    moment ||--o{ anything : sound
    moment {
        VARCHAR(50) sound
        DATE action
    }
    anything ||--o{ international : number
    anything {
        DATE number
        TEXT speak
        VARCHAR(50) reveal
    }
    international ||--o{ play : small
    international {
        VARCHAR(50) small
        DATE drug
    }
    play ||--o{ section : senior
    play {
        DATE senior
        TEXT including
        VARCHAR(50) especially
    }
    section ||--o{ notice : degree
    section {
        VARCHAR(50) degree
        DATE arm
    }