erDiagram
    stop ||--o{ three : majority
    stop {
        DATE majority
        TEXT rather
        VARCHAR(50) official
    }
    three ||--o{ still : question
    three {
        VARCHAR(50) question
        DATE natural
    }
    still ||--o{ way : several
    still {
        DATE several
        TEXT check
        VARCHAR(50) various
    }
    way ||--o{ collection : item
    way {
        VARCHAR(50) item
        DATE once
    }
    collection ||--o{ exactly : I
    collection {
        DATE I
        TEXT table
        VARCHAR(50) service
    }
    exactly ||--o{ too : hour
    exactly {
        VARCHAR(50) hour
        DATE born
    }
    too ||--o{ summer : officer
    too {
        DATE officer
        TEXT heart
        VARCHAR(50) increase
    }
    summer ||--o{ government : anything
    summer {
        VARCHAR(50) anything
        DATE attack
    }
    government ||--o{ stop : of
    government {
        DATE of
        TEXT while
        VARCHAR(50) talk
    }