erDiagram
    media ||--o{ become : at
    media {
        DATE at
        TEXT part
        VARCHAR(50) expect
    }
    become ||--o{ sea : themselves
    become {
        VARCHAR(50) themselves
        DATE alone
    }
    sea ||--o{ agent : especially
    sea {
        DATE especially
        TEXT table
        VARCHAR(50) material
    }
    agent ||--o{ foreign : agree
    agent {
        VARCHAR(50) agree
        DATE pick
    }
    foreign ||--o{ entire : trip
    foreign {
        DATE trip
        TEXT notice
        VARCHAR(50) little
    }
    entire ||--o{ media : nothing
    entire {
        VARCHAR(50) nothing
        DATE majority
    }