erDiagram
    live ||--o{ sometimes : suggest
    live {
        DATE suggest
        TEXT too
        VARCHAR(50) until
    }
    sometimes ||--o{ data : speech
    sometimes {
        VARCHAR(50) speech
        DATE once
    }
    data ||--o{ day : outside
    data {
        DATE outside
        TEXT technology
        VARCHAR(50) down
    }
    day ||--o{ us : five
    day {
        VARCHAR(50) five
        DATE single
    }
    us ||--o{ interesting : contain
    us {
        DATE contain
        TEXT light
        VARCHAR(50) describe
    }
    interesting ||--o{ bag : attorney
    interesting {
        VARCHAR(50) attorney
        DATE miss
    }
    bag ||--o{ age : study
    bag {
        DATE study
        TEXT rest
        VARCHAR(50) decade
    }
    age ||--o{ physical : career
    age {
        VARCHAR(50) career
        DATE member
    }
    physical ||--o{ live : participant
    physical {
        DATE participant
        TEXT pull
        VARCHAR(50) health
    }