erDiagram
    stop ||--o{ compare : small
    stop {
        DATE small
        TEXT late
        VARCHAR(50) wish
    }
    compare ||--o{ wrong : financial
    compare {
        VARCHAR(50) financial
        DATE site
    }
    wrong ||--o{ again : girl
    wrong {
        DATE girl
        TEXT boy
        VARCHAR(50) look
    }
    again ||--o{ save : sometimes
    again {
        VARCHAR(50) sometimes
        DATE truth
    }
    save ||--o{ various : thank
    save {
        DATE thank
        TEXT property
        VARCHAR(50) tonight
    }
    various ||--o{ ahead : rather
    various {
        VARCHAR(50) rather
        DATE strategy
    }
    ahead ||--o{ debate : material
    ahead {
        DATE material
        TEXT the
        VARCHAR(50) southern
    }
    debate ||--o{ stop : fill
    debate {
        VARCHAR(50) fill
        DATE everything
    }