erDiagram
    pull ||--o{ sea : next
    pull {
        DATE next
        TEXT such
        VARCHAR(50) onto
    }
    sea ||--o{ forget : product
    sea {
        VARCHAR(50) product
        DATE could
    }
    forget ||--o{ direction : rise
    forget {
        DATE rise
        TEXT medical
        VARCHAR(50) or
    }
    direction ||--o{ threat : enjoy
    direction {
        VARCHAR(50) enjoy
        DATE around
    }
    threat ||--o{ young : represent
    threat {
        DATE represent
        TEXT PM
        VARCHAR(50) study
    }
    young ||--o{ really : capital
    young {
        VARCHAR(50) capital
        DATE degree
    }
    really ||--o{ machine : either
    really {
        DATE either
        TEXT city
        VARCHAR(50) these
    }
    machine ||--o{ unit : thing
    machine {
        VARCHAR(50) thing
        DATE interview
    }
    unit ||--o{ chair : question
    unit {
        DATE question
        TEXT arm
        VARCHAR(50) face
    }
    chair ||--o{ different : price
    chair {
        VARCHAR(50) price
        DATE thing
    }
    different ||--o{ their : son
    different {
        DATE son
        TEXT around
        VARCHAR(50) degree
    }
    their ||--o{ pull : back
    their {
        VARCHAR(50) back
        DATE face
    }