erDiagram
    center ||--o{ together : pretty
    center {
        DATE pretty
        TEXT perform
        VARCHAR(50) paper
    }
    together ||--o{ reveal : responsibility
    together {
        VARCHAR(50) responsibility
        DATE statement
    }
    reveal ||--o{ event : set
    reveal {
        DATE set
        TEXT sell
        VARCHAR(50) need
    }
    event ||--o{ term : television
    event {
        VARCHAR(50) television
        DATE success
    }
    term ||--o{ center : official
    term {
        DATE official
        TEXT picture
        VARCHAR(50) dog
    }