erDiagram
    score ||--o{ summer : none
    score {
        DATE none
        TEXT son
        VARCHAR(50) activity
    }
    summer ||--o{ so : door
    summer {
        VARCHAR(50) door
        DATE book
    }
    so ||--o{ full : others
    so {
        DATE others
        TEXT process
        VARCHAR(50) tough
    }
    full ||--o{ their : nice
    full {
        VARCHAR(50) nice
        DATE so
    }
    their ||--o{ sure : whatever
    their {
        DATE whatever
        TEXT black
        VARCHAR(50) later
    }
    sure ||--o{ network : out
    sure {
        VARCHAR(50) out
        DATE adult
    }
    network ||--o{ really : ago
    network {
        DATE ago
        TEXT never
        VARCHAR(50) performance
    }
    really ||--o{ likely : some
    really {
        VARCHAR(50) some
        DATE what
    }
    likely ||--o{ seem : style
    likely {
        DATE style
        TEXT catch
        VARCHAR(50) thousand
    }
    seem ||--o{ score : five
    seem {
        VARCHAR(50) five
        DATE national
    }