erDiagram
    others ||--o{ minute : several
    others {
        DATE several
        TEXT far
        VARCHAR(50) mother
    }
    minute ||--o{ land : hot
    minute {
        VARCHAR(50) hot
        DATE trial
    }
    land ||--o{ bank : quality
    land {
        DATE quality
        TEXT full
        VARCHAR(50) gas
    }
    bank ||--o{ cultural : company
    bank {
        VARCHAR(50) company
        DATE owner
    }
    cultural ||--o{ others : energy
    cultural {
        DATE energy
        TEXT national
        VARCHAR(50) choice
    }