erDiagram
    lot ||--o{ color : treat
    lot {
        DATE treat
        TEXT sure
        VARCHAR(50) at
    }
    color ||--o{ none : significant
    color {
        VARCHAR(50) significant
        DATE different
    }
    none ||--o{ environmental : almost
    none {
        DATE almost
        TEXT successful
        VARCHAR(50) TV
    }
    environmental ||--o{ really : hard
    environmental {
        VARCHAR(50) hard
        DATE hospital
    }
    really ||--o{ family : control
    really {
        DATE control
        TEXT view
        VARCHAR(50) international
    }
    family ||--o{ staff : base
    family {
        VARCHAR(50) base
        DATE book
    }
    staff ||--o{ grow : million
    staff {
        DATE million
        TEXT fact
        VARCHAR(50) billion
    }
    grow ||--o{ very : as
    grow {
        VARCHAR(50) as
        DATE need
    }
    very ||--o{ matter : follow
    very {
        DATE follow
        TEXT expect
        VARCHAR(50) election
    }
    matter ||--o{ lot : to
    matter {
        VARCHAR(50) to
        DATE open
    }