erDiagram
    baby ||--o{ many : at
    baby {
        DATE at
        TEXT all
        VARCHAR(50) kid
    }
    many ||--o{ network : indicate
    many {
        VARCHAR(50) indicate
        DATE laugh
    }
    network ||--o{ guess : could
    network {
        DATE could
        TEXT education
        VARCHAR(50) sit
    }
    guess ||--o{ charge : trial
    guess {
        VARCHAR(50) trial
        DATE recent
    }
    charge ||--o{ prepare : dream
    charge {
        DATE dream
        TEXT it
        VARCHAR(50) trouble
    }
    prepare ||--o{ activity : young
    prepare {
        VARCHAR(50) young
        DATE forget
    }
    activity ||--o{ form : owner
    activity {
        DATE owner
        TEXT any
        VARCHAR(50) thank
    }
    form ||--o{ return : first
    form {
        VARCHAR(50) first
        DATE challenge
    }
    return ||--o{ among : debate
    return {
        DATE debate
        TEXT whose
        VARCHAR(50) feeling
    }
    among ||--o{ baby : sound
    among {
        VARCHAR(50) sound
        DATE body
    }