erDiagram
    challenge ||--o{ surface : sport
    challenge {
        DATE sport
        TEXT anything
        VARCHAR(50) above
    }
    surface ||--o{ spring : four
    surface {
        VARCHAR(50) four
        DATE cut
    }
    spring ||--o{ condition : policy
    spring {
        DATE policy
        TEXT buy
        VARCHAR(50) poor
    }
    condition ||--o{ level : somebody
    condition {
        VARCHAR(50) somebody
        DATE method
    }
    level ||--o{ between : daughter
    level {
        DATE daughter
        TEXT table
        VARCHAR(50) ready
    }
    between ||--o{ also : at
    between {
        VARCHAR(50) at
        DATE grow
    }
    also ||--o{ challenge : none
    also {
        DATE none
        TEXT face
        VARCHAR(50) long
    }