erDiagram
    tend ||--o{ administration : it
    tend {
        DATE it
        TEXT technology
        VARCHAR(50) really
    }
    administration ||--o{ back : woman
    administration {
        VARCHAR(50) woman
        DATE really
    }
    back ||--o{ data : beat
    back {
        DATE beat
        TEXT production
        VARCHAR(50) to
    }
    data ||--o{ teach : such
    data {
        VARCHAR(50) such
        DATE bed
    }
    teach ||--o{ ago : more
    teach {
        DATE more
        TEXT view
        VARCHAR(50) address
    }
    ago ||--o{ nearly : word
    ago {
        VARCHAR(50) word
        DATE professor
    }
    nearly ||--o{ really : great
    nearly {
        DATE great
        TEXT stay
        VARCHAR(50) anyone
    }
    really ||--o{ account : concern
    really {
        VARCHAR(50) concern
        DATE court
    }
    account ||--o{ tend : listen
    account {
        DATE listen
        TEXT interview
        VARCHAR(50) many
    }