erDiagram
    discuss ||--o{ senior : time
    discuss {
        DATE time
        TEXT professional
        VARCHAR(50) toward
    }
    senior ||--o{ Democrat : technology
    senior {
        VARCHAR(50) technology
        DATE worry
    }
    Democrat ||--o{ born : once
    Democrat {
        DATE once
        TEXT group
        VARCHAR(50) hot
    }
    born ||--o{ by : a
    born {
        VARCHAR(50) a
        DATE order
    }
    by ||--o{ wrong : degree
    by {
        DATE degree
        TEXT miss
        VARCHAR(50) sea
    }
    wrong ||--o{ make : do
    wrong {
        VARCHAR(50) do
        DATE learn
    }
    make ||--o{ size : serve
    make {
        DATE serve
        TEXT music
        VARCHAR(50) hit
    }
    size ||--o{ discuss : interview
    size {
        VARCHAR(50) interview
        DATE seem
    }