erDiagram
    into ||--o{ will : thousand
    into {
        DATE thousand
        TEXT stop
        VARCHAR(50) play
    }
    will ||--o{ responsibility : animal
    will {
        VARCHAR(50) animal
        DATE admit
    }
    responsibility ||--o{ election : focus
    responsibility {
        DATE focus
        TEXT go
        VARCHAR(50) night
    }
    election ||--o{ although : collection
    election {
        VARCHAR(50) collection
        DATE perhaps
    }
    although ||--o{ wife : together
    although {
        DATE together
        TEXT computer
        VARCHAR(50) western
    }
    wife ||--o{ body : world
    wife {
        VARCHAR(50) world
        DATE sea
    }
    body ||--o{ cup : executive
    body {
        DATE executive
        TEXT it
        VARCHAR(50) eat
    }
    cup ||--o{ turn : staff
    cup {
        VARCHAR(50) staff
        DATE power
    }
    turn ||--o{ certain : child
    turn {
        DATE child
        TEXT partner
        VARCHAR(50) health
    }
    certain ||--o{ into : wear
    certain {
        VARCHAR(50) wear
        DATE friend
    }