erDiagram
    also ||--o{ floor : push
    also {
        DATE push
        TEXT executive
        VARCHAR(50) feel
    }
    floor ||--o{ away : same
    floor {
        VARCHAR(50) same
        DATE front
    }
    away ||--o{ somebody : successful
    away {
        DATE successful
        TEXT bank
        VARCHAR(50) mouth
    }
    somebody ||--o{ difficult : practice
    somebody {
        VARCHAR(50) practice
        DATE agent
    }
    difficult ||--o{ present : age
    difficult {
        DATE age
        TEXT exactly
        VARCHAR(50) you
    }
    present ||--o{ inside : old
    present {
        VARCHAR(50) old
        DATE world
    }
    inside ||--o{ crime : improve
    inside {
        DATE improve
        TEXT best
        VARCHAR(50) catch
    }
    crime ||--o{ finally : expert
    crime {
        VARCHAR(50) expert
        DATE us
    }
    finally ||--o{ also : room
    finally {
        DATE room
        TEXT up
        VARCHAR(50) none
    }