erDiagram
    job ||--o{ step : he
    job {
        DATE he
        TEXT me
        VARCHAR(50) popular
    }
    step ||--o{ source : among
    step {
        VARCHAR(50) among
        DATE campaign
    }
    source ||--o{ early : strong
    source {
        DATE strong
        TEXT sister
        VARCHAR(50) serious
    }
    early ||--o{ our : reveal
    early {
        VARCHAR(50) reveal
        DATE quickly
    }
    our ||--o{ job : space
    our {
        DATE space
        TEXT same
        VARCHAR(50) while
    }