erDiagram
    again ||--o{ place : speech
    again {
        DATE speech
        TEXT week
        VARCHAR(50) response
    }
    place ||--o{ newspaper : over
    place {
        VARCHAR(50) over
        DATE than
    }
    newspaper ||--o{ person : figure
    newspaper {
        DATE figure
        TEXT example
        VARCHAR(50) operation
    }
    person ||--o{ half : leader
    person {
        VARCHAR(50) leader
        DATE themselves
    }
    half ||--o{ suffer : again
    half {
        DATE again
        TEXT boy
        VARCHAR(50) man
    }
    suffer ||--o{ section : rock
    suffer {
        VARCHAR(50) rock
        DATE director
    }
    section ||--o{ crime : choose
    section {
        DATE choose
        TEXT early
        VARCHAR(50) military
    }
    crime ||--o{ view : begin
    crime {
        VARCHAR(50) begin
        DATE share
    }
    view ||--o{ heart : wind
    view {
        DATE wind
        TEXT sort
        VARCHAR(50) lay
    }
    heart ||--o{ assume : quite
    heart {
        VARCHAR(50) quite
        DATE safe
    }
    assume ||--o{ again : exactly
    assume {
        DATE exactly
        TEXT world
        VARCHAR(50) soon
    }