erDiagram
    memory ||--o{ eye : hand
    memory {
        DATE hand
        TEXT strategy
        VARCHAR(50) over
    }
    eye ||--o{ number : skin
    eye {
        VARCHAR(50) skin
        DATE table
    }
    number ||--o{ run : step
    number {
        DATE step
        TEXT training
        VARCHAR(50) arrive
    }
    run ||--o{ get : present
    run {
        VARCHAR(50) present
        DATE matter
    }
    get ||--o{ least : kitchen
    get {
        DATE kitchen
        TEXT watch
        VARCHAR(50) western
    }
    least ||--o{ lead : way
    least {
        VARCHAR(50) way
        DATE there
    }
    lead ||--o{ house : look
    lead {
        DATE look
        TEXT life
        VARCHAR(50) whether
    }
    house ||--o{ other : increase
    house {
        VARCHAR(50) increase
        DATE visit
    }
    other ||--o{ memory : cost
    other {
        DATE cost
        TEXT necessary
        VARCHAR(50) ok
    }