erDiagram
    dream ||--o{ world : media
    dream {
        DATE media
        TEXT law
        VARCHAR(50) system
    }
    world ||--o{ star : radio
    world {
        VARCHAR(50) radio
        DATE dream
    }
    star ||--o{ effort : perform
    star {
        DATE perform
        TEXT service
        VARCHAR(50) everything
    }
    effort ||--o{ expect : these
    effort {
        VARCHAR(50) these
        DATE right
    }
    expect ||--o{ small : trip
    expect {
        DATE trip
        TEXT building
        VARCHAR(50) beat
    }
    small ||--o{ economy : eat
    small {
        VARCHAR(50) eat
        DATE garden
    }
    economy ||--o{ tough : teacher
    economy {
        DATE teacher
        TEXT create
        VARCHAR(50) major
    }
    tough ||--o{ before : defense
    tough {
        VARCHAR(50) defense
        DATE his
    }
    before ||--o{ Congress : little
    before {
        DATE little
        TEXT rest
        VARCHAR(50) suggest
    }
    Congress ||--o{ still : lead
    Congress {
        VARCHAR(50) lead
        DATE every
    }
    still ||--o{ dream : explain
    still {
        DATE explain
        TEXT represent
        VARCHAR(50) story
    }