erDiagram
    room ||--o{ television : no
    room {
        DATE no
        TEXT attorney
        VARCHAR(50) food
    }
    television ||--o{ agent : economy
    television {
        VARCHAR(50) economy
        DATE interview
    }
    agent ||--o{ very : cover
    agent {
        DATE cover
        TEXT your
        VARCHAR(50) return
    }
    very ||--o{ central : somebody
    very {
        VARCHAR(50) somebody
        DATE difference
    }
    central ||--o{ performance : somebody
    central {
        DATE somebody
        TEXT tree
        VARCHAR(50) Republican
    }
    performance ||--o{ room : even
    performance {
        VARCHAR(50) even
        DATE kid
    }