erDiagram
    require ||--o{ control : but
    require {
        DATE but
        TEXT present
        VARCHAR(50) middle
    }
    control ||--o{ range : bag
    control {
        VARCHAR(50) bag
        DATE example
    }
    range ||--o{ discuss : what
    range {
        DATE what
        TEXT direction
        VARCHAR(50) beautiful
    }
    discuss ||--o{ buy : television
    discuss {
        VARCHAR(50) television
        DATE their
    }
    buy ||--o{ third : president
    buy {
        DATE president
        TEXT newspaper
        VARCHAR(50) forget
    }
    third ||--o{ name : situation
    third {
        VARCHAR(50) situation
        DATE set
    }
    name ||--o{ activity : quickly
    name {
        DATE quickly
        TEXT dog
        VARCHAR(50) full
    }
    activity ||--o{ base : decade
    activity {
        VARCHAR(50) decade
        DATE Mr
    }
    base ||--o{ less : local
    base {
        DATE local
        TEXT toward
        VARCHAR(50) trouble
    }
    less ||--o{ yard : but
    less {
        VARCHAR(50) but
        DATE sound
    }
    yard ||--o{ require : institution
    yard {
        DATE institution
        TEXT country
        VARCHAR(50) decade
    }