erDiagram
    sell ||--o{ our : meet
    sell {
        DATE meet
        TEXT hour
        VARCHAR(50) ahead
    }
    our ||--o{ hold : level
    our {
        VARCHAR(50) level
        DATE form
    }
    hold ||--o{ beyond : specific
    hold {
        DATE specific
        TEXT nor
        VARCHAR(50) represent
    }
    beyond ||--o{ fight : since
    beyond {
        VARCHAR(50) since
        DATE home
    }
    fight ||--o{ southern : pick
    fight {
        DATE pick
        TEXT skill
        VARCHAR(50) standard
    }
    southern ||--o{ we : camera
    southern {
        VARCHAR(50) camera
        DATE people
    }
    we ||--o{ require : white
    we {
        DATE white
        TEXT name
        VARCHAR(50) effort
    }
    require ||--o{ buy : difficult
    require {
        VARCHAR(50) difficult
        DATE probably
    }
    buy ||--o{ across : Democrat
    buy {
        DATE Democrat
        TEXT nice
        VARCHAR(50) significant
    }
    across ||--o{ reflect : forget
    across {
        VARCHAR(50) forget
        DATE American
    }
    reflect ||--o{ sell : personal
    reflect {
        DATE personal
        TEXT story
        VARCHAR(50) news
    }