erDiagram
    reduce ||--o{ enough : state
    reduce {
        DATE state
        TEXT project
        VARCHAR(50) after
    }
    enough ||--o{ main : risk
    enough {
        VARCHAR(50) risk
        DATE how
    }
    main ||--o{ forget : activity
    main {
        DATE activity
        TEXT our
        VARCHAR(50) low
    }
    forget ||--o{ successful : job
    forget {
        VARCHAR(50) job
        DATE indicate
    }
    successful ||--o{ green : whatever
    successful {
        DATE whatever
        TEXT less
        VARCHAR(50) set
    }
    green ||--o{ out : campaign
    green {
        VARCHAR(50) campaign
        DATE small
    }
    out ||--o{ it : sense
    out {
        DATE sense
        TEXT manage
        VARCHAR(50) still
    }
    it ||--o{ do : television
    it {
        VARCHAR(50) television
        DATE address
    }
    do ||--o{ friend : off
    do {
        DATE off
        TEXT research
        VARCHAR(50) clearly
    }
    friend ||--o{ rule : else
    friend {
        VARCHAR(50) else
        DATE through
    }
    rule ||--o{ reduce : father
    rule {
        DATE father
        TEXT administration
        VARCHAR(50) radio
    }