erDiagram
    entire ||--o{ not : paper
    entire {
        DATE paper
        TEXT one
        VARCHAR(50) might
    }
    not ||--o{ rate : good
    not {
        VARCHAR(50) good
        DATE garden
    }
    rate ||--o{ road : send
    rate {
        DATE send
        TEXT save
        VARCHAR(50) effect
    }
    road ||--o{ create : run
    road {
        VARCHAR(50) run
        DATE bed
    }
    create ||--o{ everything : wonder
    create {
        DATE wonder
        TEXT art
        VARCHAR(50) bad
    }
    everything ||--o{ ask : speech
    everything {
        VARCHAR(50) speech
        DATE management
    }
    ask ||--o{ kitchen : so
    ask {
        DATE so
        TEXT small
        VARCHAR(50) theory
    }
    kitchen ||--o{ those : officer
    kitchen {
        VARCHAR(50) officer
        DATE finish
    }
    those ||--o{ entire : machine
    those {
        DATE machine
        TEXT ok
        VARCHAR(50) safe
    }