erDiagram
    all ||--o{ eye : huge
    all {
        DATE huge
        TEXT compare
        VARCHAR(50) head
    }
    eye ||--o{ sometimes : attention
    eye {
        VARCHAR(50) attention
        DATE authority
    }
    sometimes ||--o{ he : piece
    sometimes {
        DATE piece
        TEXT paper
        VARCHAR(50) series
    }
    he ||--o{ do : step
    he {
        VARCHAR(50) step
        DATE baby
    }
    do ||--o{ though : difference
    do {
        DATE difference
        TEXT throw
        VARCHAR(50) forget
    }
    though ||--o{ growth : decision
    though {
        VARCHAR(50) decision
        DATE decision
    }
    growth ||--o{ figure : instead
    growth {
        DATE instead
        TEXT fast
        VARCHAR(50) yard
    }
    figure ||--o{ little : expect
    figure {
        VARCHAR(50) expect
        DATE arm
    }
    little ||--o{ however : have
    little {
        DATE have
        TEXT assume
        VARCHAR(50) professor
    }
    however ||--o{ all : common
    however {
        VARCHAR(50) common
        DATE who
    }