erDiagram
    let ||--o{ ability : thing
    let {
        DATE thing
        TEXT effect
        VARCHAR(50) anything
    }
    ability ||--o{ available : decade
    ability {
        VARCHAR(50) decade
        DATE wear
    }
    available ||--o{ shoulder : ok
    available {
        DATE ok
        TEXT floor
        VARCHAR(50) account
    }
    shoulder ||--o{ room : true
    shoulder {
        VARCHAR(50) true
        DATE nation
    }
    room ||--o{ number : history
    room {
        DATE history
        TEXT next
        VARCHAR(50) onto
    }
    number ||--o{ rich : address
    number {
        VARCHAR(50) address
        DATE each
    }
    rich ||--o{ sort : perhaps
    rich {
        DATE perhaps
        TEXT ahead
        VARCHAR(50) thing
    }
    sort ||--o{ last : eye
    sort {
        VARCHAR(50) eye
        DATE light
    }
    last ||--o{ by : share
    last {
        DATE share
        TEXT everyone
        VARCHAR(50) throughout
    }
    by ||--o{ us : fear
    by {
        VARCHAR(50) fear
        DATE suggest
    }
    us ||--o{ let : put
    us {
        DATE put
        TEXT none
        VARCHAR(50) point
    }