erDiagram
    thousand ||--o{ gun : customer
    thousand {
        DATE customer
        TEXT network
        VARCHAR(50) different
    }
    gun ||--o{ mind : appear
    gun {
        VARCHAR(50) appear
        DATE sense
    }
    mind ||--o{ certainly : do
    mind {
        DATE do
        TEXT quickly
        VARCHAR(50) the
    }
    certainly ||--o{ call : five
    certainly {
        VARCHAR(50) five
        DATE million
    }
    call ||--o{ very : though
    call {
        DATE though
        TEXT pressure
        VARCHAR(50) keep
    }
    very ||--o{ thousand : enough
    very {
        VARCHAR(50) enough
        DATE box
    }