erDiagram
    certainly ||--o{ notice : kind
    certainly {
        DATE kind
        TEXT join
        VARCHAR(50) song
    }
    notice ||--o{ political : vote
    notice {
        VARCHAR(50) vote
        DATE more
    }
    political ||--o{ goal : watch
    political {
        DATE watch
        TEXT image
        VARCHAR(50) onto
    }
    goal ||--o{ out : behavior
    goal {
        VARCHAR(50) behavior
        DATE seven
    }
    out ||--o{ instead : character
    out {
        DATE character
        TEXT large
        VARCHAR(50) ok
    }
    instead ||--o{ out : stuff
    instead {
        VARCHAR(50) stuff
        DATE image
    }
    out ||--o{ certainly : whose
    out {
        DATE whose
        TEXT interesting
        VARCHAR(50) color
    }