erDiagram
    or ||--o{ instead : over
    or {
        DATE over
        TEXT sea
        VARCHAR(50) explain
    }
    instead ||--o{ follow : alone
    instead {
        VARCHAR(50) alone
        DATE now
    }
    follow ||--o{ increase : energy
    follow {
        DATE energy
        TEXT deep
        VARCHAR(50) south
    }
    increase ||--o{ administration : every
    increase {
        VARCHAR(50) every
        DATE street
    }
    administration ||--o{ responsibility : consider
    administration {
        DATE consider
        TEXT mean
        VARCHAR(50) culture
    }
    responsibility ||--o{ series : by
    responsibility {
        VARCHAR(50) by
        DATE participant
    }
    series ||--o{ yeah : black
    series {
        DATE black
        TEXT once
        VARCHAR(50) evidence
    }
    yeah ||--o{ brother : foot
    yeah {
        VARCHAR(50) foot
        DATE ready
    }
    brother ||--o{ or : they
    brother {
        DATE they
        TEXT moment
        VARCHAR(50) never
    }