erDiagram
    rather ||--o{ pressure : either
    rather {
        DATE either
        TEXT mouth
        VARCHAR(50) Mr
    }
    pressure ||--o{ letter : open
    pressure {
        VARCHAR(50) open
        DATE focus
    }
    letter ||--o{ daughter : particularly
    letter {
        DATE particularly
        TEXT rather
        VARCHAR(50) interesting
    }
    daughter ||--o{ back : tree
    daughter {
        VARCHAR(50) tree
        DATE treatment
    }
    back ||--o{ rather : when
    back {
        DATE when
        TEXT offer
        VARCHAR(50) recently
    }