erDiagram
    move ||--o{ full : clear
    move {
        DATE clear
        TEXT fact
        VARCHAR(50) seat
    }
    full ||--o{ skin : under
    full {
        VARCHAR(50) under
        DATE parent
    }
    skin ||--o{ involve : impact
    skin {
        DATE impact
        TEXT continue
        VARCHAR(50) maintain
    }
    involve ||--o{ example : media
    involve {
        VARCHAR(50) media
        DATE tree
    }
    example ||--o{ charge : several
    example {
        DATE several
        TEXT community
        VARCHAR(50) father
    }
    charge ||--o{ human : rest
    charge {
        VARCHAR(50) rest
        DATE today
    }
    human ||--o{ anything : national
    human {
        DATE national
        TEXT manage
        VARCHAR(50) miss
    }
    anything ||--o{ show : air
    anything {
        VARCHAR(50) air
        DATE room
    }
    show ||--o{ color : painting
    show {
        DATE painting
        TEXT happy
        VARCHAR(50) security
    }
    color ||--o{ move : mission
    color {
        VARCHAR(50) mission
        DATE management
    }