erDiagram
    to ||--o{ stuff : over
    to {
        DATE over
        TEXT find
        VARCHAR(50) consider
    }
    stuff ||--o{ democratic : pull
    stuff {
        VARCHAR(50) pull
        DATE could
    }
    democratic ||--o{ response : glass
    democratic {
        DATE glass
        TEXT send
        VARCHAR(50) treat
    }
    response ||--o{ out : then
    response {
        VARCHAR(50) then
        DATE lose
    }
    out ||--o{ husband : job
    out {
        DATE job
        TEXT worker
        VARCHAR(50) black
    }
    husband ||--o{ politics : federal
    husband {
        VARCHAR(50) federal
        DATE institution
    }
    politics ||--o{ though : artist
    politics {
        DATE artist
        TEXT team
        VARCHAR(50) analysis
    }
    though ||--o{ degree : list
    though {
        VARCHAR(50) list
        DATE maybe
    }
    degree ||--o{ to : assume
    degree {
        DATE assume
        TEXT mother
        VARCHAR(50) center
    }