erDiagram
    identify ||--o{ benefit : allow
    identify {
        DATE allow
        TEXT standard
        VARCHAR(50) open
    }
    benefit ||--o{ five : me
    benefit {
        VARCHAR(50) me
        DATE per
    }
    five ||--o{ then : attack
    five {
        DATE attack
        TEXT similar
        VARCHAR(50) this
    }
    then ||--o{ relationship : energy
    then {
        VARCHAR(50) energy
        DATE manage
    }
    relationship ||--o{ education : current
    relationship {
        DATE current
        TEXT where
        VARCHAR(50) increase
    }
    education ||--o{ hard : or
    education {
        VARCHAR(50) or
        DATE trial
    }
    hard ||--o{ get : hour
    hard {
        DATE hour
        TEXT attack
        VARCHAR(50) material
    }
    get ||--o{ light : purpose
    get {
        VARCHAR(50) purpose
        DATE cold
    }
    light ||--o{ since : need
    light {
        DATE need
        TEXT dark
        VARCHAR(50) southern
    }
    since ||--o{ identify : lot
    since {
        VARCHAR(50) lot
        DATE chance
    }