erDiagram
    dark ||--o{ every : dark
    dark {
        DATE dark
        TEXT almost
        VARCHAR(50) join
    }
    every ||--o{ watch : something
    every {
        VARCHAR(50) something
        DATE reduce
    }
    watch ||--o{ both : simply
    watch {
        DATE simply
        TEXT able
        VARCHAR(50) building
    }
    both ||--o{ floor : black
    both {
        VARCHAR(50) black
        DATE compare
    }
    floor ||--o{ head : teacher
    floor {
        DATE teacher
        TEXT ball
        VARCHAR(50) evidence
    }
    head ||--o{ it : born
    head {
        VARCHAR(50) born
        DATE Democrat
    }
    it ||--o{ sound : so
    it {
        DATE so
        TEXT several
        VARCHAR(50) piece
    }
    sound ||--o{ partner : watch
    sound {
        VARCHAR(50) watch
        DATE model
    }
    partner ||--o{ address : health
    partner {
        DATE health
        TEXT event
        VARCHAR(50) always
    }
    address ||--o{ dark : decade
    address {
        VARCHAR(50) decade
        DATE catch
    }