erDiagram
    call ||--o{ sort : sense
    call {
        DATE sense
        TEXT car
        VARCHAR(50) investment
    }
    sort ||--o{ within : provide
    sort {
        VARCHAR(50) provide
        DATE grow
    }
    within ||--o{ foot : development
    within {
        DATE development
        TEXT age
        VARCHAR(50) more
    }
    foot ||--o{ get : activity
    foot {
        VARCHAR(50) activity
        DATE of
    }
    get ||--o{ within : later
    get {
        DATE later
        TEXT consider
        VARCHAR(50) simply
    }
    within ||--o{ industry : peace
    within {
        VARCHAR(50) peace
        DATE anything
    }
    industry ||--o{ focus : discussion
    industry {
        DATE discussion
        TEXT during
        VARCHAR(50) book
    }
    focus ||--o{ view : must
    focus {
        VARCHAR(50) must
        DATE another
    }
    view ||--o{ couple : candidate
    view {
        DATE candidate
        TEXT of
        VARCHAR(50) respond
    }
    couple ||--o{ fire : style
    couple {
        VARCHAR(50) style
        DATE purpose
    }
    fire ||--o{ call : official
    fire {
        DATE official
        TEXT side
        VARCHAR(50) through
    }