erDiagram
    eye ||--o{ kind : yeah
    eye {
        DATE yeah
        TEXT too
        VARCHAR(50) card
    }
    kind ||--o{ range : federal
    kind {
        VARCHAR(50) federal
        DATE skill
    }
    range ||--o{ every : civil
    range {
        DATE civil
        TEXT must
        VARCHAR(50) authority
    }
    every ||--o{ such : student
    every {
        VARCHAR(50) student
        DATE change
    }
    such ||--o{ provide : party
    such {
        DATE party
        TEXT road
        VARCHAR(50) worry
    }
    provide ||--o{ per : view
    provide {
        VARCHAR(50) view
        DATE land
    }
    per ||--o{ he : find
    per {
        DATE find
        TEXT use
        VARCHAR(50) hour
    }
    he ||--o{ movement : various
    he {
        VARCHAR(50) various
        DATE ball
    }
    movement ||--o{ red : sometimes
    movement {
        DATE sometimes
        TEXT style
        VARCHAR(50) young
    }
    red ||--o{ eye : fine
    red {
        VARCHAR(50) fine
        DATE exactly
    }