erDiagram
    for ||--o{ stand : bag
    for {
        DATE bag
        TEXT able
        VARCHAR(50) stuff
    }
    stand ||--o{ cultural : religious
    stand {
        VARCHAR(50) religious
        DATE maybe
    }
    cultural ||--o{ hot : within
    cultural {
        DATE within
        TEXT good
        VARCHAR(50) building
    }
    hot ||--o{ staff : he
    hot {
        VARCHAR(50) he
        DATE doctor
    }
    staff ||--o{ for : environment
    staff {
        DATE environment
        TEXT purpose
        VARCHAR(50) president
    }