erDiagram
    prevent ||--o{ billion : safe
    prevent {
        DATE safe
        TEXT learn
        VARCHAR(50) stage
    }
    billion ||--o{ idea : American
    billion {
        VARCHAR(50) American
        DATE will
    }
    idea ||--o{ strong : grow
    idea {
        DATE grow
        TEXT policy
        VARCHAR(50) mother
    }
    strong ||--o{ part : consider
    strong {
        VARCHAR(50) consider
        DATE themselves
    }
    part ||--o{ how : voice
    part {
        DATE voice
        TEXT raise
        VARCHAR(50) message
    }
    how ||--o{ hope : run
    how {
        VARCHAR(50) run
        DATE fish
    }
    hope ||--o{ rule : could
    hope {
        DATE could
        TEXT itself
        VARCHAR(50) design
    }
    rule ||--o{ thousand : new
    rule {
        VARCHAR(50) new
        DATE entire
    }
    thousand ||--o{ then : fire
    thousand {
        DATE fire
        TEXT have
        VARCHAR(50) goal
    }
    then ||--o{ agree : plan
    then {
        VARCHAR(50) plan
        DATE nice
    }
    agree ||--o{ prevent : answer
    agree {
        DATE answer
        TEXT baby
        VARCHAR(50) leader
    }