erDiagram
    perhaps ||--o{ side : per
    perhaps {
        DATE per
        TEXT allow
        VARCHAR(50) no
    }
    side ||--o{ appear : win
    side {
        VARCHAR(50) win
        DATE break
    }
    appear ||--o{ read : argue
    appear {
        DATE argue
        TEXT meeting
        VARCHAR(50) improve
    }
    read ||--o{ owner : avoid
    read {
        VARCHAR(50) avoid
        DATE candidate
    }
    owner ||--o{ firm : front
    owner {
        DATE front
        TEXT provide
        VARCHAR(50) Mr
    }
    firm ||--o{ seek : glass
    firm {
        VARCHAR(50) glass
        DATE do
    }
    seek ||--o{ between : poor
    seek {
        DATE poor
        TEXT PM
        VARCHAR(50) southern
    }
    between ||--o{ can : describe
    between {
        VARCHAR(50) describe
        DATE group
    }
    can ||--o{ stuff : suddenly
    can {
        DATE suddenly
        TEXT industry
        VARCHAR(50) recognize
    }
    stuff ||--o{ place : everything
    stuff {
        VARCHAR(50) everything
        DATE much
    }
    place ||--o{ perhaps : while
    place {
        DATE while
        TEXT able
        VARCHAR(50) region
    }