erDiagram
    never ||--o{ event : ready
    never {
        DATE ready
        TEXT cup
        VARCHAR(50) also
    }
    event ||--o{ eat : ever
    event {
        VARCHAR(50) ever
        DATE deep
    }
    eat ||--o{ if : test
    eat {
        DATE test
        TEXT stock
        VARCHAR(50) officer
    }
    if ||--o{ they : house
    if {
        VARCHAR(50) house
        DATE agree
    }
    they ||--o{ knowledge : behind
    they {
        DATE behind
        TEXT be
        VARCHAR(50) partner
    }
    knowledge ||--o{ section : game
    knowledge {
        VARCHAR(50) game
        DATE child
    }
    section ||--o{ only : decision
    section {
        DATE decision
        TEXT middle
        VARCHAR(50) would
    }
    only ||--o{ probably : leg
    only {
        VARCHAR(50) leg
        DATE rather
    }
    probably ||--o{ system : cause
    probably {
        DATE cause
        TEXT each
        VARCHAR(50) news
    }
    system ||--o{ fear : market
    system {
        VARCHAR(50) market
        DATE play
    }
    fear ||--o{ act : entire
    fear {
        DATE entire
        TEXT often
        VARCHAR(50) issue
    }
    act ||--o{ never : into
    act {
        VARCHAR(50) into
        DATE contain
    }