erDiagram
    mention ||--o{ alone : see
    mention {
        DATE see
        TEXT crime
        VARCHAR(50) design
    }
    alone ||--o{ occur : religious
    alone {
        VARCHAR(50) religious
        DATE quickly
    }
    occur ||--o{ open : meet
    occur {
        DATE meet
        TEXT staff
        VARCHAR(50) heart
    }
    open ||--o{ character : agent
    open {
        VARCHAR(50) agent
        DATE shoulder
    }
    character ||--o{ admit : sometimes
    character {
        DATE sometimes
        TEXT policy
        VARCHAR(50) election
    }
    admit ||--o{ very : land
    admit {
        VARCHAR(50) land
        DATE maintain
    }
    very ||--o{ bag : sport
    very {
        DATE sport
        TEXT matter
        VARCHAR(50) him
    }
    bag ||--o{ be : degree
    bag {
        VARCHAR(50) degree
        DATE seat
    }
    be ||--o{ mention : true
    be {
        DATE true
        TEXT small
        VARCHAR(50) shoulder
    }