erDiagram
    anything ||--o{ daughter : history
    anything {
        DATE history
        TEXT happy
        VARCHAR(50) measure
    }
    daughter ||--o{ boy : positive
    daughter {
        VARCHAR(50) positive
        DATE both
    }
    boy ||--o{ road : thank
    boy {
        DATE thank
        TEXT return
        VARCHAR(50) adult
    }
    road ||--o{ instead : rich
    road {
        VARCHAR(50) rich
        DATE want
    }
    instead ||--o{ method : concern
    instead {
        DATE concern
        TEXT such
        VARCHAR(50) north
    }
    method ||--o{ anything : cold
    method {
        VARCHAR(50) cold
        DATE establish
    }