erDiagram
    address ||--o{ skin : attack
    address {
        DATE attack
        TEXT new
        VARCHAR(50) mean
    }
    skin ||--o{ five : stop
    skin {
        VARCHAR(50) stop
        DATE debate
    }
    five ||--o{ certain : specific
    five {
        DATE specific
        TEXT decide
        VARCHAR(50) throughout
    }
    certain ||--o{ director : happen
    certain {
        VARCHAR(50) happen
        DATE young
    }
    director ||--o{ teach : help
    director {
        DATE help
        TEXT office
        VARCHAR(50) democratic
    }
    teach ||--o{ decision : particular
    teach {
        VARCHAR(50) particular
        DATE possible
    }
    decision ||--o{ address : page
    decision {
        DATE page
        TEXT foot
        VARCHAR(50) one
    }