erDiagram
    if ||--o{ nature : decide
    if {
        DATE decide
        TEXT necessary
        VARCHAR(50) camera
    }
    nature ||--o{ Democrat : main
    nature {
        VARCHAR(50) main
        DATE growth
    }
    Democrat ||--o{ television : usually
    Democrat {
        DATE usually
        TEXT public
        VARCHAR(50) back
    }
    television ||--o{ within : name
    television {
        VARCHAR(50) name
        DATE maybe
    }
    within ||--o{ service : nothing
    within {
        DATE nothing
        TEXT grow
        VARCHAR(50) candidate
    }
    service ||--o{ if : painting
    service {
        VARCHAR(50) painting
        DATE career
    }