erDiagram
    wish ||--o{ Mrs : cell
    wish {
        DATE cell
        TEXT his
        VARCHAR(50) movie
    }
    Mrs ||--o{ focus : fall
    Mrs {
        VARCHAR(50) fall
        DATE dream
    }
    focus ||--o{ recent : wall
    focus {
        DATE wall
        TEXT bar
        VARCHAR(50) fire
    }
    recent ||--o{ property : century
    recent {
        VARCHAR(50) century
        DATE save
    }
    property ||--o{ training : she
    property {
        DATE she
        TEXT job
        VARCHAR(50) themselves
    }
    training ||--o{ major : court
    training {
        VARCHAR(50) court
        DATE half
    }
    major ||--o{ drop : push
    major {
        DATE push
        TEXT let
        VARCHAR(50) professor
    }
    drop ||--o{ wish : network
    drop {
        VARCHAR(50) network
        DATE strategy
    }