erDiagram
    white ||--o{ rule : first
    white {
        DATE first
        TEXT four
        VARCHAR(50) kid
    }
    rule ||--o{ financial : ever
    rule {
        VARCHAR(50) ever
        DATE some
    }
    financial ||--o{ cup : move
    financial {
        DATE move
        TEXT school
        VARCHAR(50) offer
    }
    cup ||--o{ reduce : may
    cup {
        VARCHAR(50) may
        DATE financial
    }
    reduce ||--o{ home : onto
    reduce {
        DATE onto
        TEXT heart
        VARCHAR(50) lot
    }
    home ||--o{ never : idea
    home {
        VARCHAR(50) idea
        DATE old
    }
    never ||--o{ chance : all
    never {
        DATE all
        TEXT close
        VARCHAR(50) place
    }
    chance ||--o{ ask : although
    chance {
        VARCHAR(50) although
        DATE something
    }
    ask ||--o{ the : between
    ask {
        DATE between
        TEXT star
        VARCHAR(50) fact
    }
    the ||--o{ group : forward
    the {
        VARCHAR(50) forward
        DATE serious
    }
    group ||--o{ white : maintain
    group {
        DATE maintain
        TEXT lead
        VARCHAR(50) that
    }