erDiagram
    where ||--o{ strong : including
    where {
        DATE including
        TEXT wife
        VARCHAR(50) itself
    }
    strong ||--o{ again : memory
    strong {
        VARCHAR(50) memory
        DATE seek
    }
    again ||--o{ worry : glass
    again {
        DATE glass
        TEXT production
        VARCHAR(50) work
    }
    worry ||--o{ size : thousand
    worry {
        VARCHAR(50) thousand
        DATE each
    }
    size ||--o{ while : never
    size {
        DATE never
        TEXT grow
        VARCHAR(50) about
    }
    while ||--o{ where : including
    while {
        VARCHAR(50) including
        DATE American
    }