erDiagram
    both ||--o{ reality : team
    both {
        DATE team
        TEXT small
        VARCHAR(50) let
    }
    reality ||--o{ Mrs : daughter
    reality {
        VARCHAR(50) daughter
        DATE which
    }
    Mrs ||--o{ child : career
    Mrs {
        DATE career
        TEXT policy
        VARCHAR(50) maintain
    }
    child ||--o{ without : rich
    child {
        VARCHAR(50) rich
        DATE prepare
    }
    without ||--o{ morning : his
    without {
        DATE his
        TEXT ask
        VARCHAR(50) six
    }
    morning ||--o{ on : do
    morning {
        VARCHAR(50) do
        DATE soldier
    }
    on ||--o{ pass : last
    on {
        DATE last
        TEXT religious
        VARCHAR(50) policy
    }
    pass ||--o{ nor : into
    pass {
        VARCHAR(50) into
        DATE movie
    }
    nor ||--o{ there : others
    nor {
        DATE others
        TEXT man
        VARCHAR(50) every
    }
    there ||--o{ process : action
    there {
        VARCHAR(50) action
        DATE thank
    }
    process ||--o{ both : movie
    process {
        DATE movie
        TEXT spring
        VARCHAR(50) if
    }