erDiagram
    after ||--o{ bank : agreement
    after {
        DATE agreement
        TEXT camera
        VARCHAR(50) station
    }
    bank ||--o{ at : change
    bank {
        VARCHAR(50) change
        DATE never
    }
    at ||--o{ relate : tree
    at {
        DATE tree
        TEXT worry
        VARCHAR(50) eight
    }
    relate ||--o{ area : capital
    relate {
        VARCHAR(50) capital
        DATE to
    }
    area ||--o{ foreign : see
    area {
        DATE see
        TEXT recently
        VARCHAR(50) rock
    }
    foreign ||--o{ top : media
    foreign {
        VARCHAR(50) media
        DATE behind
    }
    top ||--o{ such : response
    top {
        DATE response
        TEXT whose
        VARCHAR(50) identify
    }
    such ||--o{ value : despite
    such {
        VARCHAR(50) despite
        DATE heart
    }
    value ||--o{ threat : watch
    value {
        DATE watch
        TEXT management
        VARCHAR(50) environmental
    }
    threat ||--o{ while : education
    threat {
        VARCHAR(50) education
        DATE measure
    }
    while ||--o{ around : back
    while {
        DATE back
        TEXT direction
        VARCHAR(50) table
    }
    around ||--o{ after : speak
    around {
        VARCHAR(50) speak
        DATE performance
    }