erDiagram
    value ||--o{ understand : wall
    value {
        DATE wall
        TEXT method
        VARCHAR(50) baby
    }
    understand ||--o{ impact : hope
    understand {
        VARCHAR(50) hope
        DATE teach
    }
    impact ||--o{ record : current
    impact {
        DATE current
        TEXT guy
        VARCHAR(50) hospital
    }
    record ||--o{ few : remain
    record {
        VARCHAR(50) remain
        DATE protect
    }
    few ||--o{ decade : laugh
    few {
        DATE laugh
        TEXT per
        VARCHAR(50) major
    }
    decade ||--o{ establish : result
    decade {
        VARCHAR(50) result
        DATE serve
    }
    establish ||--o{ trade : case
    establish {
        DATE case
        TEXT many
        VARCHAR(50) look
    }
    trade ||--o{ pressure : answer
    trade {
        VARCHAR(50) answer
        DATE suggest
    }
    pressure ||--o{ standard : tree
    pressure {
        DATE tree
        TEXT heart
        VARCHAR(50) possible
    }
    standard ||--o{ meet : develop
    standard {
        VARCHAR(50) develop
        DATE class
    }
    meet ||--o{ blue : for
    meet {
        DATE for
        TEXT bank
        VARCHAR(50) page
    }
    blue ||--o{ value : change
    blue {
        VARCHAR(50) change
        DATE maybe
    }