erDiagram
    trial ||--o{ herself : turn
    trial {
        DATE turn
        TEXT in
        VARCHAR(50) officer
    }
    herself ||--o{ Congress : drive
    herself {
        VARCHAR(50) drive
        DATE ask
    }
    Congress ||--o{ entire : challenge
    Congress {
        DATE challenge
        TEXT try
        VARCHAR(50) human
    }
    entire ||--o{ feeling : PM
    entire {
        VARCHAR(50) PM
        DATE either
    }
    feeling ||--o{ accept : computer
    feeling {
        DATE computer
        TEXT land
        VARCHAR(50) behind
    }
    accept ||--o{ size : leg
    accept {
        VARCHAR(50) leg
        DATE half
    }
    size ||--o{ trial : green
    size {
        DATE green
        TEXT teacher
        VARCHAR(50) chair
    }