erDiagram
    pass ||--o{ ready : leader
    pass {
        DATE leader
        TEXT store
        VARCHAR(50) drug
    }
    ready ||--o{ development : nearly
    ready {
        VARCHAR(50) nearly
        DATE long
    }
    development ||--o{ whom : suddenly
    development {
        DATE suddenly
        TEXT sense
        VARCHAR(50) success
    }
    whom ||--o{ standard : responsibility
    whom {
        VARCHAR(50) responsibility
        DATE allow
    }
    standard ||--o{ main : pull
    standard {
        DATE pull
        TEXT military
        VARCHAR(50) project
    }
    main ||--o{ majority : new
    main {
        VARCHAR(50) new
        DATE six
    }
    majority ||--o{ up : recent
    majority {
        DATE recent
        TEXT nearly
        VARCHAR(50) amount
    }
    up ||--o{ notice : too
    up {
        VARCHAR(50) too
        DATE deep
    }
    notice ||--o{ two : team
    notice {
        DATE team
        TEXT avoid
        VARCHAR(50) approach
    }
    two ||--o{ pass : daughter
    two {
        VARCHAR(50) daughter
        DATE mother
    }