erDiagram
    white ||--o{ behind : end
    white {
        DATE end
        TEXT rather
        VARCHAR(50) student
    }
    behind ||--o{ interview : fall
    behind {
        VARCHAR(50) fall
        DATE field
    }
    interview ||--o{ put : training
    interview {
        DATE training
        TEXT enough
        VARCHAR(50) agree
    }
    put ||--o{ woman : evening
    put {
        VARCHAR(50) evening
        DATE garden
    }
    woman ||--o{ purpose : thus
    woman {
        DATE thus
        TEXT international
        VARCHAR(50) body
    }
    purpose ||--o{ possible : reduce
    purpose {
        VARCHAR(50) reduce
        DATE continue
    }
    possible ||--o{ white : police
    possible {
        DATE police
        TEXT continue
        VARCHAR(50) control
    }