erDiagram
    forget ||--o{ mouth : might
    forget {
        DATE might
        TEXT share
        VARCHAR(50) order
    }
    mouth ||--o{ against : American
    mouth {
        VARCHAR(50) American
        DATE why
    }
    against ||--o{ hundred : child
    against {
        DATE child
        TEXT reality
        VARCHAR(50) you
    }
    hundred ||--o{ east : down
    hundred {
        VARCHAR(50) down
        DATE international
    }
    east ||--o{ part : oil
    east {
        DATE oil
        TEXT behind
        VARCHAR(50) attorney
    }
    part ||--o{ forget : foreign
    part {
        DATE special
    }