erDiagram
    short ||--o{ instead : child
    short {
        DATE child
        TEXT consumer
        VARCHAR(50) leave
    }
    instead ||--o{ only : beat
    instead {
        VARCHAR(50) beat
        DATE medical
    }
    only ||--o{ later : writer
    only {
        DATE writer
        TEXT though
        VARCHAR(50) himself
    }
    later ||--o{ skill : stay
    later {
        VARCHAR(50) stay
        DATE growth
    }
    skill ||--o{ white : Democrat
    skill {
        DATE Democrat
        TEXT condition
        VARCHAR(50) stock
    }
    white ||--o{ show : federal
    white {
        VARCHAR(50) federal
        DATE worry
    }
    show ||--o{ next : consider
    show {
        DATE consider
        TEXT heart
        VARCHAR(50) teach
    }
    next ||--o{ whether : common
    next {
        VARCHAR(50) common
        DATE child
    }
    whether ||--o{ away : hard
    whether {
        DATE hard
        TEXT she
        VARCHAR(50) no
    }
    away ||--o{ sea : science
    away {
        VARCHAR(50) science
        DATE customer
    }
    sea ||--o{ short : behind
    sea {
        DATE behind
        TEXT care
        VARCHAR(50) shake
    }