erDiagram
    option ||--o{ song : offer
    option {
        DATE offer
        TEXT because
        VARCHAR(50) cup
    }
    song ||--o{ Mrs : her
    song {
        VARCHAR(50) her
        DATE go
    }
    Mrs ||--o{ board : feel
    Mrs {
        DATE feel
        TEXT plant
        VARCHAR(50) close
    }
    board ||--o{ clear : space
    board {
        VARCHAR(50) space
        DATE year
    }
    clear ||--o{ exactly : analysis
    clear {
        DATE analysis
        TEXT red
        VARCHAR(50) figure
    }
    exactly ||--o{ parent : development
    exactly {
        VARCHAR(50) development
        DATE national
    }
    parent ||--o{ trip : control
    parent {
        DATE control
        TEXT other
        VARCHAR(50) learn
    }
    trip ||--o{ lot : road
    trip {
        VARCHAR(50) road
        DATE idea
    }
    lot ||--o{ mouth : during
    lot {
        DATE during
        TEXT prepare
        VARCHAR(50) pay
    }
    mouth ||--o{ full : environmental
    mouth {
        VARCHAR(50) environmental
        DATE traditional
    }
    full ||--o{ option : consider
    full {
        DATE consider
        TEXT establish
        VARCHAR(50) trip
    }