erDiagram
    bank ||--o{ radio : for
    bank {
        DATE for
        TEXT reality
        VARCHAR(50) view
    }
    radio ||--o{ enjoy : recent
    radio {
        VARCHAR(50) recent
        DATE address
    }
    enjoy ||--o{ our : chair
    enjoy {
        DATE chair
        TEXT mention
        VARCHAR(50) growth
    }
    our ||--o{ example : participant
    our {
        VARCHAR(50) participant
        DATE window
    }
    example ||--o{ foot : wind
    example {
        DATE wind
        TEXT as
        VARCHAR(50) new
    }
    foot ||--o{ most : employee
    foot {
        VARCHAR(50) employee
        DATE government
    }
    most ||--o{ check : cause
    most {
        DATE cause
        TEXT medical
        VARCHAR(50) special
    }
    check ||--o{ little : nice
    check {
        VARCHAR(50) nice
        DATE three
    }
    little ||--o{ bank : behavior
    little {
        DATE behavior
        TEXT letter
        VARCHAR(50) describe
    }