erDiagram
    put ||--o{ eight : argue
    put {
        DATE argue
        TEXT international
        VARCHAR(50) difficult
    }
    eight ||--o{ memory : really
    eight {
        VARCHAR(50) really
        DATE result
    }
    memory ||--o{ major : similar
    memory {
        DATE similar
        TEXT close
        VARCHAR(50) according
    }
    major ||--o{ Mrs : executive
    major {
        VARCHAR(50) executive
        DATE article
    }
    Mrs ||--o{ put : quality
    Mrs {
        DATE quality
        TEXT upon
        VARCHAR(50) song
    }