erDiagram
    within ||--o{ claim : close
    within {
        DATE close
        TEXT wind
        VARCHAR(50) two
    }
    claim ||--o{ Democrat : tree
    claim {
        VARCHAR(50) tree
        DATE effort
    }
    Democrat ||--o{ teacher : worker
    Democrat {
        DATE worker
        TEXT final
        VARCHAR(50) nation
    }
    teacher ||--o{ religious : cup
    teacher {
        VARCHAR(50) cup
        DATE total
    }
    religious ||--o{ join : plan
    religious {
        DATE plan
        TEXT population
        VARCHAR(50) say
    }
    join ||--o{ leg : song
    join {
        VARCHAR(50) song
        DATE structure
    }
    leg ||--o{ clearly : kitchen
    leg {
        DATE kitchen
        TEXT I
        VARCHAR(50) traditional
    }
    clearly ||--o{ within : size
    clearly {
        VARCHAR(50) size
        DATE natural
    }