erDiagram
    crime ||--o{ next : camera
    crime {
        DATE camera
        TEXT class
        VARCHAR(50) listen
    }
    next ||--o{ economic : indicate
    next {
        VARCHAR(50) indicate
        DATE including
    }
    economic ||--o{ hard : see
    economic {
        DATE see
        TEXT why
        VARCHAR(50) table
    }
    hard ||--o{ look : to
    hard {
        VARCHAR(50) to
        DATE nice
    }
    look ||--o{ final : position
    look {
        DATE position
        TEXT project
        VARCHAR(50) trouble
    }
    final ||--o{ follow : nature
    final {
        VARCHAR(50) nature
        DATE forget
    }
    follow ||--o{ crime : own
    follow {
        DATE own
        TEXT which
        VARCHAR(50) point
    }