erDiagram
    exist ||--o{ fast : development
    exist {
        DATE development
        TEXT win
        VARCHAR(50) too
    }
    fast ||--o{ effect : crime
    fast {
        VARCHAR(50) crime
        DATE foot
    }
    effect ||--o{ read : region
    effect {
        DATE region
        TEXT such
        VARCHAR(50) involve
    }
    read ||--o{ which : give
    read {
        VARCHAR(50) give
        DATE career
    }
    which ||--o{ up : election
    which {
        DATE election
        TEXT series
        VARCHAR(50) mention
    }
    up ||--o{ send : stock
    up {
        VARCHAR(50) stock
        DATE sister
    }
    send ||--o{ which : south
    send {
        DATE south
        TEXT best
        VARCHAR(50) save
    }
    which ||--o{ share : card
    which {
        VARCHAR(50) card
        DATE either
    }
    share ||--o{ remain : wind
    share {
        DATE wind
        TEXT around
        VARCHAR(50) institution
    }
    remain ||--o{ issue : bank
    remain {
        VARCHAR(50) bank
        DATE team
    }
    issue ||--o{ exist : set
    issue {
        DATE set
        TEXT family
        VARCHAR(50) cause
    }