erDiagram
    position ||--o{ machine : miss
    position {
        DATE miss
        TEXT time
        VARCHAR(50) traditional
    }
    machine ||--o{ line : stop
    machine {
        VARCHAR(50) stop
        DATE black
    }
    line ||--o{ school : deep
    line {
        DATE deep
        TEXT here
        VARCHAR(50) build
    }
    school ||--o{ suddenly : board
    school {
        VARCHAR(50) board
        DATE firm
    }
    suddenly ||--o{ friend : organization
    suddenly {
        DATE organization
        TEXT each
        VARCHAR(50) clear
    }
    friend ||--o{ prepare : benefit
    friend {
        VARCHAR(50) benefit
        DATE now
    }
    prepare ||--o{ fill : body
    prepare {
        DATE body
        TEXT during
        VARCHAR(50) number
    }
    fill ||--o{ name : decide
    fill {
        VARCHAR(50) decide
        DATE side
    }
    name ||--o{ difficult : beautiful
    name {
        DATE beautiful
        TEXT mention
        VARCHAR(50) value
    }
    difficult ||--o{ position : point
    difficult {
        VARCHAR(50) point
        DATE scene
    }