erDiagram
    still ||--o{ head : generation
    still {
        DATE generation
        TEXT must
        VARCHAR(50) simply
    }
    head ||--o{ short : easy
    head {
        VARCHAR(50) easy
        DATE almost
    }
    short ||--o{ together : produce
    short {
        DATE produce
        TEXT senior
        VARCHAR(50) reach
    }
    together ||--o{ six : car
    together {
        VARCHAR(50) car
        DATE thing
    }
    six ||--o{ still : audience
    six {
        DATE audience
        TEXT war
        VARCHAR(50) pay
    }