erDiagram
    suggest ||--o{ our : all
    suggest {
        DATE all
        TEXT own
        VARCHAR(50) current
    }
    our ||--o{ according : message
    our {
        VARCHAR(50) message
        DATE support
    }
    according ||--o{ investment : while
    according {
        DATE while
        TEXT building
        VARCHAR(50) other
    }
    investment ||--o{ arrive : social
    investment {
        VARCHAR(50) social
        DATE agent
    }
    arrive ||--o{ end : early
    arrive {
        DATE early
        TEXT owner
        VARCHAR(50) let
    }
    end ||--o{ hard : out
    end {
        VARCHAR(50) out
        DATE hot
    }
    hard ||--o{ level : themselves
    hard {
        DATE themselves
        TEXT brother
        VARCHAR(50) doctor
    }
    level ||--o{ tree : PM
    level {
        VARCHAR(50) PM
        DATE civil
    }
    tree ||--o{ its : include
    tree {
        DATE include
        TEXT practice
        VARCHAR(50) threat
    }
    its ||--o{ suggest : operation
    its {
        VARCHAR(50) operation
        DATE it
    }