erDiagram
    decide ||--o{ professional : market
    decide {
        DATE market
        TEXT wish
        VARCHAR(50) someone
    }
    professional ||--o{ mouth : hold
    professional {
        VARCHAR(50) hold
        DATE sort
    }
    mouth ||--o{ cold : base
    mouth {
        DATE base
        TEXT level
        VARCHAR(50) blood
    }
    cold ||--o{ individual : rich
    cold {
        VARCHAR(50) rich
        DATE discuss
    }
    individual ||--o{ decide : anything
    individual {
        DATE anything
        TEXT create
        VARCHAR(50) discuss
    }