erDiagram
    despite ||--o{ performance : image
    despite {
        DATE image
        TEXT may
        VARCHAR(50) continue
    }
    performance ||--o{ relate : identify
    performance {
        VARCHAR(50) identify
        DATE six
    }
    relate ||--o{ use : interesting
    relate {
        DATE interesting
        TEXT court
        VARCHAR(50) customer
    }
    use ||--o{ alone : evidence
    use {
        VARCHAR(50) evidence
        DATE over
    }
    alone ||--o{ responsibility : now
    alone {
        DATE now
        TEXT past
        VARCHAR(50) former
    }
    responsibility ||--o{ hospital : surface
    responsibility {
        VARCHAR(50) surface
        DATE senior
    }
    hospital ||--o{ eat : short
    hospital {
        DATE short
        TEXT there
        VARCHAR(50) popular
    }
    eat ||--o{ try : plant
    eat {
        VARCHAR(50) plant
        DATE start
    }
    try ||--o{ despite : leave
    try {
        DATE leave
        TEXT pull
        VARCHAR(50) reach
    }