erDiagram
    former ||--o{ represent : that
    former {
        DATE that
        TEXT message
        VARCHAR(50) entire
    }
    represent ||--o{ write : financial
    represent {
        VARCHAR(50) financial
        DATE lead
    }
    write ||--o{ statement : policy
    write {
        DATE policy
        TEXT single
        VARCHAR(50) attorney
    }
    statement ||--o{ tell : happen
    statement {
        VARCHAR(50) happen
        DATE beyond
    }
    tell ||--o{ former : sea
    tell {
        DATE sea
        TEXT ball
        VARCHAR(50) vote
    }