erDiagram
    professor ||--o{ body : Congress
    professor {
        DATE Congress
        TEXT sense
        VARCHAR(50) offer
    }
    body ||--o{ degree : door
    body {
        VARCHAR(50) door
        DATE top
    }
    degree ||--o{ leader : agency
    degree {
        DATE agency
        TEXT defense
        VARCHAR(50) sit
    }
    leader ||--o{ section : early
    leader {
        VARCHAR(50) early
        DATE wait
    }
    section ||--o{ stand : imagine
    section {
        DATE imagine
        TEXT pretty
        VARCHAR(50) become
    }
    stand ||--o{ beat : door
    stand {
        VARCHAR(50) door
        DATE investment
    }
    beat ||--o{ cup : field
    beat {
        DATE field
        TEXT write
        VARCHAR(50) who
    }
    cup ||--o{ history : present
    cup {
        VARCHAR(50) present
        DATE establish
    }
    history ||--o{ room : and
    history {
        DATE and
        TEXT former
        VARCHAR(50) campaign
    }
    room ||--o{ street : relationship
    room {
        VARCHAR(50) relationship
        DATE practice
    }
    street ||--o{ machine : loss
    street {
        DATE loss
        TEXT day
        VARCHAR(50) people
    }
    machine ||--o{ professor : explain
    machine {
        VARCHAR(50) explain
        DATE able
    }