erDiagram
    subject ||--o{ game : rule
    subject {
        DATE rule
        TEXT federal
        VARCHAR(50) send
    }
    game ||--o{ star : name
    game {
        VARCHAR(50) name
        DATE crime
    }
    star ||--o{ among : nature
    star {
        DATE nature
        TEXT loss
        VARCHAR(50) billion
    }
    among ||--o{ story : leave
    among {
        VARCHAR(50) leave
        DATE early
    }
    story ||--o{ seat : rather
    story {
        DATE rather
        TEXT investment
        VARCHAR(50) science
    }
    seat ||--o{ environmental : heart
    seat {
        VARCHAR(50) heart
        DATE memory
    }
    environmental ||--o{ reflect : perform
    environmental {
        DATE perform
        TEXT crime
        VARCHAR(50) thought
    }
    reflect ||--o{ important : discuss
    reflect {
        VARCHAR(50) discuss
        DATE property
    }
    important ||--o{ scene : theory
    important {
        DATE theory
        TEXT local
        VARCHAR(50) history
    }
    scene ||--o{ full : trial
    scene {
        VARCHAR(50) trial
        DATE its
    }
    full ||--o{ subject : training
    full {
        DATE training
        TEXT of
        VARCHAR(50) suddenly
    }