erDiagram
    exactly ||--o{ become : us
    exactly {
        DATE us
        TEXT white
        VARCHAR(50) among
    }
    become ||--o{ pick : lose
    become {
        VARCHAR(50) lose
        DATE something
    }
    pick ||--o{ attack : yard
    pick {
        DATE yard
        TEXT sell
        VARCHAR(50) not
    }
    attack ||--o{ example : Congress
    attack {
        VARCHAR(50) Congress
        DATE close
    }
    example ||--o{ land : join
    example {
        DATE join
        TEXT learn
        VARCHAR(50) southern
    }
    land ||--o{ goal : picture
    land {
        VARCHAR(50) picture
        DATE or
    }
    goal ||--o{ sit : quite
    goal {
        DATE quite
        TEXT arm
        VARCHAR(50) agreement
    }
    sit ||--o{ explain : wind
    sit {
        VARCHAR(50) wind
        DATE push
    }
    explain ||--o{ become : find
    explain {
        DATE find
        TEXT without
        VARCHAR(50) not
    }
    become ||--o{ market : present
    become {
        VARCHAR(50) present
        DATE fall
    }
    market ||--o{ exactly : specific
    market {
        DATE specific
        TEXT former
        VARCHAR(50) environment
    }