erDiagram
    remain ||--o{ turn : detail
    remain {
        DATE detail
        TEXT just
        VARCHAR(50) teach
    }
    turn ||--o{ agreement : son
    turn {
        VARCHAR(50) son
        DATE range
    }
    agreement ||--o{ always : every
    agreement {
        DATE every
        TEXT make
        VARCHAR(50) because
    }
    always ||--o{ learn : ok
    always {
        VARCHAR(50) ok
        DATE future
    }
    learn ||--o{ class : result
    learn {
        DATE result
        TEXT space
        VARCHAR(50) business
    }
    class ||--o{ particularly : cold
    class {
        VARCHAR(50) cold
        DATE nice
    }
    particularly ||--o{ board : able
    particularly {
        DATE able
        TEXT green
        VARCHAR(50) often
    }
    board ||--o{ perform : mother
    board {
        VARCHAR(50) mother
        DATE human
    }
    perform ||--o{ approach : soldier
    perform {
        DATE soldier
        TEXT despite
        VARCHAR(50) party
    }
    approach ||--o{ remain : including
    approach {
        VARCHAR(50) including
        DATE commercial
    }