erDiagram
    continue ||--o{ fill : article
    continue {
        DATE article
        TEXT into
        VARCHAR(50) white
    }
    fill ||--o{ under : happen
    fill {
        VARCHAR(50) happen
        DATE full
    }
    under ||--o{ system : training
    under {
        DATE training
        TEXT off
        VARCHAR(50) use
    }
    system ||--o{ major : outside
    system {
        VARCHAR(50) outside
        DATE maybe
    }
    major ||--o{ candidate : about
    major {
        DATE about
        TEXT laugh
        VARCHAR(50) then
    }
    candidate ||--o{ development : professional
    candidate {
        VARCHAR(50) professional
        DATE sometimes
    }
    development ||--o{ happen : once
    development {
        DATE once
        TEXT simple
        VARCHAR(50) involve
    }
    happen ||--o{ left : girl
    happen {
        VARCHAR(50) girl
        DATE save
    }
    left ||--o{ professional : radio
    left {
        DATE radio
        TEXT attention
        VARCHAR(50) wind
    }
    professional ||--o{ continue : choose
    professional {
        VARCHAR(50) choose
        DATE either
    }