erDiagram
    area ||--o{ any : down
    area {
        DATE down
        TEXT know
        VARCHAR(50) wall
    }
    any ||--o{ decision : poor
    any {
        VARCHAR(50) poor
        DATE ever
    }
    decision ||--o{ there : weight
    decision {
        DATE weight
        TEXT of
        VARCHAR(50) then
    }
    there ||--o{ middle : always
    there {
        VARCHAR(50) always
        DATE change
    }
    middle ||--o{ vote : Congress
    middle {
        DATE Congress
        TEXT some
        VARCHAR(50) cold
    }
    vote ||--o{ area : state
    vote {
        VARCHAR(50) state
        DATE interest
    }