erDiagram
    manage ||--o{ either : play
    manage {
        DATE play
        TEXT human
        VARCHAR(50) city
    }
    either ||--o{ model : ever
    either {
        VARCHAR(50) ever
        DATE those
    }
    model ||--o{ church : power
    model {
        DATE power
        TEXT fire
        VARCHAR(50) production
    }
    church ||--o{ medical : establish
    church {
        VARCHAR(50) establish
        DATE to
    }
    medical ||--o{ government : camera
    medical {
        DATE camera
        TEXT character
        VARCHAR(50) him
    }
    government ||--o{ next : pattern
    government {
        VARCHAR(50) pattern
        DATE throughout
    }
    next ||--o{ land : lay
    next {
        DATE lay
        TEXT begin
        VARCHAR(50) there
    }
    land ||--o{ describe : religious
    land {
        VARCHAR(50) religious
        DATE language
    }
    describe ||--o{ soon : figure
    describe {
        DATE figure
        TEXT positive
        VARCHAR(50) party
    }
    soon ||--o{ anything : employee
    soon {
        VARCHAR(50) employee
        DATE a
    }
    anything ||--o{ choose : role
    anything {
        DATE role
        TEXT seven
        VARCHAR(50) customer
    }
    choose ||--o{ manage : provide
    choose {
        VARCHAR(50) provide
        DATE other
    }