erDiagram
    enjoy ||--o{ second : financial
    enjoy {
        DATE financial
        TEXT walk
        VARCHAR(50) create
    }
    second ||--o{ eat : choice
    second {
        VARCHAR(50) choice
        DATE describe
    }
    eat ||--o{ garden : last
    eat {
        DATE last
        TEXT beautiful
        VARCHAR(50) dinner
    }
    garden ||--o{ order : right
    garden {
        VARCHAR(50) right
        DATE kitchen
    }
    order ||--o{ some : tough
    order {
        DATE tough
        TEXT war
        VARCHAR(50) little
    }
    some ||--o{ subject : compare
    some {
        VARCHAR(50) compare
        DATE respond
    }
    subject ||--o{ nature : water
    subject {
        DATE water
        TEXT teach
        VARCHAR(50) soon
    }
    nature ||--o{ commercial : push
    nature {
        VARCHAR(50) push
        DATE billion
    }
    commercial ||--o{ particular : station
    commercial {
        DATE station
        TEXT young
        VARCHAR(50) as
    }
    particular ||--o{ large : game
    particular {
        VARCHAR(50) game
        DATE perform
    }
    large ||--o{ note : particularly
    large {
        DATE particularly
        TEXT party
        VARCHAR(50) source
    }
    note ||--o{ enjoy : issue
    note {
        VARCHAR(50) issue
        DATE stand
    }