erDiagram
    company ||--o{ something : many
    company {
        DATE many
        TEXT poor
        VARCHAR(50) beat
    }
    something ||--o{ return : factor
    something {
        VARCHAR(50) factor
        DATE support
    }
    return ||--o{ campaign : forget
    return {
        DATE forget
        TEXT issue
        VARCHAR(50) theory
    }
    campaign ||--o{ bad : camera
    campaign {
        VARCHAR(50) camera
        DATE team
    }
    bad ||--o{ rich : will
    bad {
        DATE will
        TEXT out
        VARCHAR(50) government
    }
    rich ||--o{ early : paper
    rich {
        VARCHAR(50) paper
        DATE person
    }
    early ||--o{ company : design
    early {
        DATE design
        TEXT executive
        VARCHAR(50) try
    }