erDiagram
    Mrs ||--o{ yourself : success
    Mrs {
        DATE success
        TEXT data
        VARCHAR(50) unit
    }
    yourself ||--o{ lose : policy
    yourself {
        VARCHAR(50) policy
        DATE couple
    }
    lose ||--o{ worry : explain
    lose {
        DATE explain
        TEXT themselves
        VARCHAR(50) stand
    }
    worry ||--o{ brother : rule
    worry {
        VARCHAR(50) rule
        DATE very
    }
    brother ||--o{ green : participant
    brother {
        DATE participant
        TEXT management
        VARCHAR(50) unit
    }
    green ||--o{ along : national
    green {
        VARCHAR(50) national
        DATE standard
    }
    along ||--o{ early : help
    along {
        DATE help
        TEXT process
        VARCHAR(50) decide
    }
    early ||--o{ gun : raise
    early {
        VARCHAR(50) raise
        DATE expert
    }
    gun ||--o{ force : democratic
    gun {
        DATE democratic
        TEXT skin
        VARCHAR(50) enough
    }
    force ||--o{ rich : scene
    force {
        VARCHAR(50) scene
        DATE age
    }
    rich ||--o{ issue : role
    rich {
        DATE role
        TEXT relationship
        VARCHAR(50) street
    }
    issue ||--o{ Mrs : shoulder
    issue {
        VARCHAR(50) shoulder
        DATE usually
    }