erDiagram
    speak ||--o{ treatment : maybe
    speak {
        DATE maybe
        TEXT determine
        VARCHAR(50) something
    }
    treatment ||--o{ guess : kid
    treatment {
        VARCHAR(50) kid
        DATE six
    }
    guess ||--o{ skin : movie
    guess {
        DATE movie
        TEXT produce
        VARCHAR(50) share
    }
    skin ||--o{ attack : strategy
    skin {
        VARCHAR(50) strategy
        DATE attack
    }
    attack ||--o{ call : away
    attack {
        DATE away
        TEXT left
        VARCHAR(50) think
    }
    call ||--o{ police : benefit
    call {
        VARCHAR(50) benefit
        DATE something
    }
    police ||--o{ story : writer
    police {
        DATE writer
        TEXT money
        VARCHAR(50) stop
    }
    story ||--o{ environment : finish
    story {
        VARCHAR(50) finish
        DATE agreement
    }
    environment ||--o{ speak : friend
    environment {
        DATE friend
        TEXT here
        VARCHAR(50) record
    }