erDiagram
    send ||--o{ after : factor
    send {
        DATE factor
        TEXT face
        VARCHAR(50) step
    }
    after ||--o{ half : necessary
    after {
        VARCHAR(50) necessary
        DATE attorney
    }
    half ||--o{ class : happy
    half {
        DATE happy
        TEXT sign
        VARCHAR(50) model
    }
    class ||--o{ few : mission
    class {
        VARCHAR(50) mission
        DATE deal
    }
    few ||--o{ send : attack
    few {
        DATE attack
        TEXT paper
        VARCHAR(50) bank
    }