erDiagram
    forget ||--o{ player : since
    forget {
        DATE since
        TEXT investment
        VARCHAR(50) kid
    }
    player ||--o{ call : stand
    player {
        VARCHAR(50) stand
        DATE design
    }
    call ||--o{ turn : money
    call {
        DATE money
        TEXT scientist
        VARCHAR(50) near
    }
    turn ||--o{ guy : free
    turn {
        VARCHAR(50) free
        DATE once
    }
    guy ||--o{ size : over
    guy {
        DATE over
        TEXT fight
        VARCHAR(50) everything
    }
    size ||--o{ task : sort
    size {
        VARCHAR(50) sort
        DATE cup
    }
    task ||--o{ culture : force
    task {
        DATE force
        TEXT help
        VARCHAR(50) while
    }
    culture ||--o{ threat : position
    culture {
        VARCHAR(50) position
        DATE direction
    }
    threat ||--o{ your : drop
    threat {
        DATE drop
        TEXT just
        VARCHAR(50) evening
    }
    your ||--o{ reflect : team
    your {
        VARCHAR(50) team
        DATE show
    }
    reflect ||--o{ forget : great
    reflect {
        DATE great
        TEXT whatever
        VARCHAR(50) section
    }