erDiagram
    half ||--o{ task : water
    half {
        DATE water
        TEXT prove
        VARCHAR(50) trade
    }
    task ||--o{ investment : audience
    task {
        VARCHAR(50) audience
        DATE design
    }
    investment ||--o{ hope : quickly
    investment {
        DATE quickly
        TEXT through
        VARCHAR(50) start
    }
    hope ||--o{ degree : father
    hope {
        VARCHAR(50) father
        DATE real
    }
    degree ||--o{ simply : positive
    degree {
        DATE positive
        TEXT physical
        VARCHAR(50) sister
    }
    simply ||--o{ good : hold
    simply {
        VARCHAR(50) hold
        DATE voice
    }
    good ||--o{ half : Mrs
    good {
        DATE Mrs
        TEXT participant
        VARCHAR(50) this
    }