erDiagram
    only ||--o{ Mr : term
    only {
        DATE term
        TEXT when
        VARCHAR(50) reveal
    }
    Mr ||--o{ different : oil
    Mr {
        VARCHAR(50) oil
        DATE prevent
    }
    different ||--o{ old : audience
    different {
        DATE audience
        TEXT dinner
        VARCHAR(50) forget
    }
    old ||--o{ type : official
    old {
        VARCHAR(50) official
        DATE our
    }
    type ||--o{ subject : single
    type {
        DATE single
        TEXT rich
        VARCHAR(50) debate
    }
    subject ||--o{ head : myself
    subject {
        VARCHAR(50) myself
        DATE himself
    }
    head ||--o{ where : health
    head {
        DATE health
        TEXT position
        VARCHAR(50) according
    }
    where ||--o{ different : continue
    where {
        VARCHAR(50) continue
        DATE enter
    }
    different ||--o{ far : couple
    different {
        DATE couple
        TEXT throughout
        VARCHAR(50) matter
    }
    far ||--o{ only : television
    far {
        VARCHAR(50) television
        DATE suggest
    }