erDiagram
    measure ||--o{ sea : knowledge
    measure {
        DATE knowledge
        TEXT Republican
        VARCHAR(50) practice
    }
    sea ||--o{ center : late
    sea {
        VARCHAR(50) late
        DATE power
    }
    center ||--o{ leader : trip
    center {
        DATE trip
        TEXT team
        VARCHAR(50) require
    }
    leader ||--o{ painting : key
    leader {
        VARCHAR(50) key
        DATE radio
    }
    painting ||--o{ very : week
    painting {
        DATE week
        TEXT them
        VARCHAR(50) usually
    }
    very ||--o{ true : fact
    very {
        VARCHAR(50) fact
        DATE former
    }
    true ||--o{ skill : ahead
    true {
        DATE ahead
        TEXT similar
        VARCHAR(50) career
    }
    skill ||--o{ American : foreign
    skill {
        DATE almost
    }
    American ||--o{ defense : focus
    American {
        DATE focus
        TEXT build
        VARCHAR(50) four
    }
    defense ||--o{ account : deal
    defense {
        VARCHAR(50) deal
        DATE science
    }
    account ||--o{ measure : term
    account {
        DATE term
        TEXT body
        VARCHAR(50) theory
    }