erDiagram
    whatever ||--o{ past : view
    whatever {
        DATE view
        TEXT out
        VARCHAR(50) medical
    }
    past ||--o{ arrive : key
    past {
        VARCHAR(50) key
        DATE government
    }
    arrive ||--o{ work : stay
    arrive {
        DATE stay
        TEXT important
        VARCHAR(50) ago
    }
    work ||--o{ not : type
    work {
        VARCHAR(50) type
        DATE official
    }
    not ||--o{ effort : specific
    not {
        DATE specific
        TEXT enjoy
        VARCHAR(50) nearly
    }
    effort ||--o{ popular : eat
    effort {
        VARCHAR(50) eat
        DATE around
    }
    popular ||--o{ place : whole
    popular {
        DATE whole
        TEXT budget
        VARCHAR(50) cause
    }
    place ||--o{ improve : cell
    place {
        VARCHAR(50) cell
        DATE chance
    }
    improve ||--o{ into : alone
    improve {
        DATE alone
        TEXT catch
        VARCHAR(50) trial
    }
    into ||--o{ whatever : protect
    into {
        VARCHAR(50) protect
        DATE spring
    }