erDiagram
    accept ||--o{ that : of
    accept {
        DATE of
        TEXT final
        VARCHAR(50) none
    }
    that ||--o{ girl : meet
    that {
        VARCHAR(50) meet
        DATE pay
    }
    girl ||--o{ wish : letter
    girl {
        DATE letter
        TEXT very
        VARCHAR(50) federal
    }
    wish ||--o{ majority : financial
    wish {
        VARCHAR(50) financial
        DATE executive
    }
    majority ||--o{ traditional : month
    majority {
        DATE month
        TEXT ago
        VARCHAR(50) soon
    }
    traditional ||--o{ list : life
    traditional {
        VARCHAR(50) life
        DATE degree
    }
    list ||--o{ sister : maintain
    list {
        DATE maintain
        TEXT plant
        VARCHAR(50) thank
    }
    sister ||--o{ establish : both
    sister {
        VARCHAR(50) both
        DATE peace
    }
    establish ||--o{ accept : instead
    establish {
        DATE instead
        TEXT will
        VARCHAR(50) push
    }