erDiagram
    general ||--o{ by : respond
    general {
        DATE respond
        TEXT ever
        VARCHAR(50) born
    }
    by ||--o{ herself : father
    by {
        VARCHAR(50) father
        DATE why
    }
    herself ||--o{ or : build
    herself {
        DATE build
        TEXT contain
        VARCHAR(50) food
    }
    or ||--o{ social : spend
    or {
        VARCHAR(50) spend
        DATE student
    }
    social ||--o{ number : upon
    social {
        DATE upon
        TEXT professional
        VARCHAR(50) line
    }
    number ||--o{ anyone : yet
    number {
        VARCHAR(50) yet
        DATE challenge
    }
    anyone ||--o{ establish : across
    anyone {
        DATE across
        TEXT war
        VARCHAR(50) quite
    }
    establish ||--o{ among : similar
    establish {
        VARCHAR(50) similar
        DATE air
    }
    among ||--o{ unit : small
    among {
        DATE small
        TEXT particularly
        VARCHAR(50) type
    }
    unit ||--o{ drive : official
    unit {
        VARCHAR(50) official
        DATE compare
    }
    drive ||--o{ nothing : glass
    drive {
        DATE glass
        TEXT almost
        VARCHAR(50) blood
    }
    nothing ||--o{ general : sister
    nothing {
        VARCHAR(50) sister
        DATE employee
    }