erDiagram
    local ||--o{ remain : agreement
    local {
        DATE agreement
        TEXT whose
        VARCHAR(50) none
    }
    remain ||--o{ they : become
    remain {
        VARCHAR(50) become
        DATE themselves
    }
    they ||--o{ away : later
    they {
        DATE later
        TEXT listen
        VARCHAR(50) picture
    }
    away ||--o{ wish : market
    away {
        VARCHAR(50) market
        DATE structure
    }
    wish ||--o{ vote : day
    wish {
        DATE day
        TEXT fight
        VARCHAR(50) drop
    }
    vote ||--o{ truth : only
    vote {
        VARCHAR(50) only
        DATE man
    }
    truth ||--o{ help : side
    truth {
        DATE side
        TEXT must
        VARCHAR(50) teach
    }
    help ||--o{ very : others
    help {
        VARCHAR(50) others
        DATE much
    }
    very ||--o{ available : office
    very {
        DATE office
        TEXT manage
        VARCHAR(50) notice
    }
    available ||--o{ local : it
    available {
        VARCHAR(50) it
        DATE watch
    }