erDiagram
    month ||--o{ final : benefit
    month {
        DATE benefit
        TEXT seven
        VARCHAR(50) surface
    }
    final ||--o{ pressure : certainly
    final {
        VARCHAR(50) certainly
        DATE read
    }
    pressure ||--o{ partner : little
    pressure {
        DATE little
        TEXT know
        VARCHAR(50) song
    }
    partner ||--o{ according : standard
    partner {
        VARCHAR(50) standard
        DATE poor
    }
    according ||--o{ month : executive
    according {
        DATE executive
        TEXT key
        VARCHAR(50) present
    }