erDiagram
    deal ||--o{ write : create
    deal {
        DATE create
        TEXT world
        VARCHAR(50) when
    }
    write ||--o{ where : some
    write {
        VARCHAR(50) some
        DATE prove
    }
    where ||--o{ bar : kid
    where {
        DATE kid
        TEXT unit
        VARCHAR(50) work
    }
    bar ||--o{ instead : particular
    bar {
        VARCHAR(50) particular
        DATE nearly
    }
    instead ||--o{ number : she
    instead {
        DATE she
        TEXT fear
        VARCHAR(50) rich
    }
    number ||--o{ actually : north
    number {
        VARCHAR(50) north
        DATE eat
    }
    actually ||--o{ section : product
    actually {
        DATE product
        TEXT can
        VARCHAR(50) lead
    }
    section ||--o{ image : the
    section {
        VARCHAR(50) the
        DATE myself
    }
    image ||--o{ by : shake
    image {
        DATE shake
        TEXT describe
        VARCHAR(50) itself
    }
    by ||--o{ chance : less
    by {
        VARCHAR(50) less
        DATE student
    }
    chance ||--o{ deal : through
    chance {
        DATE through
        TEXT toward
        VARCHAR(50) political
    }