erDiagram
    wear ||--o{ always : also
    wear {
        DATE also
        TEXT suddenly
        VARCHAR(50) interesting
    }
    always ||--o{ environmental : probably
    always {
        VARCHAR(50) probably
        DATE almost
    }
    environmental ||--o{ evidence : town
    environmental {
        DATE town
        TEXT manage
        VARCHAR(50) little
    }
    evidence ||--o{ every : speech
    evidence {
        VARCHAR(50) speech
        DATE eat
    }
    every ||--o{ wear : office
    every {
        DATE office
        TEXT real
        VARCHAR(50) significant
    }