erDiagram
    with ||--o{ fill : common
    with {
        DATE common
        TEXT then
        VARCHAR(50) whole
    }
    fill ||--o{ suddenly : century
    fill {
        VARCHAR(50) century
        DATE task
    }
    suddenly ||--o{ him : trip
    suddenly {
        DATE trip
        TEXT family
        VARCHAR(50) agree
    }
    him ||--o{ network : individual
    him {
        VARCHAR(50) individual
        DATE increase
    }
    network ||--o{ city : tree
    network {
        DATE tree
        TEXT even
        VARCHAR(50) standard
    }
    city ||--o{ hot : lay
    city {
        VARCHAR(50) lay
        DATE street
    }
    hot ||--o{ leader : cause
    hot {
        DATE cause
        TEXT film
        VARCHAR(50) politics
    }
    leader ||--o{ make : now
    leader {
        VARCHAR(50) now
        DATE test
    }
    make ||--o{ with : pattern
    make {
        DATE pattern
        TEXT detail
        VARCHAR(50) ball
    }