erDiagram
    sort ||--o{ full : film
    sort {
        DATE film
        TEXT blood
        VARCHAR(50) east
    }
    full ||--o{ possible : trouble
    full {
        VARCHAR(50) trouble
        DATE industry
    }
    possible ||--o{ wait : its
    possible {
        DATE its
        TEXT impact
        VARCHAR(50) rate
    }
    wait ||--o{ daughter : career
    wait {
        VARCHAR(50) career
        DATE air
    }
    daughter ||--o{ president : his
    daughter {
        DATE his
        TEXT tonight
        VARCHAR(50) again
    }
    president ||--o{ budget : generation
    president {
        VARCHAR(50) generation
        DATE idea
    }
    budget ||--o{ explain : maintain
    budget {
        DATE maintain
        TEXT government
        VARCHAR(50) charge
    }
    explain ||--o{ quickly : back
    explain {
        VARCHAR(50) back
        DATE different
    }
    quickly ||--o{ president : hair
    quickly {
        DATE hair
        TEXT necessary
        VARCHAR(50) pull
    }
    president ||--o{ hope : goal
    president {
        VARCHAR(50) goal
        DATE continue
    }
    hope ||--o{ sort : night
    hope {
        DATE night
        TEXT very
        VARCHAR(50) difference
    }