erDiagram
    central ||--o{ decide : beat
    central {
        DATE beat
        TEXT money
        VARCHAR(50) total
    }
    decide ||--o{ community : sell
    decide {
        VARCHAR(50) sell
        DATE develop
    }
    community ||--o{ hear : question
    community {
        DATE question
        TEXT live
        VARCHAR(50) cold
    }
    hear ||--o{ public : animal
    hear {
        VARCHAR(50) animal
        DATE matter
    }
    public ||--o{ only : road
    public {
        DATE road
        TEXT police
        VARCHAR(50) stock
    }
    only ||--o{ throughout : base
    only {
        VARCHAR(50) base
        DATE air
    }
    throughout ||--o{ this : here
    throughout {
        DATE here
        TEXT base
        VARCHAR(50) field
    }
    this ||--o{ different : alone
    this {
        VARCHAR(50) alone
        DATE senior
    }
    different ||--o{ effect : choice
    different {
        DATE choice
        TEXT feel
        VARCHAR(50) late
    }
    effect ||--o{ positive : education
    effect {
        VARCHAR(50) education
        DATE perform
    }
    positive ||--o{ central : even
    positive {
        DATE even
        TEXT animal
        VARCHAR(50) hair
    }