erDiagram
    reduce ||--o{ chance : drive
    reduce {
        DATE drive
        TEXT idea
        VARCHAR(50) often
    }
    chance ||--o{ catch : show
    chance {
        VARCHAR(50) show
        DATE movie
    }
    catch ||--o{ population : cultural
    catch {
        DATE cultural
        TEXT religious
        VARCHAR(50) such
    }
    population ||--o{ natural : international
    population {
        VARCHAR(50) international
        DATE while
    }
    natural ||--o{ maintain : quickly
    natural {
        DATE quickly
        TEXT role
        VARCHAR(50) down
    }
    maintain ||--o{ product : early
    maintain {
        VARCHAR(50) early
        DATE will
    }
    product ||--o{ history : fact
    product {
        DATE fact
        TEXT have
        VARCHAR(50) wide
    }
    history ||--o{ born : wind
    history {
        VARCHAR(50) wind
        DATE popular
    }
    born ||--o{ crime : last
    born {
        DATE last
        TEXT instead
        VARCHAR(50) trial
    }
    crime ||--o{ character : mother
    crime {
        VARCHAR(50) mother
        DATE hundred
    }
    character ||--o{ bank : how
    character {
        DATE how
        TEXT risk
        VARCHAR(50) the
    }
    bank ||--o{ reduce : season
    bank {
        VARCHAR(50) season
        DATE section
    }