erDiagram
    drive ||--o{ audience : success
    drive {
        DATE success
        TEXT physical
        VARCHAR(50) bag
    }
    audience ||--o{ better : race
    audience {
        VARCHAR(50) race
        DATE short
    }
    better ||--o{ hit : per
    better {
        DATE per
        TEXT mouth
        VARCHAR(50) month
    }
    hit ||--o{ laugh : beyond
    hit {
        VARCHAR(50) beyond
        DATE should
    }
    laugh ||--o{ bank : public
    laugh {
        DATE public
        TEXT all
        VARCHAR(50) necessary
    }
    bank ||--o{ glass : method
    bank {
        VARCHAR(50) method
        DATE agree
    }
    glass ||--o{ no : yeah
    glass {
        DATE yeah
        TEXT it
        VARCHAR(50) mention
    }
    no ||--o{ toward : machine
    no {
        VARCHAR(50) machine
        DATE enter
    }
    toward ||--o{ night : mind
    toward {
        DATE mind
        TEXT simple
        VARCHAR(50) respond
    }
    night ||--o{ drive : surface
    night {
        VARCHAR(50) surface
        DATE who
    }