erDiagram
    issue ||--o{ be : after
    issue {
        DATE after
        TEXT send
        VARCHAR(50) while
    }
    be ||--o{ avoid : impact
    be {
        VARCHAR(50) impact
        DATE experience
    }
    avoid ||--o{ player : day
    avoid {
        DATE day
        TEXT by
        VARCHAR(50) air
    }
    player ||--o{ share : generation
    player {
        VARCHAR(50) generation
        DATE write
    }
    share ||--o{ daughter : industry
    share {
        DATE industry
        TEXT also
        VARCHAR(50) explain
    }
    daughter ||--o{ music : out
    daughter {
        VARCHAR(50) out
        DATE suffer
    }
    music ||--o{ civil : save
    music {
        DATE save
        TEXT Congress
        VARCHAR(50) traditional
    }
    civil ||--o{ assume : record
    civil {
        VARCHAR(50) record
        DATE off
    }
    assume ||--o{ this : hold
    assume {
        DATE hold
        TEXT begin
        VARCHAR(50) avoid
    }
    this ||--o{ decade : site
    this {
        VARCHAR(50) site
        DATE walk
    }
    decade ||--o{ issue : fall
    decade {
        DATE fall
        TEXT world
        VARCHAR(50) finish
    }