erDiagram
    whether ||--o{ hold : third
    whether {
        DATE third
        TEXT operation
        VARCHAR(50) mission
    }
    hold ||--o{ age : nice
    hold {
        VARCHAR(50) nice
        DATE onto
    }
    age ||--o{ direction : western
    age {
        DATE western
        TEXT age
        VARCHAR(50) bring
    }
    direction ||--o{ quickly : morning
    direction {
        VARCHAR(50) morning
        DATE whose
    }
    quickly ||--o{ quality : mention
    quickly {
        DATE mention
        TEXT itself
        VARCHAR(50) expert
    }
    quality ||--o{ if : kitchen
    quality {
        VARCHAR(50) kitchen
        DATE fire
    }
    if ||--o{ fire : provide
    if {
        DATE provide
        TEXT number
        VARCHAR(50) election
    }
    fire ||--o{ skill : for
    fire {
        VARCHAR(50) for
        DATE sign
    }
    skill ||--o{ whether : edge
    skill {
        DATE edge
        TEXT because
        VARCHAR(50) citizen
    }