erDiagram
    maybe ||--o{ quality : stand
    maybe {
        DATE stand
        TEXT nation
        VARCHAR(50) capital
    }
    quality ||--o{ thank : off
    quality {
        VARCHAR(50) off
        DATE behavior
    }
    thank ||--o{ well : sense
    thank {
        DATE sense
        TEXT mind
        VARCHAR(50) sea
    }
    well ||--o{ fact : assume
    well {
        VARCHAR(50) assume
        DATE everything
    }
    fact ||--o{ maybe : executive
    fact {
        DATE executive
        TEXT eight
        VARCHAR(50) look
    }