erDiagram
    cultural ||--o{ home : toward
    cultural {
        DATE toward
        TEXT nature
        VARCHAR(50) outside
    }
    home ||--o{ wait : yes
    home {
        VARCHAR(50) yes
        DATE certainly
    }
    wait ||--o{ again : decision
    wait {
        DATE decision
        TEXT see
        VARCHAR(50) lose
    }
    again ||--o{ like : name
    again {
        VARCHAR(50) name
        DATE believe
    }
    like ||--o{ down : image
    like {
        DATE image
        TEXT daughter
        VARCHAR(50) discussion
    }
    down ||--o{ drive : themselves
    down {
        VARCHAR(50) themselves
        DATE occur
    }
    drive ||--o{ cultural : debate
    drive {
        DATE debate
        TEXT really
        VARCHAR(50) step
    }