erDiagram
    attention ||--o{ star : way
    attention {
        DATE way
        TEXT black
        VARCHAR(50) class
    }
    star ||--o{ maybe : window
    star {
        VARCHAR(50) window
        DATE fund
    }
    maybe ||--o{ impact : appear
    maybe {
        DATE appear
        TEXT tax
        VARCHAR(50) space
    }
    impact ||--o{ establish : say
    impact {
        VARCHAR(50) say
        DATE myself
    }
    establish ||--o{ together : song
    establish {
        DATE song
        TEXT night
        VARCHAR(50) training
    }
    together ||--o{ activity : factor
    together {
        VARCHAR(50) factor
        DATE idea
    }
    activity ||--o{ body : condition
    activity {
        DATE condition
        TEXT long
        VARCHAR(50) ok
    }
    body ||--o{ drive : join
    body {
        VARCHAR(50) join
        DATE majority
    }
    drive ||--o{ attention : western
    drive {
        DATE western
        TEXT gun
        VARCHAR(50) language
    }