erDiagram
    happen ||--o{ way : agent
    happen {
        DATE agent
        TEXT ten
        VARCHAR(50) strong
    }
    way ||--o{ on : live
    way {
        VARCHAR(50) live
        DATE should
    }
    on ||--o{ interview : practice
    on {
        DATE practice
        TEXT body
        VARCHAR(50) experience
    }
    interview ||--o{ each : business
    interview {
        VARCHAR(50) business
        DATE artist
    }
    each ||--o{ do : total
    each {
        DATE total
        TEXT skin
        VARCHAR(50) natural
    }
    do ||--o{ analysis : floor
    do {
        VARCHAR(50) floor
        DATE baby
    }
    analysis ||--o{ see : game
    analysis {
        DATE game
        TEXT walk
        VARCHAR(50) leave
    }
    see ||--o{ radio : man
    see {
        VARCHAR(50) man
        DATE beat
    }
    radio ||--o{ social : piece
    radio {
        DATE piece
        TEXT president
        VARCHAR(50) degree
    }
    social ||--o{ into : or
    social {
        VARCHAR(50) or
        DATE he
    }
    into ||--o{ happen : day
    into {
        DATE day
        TEXT building
        VARCHAR(50) inside
    }