erDiagram
    pay ||--o{ for : better
    pay {
        DATE better
        TEXT sound
        VARCHAR(50) serve
    }
    for ||--o{ center : still
    for {
        VARCHAR(50) still
        DATE scientist
    }
    center ||--o{ develop : brother
    center {
        DATE brother
        TEXT lot
        VARCHAR(50) respond
    }
    develop ||--o{ continue : popular
    develop {
        VARCHAR(50) popular
        DATE smile
    }
    continue ||--o{ theory : organization
    continue {
        DATE organization
        TEXT mouth
        VARCHAR(50) reason
    }
    theory ||--o{ pay : line
    theory {
        VARCHAR(50) line
        DATE manage
    }