erDiagram
    late ||--o{ industry : huge
    late {
        DATE huge
        TEXT husband
        VARCHAR(50) interest
    }
    industry ||--o{ hour : like
    industry {
        VARCHAR(50) like
        DATE dog
    }
    hour ||--o{ drop : every
    hour {
        DATE every
        TEXT state
        VARCHAR(50) without
    }
    drop ||--o{ open : deal
    drop {
        VARCHAR(50) deal
        DATE son
    }
    open ||--o{ smile : modern
    open {
        DATE modern
        TEXT science
        VARCHAR(50) behind
    }
    smile ||--o{ whose : Congress
    smile {
        VARCHAR(50) Congress
        DATE compare
    }
    whose ||--o{ different : process
    whose {
        DATE process
        TEXT everything
        VARCHAR(50) southern
    }
    different ||--o{ herself : sport
    different {
        VARCHAR(50) sport
        DATE represent
    }
    herself ||--o{ wide : second
    herself {
        DATE second
        TEXT night
        VARCHAR(50) effect
    }
    wide ||--o{ somebody : scene
    wide {
        VARCHAR(50) scene
        DATE allow
    }
    somebody ||--o{ deep : green
    somebody {
        DATE green
        TEXT sell
        VARCHAR(50) current
    }
    deep ||--o{ late : yet
    deep {
        VARCHAR(50) yet
        DATE though
    }