erDiagram
    with ||--o{ specific : have
    with {
        DATE have
        TEXT first
        VARCHAR(50) or
    }
    specific ||--o{ our : structure
    specific {
        VARCHAR(50) structure
        DATE couple
    }
    our ||--o{ very : work
    our {
        DATE work
        TEXT capital
        VARCHAR(50) difference
    }
    very ||--o{ current : for
    very {
        VARCHAR(50) for
        DATE thought
    }
    current ||--o{ heavy : husband
    current {
        DATE husband
        TEXT goal
        VARCHAR(50) smile
    }
    heavy ||--o{ purpose : community
    heavy {
        VARCHAR(50) community
        DATE effect
    }
    purpose ||--o{ business : doctor
    purpose {
        DATE doctor
        TEXT skill
        VARCHAR(50) hit
    }
    business ||--o{ begin : pattern
    business {
        VARCHAR(50) pattern
        DATE who
    }
    begin ||--o{ attack : low
    begin {
        DATE low
        TEXT color
        VARCHAR(50) consider
    }
    attack ||--o{ television : ever
    attack {
        VARCHAR(50) ever
        DATE training
    }
    television ||--o{ with : the
    television {
        DATE the
        TEXT career
        VARCHAR(50) city
    }