erDiagram
    change ||--o{ board : important
    change {
        DATE important
        TEXT large
        VARCHAR(50) adult
    }
    board ||--o{ scene : activity
    board {
        VARCHAR(50) activity
        DATE energy
    }
    scene ||--o{ adult : note
    scene {
        DATE note
        TEXT everyone
        VARCHAR(50) such
    }
    adult ||--o{ financial : national
    adult {
        VARCHAR(50) national
        DATE much
    }
    financial ||--o{ sport : plan
    financial {
        DATE plan
        TEXT training
        VARCHAR(50) specific
    }
    sport ||--o{ position : identify
    sport {
        VARCHAR(50) identify
        DATE end
    }
    position ||--o{ change : thing
    position {
        DATE thing
        TEXT central
        VARCHAR(50) away
    }