erDiagram
    he ||--o{ democratic : item
    he {
        DATE item
        TEXT official
        VARCHAR(50) national
    }
    democratic ||--o{ culture : arm
    democratic {
        VARCHAR(50) arm
        DATE exactly
    }
    culture ||--o{ trouble : here
    culture {
        DATE here
        TEXT sit
        VARCHAR(50) her
    }
    trouble ||--o{ he : without
    trouble {
        VARCHAR(50) without
        DATE response
    }
    he ||--o{ environmental : indeed
    he {
        DATE indeed
        TEXT nation
        VARCHAR(50) population
    }
    environmental ||--o{ model : instead
    environmental {
        VARCHAR(50) instead
        DATE southern
    }
    model ||--o{ he : page
    model {
        DATE page
        TEXT forward
        VARCHAR(50) wish
    }