erDiagram
    law ||--o{ send : class
    law {
        DATE class
        TEXT high
        VARCHAR(50) shoulder
    }
    send ||--o{ herself : east
    send {
        VARCHAR(50) east
        DATE baby
    }
    herself ||--o{ situation : soldier
    herself {
        DATE soldier
        TEXT financial
        VARCHAR(50) another
    }
    situation ||--o{ main : speak
    situation {
        VARCHAR(50) speak
        DATE base
    }
    main ||--o{ affect : enter
    main {
        DATE enter
        TEXT all
        VARCHAR(50) brother
    }
    affect ||--o{ final : employee
    affect {
        VARCHAR(50) employee
        DATE arrive
    }
    final ||--o{ fire : himself
    final {
        DATE himself
        TEXT watch
        VARCHAR(50) above
    }
    fire ||--o{ form : laugh
    fire {
        VARCHAR(50) laugh
        DATE bed
    }
    form ||--o{ peace : future
    form {
        DATE future
        TEXT citizen
        VARCHAR(50) realize
    }
    peace ||--o{ quickly : plan
    peace {
        VARCHAR(50) plan
        DATE minute
    }
    quickly ||--o{ law : since
    quickly {
        DATE since
        TEXT evidence
        VARCHAR(50) main
    }