erDiagram
    image ||--o{ staff : rock
    image {
        DATE rock
        TEXT member
        VARCHAR(50) then
    }
    staff ||--o{ prepare : commercial
    staff {
        VARCHAR(50) commercial
        DATE inside
    }
    prepare ||--o{ once : choice
    prepare {
        DATE choice
        TEXT walk
        VARCHAR(50) include
    }
    once ||--o{ billion : score
    once {
        VARCHAR(50) score
        DATE control
    }
    billion ||--o{ debate : prevent
    billion {
        DATE prevent
        TEXT every
        VARCHAR(50) city
    }
    debate ||--o{ conference : have
    debate {
        VARCHAR(50) have
        DATE player
    }
    conference ||--o{ make : staff
    conference {
        DATE staff
        TEXT meeting
        VARCHAR(50) nearly
    }
    make ||--o{ image : certainly
    make {
        VARCHAR(50) certainly
        DATE but
    }