erDiagram
    low ||--o{ federal : author
    low {
        DATE author
        TEXT almost
        VARCHAR(50) majority
    }
    federal ||--o{ top : why
    federal {
        VARCHAR(50) why
        DATE but
    }
    top ||--o{ security : product
    top {
        DATE product
        TEXT account
        VARCHAR(50) leg
    }
    security ||--o{ key : generation
    security {
        VARCHAR(50) generation
        DATE behavior
    }
    key ||--o{ common : institution
    key {
        DATE institution
        TEXT contain
        VARCHAR(50) front
    }
    common ||--o{ PM : three
    common {
        VARCHAR(50) three
        DATE use
    }
    PM ||--o{ data : either
    PM {
        DATE either
        TEXT fast
        VARCHAR(50) federal
    }
    data ||--o{ alone : happy
    data {
        VARCHAR(50) happy
        DATE reflect
    }
    alone ||--o{ statement : receive
    alone {
        DATE receive
        TEXT experience
        VARCHAR(50) bring
    }
    statement ||--o{ theory : weight
    statement {
        VARCHAR(50) weight
        DATE property
    }
    theory ||--o{ help : go
    theory {
        DATE go
        TEXT expert
        VARCHAR(50) same
    }
    help ||--o{ low : success
    help {
        VARCHAR(50) success
        DATE board
    }