erDiagram
    government ||--o{ speak : least
    government {
        DATE least
        TEXT this
        VARCHAR(50) pretty
    }
    speak ||--o{ exist : need
    speak {
        VARCHAR(50) need
        DATE maybe
    }
    exist ||--o{ rock : hit
    exist {
        DATE hit
        TEXT example
        VARCHAR(50) send
    }
    rock ||--o{ bring : summer
    rock {
        VARCHAR(50) summer
        DATE whose
    }
    bring ||--o{ her : because
    bring {
        DATE because
        TEXT great
        VARCHAR(50) decide
    }
    her ||--o{ exist : brother
    her {
        VARCHAR(50) brother
        DATE step
    }
    exist ||--o{ party : position
    exist {
        DATE position
        TEXT arm
        VARCHAR(50) include
    }
    party ||--o{ natural : myself
    party {
        VARCHAR(50) myself
        DATE consider
    }
    natural ||--o{ government : minute
    natural {
        DATE minute
        TEXT nation
        VARCHAR(50) cultural
    }