erDiagram
    perform ||--o{ often : upon
    perform {
        DATE upon
        TEXT give
        VARCHAR(50) seven
    }
    often ||--o{ hard : third
    often {
        VARCHAR(50) third
        DATE talk
    }
    hard ||--o{ story : toward
    hard {
        DATE toward
        TEXT type
        VARCHAR(50) world
    }
    story ||--o{ also : travel
    story {
        VARCHAR(50) travel
        DATE parent
    }
    also ||--o{ director : social
    also {
        DATE social
        TEXT land
        VARCHAR(50) upon
    }
    director ||--o{ perform : however
    director {
        VARCHAR(50) however
        DATE tend
    }