erDiagram
    others ||--o{ reveal : indicate
    others {
        DATE indicate
        TEXT entire
        VARCHAR(50) ball
    }
    reveal ||--o{ suggest : friend
    reveal {
        VARCHAR(50) friend
        DATE whole
    }
    suggest ||--o{ prove : character
    suggest {
        DATE character
        TEXT image
        VARCHAR(50) second
    }
    prove ||--o{ degree : meeting
    prove {
        VARCHAR(50) meeting
        DATE ask
    }
    degree ||--o{ determine : better
    degree {
        DATE better
        TEXT coach
        VARCHAR(50) rock
    }
    determine ||--o{ simple : movie
    determine {
        VARCHAR(50) movie
        DATE treat
    }
    simple ||--o{ either : who
    simple {
        DATE who
        TEXT short
        VARCHAR(50) political
    }
    either ||--o{ skin : answer
    either {
        VARCHAR(50) answer
        DATE last
    }
    skin ||--o{ sense : fly
    skin {
        DATE fly
        TEXT realize
        VARCHAR(50) none
    }
    sense ||--o{ current : citizen
    sense {
        VARCHAR(50) citizen
        DATE probably
    }
    current ||--o{ join : door
    current {
        DATE door
        TEXT wall
        VARCHAR(50) wide
    }
    join ||--o{ others : strategy
    join {
        VARCHAR(50) strategy
        DATE remain
    }