erDiagram
    PM ||--o{ describe : across
    PM {
        DATE across
        TEXT away
        VARCHAR(50) statement
    }
    describe ||--o{ enough : student
    describe {
        VARCHAR(50) student
        DATE firm
    }
    enough ||--o{ case : material
    enough {
        DATE material
        TEXT road
        VARCHAR(50) gun
    }
    case ||--o{ study : fact
    case {
        VARCHAR(50) fact
        DATE real
    }
    study ||--o{ include : site
    study {
        DATE site
        TEXT last
        VARCHAR(50) can
    }
    include ||--o{ magazine : west
    include {
        VARCHAR(50) west
        DATE rest
    }
    magazine ||--o{ evidence : care
    magazine {
        DATE care
        TEXT left
        VARCHAR(50) outside
    }
    evidence ||--o{ PM : lay
    evidence {
        VARCHAR(50) lay
        DATE natural
    }