erDiagram
    summer ||--o{ none : everyone
    summer {
        DATE everyone
        TEXT fund
        VARCHAR(50) former
    }
    none ||--o{ necessary : run
    none {
        VARCHAR(50) run
        DATE their
    }
    necessary ||--o{ despite : seek
    necessary {
        DATE seek
        TEXT kitchen
        VARCHAR(50) court
    }
    despite ||--o{ operation : especially
    despite {
        VARCHAR(50) especially
        DATE somebody
    }
    operation ||--o{ medical : miss
    operation {
        DATE miss
        TEXT majority
        VARCHAR(50) event
    }
    medical ||--o{ rest : official
    medical {
        VARCHAR(50) official
        DATE main
    }
    rest ||--o{ impact : line
    rest {
        DATE line
        TEXT imagine
        VARCHAR(50) pick
    }
    impact ||--o{ off : medical
    impact {
        VARCHAR(50) medical
        DATE how
    }
    off ||--o{ continue : seat
    off {
        DATE seat
        TEXT reason
        VARCHAR(50) along
    }
    continue ||--o{ under : door
    continue {
        VARCHAR(50) door
        DATE front
    }
    under ||--o{ summer : yes
    under {
        DATE yes
        TEXT purpose
        VARCHAR(50) way
    }