erDiagram
    draw ||--o{ production : wonder
    draw {
        DATE wonder
        TEXT such
        VARCHAR(50) far
    }
    production ||--o{ toward : nature
    production {
        VARCHAR(50) nature
        DATE training
    }
    toward ||--o{ impact : explain
    toward {
        DATE explain
        TEXT despite
        VARCHAR(50) power
    }
    impact ||--o{ research : challenge
    impact {
        VARCHAR(50) challenge
        DATE choose
    }
    research ||--o{ size : edge
    research {
        DATE edge
        TEXT hard
        VARCHAR(50) move
    }
    size ||--o{ goal : federal
    size {
        VARCHAR(50) federal
        DATE call
    }
    goal ||--o{ draw : just
    goal {
        DATE just
        TEXT process
        VARCHAR(50) stay
    }