erDiagram
    grow ||--o{ process : message
    grow {
        DATE message
        TEXT room
        VARCHAR(50) beautiful
    }
    process ||--o{ generation : media
    process {
        VARCHAR(50) media
        DATE despite
    }
    generation ||--o{ rest : garden
    generation {
        DATE garden
        TEXT fall
        VARCHAR(50) put
    }
    rest ||--o{ agent : particular
    rest {
        VARCHAR(50) particular
        DATE chair
    }
    agent ||--o{ control : box
    agent {
        DATE box
        TEXT exactly
        VARCHAR(50) candidate
    }
    control ||--o{ reality : style
    control {
        VARCHAR(50) style
        DATE market
    }
    reality ||--o{ race : discuss
    reality {
        DATE discuss
        TEXT whose
        VARCHAR(50) plant
    }
    race ||--o{ grow : new
    race {
        VARCHAR(50) new
        DATE address
    }