erDiagram
    mouth ||--o{ gas : behind
    mouth {
        DATE behind
        TEXT treatment
        VARCHAR(50) one
    }
    gas ||--o{ democratic : manage
    gas {
        VARCHAR(50) manage
        DATE culture
    }
    democratic ||--o{ space : live
    democratic {
        DATE live
        TEXT check
        VARCHAR(50) marriage
    }
    space ||--o{ myself : relate
    space {
        VARCHAR(50) relate
        DATE heavy
    }
    myself ||--o{ morning : avoid
    myself {
        DATE avoid
        TEXT dream
        VARCHAR(50) I
    }
    morning ||--o{ board : past
    morning {
        VARCHAR(50) past
        DATE choice
    }
    board ||--o{ mouth : director
    board {
        DATE director
        TEXT real
        VARCHAR(50) note
    }