erDiagram
    main ||--o{ produce : green
    main {
        DATE green
        TEXT single
        VARCHAR(50) should
    }
    produce ||--o{ out : friend
    produce {
        VARCHAR(50) friend
        DATE country
    }
    out ||--o{ range : late
    out {
        DATE late
        TEXT mother
        VARCHAR(50) movement
    }
    range ||--o{ law : forget
    range {
        VARCHAR(50) forget
        DATE food
    }
    law ||--o{ too : we
    law {
        DATE we
        TEXT skill
        VARCHAR(50) class
    }
    too ||--o{ five : table
    too {
        VARCHAR(50) table
        DATE work
    }
    five ||--o{ head : back
    five {
        DATE back
        TEXT memory
        VARCHAR(50) realize
    }
    head ||--o{ fill : usually
    head {
        VARCHAR(50) usually
        DATE fine
    }
    fill ||--o{ take : several
    fill {
        DATE several
        TEXT sit
        VARCHAR(50) listen
    }
    take ||--o{ main : how
    take {
        VARCHAR(50) how
        DATE small
    }