erDiagram
    success ||--o{ green : movement
    success {
        DATE movement
        TEXT west
        VARCHAR(50) beautiful
    }
    green ||--o{ account : however
    green {
        VARCHAR(50) however
        DATE write
    }
    account ||--o{ something : their
    account {
        DATE their
        TEXT everybody
        VARCHAR(50) again
    }
    something ||--o{ class : never
    something {
        VARCHAR(50) never
        DATE girl
    }
    class ||--o{ along : today
    class {
        DATE today
        TEXT city
        VARCHAR(50) employee
    }
    along ||--o{ nearly : Democrat
    along {
        VARCHAR(50) Democrat
        DATE although
    }
    nearly ||--o{ common : yard
    nearly {
        DATE yard
        TEXT health
        VARCHAR(50) education
    }
    common ||--o{ billion : despite
    common {
        VARCHAR(50) despite
        DATE guy
    }
    billion ||--o{ painting : article
    billion {
        DATE article
        TEXT officer
        VARCHAR(50) fund
    }
    painting ||--o{ space : turn
    painting {
        VARCHAR(50) turn
        DATE rule
    }
    space ||--o{ success : wrong
    space {
        DATE wrong
        TEXT grow
        VARCHAR(50) central
    }