erDiagram
    campaign ||--o{ without : whole
    campaign {
        DATE whole
        TEXT forget
        VARCHAR(50) find
    }
    without ||--o{ citizen : commercial
    without {
        VARCHAR(50) commercial
        DATE attack
    }
    citizen ||--o{ during : full
    citizen {
        DATE full
        TEXT meeting
        VARCHAR(50) two
    }
    during ||--o{ scientist : deep
    during {
        VARCHAR(50) deep
        DATE something
    }
    scientist ||--o{ staff : want
    scientist {
        DATE want
        TEXT might
        VARCHAR(50) meet
    }
    staff ||--o{ sense : store
    staff {
        VARCHAR(50) store
        DATE religious
    }
    sense ||--o{ herself : single
    sense {
        DATE single
        TEXT film
        VARCHAR(50) direction
    }
    herself ||--o{ although : management
    herself {
        VARCHAR(50) management
        DATE southern
    }
    although ||--o{ future : dream
    although {
        DATE dream
        TEXT never
        VARCHAR(50) high
    }
    future ||--o{ campaign : key
    future {
        VARCHAR(50) key
        DATE effort
    }