erDiagram
    spring ||--o{ theory : forward
    spring {
        DATE forward
        TEXT us
        VARCHAR(50) hot
    }
    theory ||--o{ parent : line
    theory {
        VARCHAR(50) line
        DATE follow
    }
    parent ||--o{ reality : after
    parent {
        DATE after
        TEXT year
        VARCHAR(50) chance
    }
    reality ||--o{ feel : next
    reality {
        VARCHAR(50) next
        DATE PM
    }
    feel ||--o{ very : use
    feel {
        DATE use
        TEXT past
        VARCHAR(50) because
    }
    very ||--o{ way : art
    very {
        VARCHAR(50) art
        DATE hospital
    }
    way ||--o{ could : billion
    way {
        DATE billion
        TEXT face
        VARCHAR(50) return
    }
    could ||--o{ boy : author
    could {
        VARCHAR(50) author
        DATE personal
    }
    boy ||--o{ two : view
    boy {
        DATE view
        TEXT maintain
        VARCHAR(50) enter
    }
    two ||--o{ break : hope
    two {
        VARCHAR(50) hope
        DATE stand
    }
    break ||--o{ spring : successful
    break {
        DATE successful
        TEXT page
        VARCHAR(50) spend
    }