erDiagram
    trial ||--o{ run : hope
    trial {
        DATE hope
        TEXT civil
        VARCHAR(50) song
    }
    run ||--o{ treatment : heavy
    run {
        VARCHAR(50) heavy
        DATE include
    }
    treatment ||--o{ any : design
    treatment {
        DATE design
        TEXT public
        VARCHAR(50) how
    }
    any ||--o{ mind : watch
    any {
        VARCHAR(50) watch
        DATE them
    }
    mind ||--o{ brother : possible
    mind {
        DATE possible
        TEXT around
        VARCHAR(50) operation
    }
    brother ||--o{ fund : pull
    brother {
        VARCHAR(50) pull
        DATE television
    }
    fund ||--o{ season : professional
    fund {
        DATE professional
        TEXT human
        VARCHAR(50) car
    }
    season ||--o{ quickly : within
    season {
        VARCHAR(50) within
        DATE teach
    }
    quickly ||--o{ catch : security
    quickly {
        DATE security
        TEXT lot
        VARCHAR(50) manager
    }
    catch ||--o{ first : enter
    catch {
        VARCHAR(50) enter
        DATE wrong
    }
    first ||--o{ trial : and
    first {
        DATE and
        TEXT general
        VARCHAR(50) long
    }