erDiagram
    enter ||--o{ many : look
    enter {
        DATE look
        TEXT floor
        VARCHAR(50) out
    }
    many ||--o{ detail : world
    many {
        VARCHAR(50) world
        DATE house
    }
    detail ||--o{ thus : reveal
    detail {
        DATE reveal
        TEXT avoid
        VARCHAR(50) near
    }
    thus ||--o{ student : brother
    thus {
        VARCHAR(50) brother
        DATE agency
    }
    student ||--o{ week : build
    student {
        DATE build
        TEXT half
        VARCHAR(50) back
    }
    week ||--o{ moment : financial
    week {
        VARCHAR(50) financial
        DATE discover
    }
    moment ||--o{ short : a
    moment {
        DATE a
        TEXT information
        VARCHAR(50) property
    }
    short ||--o{ measure : wear
    short {
        VARCHAR(50) wear
        DATE others
    }
    measure ||--o{ water : yeah
    measure {
        DATE yeah
        TEXT carry
        VARCHAR(50) standard
    }
    water ||--o{ worker : its
    water {
        VARCHAR(50) its
        DATE real
    }
    worker ||--o{ tree : and
    worker {
        DATE and
        TEXT either
        VARCHAR(50) manage
    }
    tree ||--o{ enter : special
    tree {
        VARCHAR(50) special
        DATE surface
    }