erDiagram
    cut ||--o{ on : where
    cut {
        DATE where
        TEXT ask
        VARCHAR(50) decide
    }
    on ||--o{ think : dream
    on {
        VARCHAR(50) dream
        DATE spend
    }
    think ||--o{ TV : large
    think {
        DATE large
        TEXT customer
        VARCHAR(50) have
    }
    TV ||--o{ chair : general
    TV {
        VARCHAR(50) general
        DATE put
    }
    chair ||--o{ suffer : too
    chair {
        DATE too
        TEXT audience
        VARCHAR(50) couple
    }
    suffer ||--o{ training : data
    suffer {
        VARCHAR(50) data
        DATE value
    }
    training ||--o{ effort : couple
    training {
        DATE couple
        TEXT middle
        VARCHAR(50) increase
    }
    effort ||--o{ must : off
    effort {
        VARCHAR(50) off
        DATE which
    }
    must ||--o{ cut : you
    must {
        DATE you
        TEXT score
        VARCHAR(50) offer
    }