erDiagram
    morning ||--o{ position : poor
    morning {
        DATE poor
        TEXT clear
        VARCHAR(50) better
    }
    position ||--o{ different : perform
    position {
        VARCHAR(50) perform
        DATE exist
    }
    different ||--o{ everything : respond
    different {
        DATE respond
        TEXT final
        VARCHAR(50) couple
    }
    everything ||--o{ guess : consumer
    everything {
        VARCHAR(50) consumer
        DATE however
    }
    guess ||--o{ possible : compare
    guess {
        DATE compare
        TEXT rich
        VARCHAR(50) hold
    }
    possible ||--o{ imagine : short
    possible {
        VARCHAR(50) short
        DATE realize
    }
    imagine ||--o{ tax : raise
    imagine {
        DATE raise
        TEXT reveal
        VARCHAR(50) sea
    }
    tax ||--o{ low : prepare
    tax {
        VARCHAR(50) prepare
        DATE hour
    }
    low ||--o{ head : land
    low {
        DATE land
        TEXT religious
        VARCHAR(50) ability
    }
    head ||--o{ check : service
    head {
        VARCHAR(50) service
        DATE benefit
    }
    check ||--o{ morning : despite
    check {
        DATE despite
        TEXT exactly
        VARCHAR(50) inside
    }