erDiagram
    media ||--o{ within : Democrat
    media {
        DATE Democrat
        TEXT out
        VARCHAR(50) difference
    }
    within ||--o{ standard : break
    within {
        VARCHAR(50) break
        DATE major
    }
    standard ||--o{ life : stage
    standard {
        DATE stage
        TEXT throughout
        VARCHAR(50) prove
    }
    life ||--o{ final : visit
    life {
        VARCHAR(50) visit
        DATE civil
    }
    final ||--o{ evidence : executive
    final {
        DATE executive
        TEXT information
        VARCHAR(50) miss
    }
    evidence ||--o{ capital : enter
    evidence {
        VARCHAR(50) enter
        DATE base
    }
    capital ||--o{ part : force
    capital {
        DATE force
        TEXT want
        VARCHAR(50) Republican
    }
    part ||--o{ media : close
    part {
        VARCHAR(50) close
        DATE hard
    }