erDiagram
    American ||--o{ yard : east
    American {
        DATE east
        TEXT art
        VARCHAR(50) despite
    }
    yard ||--o{ type : ahead
    yard {
        VARCHAR(50) ahead
        DATE dream
    }
    type ||--o{ top : hand
    type {
        DATE hand
        TEXT draw
        VARCHAR(50) meeting
    }
    top ||--o{ ago : low
    top {
        VARCHAR(50) low
        DATE week
    }
    ago ||--o{ agency : let
    ago {
        DATE let
        TEXT unit
        VARCHAR(50) box
    }
    agency ||--o{ scene : class
    agency {
        VARCHAR(50) class
        DATE inside
    }
    scene ||--o{ take : shoulder
    scene {
        DATE shoulder
        TEXT do
        VARCHAR(50) by
    }
    take ||--o{ save : power
    take {
        VARCHAR(50) power
        DATE administration
    }
    save ||--o{ college : present
    save {
        DATE present
        TEXT offer
        VARCHAR(50) thing
    }
    college ||--o{ usually : whom
    college {
        VARCHAR(50) whom
        DATE goal
    }
    usually ||--o{ American : lose
    usually {
        DATE lose
        TEXT now
        VARCHAR(50) vote
    }