erDiagram
    focus ||--o{ behavior : senior
    focus {
        DATE senior
        TEXT which
        VARCHAR(50) skill
    }
    behavior ||--o{ finally : another
    behavior {
        VARCHAR(50) another
        DATE sell
    }
    finally ||--o{ serious : in
    finally {
        DATE in
        TEXT than
        VARCHAR(50) a
    }
    serious ||--o{ race : return
    serious {
        VARCHAR(50) return
        DATE cover
    }
    race ||--o{ focus : sign
    race {
        DATE sign
        TEXT western
        VARCHAR(50) add
    }