erDiagram
    movement ||--o{ hour : understand
    movement {
        DATE understand
        TEXT manage
        VARCHAR(50) statement
    }
    hour ||--o{ his : day
    hour {
        VARCHAR(50) day
        DATE community
    }
    his ||--o{ it : painting
    his {
        DATE painting
        TEXT feeling
        VARCHAR(50) interest
    }
    it ||--o{ hundred : more
    it {
        VARCHAR(50) more
        DATE leave
    }
    hundred ||--o{ try : billion
    hundred {
        DATE billion
        TEXT say
        VARCHAR(50) should
    }
    try ||--o{ group : commercial
    try {
        VARCHAR(50) commercial
        DATE way
    }
    group ||--o{ seem : whose
    group {
        DATE whose
        TEXT three
        VARCHAR(50) scene
    }
    seem ||--o{ member : morning
    seem {
        VARCHAR(50) morning
        DATE including
    }
    member ||--o{ room : town
    member {
        DATE town
        TEXT design
        VARCHAR(50) interview
    }
    room ||--o{ pick : office
    room {
        VARCHAR(50) office
        DATE season
    }
    pick ||--o{ surface : begin
    pick {
        DATE begin
        TEXT moment
        VARCHAR(50) build
    }
    surface ||--o{ movement : final
    surface {
        VARCHAR(50) final
        DATE direction
    }