erDiagram
    act ||--o{ true : teach
    act {
        DATE teach
        TEXT cell
        VARCHAR(50) share
    }
    true ||--o{ around : small
    true {
        VARCHAR(50) small
        DATE tend
    }
    around ||--o{ yet : hair
    around {
        DATE hair
        TEXT its
        VARCHAR(50) support
    }
    yet ||--o{ no : often
    yet {
        VARCHAR(50) often
        DATE wind
    }
    no ||--o{ science : high
    no {
        DATE high
        TEXT occur
        VARCHAR(50) color
    }
    science ||--o{ consumer : yourself
    science {
        VARCHAR(50) yourself
        DATE cover
    }
    consumer ||--o{ response : end
    consumer {
        DATE end
        TEXT stock
        VARCHAR(50) hundred
    }
    response ||--o{ get : business
    response {
        VARCHAR(50) business
        DATE for
    }
    get ||--o{ offer : likely
    get {
        DATE likely
        TEXT site
        VARCHAR(50) describe
    }
    offer ||--o{ central : method
    offer {
        VARCHAR(50) method
        DATE build
    }
    central ||--o{ act : miss
    central {
        DATE miss
        TEXT it
        VARCHAR(50) pay
    }