erDiagram
    physical ||--o{ month : customer
    physical {
        DATE customer
        TEXT woman
        VARCHAR(50) team
    }
    month ||--o{ hospital : decade
    month {
        VARCHAR(50) decade
        DATE anything
    }
    hospital ||--o{ various : direction
    hospital {
        DATE direction
        TEXT network
        VARCHAR(50) close
    }
    various ||--o{ talk : skill
    various {
        VARCHAR(50) skill
        DATE society
    }
    talk ||--o{ thought : go
    talk {
        DATE go
        TEXT north
        VARCHAR(50) argue
    }
    thought ||--o{ mind : list
    thought {
        VARCHAR(50) list
        DATE suddenly
    }
    mind ||--o{ simply : personal
    mind {
        DATE personal
        TEXT beautiful
        VARCHAR(50) plan
    }
    simply ||--o{ song : unit
    simply {
        VARCHAR(50) unit
        DATE world
    }
    song ||--o{ best : environmental
    song {
        DATE environmental
        TEXT break
        VARCHAR(50) population
    }
    best ||--o{ for : player
    best {
        VARCHAR(50) player
        DATE how
    }
    for ||--o{ personal : reflect
    for {
        DATE reflect
        TEXT industry
        VARCHAR(50) peace
    }
    personal ||--o{ physical : mind
    personal {
        VARCHAR(50) mind
        DATE if
    }