erDiagram
    him ||--o{ quite : call
    him {
        DATE call
        TEXT central
        VARCHAR(50) meet
    }
    quite ||--o{ how : case
    quite {
        VARCHAR(50) case
        DATE sing
    }
    how ||--o{ executive : responsibility
    how {
        DATE responsibility
        TEXT send
        VARCHAR(50) partner
    }
    executive ||--o{ southern : require
    executive {
        VARCHAR(50) require
        DATE example
    }
    southern ||--o{ responsibility : my
    southern {
        DATE my
        TEXT ok
        VARCHAR(50) base
    }
    responsibility ||--o{ ahead : matter
    responsibility {
        VARCHAR(50) matter
        DATE agreement
    }
    ahead ||--o{ him : few
    ahead {
        DATE few
        TEXT over
        VARCHAR(50) well
    }