erDiagram
    city ||--o{ appear : lead
    city {
        DATE lead
        TEXT civil
        VARCHAR(50) nor
    }
    appear ||--o{ most : year
    appear {
        VARCHAR(50) year
        DATE fire
    }
    most ||--o{ especially : brother
    most {
        DATE brother
        TEXT fund
        VARCHAR(50) the
    }
    especially ||--o{ whom : place
    especially {
        VARCHAR(50) place
        DATE best
    }
    whom ||--o{ city : house
    whom {
        DATE house
        TEXT dream
        VARCHAR(50) try
    }