erDiagram
    skill ||--o{ ten : summer
    skill {
        DATE summer
        TEXT grow
        VARCHAR(50) every
    }
    ten ||--o{ all : study
    ten {
        VARCHAR(50) study
        DATE threat
    }
    all ||--o{ democratic : must
    all {
        DATE must
        TEXT article
        VARCHAR(50) ready
    }
    democratic ||--o{ institution : main
    democratic {
        VARCHAR(50) main
        DATE others
    }
    institution ||--o{ good : general
    institution {
        DATE general
        TEXT various
        VARCHAR(50) candidate
    }
    good ||--o{ skill : force
    good {
        VARCHAR(50) force
        DATE individual
    }