erDiagram
    today ||--o{ heart : often
    today {
        DATE often
        TEXT democratic
        VARCHAR(50) fund
    }
    heart ||--o{ major : no
    heart {
        VARCHAR(50) no
        DATE job
    }
    major ||--o{ ready : employee
    major {
        DATE employee
        TEXT into
        VARCHAR(50) wish
    }
    ready ||--o{ sister : end
    ready {
        VARCHAR(50) end
        DATE spend
    }
    sister ||--o{ term : area
    sister {
        DATE area
        TEXT investment
        VARCHAR(50) no
    }
    term ||--o{ develop : election
    term {
        VARCHAR(50) election
        DATE bad
    }
    develop ||--o{ each : crime
    develop {
        DATE crime
        TEXT while
        VARCHAR(50) create
    }
    each ||--o{ today : memory
    each {
        VARCHAR(50) memory
        DATE involve
    }