erDiagram
    company ||--o{ heavy : short
    company {
        DATE short
        TEXT agent
        VARCHAR(50) line
    }
    heavy ||--o{ top : lay
    heavy {
        VARCHAR(50) lay
        DATE player
    }
    top ||--o{ arm : well
    top {
        DATE well
        TEXT reflect
        VARCHAR(50) keep
    }
    arm ||--o{ ago : final
    arm {
        VARCHAR(50) final
        DATE effort
    }
    ago ||--o{ above : enter
    ago {
        DATE enter
        TEXT clear
        VARCHAR(50) situation
    }
    above ||--o{ company : build
    above {
        VARCHAR(50) build
        DATE human
    }