erDiagram
    American ||--o{ type : treatment
    American {
        DATE treatment
        TEXT positive
        VARCHAR(50) medical
    }
    type ||--o{ peace : evening
    type {
        VARCHAR(50) evening
        DATE range
    }
    peace ||--o{ cultural : often
    peace {
        DATE often
        TEXT strong
        VARCHAR(50) blue
    }
    cultural ||--o{ me : director
    cultural {
        VARCHAR(50) director
        DATE result
    }
    me ||--o{ body : firm
    me {
        DATE firm
        TEXT receive
        VARCHAR(50) cup
    }
    body ||--o{ seem : guess
    body {
        VARCHAR(50) guess
        DATE forget
    }
    seem ||--o{ debate : establish
    seem {
        DATE establish
        TEXT cultural
        VARCHAR(50) term
    }
    debate ||--o{ yard : wish
    debate {
        VARCHAR(50) wish
        DATE light
    }
    yard ||--o{ tonight : house
    yard {
        DATE house
        TEXT subject
        VARCHAR(50) room
    }
    tonight ||--o{ American : suddenly
    tonight {
        VARCHAR(50) suddenly
        DATE quickly
    }