erDiagram
    structure ||--o{ animal : home
    structure {
        DATE home
        TEXT security
        VARCHAR(50) among
    }
    animal ||--o{ think : build
    animal {
        VARCHAR(50) build
        DATE conference
    }
    think ||--o{ meeting : space
    think {
        DATE space
        TEXT believe
        VARCHAR(50) us
    }
    meeting ||--o{ there : recent
    meeting {
        VARCHAR(50) recent
        DATE step
    }
    there ||--o{ class : kid
    there {
        DATE kid
        TEXT relationship
        VARCHAR(50) mean
    }
    class ||--o{ manager : see
    class {
        VARCHAR(50) see
        DATE study
    }
    manager ||--o{ sing : physical
    manager {
        DATE physical
        TEXT law
        VARCHAR(50) knowledge
    }
    sing ||--o{ structure : night
    sing {
        VARCHAR(50) night
        DATE suggest
    }