erDiagram
    air ||--o{ foreign : reality
    air {
        DATE reality
        TEXT visit
        VARCHAR(50) theory
    }
    foreign ||--o{ approach : in
    foreign {
        VARCHAR(50) in
        DATE citizen
    }
    approach ||--o{ should : traditional
    approach {
        DATE traditional
        TEXT exist
        VARCHAR(50) question
    }
    should ||--o{ reality : democratic
    should {
        VARCHAR(50) democratic
        DATE camera
    }
    reality ||--o{ agency : low
    reality {
        DATE low
        TEXT try
        VARCHAR(50) race
    }
    agency ||--o{ else : offer
    agency {
        VARCHAR(50) offer
        DATE discover
    }
    else ||--o{ capital : decade
    else {
        DATE decade
        TEXT stop
        VARCHAR(50) since
    }
    capital ||--o{ score : part
    capital {
        VARCHAR(50) part
        DATE wrong
    }
    score ||--o{ air : mean
    score {
        DATE mean
        TEXT how
        VARCHAR(50) gas
    }