erDiagram
    see ||--o{ color : country
    see {
        DATE country
        TEXT paper
        VARCHAR(50) military
    }
    color ||--o{ imagine : participant
    color {
        VARCHAR(50) participant
        DATE remember
    }
    imagine ||--o{ Mr : decade
    imagine {
        DATE decade
        TEXT entire
        VARCHAR(50) suggest
    }
    Mr ||--o{ program : see
    Mr {
        VARCHAR(50) see
        DATE travel
    }
    program ||--o{ item : thought
    program {
        DATE thought
        TEXT join
        VARCHAR(50) field
    }
    item ||--o{ could : real
    item {
        VARCHAR(50) real
        DATE popular
    }
    could ||--o{ same : nothing
    could {
        DATE nothing
        TEXT hundred
        VARCHAR(50) let
    }
    same ||--o{ behavior : him
    same {
        VARCHAR(50) him
        DATE book
    }
    behavior ||--o{ data : ball
    behavior {
        DATE ball
        TEXT find
        VARCHAR(50) return
    }
    data ||--o{ see : situation
    data {
        VARCHAR(50) situation
        DATE type
    }