erDiagram
    lot ||--o{ bring : outside
    lot {
        DATE outside
        TEXT push
        VARCHAR(50) various
    }
    bring ||--o{ themselves : thing
    bring {
        VARCHAR(50) thing
        DATE instead
    }
    themselves ||--o{ stop : pattern
    themselves {
        DATE pattern
        TEXT race
        VARCHAR(50) give
    }
    stop ||--o{ loss : design
    stop {
        VARCHAR(50) design
        DATE somebody
    }
    loss ||--o{ project : boy
    loss {
        DATE boy
        TEXT me
        VARCHAR(50) start
    }
    project ||--o{ recognize : instead
    project {
        VARCHAR(50) instead
        DATE mother
    }
    recognize ||--o{ person : vote
    recognize {
        DATE vote
        TEXT herself
        VARCHAR(50) strategy
    }
    person ||--o{ add : learn
    person {
        VARCHAR(50) learn
        DATE send
    }
    add ||--o{ baby : end
    add {
        DATE end
        TEXT travel
        VARCHAR(50) themselves
    }
    baby ||--o{ TV : player
    baby {
        VARCHAR(50) player
        DATE step
    }
    TV ||--o{ center : begin
    TV {
        DATE begin
        TEXT be
        VARCHAR(50) around
    }
    center ||--o{ lot : approach
    center {
        VARCHAR(50) approach
        DATE see
    }