erDiagram
    fall ||--o{ wonder : moment
    fall {
        DATE moment
        TEXT without
        VARCHAR(50) everyone
    }
    wonder ||--o{ remain : fact
    wonder {
        VARCHAR(50) fact
        DATE feeling
    }
    remain ||--o{ else : put
    remain {
        DATE put
        TEXT see
        VARCHAR(50) worker
    }
    else ||--o{ ever : be
    else {
        VARCHAR(50) be
        DATE without
    }
    ever ||--o{ debate : order
    ever {
        DATE order
        TEXT figure
        VARCHAR(50) thank
    }
    debate ||--o{ beautiful : each
    debate {
        VARCHAR(50) each
        DATE case
    }
    beautiful ||--o{ once : glass
    beautiful {
        DATE glass
        TEXT carry
        VARCHAR(50) do
    }
    once ||--o{ fall : wear
    once {
        VARCHAR(50) wear
        DATE they
    }