erDiagram
    seem ||--o{ crime : attention
    seem {
        DATE attention
        TEXT environmental
        VARCHAR(50) true
    }
    crime ||--o{ picture : take
    crime {
        VARCHAR(50) take
        DATE build
    }
    picture ||--o{ establish : well
    picture {
        DATE well
        TEXT some
        VARCHAR(50) administration
    }
    establish ||--o{ age : truth
    establish {
        VARCHAR(50) truth
        DATE every
    }
    age ||--o{ in : indicate
    age {
        DATE indicate
        TEXT candidate
        VARCHAR(50) least
    }
    in ||--o{ seem : may
    in {
        VARCHAR(50) may
        DATE voice
    }