erDiagram
    culture ||--o{ option : involve
    culture {
        DATE involve
        TEXT think
        VARCHAR(50) middle
    }
    option ||--o{ pass : win
    option {
        VARCHAR(50) win
        DATE reveal
    }
    pass ||--o{ story : long
    pass {
        DATE long
        TEXT week
        VARCHAR(50) within
    }
    story ||--o{ care : cold
    story {
        VARCHAR(50) cold
        DATE natural
    }
    care ||--o{ beyond : answer
    care {
        DATE answer
        TEXT tax
        VARCHAR(50) plan
    }
    beyond ||--o{ culture : level
    beyond {
        VARCHAR(50) level
        DATE beat
    }