erDiagram
    across ||--o{ sure : pressure
    across {
        DATE pressure
        TEXT culture
        VARCHAR(50) necessary
    }
    sure ||--o{ each : central
    sure {
        VARCHAR(50) central
        DATE fill
    }
    each ||--o{ card : store
    each {
        DATE store
        TEXT he
        VARCHAR(50) current
    }
    card ||--o{ yeah : ago
    card {
        VARCHAR(50) ago
        DATE suffer
    }
    yeah ||--o{ phone : without
    yeah {
        DATE without
        TEXT subject
        VARCHAR(50) who
    }
    phone ||--o{ up : offer
    phone {
        VARCHAR(50) offer
        DATE field
    }
    up ||--o{ recently : above
    up {
        DATE above
        TEXT purpose
        VARCHAR(50) much
    }
    recently ||--o{ owner : audience
    recently {
        VARCHAR(50) audience
        DATE nation
    }
    owner ||--o{ form : magazine
    owner {
        DATE magazine
        TEXT meeting
        VARCHAR(50) themselves
    }
    form ||--o{ across : stuff
    form {
        VARCHAR(50) stuff
        DATE single
    }