erDiagram
    world ||--o{ onto : budget
    world {
        DATE budget
        TEXT change
        VARCHAR(50) wear
    }
    onto ||--o{ experience : maintain
    onto {
        VARCHAR(50) maintain
        DATE each
    }
    experience ||--o{ boy : run
    experience {
        DATE run
        TEXT image
        VARCHAR(50) child
    }
    boy ||--o{ amount : place
    boy {
        VARCHAR(50) place
        DATE other
    }
    amount ||--o{ former : billion
    amount {
        DATE billion
        TEXT suggest
        VARCHAR(50) stuff
    }
    former ||--o{ eat : company
    former {
        VARCHAR(50) company
        DATE sport
    }
    eat ||--o{ beyond : risk
    eat {
        DATE risk
        TEXT where
        VARCHAR(50) almost
    }
    beyond ||--o{ stop : nothing
    beyond {
        VARCHAR(50) nothing
        DATE method
    }
    stop ||--o{ test : trade
    stop {
        DATE trade
        TEXT house
        VARCHAR(50) charge
    }
    test ||--o{ world : girl
    test {
        VARCHAR(50) girl
        DATE at
    }