erDiagram
    hard ||--o{ church : site
    hard {
        DATE site
        TEXT resource
        VARCHAR(50) wind
    }
    church ||--o{ just : least
    church {
        VARCHAR(50) least
        DATE give
    }
    just ||--o{ leader : whom
    just {
        DATE whom
        TEXT so
        VARCHAR(50) executive
    }
    leader ||--o{ fine : somebody
    leader {
        VARCHAR(50) somebody
        DATE ball
    }
    fine ||--o{ feel : all
    fine {
        DATE all
        TEXT break
        VARCHAR(50) appear
    }
    feel ||--o{ staff : finally
    feel {
        VARCHAR(50) finally
        DATE property
    }
    staff ||--o{ recent : table
    staff {
        DATE table
        TEXT century
        VARCHAR(50) successful
    }
    recent ||--o{ hard : leave
    recent {
        VARCHAR(50) leave
        DATE TV
    }