erDiagram
    whom ||--o{ operation : parent
    whom {
        DATE parent
        TEXT service
        VARCHAR(50) deal
    }
    operation ||--o{ any : weight
    operation {
        VARCHAR(50) weight
        DATE stuff
    }
    any ||--o{ describe : back
    any {
        DATE back
        TEXT realize
        VARCHAR(50) especially
    }
    describe ||--o{ create : voice
    describe {
        VARCHAR(50) voice
        DATE fill
    }
    create ||--o{ whom : machine
    create {
        DATE machine
        TEXT pattern
        VARCHAR(50) war
    }