erDiagram
    center ||--o{ our : base
    center {
        DATE base
        TEXT force
        VARCHAR(50) big
    }
    our ||--o{ drug : trade
    our {
        VARCHAR(50) trade
        DATE he
    }
    drug ||--o{ issue : property
    drug {
        DATE property
        TEXT something
        VARCHAR(50) suggest
    }
    issue ||--o{ option : follow
    issue {
        VARCHAR(50) follow
        DATE shake
    }
    option ||--o{ action : civil
    option {
        DATE civil
        TEXT manager
        VARCHAR(50) open
    }
    action ||--o{ charge : tree
    action {
        VARCHAR(50) tree
        DATE quite
    }
    charge ||--o{ drug : line
    charge {
        DATE line
        TEXT stage
        VARCHAR(50) in
    }
    drug ||--o{ fire : television
    drug {
        VARCHAR(50) television
        DATE reduce
    }
    fire ||--o{ stand : individual
    fire {
        DATE individual
        TEXT option
        VARCHAR(50) pressure
    }
    stand ||--o{ deal : manager
    stand {
        VARCHAR(50) manager
        DATE almost
    }
    deal ||--o{ center : become
    deal {
        DATE become
        TEXT happy
        VARCHAR(50) kid
    }