erDiagram
    start ||--o{ indicate : none
    start {
        DATE none
        TEXT television
        VARCHAR(50) their
    }
    indicate ||--o{ service : western
    indicate {
        VARCHAR(50) western
        DATE eat
    }
    service ||--o{ argue : nature
    service {
        DATE nature
        TEXT become
        VARCHAR(50) building
    }
    argue ||--o{ action : early
    argue {
        VARCHAR(50) early
        DATE cost
    }
    action ||--o{ forward : think
    action {
        DATE think
        TEXT still
        VARCHAR(50) role
    }
    forward ||--o{ nothing : cover
    forward {
        VARCHAR(50) cover
        DATE likely
    }
    nothing ||--o{ present : while
    nothing {
        DATE while
        TEXT I
        VARCHAR(50) right
    }
    present ||--o{ do : point
    present {
        VARCHAR(50) point
        DATE how
    }
    do ||--o{ to : without
    do {
        DATE without
        TEXT them
        VARCHAR(50) account
    }
    to ||--o{ car : president
    to {
        VARCHAR(50) president
        DATE different
    }
    car ||--o{ start : spend
    car {
        DATE spend
        TEXT participant
        VARCHAR(50) career
    }