erDiagram
    tax ||--o{ relationship : talk
    tax {
        DATE talk
        TEXT cultural
        VARCHAR(50) today
    }
    relationship ||--o{ company : eight
    relationship {
        VARCHAR(50) eight
        DATE improve
    }
    company ||--o{ evening : this
    company {
        DATE this
        TEXT wrong
        VARCHAR(50) indeed
    }
    evening ||--o{ world : speak
    evening {
        VARCHAR(50) speak
        DATE like
    }
    world ||--o{ itself : power
    world {
        DATE power
        TEXT service
        VARCHAR(50) big
    }
    itself ||--o{ tough : thousand
    itself {
        VARCHAR(50) thousand
        DATE attack
    }
    tough ||--o{ tax : central
    tough {
        DATE central
        TEXT have
        VARCHAR(50) administration
    }