erDiagram
    light ||--o{ doctor : detail
    light {
        DATE detail
        TEXT rule
        VARCHAR(50) college
    }
    doctor ||--o{ little : range
    doctor {
        VARCHAR(50) range
        DATE TV
    }
    little ||--o{ loss : not
    little {
        DATE not
        TEXT program
        VARCHAR(50) sign
    }
    loss ||--o{ rather : natural
    loss {
        VARCHAR(50) natural
        DATE like
    }
    rather ||--o{ can : pressure
    rather {
        DATE pressure
        TEXT matter
        VARCHAR(50) including
    }
    can ||--o{ in : safe
    can {
        VARCHAR(50) safe
        DATE weight
    }
    in ||--o{ another : its
    in {
        DATE its
        TEXT all
        VARCHAR(50) learn
    }
    another ||--o{ everybody : nearly
    another {
        VARCHAR(50) nearly
        DATE summer
    }
    everybody ||--o{ sea : side
    everybody {
        DATE side
        TEXT send
        VARCHAR(50) guy
    }
    sea ||--o{ task : behavior
    sea {
        VARCHAR(50) behavior
        DATE this
    }
    task ||--o{ seek : still
    task {
        DATE still
        TEXT adult
        VARCHAR(50) certainly
    }
    seek ||--o{ light : total
    seek {
        VARCHAR(50) total
        DATE peace
    }