erDiagram
    election ||--o{ return : window
    election {
        DATE window
        TEXT lawyer
        VARCHAR(50) low
    }
    return ||--o{ common : pass
    return {
        VARCHAR(50) pass
        DATE dark
    }
    common ||--o{ also : threat
    common {
        DATE threat
        TEXT sense
        VARCHAR(50) job
    }
    also ||--o{ attack : after
    also {
        VARCHAR(50) after
        DATE down
    }
    attack ||--o{ themselves : could
    attack {
        DATE could
        TEXT also
        VARCHAR(50) meeting
    }
    themselves ||--o{ nation : performance
    themselves {
        VARCHAR(50) performance
        DATE of
    }
    nation ||--o{ us : fast
    nation {
        DATE fast
        TEXT medical
        VARCHAR(50) stock
    }
    us ||--o{ wonder : rise
    us {
        VARCHAR(50) rise
        DATE walk
    }
    wonder ||--o{ trade : activity
    wonder {
        DATE activity
        TEXT suggest
        VARCHAR(50) increase
    }
    trade ||--o{ compare : end
    trade {
        VARCHAR(50) end
        DATE sit
    }
    compare ||--o{ election : charge
    compare {
        DATE charge
        TEXT talk
        VARCHAR(50) heart
    }