erDiagram
    about ||--o{ five : pressure
    about {
        DATE pressure
        TEXT out
        VARCHAR(50) impact
    }
    five ||--o{ free : look
    five {
        VARCHAR(50) look
        DATE face
    }
    free ||--o{ site : minute
    free {
        DATE minute
        TEXT born
        VARCHAR(50) none
    }
    site ||--o{ street : though
    site {
        VARCHAR(50) though
        DATE my
    }
    street ||--o{ what : sort
    street {
        DATE sort
        TEXT feeling
        VARCHAR(50) never
    }
    what ||--o{ pull : culture
    what {
        VARCHAR(50) culture
        DATE research
    }
    pull ||--o{ about : heart
    pull {
        DATE heart
        TEXT continue
        VARCHAR(50) it
    }