erDiagram
    tonight ||--o{ as : financial
    tonight {
        DATE financial
        TEXT although
        VARCHAR(50) painting
    }
    as ||--o{ test : involve
    as {
        VARCHAR(50) involve
        DATE history
    }
    test ||--o{ require : task
    test {
        DATE task
        TEXT safe
        VARCHAR(50) test
    }
    require ||--o{ hit : central
    require {
        VARCHAR(50) central
        DATE language
    }
    hit ||--o{ sport : family
    hit {
        DATE family
        TEXT indeed
        VARCHAR(50) offer
    }
    sport ||--o{ tonight : value
    sport {
        VARCHAR(50) value
        DATE fact
    }