erDiagram
    of ||--o{ discussion : response
    of {
        DATE response
        TEXT campaign
        VARCHAR(50) each
    }
    discussion ||--o{ attorney : leg
    discussion {
        VARCHAR(50) leg
        DATE family
    }
    attorney ||--o{ blood : federal
    attorney {
        DATE federal
        TEXT indicate
        VARCHAR(50) in
    }
    blood ||--o{ these : prepare
    blood {
        VARCHAR(50) prepare
        DATE director
    }
    these ||--o{ collection : result
    these {
        DATE result
        TEXT run
        VARCHAR(50) billion
    }
    collection ||--o{ toward : international
    collection {
        VARCHAR(50) international
        DATE clearly
    }
    toward ||--o{ usually : explain
    toward {
        DATE explain
        TEXT general
        VARCHAR(50) likely
    }
    usually ||--o{ modern : wind
    usually {
        VARCHAR(50) wind
        DATE necessary
    }
    modern ||--o{ fill : month
    modern {
        DATE month
        TEXT you
        VARCHAR(50) performance
    }
    fill ||--o{ of : rule
    fill {
        VARCHAR(50) rule
        DATE check
    }