erDiagram
    red ||--o{ maintain : pattern
    red {
        DATE pattern
        TEXT different
        VARCHAR(50) third
    }
    maintain ||--o{ product : everyone
    maintain {
        VARCHAR(50) everyone
        DATE day
    }
    product ||--o{ floor : model
    product {
        DATE model
        TEXT force
        VARCHAR(50) decade
    }
    floor ||--o{ us : relate
    floor {
        VARCHAR(50) relate
        DATE claim
    }
    us ||--o{ night : operation
    us {
        DATE operation
        TEXT stock
        VARCHAR(50) police
    }
    night ||--o{ red : table
    night {
        VARCHAR(50) table
        DATE attention
    }