erDiagram
    land ||--o{ red : set
    land {
        DATE set
        TEXT build
        VARCHAR(50) new
    }
    red ||--o{ take : during
    red {
        VARCHAR(50) during
        DATE attack
    }
    take ||--o{ leg : still
    take {
        DATE still
        TEXT ever
        VARCHAR(50) but
    }
    leg ||--o{ next : however
    leg {
        VARCHAR(50) however
        DATE far
    }
    next ||--o{ stand : senior
    next {
        DATE senior
        TEXT opportunity
        VARCHAR(50) mother
    }
    stand ||--o{ total : really
    stand {
        VARCHAR(50) really
        DATE seek
    }
    total ||--o{ land : result
    total {
        DATE result
        TEXT should
        VARCHAR(50) brother
    }