erDiagram
    way ||--o{ explain : someone
    way {
        DATE someone
        TEXT shake
        VARCHAR(50) learn
    }
    explain ||--o{ usually : them
    explain {
        VARCHAR(50) them
        DATE act
    }
    usually ||--o{ long : bring
    usually {
        DATE bring
        TEXT then
        VARCHAR(50) Congress
    }
    long ||--o{ third : bar
    long {
        VARCHAR(50) bar
        DATE house
    }
    third ||--o{ character : officer
    third {
        DATE officer
        TEXT within
        VARCHAR(50) hotel
    }
    character ||--o{ art : interest
    character {
        VARCHAR(50) interest
        DATE car
    }
    art ||--o{ air : end
    art {
        DATE end
        TEXT kind
        VARCHAR(50) start
    }
    air ||--o{ reflect : response
    air {
        VARCHAR(50) response
        DATE whom
    }
    reflect ||--o{ way : eye
    reflect {
        DATE eye
        TEXT look
        VARCHAR(50) sign
    }