erDiagram
    room ||--o{ official : light
    room {
        DATE light
        TEXT recognize
        VARCHAR(50) read
    }
    official ||--o{ institution : price
    official {
        VARCHAR(50) price
        DATE laugh
    }
    institution ||--o{ tell : get
    institution {
        DATE get
        TEXT none
        VARCHAR(50) property
    }
    tell ||--o{ safe : road
    tell {
        VARCHAR(50) road
        DATE cup
    }
    safe ||--o{ easy : couple
    safe {
        DATE couple
        TEXT program
        VARCHAR(50) accept
    }
    easy ||--o{ onto : back
    easy {
        VARCHAR(50) back
        DATE not
    }
    onto ||--o{ room : finish
    onto {
        DATE finish
        TEXT nor
        VARCHAR(50) clearly
    }