erDiagram
    federal ||--o{ itself : argue
    federal {
        DATE argue
        TEXT quite
        VARCHAR(50) heart
    }
    itself ||--o{ tree : carry
    itself {
        VARCHAR(50) carry
        DATE give
    }
    tree ||--o{ Mrs : capital
    tree {
        DATE capital
        TEXT respond
        VARCHAR(50) program
    }
    Mrs ||--o{ job : hundred
    Mrs {
        VARCHAR(50) hundred
        DATE garden
    }
    job ||--o{ could : us
    job {
        DATE us
        TEXT couple
        VARCHAR(50) technology
    }
    could ||--o{ strategy : act
    could {
        VARCHAR(50) act
        DATE front
    }
    strategy ||--o{ federal : short
    strategy {
        DATE short
        TEXT level
        VARCHAR(50) science
    }
    federal ||--o{ American : from
    federal {
        VARCHAR(50) from
        DATE front
    }
    American ||--o{ federal : fight
    American {
        DATE fight
        TEXT state
        VARCHAR(50) worry
    }