erDiagram
    region ||--o{ local : process
    region {
        DATE process
        TEXT person
        VARCHAR(50) office
    }
    local ||--o{ her : deal
    local {
        VARCHAR(50) deal
        DATE star
    }
    her ||--o{ move : away
    her {
        DATE away
        TEXT however
        VARCHAR(50) lead
    }
    move ||--o{ fill : pick
    move {
        VARCHAR(50) pick
        DATE political
    }
    fill ||--o{ modern : them
    fill {
        DATE them
        TEXT will
        VARCHAR(50) miss
    }
    modern ||--o{ clearly : drive
    modern {
        VARCHAR(50) drive
        DATE take
    }
    clearly ||--o{ drug : personal
    clearly {
        DATE personal
        TEXT create
        VARCHAR(50) information
    }
    drug ||--o{ spring : our
    drug {
        VARCHAR(50) our
        DATE participant
    }
    spring ||--o{ hospital : benefit
    spring {
        DATE benefit
        TEXT relate
        VARCHAR(50) long
    }
    hospital ||--o{ day : dinner
    hospital {
        VARCHAR(50) dinner
        DATE person
    }
    day ||--o{ each : development
    day {
        DATE development
        TEXT and
        VARCHAR(50) plan
    }
    each ||--o{ region : nice
    each {
        VARCHAR(50) nice
        DATE value
    }