erDiagram
    recognize ||--o{ you : visit
    recognize {
        DATE visit
        TEXT bank
        VARCHAR(50) task
    }
    you ||--o{ it : management
    you {
        VARCHAR(50) management
        DATE after
    }
    it ||--o{ their : travel
    it {
        DATE travel
        TEXT situation
        VARCHAR(50) I
    }
    their ||--o{ because : to
    their {
        VARCHAR(50) to
    }
    because ||--o{ physical : strategy
    because {
        DATE strategy
        TEXT significant
        VARCHAR(50) weight
    }
    physical ||--o{ value : price
    physical {
        VARCHAR(50) price
        DATE author
    }
    value ||--o{ turn : treatment
    value {
        DATE treatment
        TEXT meet
        VARCHAR(50) let
    }
    turn ||--o{ create : job
    turn {
        VARCHAR(50) job
        DATE recent
    }
    create ||--o{ write : Democrat
    create {
        DATE Democrat
        TEXT nation
        VARCHAR(50) near
    }
    write ||--o{ cost : relate
    write {
        VARCHAR(50) relate
        DATE every
    }
    cost ||--o{ accept : assume
    cost {
        DATE assume
        TEXT morning
        VARCHAR(50) shake
    }
    accept ||--o{ recognize : avoid
    accept {
        VARCHAR(50) avoid
        DATE close
    }