erDiagram
    five ||--o{ foot : force
    five {
        DATE force
        TEXT leg
        VARCHAR(50) seven
    }
    foot ||--o{ surface : employee
    foot {
        VARCHAR(50) employee
        DATE floor
    }
    surface ||--o{ three : available
    surface {
        DATE available
        TEXT civil
        VARCHAR(50) performance
    }
    three ||--o{ ball : way
    three {
        VARCHAR(50) way
        DATE former
    }
    ball ||--o{ five : sell
    ball {
        DATE sell
        TEXT until
        VARCHAR(50) cost
    }