erDiagram
    decade ||--o{ song : he
    decade {
        DATE he
        TEXT maintain
        VARCHAR(50) minute
    }
    song ||--o{ present : human
    song {
        VARCHAR(50) human
        DATE member
    }
    present ||--o{ side : task
    present {
        DATE task
        TEXT church
        VARCHAR(50) question
    }
    side ||--o{ director : respond
    side {
        VARCHAR(50) respond
        DATE why
    }
    director ||--o{ health : beat
    director {
        DATE beat
        TEXT might
        VARCHAR(50) cover
    }
    health ||--o{ social : cut
    health {
        VARCHAR(50) cut
        DATE rise
    }
    social ||--o{ road : way
    social {
        DATE way
        TEXT play
        VARCHAR(50) least
    }
    road ||--o{ artist : brother
    road {
        VARCHAR(50) brother
        DATE road
    }
    artist ||--o{ Mrs : easy
    artist {
        DATE easy
        TEXT break
        VARCHAR(50) reason
    }
    Mrs ||--o{ recently : campaign
    Mrs {
        VARCHAR(50) campaign
        DATE owner
    }
    recently ||--o{ decade : green
    recently {
        DATE green
        TEXT positive
        VARCHAR(50) dinner
    }