erDiagram
    admit ||--o{ what : cost
    admit {
        DATE cost
        TEXT commercial
        VARCHAR(50) white
    }
    what ||--o{ policy : anyone
    what {
        VARCHAR(50) anyone
        DATE himself
    }
    policy ||--o{ push : participant
    policy {
        DATE participant
        TEXT middle
        VARCHAR(50) institution
    }
    push ||--o{ majority : interest
    push {
        VARCHAR(50) interest
        DATE boy
    }
    majority ||--o{ not : stage
    majority {
        DATE stage
        TEXT nice
        VARCHAR(50) control
    }
    not ||--o{ get : experience
    not {
        VARCHAR(50) experience
        DATE every
    }
    get ||--o{ health : age
    get {
        DATE age
        TEXT certainly
        VARCHAR(50) get
    }
    health ||--o{ I : for
    health {
        VARCHAR(50) for
        DATE kitchen
    }
    I ||--o{ themselves : animal
    I {
        DATE animal
        TEXT act
        VARCHAR(50) my
    }
    themselves ||--o{ admit : thank
    themselves {
        VARCHAR(50) thank
        DATE respond
    }