erDiagram
    draw ||--o{ discover : beat
    draw {
        DATE beat
        TEXT onto
        VARCHAR(50) there
    }
    discover ||--o{ current : half
    discover {
        VARCHAR(50) half
        DATE floor
    }
    current ||--o{ message : result
    current {
        DATE result
        TEXT step
        VARCHAR(50) positive
    }
    message ||--o{ treatment : very
    message {
        VARCHAR(50) very
        DATE hold
    }
    treatment ||--o{ road : agency
    treatment {
        DATE agency
        TEXT page
        VARCHAR(50) happy
    }
    road ||--o{ blood : audience
    road {
        VARCHAR(50) audience
        DATE imagine
    }
    blood ||--o{ provide : know
    blood {
        DATE know
        TEXT wind
        VARCHAR(50) spend
    }
    provide ||--o{ maybe : face
    provide {
        VARCHAR(50) face
        DATE again
    }
    maybe ||--o{ draw : yourself
    maybe {
        DATE yourself
        TEXT country
        VARCHAR(50) cold
    }