erDiagram
    environment ||--o{ although : machine
    environment {
        DATE machine
        TEXT institution
        VARCHAR(50) me
    }
    although ||--o{ among : contain
    although {
        VARCHAR(50) contain
        DATE large
    }
    among ||--o{ price : power
    among {
        DATE power
        TEXT fish
        VARCHAR(50) either
    }
    price ||--o{ whether : let
    price {
        VARCHAR(50) let
        DATE outside
    }
    whether ||--o{ plan : good
    whether {
        DATE good
        TEXT live
        VARCHAR(50) structure
    }
    plan ||--o{ go : whom
    plan {
        VARCHAR(50) whom
        DATE necessary
    }
    go ||--o{ economic : individual
    go {
        DATE individual
        TEXT design
        VARCHAR(50) likely
    }
    economic ||--o{ herself : financial
    economic {
        VARCHAR(50) financial
        DATE heart
    }
    herself ||--o{ environment : newspaper
    herself {
        DATE newspaper
        TEXT too
        VARCHAR(50) skin
    }