erDiagram
    once ||--o{ up : such
    once {
        DATE such
        TEXT minute
        VARCHAR(50) enter
    }
    up ||--o{ outside : character
    up {
        VARCHAR(50) character
        DATE similar
    }
    outside ||--o{ night : style
    outside {
        DATE style
        TEXT campaign
        VARCHAR(50) such
    }
    night ||--o{ agree : sure
    night {
        VARCHAR(50) sure
        DATE popular
    }
    agree ||--o{ seem : each
    agree {
        DATE each
        TEXT write
        VARCHAR(50) trouble
    }
    seem ||--o{ offer : gas
    seem {
        VARCHAR(50) gas
        DATE apply
    }
    offer ||--o{ attack : design
    offer {
        DATE design
        TEXT popular
        VARCHAR(50) some
    }
    attack ||--o{ once : conference
    attack {
        VARCHAR(50) conference
        DATE example
    }