erDiagram
    describe ||--o{ stage : early
    describe {
        DATE early
        TEXT may
        VARCHAR(50) religious
    }
    stage ||--o{ power : outside
    stage {
        VARCHAR(50) outside
        DATE worry
    }
    power ||--o{ evening : shoulder
    power {
        DATE shoulder
        TEXT produce
        VARCHAR(50) interview
    }
    evening ||--o{ garden : music
    evening {
        VARCHAR(50) music
        DATE she
    }
    garden ||--o{ personal : lot
    garden {
        DATE lot
        TEXT thing
        VARCHAR(50) less
    }
    personal ||--o{ church : area
    personal {
        VARCHAR(50) area
        DATE among
    }
    church ||--o{ evening : character
    church {
        DATE character
        TEXT report
        VARCHAR(50) well
    }
    evening ||--o{ move : too
    evening {
        VARCHAR(50) too
        DATE medical
    }
    move ||--o{ truth : year
    move {
        DATE year
        TEXT let
        VARCHAR(50) positive
    }
    truth ||--o{ beyond : common
    truth {
        VARCHAR(50) common
        DATE may
    }
    beyond ||--o{ describe : behavior
    beyond {
        DATE behavior
        TEXT word
        VARCHAR(50) mean
    }