erDiagram
    thousand ||--o{ media : smile
    thousand {
        DATE smile
        TEXT buy
        VARCHAR(50) civil
    }
    media ||--o{ question : perform
    media {
        VARCHAR(50) perform
        DATE level
    }
    question ||--o{ government : where
    question {
        DATE where
        TEXT investment
        VARCHAR(50) beautiful
    }
    government ||--o{ themselves : million
    government {
        VARCHAR(50) million
        DATE first
    }
    themselves ||--o{ as : some
    themselves {
        DATE some
        TEXT around
        VARCHAR(50) production
    }
    as ||--o{ itself : second
    as {
        VARCHAR(50) second
        DATE close
    }
    itself ||--o{ market : quite
    itself {
        DATE quite
        TEXT live
        VARCHAR(50) couple
    }
    market ||--o{ expect : television
    market {
        VARCHAR(50) television
        DATE near
    }
    expect ||--o{ though : fast
    expect {
        DATE fast
        TEXT kind
        VARCHAR(50) thousand
    }
    though ||--o{ one : buy
    though {
        VARCHAR(50) buy
        DATE same
    }
    one ||--o{ thousand : process
    one {
        DATE process
        TEXT poor
        VARCHAR(50) watch
    }