erDiagram
    measure ||--o{ also : gas
    measure {
        DATE gas
        TEXT protect
        VARCHAR(50) late
    }
    also ||--o{ choose : month
    also {
        VARCHAR(50) month
        DATE poor
    }
    choose ||--o{ catch : cover
    choose {
        DATE cover
        TEXT full
        VARCHAR(50) member
    }
    catch ||--o{ possible : myself
    catch {
        VARCHAR(50) myself
        DATE region
    }
    possible ||--o{ floor : wide
    possible {
        DATE wide
        TEXT lose
        VARCHAR(50) shake
    }
    floor ||--o{ southern : firm
    floor {
        VARCHAR(50) firm
        DATE concern
    }
    southern ||--o{ fly : civil
    southern {
        DATE civil
        TEXT blue
        VARCHAR(50) wind
    }
    fly ||--o{ measure : throw
    fly {
        VARCHAR(50) throw
        DATE paper
    }