erDiagram
    deal ||--o{ pay : national
    deal {
        DATE national
        TEXT go
        VARCHAR(50) seat
    }
    pay ||--o{ street : action
    pay {
        VARCHAR(50) action
        DATE news
    }
    street ||--o{ tend : it
    street {
        DATE it
        TEXT eye
        VARCHAR(50) fact
    }
    tend ||--o{ evidence : understand
    tend {
        VARCHAR(50) understand
        DATE money
    }
    evidence ||--o{ scientist : six
    evidence {
        DATE six
        TEXT happen
        VARCHAR(50) recognize
    }
    scientist ||--o{ interview : avoid
    scientist {
        VARCHAR(50) avoid
        DATE travel
    }
    interview ||--o{ network : game
    interview {
        DATE game
        TEXT product
        VARCHAR(50) investment
    }
    network ||--o{ case : score
    network {
        VARCHAR(50) score
        DATE imagine
    }
    case ||--o{ recently : however
    case {
        DATE however
        TEXT process
        VARCHAR(50) tax
    }
    recently ||--o{ national : agree
    recently {
        VARCHAR(50) agree
        DATE culture
    }
    national ||--o{ deal : brother
    national {
        DATE brother
        TEXT girl
        VARCHAR(50) picture
    }