erDiagram
    foreign ||--o{ plan : school
    foreign {
        DATE school
        TEXT fight
        VARCHAR(50) street
    }
    plan ||--o{ deep : know
    plan {
        VARCHAR(50) know
        DATE despite
    }
    deep ||--o{ morning : blue
    deep {
        DATE blue
        TEXT cause
        VARCHAR(50) organization
    }
    morning ||--o{ knowledge : treatment
    morning {
        VARCHAR(50) treatment
        DATE unit
    }
    knowledge ||--o{ theory : theory
    knowledge {
        DATE theory
        TEXT green
        VARCHAR(50) relate
    }
    theory ||--o{ year : remember
    theory {
        VARCHAR(50) remember
        DATE doctor
    }
    year ||--o{ part : oil
    year {
        DATE oil
        TEXT enter
        VARCHAR(50) attack
    }
    part ||--o{ moment : vote
    part {
        VARCHAR(50) vote
        DATE bad
    }
    moment ||--o{ plan : all
    moment {
        DATE all
        TEXT suggest
        VARCHAR(50) fast
    }
    plan ||--o{ after : various
    plan {
        VARCHAR(50) various
        DATE sport
    }
    after ||--o{ foreign : for
    after {
        DATE for
        TEXT amount
        VARCHAR(50) space
    }