erDiagram
    yet ||--o{ make : hear
    yet {
        DATE hear
        TEXT executive
        VARCHAR(50) piece
    }
    make ||--o{ focus : staff
    make {
        VARCHAR(50) staff
        DATE TV
    }
    focus ||--o{ beautiful : off
    focus {
        DATE off
        TEXT play
        VARCHAR(50) voice
    }
    beautiful ||--o{ five : social
    beautiful {
        VARCHAR(50) social
        DATE service
    }
    five ||--o{ federal : hair
    five {
        DATE hair
        TEXT later
        VARCHAR(50) party
    }
    federal ||--o{ ability : group
    federal {
        VARCHAR(50) group
        DATE several
    }
    ability ||--o{ food : agreement
    ability {
        DATE agreement
        TEXT customer
        VARCHAR(50) beautiful
    }
    food ||--o{ create : carry
    food {
        VARCHAR(50) carry
        DATE beautiful
    }
    create ||--o{ yet : approach
    create {
        DATE approach
        TEXT success
        VARCHAR(50) thing
    }