erDiagram
    hear ||--o{ probably : affect
    hear {
        DATE affect
        TEXT dream
        VARCHAR(50) inside
    }
    probably ||--o{ often : drug
    probably {
        VARCHAR(50) drug
        DATE some
    }
    often ||--o{ second : moment
    often {
        DATE moment
        TEXT prove
        VARCHAR(50) throw
    }
    second ||--o{ realize : make
    second {
        VARCHAR(50) make
        DATE after
    }
    realize ||--o{ show : guy
    realize {
        DATE guy
        TEXT who
        VARCHAR(50) institution
    }
    show ||--o{ hear : program
    show {
        VARCHAR(50) program
        DATE pass
    }