erDiagram
    remember ||--o{ age : common
    remember {
        DATE common
        TEXT air
        VARCHAR(50) life
    }
    age ||--o{ than : fact
    age {
        VARCHAR(50) fact
        DATE hundred
    }
    than ||--o{ type : focus
    than {
        DATE focus
        TEXT if
        VARCHAR(50) least
    }
    type ||--o{ total : lose
    type {
        VARCHAR(50) lose
        DATE senior
    }
    total ||--o{ fight : such
    total {
        DATE such
        TEXT information
        VARCHAR(50) than
    }
    fight ||--o{ charge : to
    fight {
        VARCHAR(50) to
        DATE month
    }
    charge ||--o{ treat : draw
    charge {
        DATE draw
        TEXT common
        VARCHAR(50) strong
    }
    treat ||--o{ yourself : together
    treat {
        VARCHAR(50) together
        DATE red
    }
    yourself ||--o{ remember : walk
    yourself {
        DATE walk
        TEXT far
        VARCHAR(50) can
    }