erDiagram
    buy ||--o{ dog : daughter
    buy {
        DATE daughter
        TEXT long
        VARCHAR(50) him
    }
    dog ||--o{ radio : agency
    dog {
        VARCHAR(50) agency
        DATE however
    }
    radio ||--o{ you : side
    radio {
        DATE side
        TEXT rich
        VARCHAR(50) cover
    }
    you ||--o{ bank : apply
    you {
        VARCHAR(50) apply
        DATE return
    }
    bank ||--o{ buy : condition
    bank {
        DATE condition
        TEXT yeah
        VARCHAR(50) prove
    }