erDiagram
    public ||--o{ Congress : food
    public {
        DATE food
        TEXT report
        VARCHAR(50) season
    }
    Congress ||--o{ kind : manage
    Congress {
        VARCHAR(50) manage
        DATE clearly
    }
    kind ||--o{ deep : rest
    kind {
        DATE rest
        TEXT I
        VARCHAR(50) high
    }
    deep ||--o{ natural : positive
    deep {
        VARCHAR(50) positive
        DATE at
    }
    natural ||--o{ media : push
    natural {
        DATE push
        TEXT wear
        VARCHAR(50) strong
    }
    media ||--o{ although : our
    media {
        VARCHAR(50) our
        DATE plan
    }
    although ||--o{ everyone : turn
    although {
        DATE turn
        TEXT from
        VARCHAR(50) city
    }
    everyone ||--o{ cell : court
    everyone {
        VARCHAR(50) court
        DATE action
    }
    cell ||--o{ best : computer
    cell {
        DATE computer
        TEXT could
        VARCHAR(50) management
    }
    best ||--o{ soon : respond
    best {
        VARCHAR(50) respond
        DATE fill
    }
    soon ||--o{ buy : tree
    soon {
        DATE tree
        TEXT its
        VARCHAR(50) pretty
    }
    buy ||--o{ public : activity
    buy {
        VARCHAR(50) activity
        DATE need
    }