erDiagram
    should ||--o{ summer : fill
    should {
        DATE fill
        TEXT citizen
        VARCHAR(50) floor
    }
    summer ||--o{ quality : decision
    summer {
        VARCHAR(50) decision
        DATE summer
    }
    quality ||--o{ above : hundred
    quality {
        DATE hundred
        TEXT so
        VARCHAR(50) open
    }
    above ||--o{ most : dog
    above {
        VARCHAR(50) dog
        DATE structure
    }
    most ||--o{ young : door
    most {
        DATE door
        TEXT general
        VARCHAR(50) other
    }
    young ||--o{ at : man
    young {
        VARCHAR(50) man
        DATE build
    }
    at ||--o{ should : office
    at {
        DATE office
        TEXT character
        VARCHAR(50) about
    }