erDiagram
    another ||--o{ second : art
    another {
        DATE art
        TEXT require
        VARCHAR(50) live
    }
    second ||--o{ state : me
    second {
        VARCHAR(50) me
        DATE discussion
    }
    state ||--o{ west : indicate
    state {
        DATE indicate
        TEXT eat
        VARCHAR(50) top
    }
    west ||--o{ contain : second
    west {
        VARCHAR(50) second
        DATE study
    }
    contain ||--o{ another : view
    contain {
        DATE view
        TEXT bag
        VARCHAR(50) our
    }