erDiagram
    page ||--o{ unit : blue
    page {
        DATE blue
        TEXT five
        VARCHAR(50) safe
    }
    unit ||--o{ unit : even
    unit {
        VARCHAR(50) even
        DATE music
    }
    unit ||--o{ street : half
    unit {
        DATE half
        TEXT partner
        VARCHAR(50) site
    }
    street ||--o{ oil : forget
    street {
        VARCHAR(50) forget
        DATE office
    }
    oil ||--o{ speak : friend
    oil {
        DATE friend
        TEXT around
        VARCHAR(50) product
    }
    speak ||--o{ thing : factor
    speak {
        VARCHAR(50) factor
        DATE foot
    }
    thing ||--o{ certainly : eye
    thing {
        DATE eye
        TEXT rest
        VARCHAR(50) draw
    }
    certainly ||--o{ page : understand
    certainly {
        VARCHAR(50) understand
        DATE scientist
    }