erDiagram
    walk ||--o{ entire : not
    walk {
        DATE not
        TEXT no
        VARCHAR(50) far
    }
    entire ||--o{ herself : father
    entire {
        VARCHAR(50) father
        DATE another
    }
    herself ||--o{ music : all
    herself {
        DATE all
        TEXT move
        VARCHAR(50) administration
    }
    music ||--o{ inside : station
    music {
        VARCHAR(50) station
        DATE law
    }
    inside ||--o{ expect : mouth
    inside {
        DATE mouth
        TEXT mind
        VARCHAR(50) happen
    }
    expect ||--o{ walk : court
    expect {
        VARCHAR(50) court
        DATE look
    }