erDiagram
    sort ||--o{ among : ready
    sort {
        DATE ready
        TEXT manage
        VARCHAR(50) including
    }
    among ||--o{ forward : stuff
    among {
        VARCHAR(50) stuff
        DATE cultural
    }
    forward ||--o{ its : first
    forward {
        DATE first
        TEXT image
        VARCHAR(50) there
    }
    its ||--o{ but : break
    its {
        VARCHAR(50) break
        DATE with
    }
    but ||--o{ thus : town
    but {
        DATE town
        TEXT spend
        VARCHAR(50) nature
    }
    thus ||--o{ song : from
    thus {
        VARCHAR(50) from
        DATE board
    }
    song ||--o{ use : senior
    song {
        DATE senior
        TEXT gas
        VARCHAR(50) discussion
    }
    use ||--o{ sort : within
    use {
        VARCHAR(50) within
        DATE east
    }