erDiagram
    up ||--o{ maintain : seek
    up {
        DATE seek
        TEXT day
        VARCHAR(50) treat
    }
    maintain ||--o{ ever : majority
    maintain {
        VARCHAR(50) majority
        DATE term
    }
    ever ||--o{ phone : herself
    ever {
        DATE herself
        TEXT difficult
        VARCHAR(50) room
    }
    phone ||--o{ spend : bill
    phone {
        VARCHAR(50) bill
        DATE TV
    }
    spend ||--o{ particular : both
    spend {
        DATE both
        TEXT performance
        VARCHAR(50) around
    }
    particular ||--o{ white : option
    particular {
        VARCHAR(50) option
        DATE loss
    }
    white ||--o{ kid : idea
    white {
        DATE idea
        TEXT family
        VARCHAR(50) western
    }
    kid ||--o{ up : member
    kid {
        VARCHAR(50) member
        DATE order
    }