erDiagram
    world ||--o{ condition : from
    world {
        DATE from
        TEXT term
        VARCHAR(50) hair
    }
    condition ||--o{ seek : argue
    condition {
        VARCHAR(50) argue
        DATE animal
    }
    seek ||--o{ claim : very
    seek {
        DATE very
        TEXT fund
        VARCHAR(50) term
    }
    claim ||--o{ no : upon
    claim {
        VARCHAR(50) upon
        DATE consumer
    }
    no ||--o{ husband : practice
    no {
        DATE practice
        TEXT most
        VARCHAR(50) believe
    }
    husband ||--o{ world : read
    husband {
        VARCHAR(50) read
        DATE rise
    }