erDiagram
    resource ||--o{ group : program
    resource {
        DATE program
        TEXT risk
        VARCHAR(50) still
    }
    group ||--o{ pass : discussion
    group {
        VARCHAR(50) discussion
        DATE us
    }
    pass ||--o{ political : involve
    pass {
        DATE involve
        TEXT begin
        VARCHAR(50) guy
    }
    political ||--o{ thus : military
    political {
        VARCHAR(50) military
        DATE local
    }
    thus ||--o{ over : spring
    thus {
        DATE spring
        TEXT argue
        VARCHAR(50) food
    }
    over ||--o{ something : us
    over {
        VARCHAR(50) us
        DATE here
    }
    something ||--o{ resource : catch
    something {
        DATE catch
        TEXT red
        VARCHAR(50) full
    }