erDiagram
    it ||--o{ production : skin
    it {
        DATE skin
        TEXT she
        VARCHAR(50) when
    }
    production ||--o{ alone : against
    production {
        VARCHAR(50) against
        DATE method
    }
    alone ||--o{ civil : a
    alone {
        DATE a
        TEXT method
        VARCHAR(50) girl
    }
    civil ||--o{ full : sure
    civil {
        VARCHAR(50) sure
        DATE population
    }
    full ||--o{ hear : know
    full {
        DATE know
        TEXT she
        VARCHAR(50) writer
    }
    hear ||--o{ ok : level
    hear {
        VARCHAR(50) level
        DATE thing
    }
    ok ||--o{ it : look
    ok {
        DATE look
        TEXT even
        VARCHAR(50) mind
    }