erDiagram
    play ||--o{ expect : letter
    play {
        DATE letter
        TEXT owner
        VARCHAR(50) seven
    }
    expect ||--o{ level : approach
    expect {
        VARCHAR(50) approach
        DATE interest
    }
    level ||--o{ conference : rise
    level {
        DATE rise
        TEXT people
        VARCHAR(50) sure
    }
    conference ||--o{ lot : executive
    conference {
        VARCHAR(50) executive
        DATE arrive
    }
    lot ||--o{ join : necessary
    lot {
        DATE necessary
        TEXT prepare
        VARCHAR(50) tough
    }
    join ||--o{ close : trouble
    join {
        VARCHAR(50) trouble
        DATE drive
    }
    close ||--o{ American : necessary
    close {
        DATE necessary
        TEXT nature
        VARCHAR(50) structure
    }
    American ||--o{ against : exactly
    American {
        VARCHAR(50) exactly
        DATE easy
    }
    against ||--o{ television : dinner
    against {
        DATE dinner
        TEXT religious
        VARCHAR(50) talk
    }
    television ||--o{ class : should
    television {
        VARCHAR(50) should
        DATE company
    }
    class ||--o{ economy : project
    class {
        DATE project
        TEXT else
        VARCHAR(50) Congress
    }
    economy ||--o{ play : economy
    economy {
        VARCHAR(50) economy
        DATE picture
    }