erDiagram
    save ||--o{ new : thank
    save {
        DATE thank
        TEXT low
        VARCHAR(50) whether
    }
    new ||--o{ no : health
    new {
        VARCHAR(50) health
        DATE first
    }
    no ||--o{ partner : indeed
    no {
        DATE indeed
        TEXT choose
        VARCHAR(50) exist
    }
    partner ||--o{ which : amount
    partner {
        VARCHAR(50) amount
        DATE security
    }
    which ||--o{ audience : size
    which {
        DATE size
        TEXT account
        VARCHAR(50) also
    }
    audience ||--o{ save : sea
    audience {
        VARCHAR(50) sea
        DATE age
    }