erDiagram
    interesting ||--o{ yet : speech
    interesting {
        DATE speech
        TEXT Democrat
        VARCHAR(50) capital
    }
    yet ||--o{ dog : fight
    yet {
        VARCHAR(50) fight
        DATE prove
    }
    dog ||--o{ certain : often
    dog {
        DATE often
        TEXT left
        VARCHAR(50) per
    }
    certain ||--o{ store : democratic
    certain {
        VARCHAR(50) democratic
        DATE growth
    }
    store ||--o{ sport : mean
    store {
        DATE mean
        TEXT camera
        VARCHAR(50) need
    }
    sport ||--o{ social : ability
    sport {
        VARCHAR(50) ability
        DATE space
    }
    social ||--o{ who : former
    social {
        DATE former
        TEXT enter
        VARCHAR(50) style
    }
    who ||--o{ interesting : war
    who {
        VARCHAR(50) war
        DATE campaign
    }