erDiagram
    health ||--o{ story : audience
    health {
        DATE audience
        TEXT particularly
        VARCHAR(50) report
    }
    story ||--o{ bar : indicate
    story {
        VARCHAR(50) indicate
        DATE baby
    }
    bar ||--o{ scientist : mouth
    bar {
        DATE mouth
        TEXT toward
        VARCHAR(50) democratic
    }
    scientist ||--o{ tough : how
    scientist {
        VARCHAR(50) how
        DATE low
    }
    tough ||--o{ somebody : real
    tough {
        DATE real
        TEXT especially
        VARCHAR(50) why
    }
    somebody ||--o{ catch : whole
    somebody {
        VARCHAR(50) whole
        DATE item
    }
    catch ||--o{ sing : give
    catch {
        DATE give
        TEXT environment
        VARCHAR(50) recent
    }
    sing ||--o{ save : mention
    sing {
        VARCHAR(50) mention
        DATE interview
    }
    save ||--o{ simple : our
    save {
        DATE our
        TEXT authority
        VARCHAR(50) save
    }
    simple ||--o{ health : military
    simple {
        VARCHAR(50) military
        DATE loss
    }