erDiagram
    still ||--o{ morning : push
    still {
        DATE push
        TEXT center
        VARCHAR(50) should
    }
    morning ||--o{ almost : knowledge
    morning {
        VARCHAR(50) knowledge
        DATE water
    }
    almost ||--o{ dinner : around
    almost {
        DATE around
        TEXT civil
        VARCHAR(50) rock
    }
    dinner ||--o{ side : far
    dinner {
        VARCHAR(50) far
        DATE firm
    }
    side ||--o{ want : reason
    side {
        DATE reason
        TEXT other
        VARCHAR(50) data
    }
    want ||--o{ everybody : Mrs
    want {
        VARCHAR(50) Mrs
        DATE nearly
    }
    everybody ||--o{ still : happen
    everybody {
        DATE happen
        TEXT under
        VARCHAR(50) treatment
    }