erDiagram
    figure ||--o{ student : apply
    figure {
        DATE apply
        TEXT understand
        VARCHAR(50) public
    }
    student ||--o{ say : choice
    student {
        VARCHAR(50) choice
        DATE too
    }
    say ||--o{ various : drug
    say {
        DATE drug
        TEXT approach
        VARCHAR(50) too
    }
    various ||--o{ task : source
    various {
        VARCHAR(50) source
        DATE executive
    }
    task ||--o{ quickly : again
    task {
        DATE again
        TEXT chair
        VARCHAR(50) fine
    }
    quickly ||--o{ lay : build
    quickly {
        VARCHAR(50) build
        DATE city
    }
    lay ||--o{ politics : week
    lay {
        DATE week
        TEXT something
        VARCHAR(50) go
    }
    politics ||--o{ along : student
    politics {
        VARCHAR(50) student
        DATE sound
    }
    along ||--o{ figure : serious
    along {
        DATE serious
        TEXT indeed
        VARCHAR(50) interview
    }