erDiagram
    maintain ||--o{ gas : offer
    maintain {
        DATE offer
        TEXT design
        VARCHAR(50) now
    }
    gas ||--o{ able : it
    gas {
        VARCHAR(50) it
        DATE food
    }
    able ||--o{ small : yourself
    able {
        DATE yourself
        TEXT democratic
        VARCHAR(50) many
    }
    small ||--o{ billion : admit
    small {
        VARCHAR(50) admit
        DATE public
    }
    billion ||--o{ bit : show
    billion {
        DATE show
        TEXT with
        VARCHAR(50) wife
    }
    bit ||--o{ you : camera
    bit {
        VARCHAR(50) camera
        DATE eye
    }
    you ||--o{ miss : hope
    you {
        DATE hope
        TEXT finally
        VARCHAR(50) save
    }
    miss ||--o{ newspaper : together
    miss {
        VARCHAR(50) together
        DATE difficult
    }
    newspaper ||--o{ often : oil
    newspaper {
        DATE oil
        TEXT management
        VARCHAR(50) institution
    }
    often ||--o{ maintain : us
    often {
        VARCHAR(50) us
        DATE maintain
    }