erDiagram
    space ||--o{ skin : pattern
    space {
        DATE pattern
        TEXT bit
        VARCHAR(50) western
    }
    skin ||--o{ other : hope
    skin {
        VARCHAR(50) hope
        DATE occur
    }
    other ||--o{ but : relationship
    other {
        DATE relationship
        TEXT idea
        VARCHAR(50) mean
    }
    but ||--o{ soldier : job
    but {
        VARCHAR(50) job
        DATE cell
    }
    soldier ||--o{ citizen : low
    soldier {
        DATE low
        TEXT situation
        VARCHAR(50) right
    }
    citizen ||--o{ surface : however
    citizen {
        VARCHAR(50) however
        DATE television
    }
    surface ||--o{ catch : peace
    surface {
        DATE peace
        TEXT possible
        VARCHAR(50) than
    }
    catch ||--o{ easy : catch
    catch {
        VARCHAR(50) catch
        DATE western
    }
    easy ||--o{ receive : majority
    easy {
        DATE majority
        TEXT four
        VARCHAR(50) true
    }
    receive ||--o{ space : very
    receive {
        VARCHAR(50) very
        DATE ahead
    }