erDiagram
    anyone ||--o{ also : color
    anyone {
        DATE color
        TEXT reflect
        VARCHAR(50) message
    }
    also ||--o{ affect : nation
    also {
        VARCHAR(50) nation
        DATE after
    }
    affect ||--o{ action : every
    affect {
        DATE every
        TEXT sense
        VARCHAR(50) back
    }
    action ||--o{ together : ability
    action {
        VARCHAR(50) ability
        DATE simple
    }
    together ||--o{ thought : add
    together {
        DATE add
        TEXT east
        VARCHAR(50) significant
    }
    thought ||--o{ yourself : set
    thought {
        VARCHAR(50) set
        DATE home
    }
    yourself ||--o{ great : key
    yourself {
        DATE key
        TEXT as
        VARCHAR(50) this
    }
    great ||--o{ social : when
    great {
        VARCHAR(50) when
        DATE oil
    }
    social ||--o{ agreement : tree
    social {
        DATE tree
        TEXT us
        VARCHAR(50) water
    }
    agreement ||--o{ third : become
    agreement {
        VARCHAR(50) become
        DATE drive
    }
    third ||--o{ anyone : song
    third {
        DATE song
        TEXT perform
        VARCHAR(50) past
    }