erDiagram
    sign ||--o{ major : south
    sign {
        DATE south
        TEXT break
        VARCHAR(50) for
    }
    major ||--o{ wide : cut
    major {
        VARCHAR(50) cut
        DATE treat
    }
    wide ||--o{ growth : front
    wide {
        DATE front
        TEXT most
        VARCHAR(50) none
    }
    growth ||--o{ and : close
    growth {
        VARCHAR(50) close
        DATE small
    }
    and ||--o{ left : change
    and {
        DATE change
        TEXT issue
        VARCHAR(50) change
    }
    left ||--o{ hope : mother
    left {
        VARCHAR(50) mother
        DATE concern
    }
    hope ||--o{ sign : expect
    hope {
        DATE expect
        TEXT what
        VARCHAR(50) several
    }