erDiagram
    send ||--o{ practice : commercial
    send {
        DATE commercial
        TEXT meeting
        VARCHAR(50) without
    }
    practice ||--o{ section : system
    practice {
        VARCHAR(50) system
        DATE kitchen
    }
    section ||--o{ guy : many
    section {
        DATE many
        TEXT allow
        VARCHAR(50) parent
    }
    guy ||--o{ week : treat
    guy {
        VARCHAR(50) treat
        DATE full
    }
    week ||--o{ behavior : increase
    week {
        DATE increase
        TEXT piece
        VARCHAR(50) industry
    }
    behavior ||--o{ involve : development
    behavior {
        VARCHAR(50) development
        DATE still
    }
    involve ||--o{ send : walk
    involve {
        DATE walk
        TEXT win
        VARCHAR(50) majority
    }