erDiagram
    employee ||--o{ concern : list
    employee {
        DATE list
        TEXT explain
        VARCHAR(50) term
    }
    concern ||--o{ see : though
    concern {
        VARCHAR(50) though
        DATE early
    }
    see ||--o{ billion : weight
    see {
        DATE weight
        TEXT despite
        VARCHAR(50) would
    }
    billion ||--o{ call : wear
    billion {
        VARCHAR(50) wear
        DATE peace
    }
    call ||--o{ near : admit
    call {
        DATE admit
        TEXT nation
        VARCHAR(50) pattern
    }
    near ||--o{ employee : among
    near {
        VARCHAR(50) among
        DATE me
    }