erDiagram
    other ||--o{ probably : bit
    other {
        DATE bit
        TEXT care
        VARCHAR(50) three
    }
    probably ||--o{ short : door
    probably {
        VARCHAR(50) door
        DATE market
    }
    short ||--o{ war : majority
    short {
        DATE majority
        TEXT real
        VARCHAR(50) debate
    }
    war ||--o{ worry : moment
    war {
        VARCHAR(50) moment
        DATE whom
    }
    worry ||--o{ beat : within
    worry {
        DATE within
        TEXT left
        VARCHAR(50) tough
    }
    beat ||--o{ section : away
    beat {
        VARCHAR(50) away
        DATE value
    }
    section ||--o{ he : some
    section {
        DATE some
        TEXT woman
        VARCHAR(50) walk
    }
    he ||--o{ agency : toward
    he {
        VARCHAR(50) toward
        DATE interview
    }
    agency ||--o{ there : TV
    agency {
        DATE TV
        TEXT TV
        VARCHAR(50) help
    }
    there ||--o{ soldier : PM
    there {
        VARCHAR(50) PM
        DATE road
    }
    soldier ||--o{ other : help
    soldier {
        DATE help
        TEXT leave
        VARCHAR(50) single
    }