erDiagram
    somebody ||--o{ rate : ball
    somebody {
        DATE ball
        TEXT message
        VARCHAR(50) stuff
    }
    rate ||--o{ size : conference
    rate {
        VARCHAR(50) conference
        DATE later
    }
    size ||--o{ sing : any
    size {
        DATE any
        TEXT decade
        VARCHAR(50) table
    }
    sing ||--o{ much : defense
    sing {
        VARCHAR(50) defense
        DATE live
    }
    much ||--o{ somebody : contain
    much {
        DATE contain
        TEXT scene
        VARCHAR(50) bad
    }