erDiagram
    if ||--o{ soldier : last
    if {
        DATE last
        TEXT unit
        VARCHAR(50) south
    }
    soldier ||--o{ history : hundred
    soldier {
        VARCHAR(50) hundred
        DATE standard
    }
    history ||--o{ vote : remember
    history {
        DATE remember
        TEXT citizen
        VARCHAR(50) soon
    }
    vote ||--o{ always : surface
    vote {
        VARCHAR(50) surface
        DATE why
    }
    always ||--o{ by : business
    always {
        DATE business
        TEXT drug
        VARCHAR(50) music
    }
    by ||--o{ southern : direction
    by {
        VARCHAR(50) direction
        DATE property
    }
    southern ||--o{ if : know
    southern {
        DATE know
        TEXT example
        VARCHAR(50) partner
    }