erDiagram
    strategy ||--o{ manager : seven
    strategy {
        DATE seven
        TEXT southern
        VARCHAR(50) rise
    }
    manager ||--o{ protect : event
    manager {
        VARCHAR(50) event
        DATE avoid
    }
    protect ||--o{ account : determine
    protect {
        DATE determine
        TEXT party
        VARCHAR(50) sure
    }
    account ||--o{ building : pattern
    account {
        VARCHAR(50) pattern
        DATE develop
    }
    building ||--o{ bank : light
    building {
        DATE light
        TEXT interest
        VARCHAR(50) somebody
    }
    bank ||--o{ teach : design
    bank {
        VARCHAR(50) design
        DATE report
    }
    teach ||--o{ strategy : yeah
    teach {
        DATE yeah
        TEXT particular
        VARCHAR(50) watch
    }