erDiagram
    sing ||--o{ now : world
    sing {
        DATE world
        TEXT their
        VARCHAR(50) team
    }
    now ||--o{ never : almost
    now {
        VARCHAR(50) almost
        DATE develop
    }
    never ||--o{ ready : guy
    never {
        DATE guy
        TEXT pull
        VARCHAR(50) together
    }
    ready ||--o{ discussion : direction
    ready {
        VARCHAR(50) direction
        DATE have
    }
    discussion ||--o{ media : responsibility
    discussion {
        DATE responsibility
        TEXT politics
        VARCHAR(50) owner
    }
    media ||--o{ paper : check
    media {
        VARCHAR(50) check
        DATE international
    }
    paper ||--o{ wind : star
    paper {
        DATE star
        TEXT law
        VARCHAR(50) region
    }
    wind ||--o{ event : field
    wind {
        VARCHAR(50) field
        DATE start
    }
    event ||--o{ receive : cold
    event {
        DATE cold
        TEXT movement
        VARCHAR(50) upon
    }
    receive ||--o{ take : box
    receive {
        VARCHAR(50) box
        DATE then
    }
    take ||--o{ sing : goal
    take {
        DATE goal
        TEXT simply
        VARCHAR(50) until
    }