erDiagram
    according ||--o{ quality : husband
    according {
        DATE husband
        TEXT series
        VARCHAR(50) picture
    }
    quality ||--o{ party : discussion
    quality {
        VARCHAR(50) discussion
        DATE skin
    }
    party ||--o{ every : develop
    party {
        DATE develop
        TEXT often
        VARCHAR(50) Democrat
    }
    every ||--o{ pretty : consider
    every {
        VARCHAR(50) consider
        DATE along
    }
    pretty ||--o{ black : child
    pretty {
        DATE child
        TEXT nature
        VARCHAR(50) themselves
    }
    black ||--o{ according : again
    black {
        VARCHAR(50) again
        DATE science
    }