erDiagram
    owner ||--o{ board : must
    owner {
        DATE must
        TEXT step
        VARCHAR(50) mind
    }
    board ||--o{ federal : data
    board {
        VARCHAR(50) data
        DATE moment
    }
    federal ||--o{ field : environmental
    federal {
        DATE environmental
        TEXT skill
        VARCHAR(50) eye
    }
    field ||--o{ available : kid
    field {
        VARCHAR(50) kid
        DATE collection
    }
    available ||--o{ some : he
    available {
        DATE he
        TEXT eat
        VARCHAR(50) without
    }
    some ||--o{ discuss : memory
    some {
        VARCHAR(50) memory
        DATE window
    }
    discuss ||--o{ owner : model
    discuss {
        DATE model
        TEXT next
        VARCHAR(50) pass
    }