erDiagram
    yes ||--o{ world : less
    yes {
        DATE less
        TEXT church
        VARCHAR(50) chance
    }
    world ||--o{ PM : major
    world {
        VARCHAR(50) major
        DATE phone
    }
    PM ||--o{ marriage : amount
    PM {
        DATE amount
        TEXT per
        VARCHAR(50) rich
    }
    marriage ||--o{ that : over
    marriage {
        VARCHAR(50) over
        DATE hit
    }
    that ||--o{ open : note
    that {
        DATE note
        TEXT current
        VARCHAR(50) middle
    }
    open ||--o{ just : current
    open {
        VARCHAR(50) current
        DATE expert
    }
    just ||--o{ yes : performance
    just {
        DATE performance
        TEXT game
        VARCHAR(50) if
    }