erDiagram
    everyone ||--o{ only : community
    everyone {
        DATE community
        TEXT he
        VARCHAR(50) hotel
    }
    only ||--o{ rich : nature
    only {
        VARCHAR(50) nature
        DATE interesting
    }
    rich ||--o{ safe : wide
    rich {
        DATE wide
        TEXT difficult
        VARCHAR(50) street
    }
    safe ||--o{ tell : body
    safe {
        VARCHAR(50) body
        DATE dog
    }
    tell ||--o{ so : dinner
    tell {
        DATE dinner
        TEXT Congress
        VARCHAR(50) explain
    }
    so ||--o{ meeting : especially
    so {
        VARCHAR(50) especially
        DATE four
    }
    meeting ||--o{ yard : new
    meeting {
        DATE new
        TEXT because
        VARCHAR(50) final
    }
    yard ||--o{ everyone : body
    yard {
        VARCHAR(50) body
        DATE candidate
    }