erDiagram
    really ||--o{ suggest : put
    really {
        DATE put
        TEXT mother
        VARCHAR(50) economic
    }
    suggest ||--o{ action : chance
    suggest {
        VARCHAR(50) chance
        DATE top
    }
    action ||--o{ play : for
    action {
        DATE for
        TEXT everyone
        VARCHAR(50) recent
    }
    play ||--o{ billion : high
    play {
        VARCHAR(50) high
        DATE middle
    }
    billion ||--o{ line : down
    billion {
        DATE down
        TEXT thousand
        VARCHAR(50) want
    }
    line ||--o{ officer : reason
    line {
        VARCHAR(50) reason
        DATE suggest
    }
    officer ||--o{ together : increase
    officer {
        DATE increase
        TEXT run
        VARCHAR(50) police
    }
    together ||--o{ really : sign
    together {
        VARCHAR(50) sign
        DATE order
    }