erDiagram
    ever ||--o{ available : plan
    ever {
        DATE plan
        TEXT third
        VARCHAR(50) above
    }
    available ||--o{ contain : boy
    available {
        VARCHAR(50) boy
        DATE might
    }
    contain ||--o{ present : go
    contain {
        DATE go
        TEXT he
        VARCHAR(50) five
    }
    present ||--o{ consider : military
    present {
        VARCHAR(50) military
        DATE participant
    }
    consider ||--o{ respond : sit
    consider {
        DATE sit
        TEXT trade
        VARCHAR(50) eye
    }
    respond ||--o{ purpose : tonight
    respond {
        VARCHAR(50) tonight
        DATE run
    }
    purpose ||--o{ itself : not
    purpose {
        DATE not
        TEXT young
        VARCHAR(50) society
    }
    itself ||--o{ teach : voice
    itself {
        VARCHAR(50) voice
        DATE very
    }
    teach ||--o{ successful : agree
    teach {
        DATE agree
        TEXT rather
        VARCHAR(50) billion
    }
    successful ||--o{ must : song
    successful {
        VARCHAR(50) song
        DATE everything
    }
    must ||--o{ ever : of
    must {
        DATE of
        TEXT show
        VARCHAR(50) popular
    }