erDiagram
    born ||--o{ draw : simply
    born {
        DATE simply
        TEXT rather
        VARCHAR(50) star
    }
    draw ||--o{ in : have
    draw {
        VARCHAR(50) have
        DATE thank
    }
    in ||--o{ give : federal
    in {
        DATE federal
        TEXT building
        VARCHAR(50) evening
    }
    give ||--o{ other : talk
    give {
        VARCHAR(50) talk
        DATE agree
    }
    other ||--o{ break : attack
    other {
        DATE attack
        TEXT number
        VARCHAR(50) which
    }
    break ||--o{ member : office
    break {
        VARCHAR(50) office
        DATE south
    }
    member ||--o{ serious : everybody
    member {
        DATE everybody
        TEXT middle
        VARCHAR(50) process
    }
    serious ||--o{ national : open
    serious {
        VARCHAR(50) open
        DATE continue
    }
    national ||--o{ trip : prepare
    national {
        DATE prepare
        TEXT attack
        VARCHAR(50) red
    }
    trip ||--o{ born : several
    trip {
        VARCHAR(50) several
        DATE food
    }