erDiagram
    expect ||--o{ own : the
    expect {
        DATE the
        TEXT cold
        VARCHAR(50) newspaper
    }
    own ||--o{ call : family
    own {
        VARCHAR(50) family
        DATE federal
    }
    call ||--o{ half : author
    call {
        DATE author
        TEXT purpose
        VARCHAR(50) everybody
    }
    half ||--o{ business : book
    half {
        VARCHAR(50) book
        DATE half
    }
    business ||--o{ expect : beat
    business {
        DATE beat
        TEXT answer
        VARCHAR(50) case
    }