erDiagram
    per ||--o{ likely : drive
    per {
        DATE drive
        TEXT let
        VARCHAR(50) top
    }
    likely ||--o{ pressure : no
    likely {
        VARCHAR(50) no
        DATE drive
    }
    pressure ||--o{ oil : really
    pressure {
        DATE really
        TEXT individual
        VARCHAR(50) raise
    }
    oil ||--o{ statement : four
    oil {
        VARCHAR(50) four
        DATE road
    }
    statement ||--o{ number : class
    statement {
        DATE class
        TEXT old
        VARCHAR(50) song
    }
    number ||--o{ real : information
    number {
        VARCHAR(50) information
        DATE participant
    }
    real ||--o{ major : rule
    real {
        DATE rule
        TEXT entire
        VARCHAR(50) option
    }
    major ||--o{ half : set
    major {
        VARCHAR(50) set
        DATE door
    }
    half ||--o{ cell : loss
    half {
        DATE loss
        TEXT nothing
        VARCHAR(50) simple
    }
    cell ||--o{ box : us
    cell {
        VARCHAR(50) us
        DATE shoulder
    }
    box ||--o{ improve : adult
    box {
        DATE adult
        TEXT onto
        VARCHAR(50) role
    }
    improve ||--o{ per : box
    improve {
        VARCHAR(50) box
        DATE part
    }