erDiagram
    would ||--o{ budget : people
    would {
        DATE people
        TEXT Mr
        VARCHAR(50) responsibility
    }
    budget ||--o{ modern : enough
    budget {
        VARCHAR(50) enough
        DATE read
    }
    modern ||--o{ career : small
    modern {
        DATE small
        TEXT usually
        VARCHAR(50) allow
    }
    career ||--o{ charge : perform
    career {
        VARCHAR(50) perform
        DATE food
    }
    charge ||--o{ rise : city
    charge {
        DATE city
        TEXT civil
        VARCHAR(50) view
    }
    rise ||--o{ data : break
    rise {
        VARCHAR(50) break
        DATE see
    }
    data ||--o{ decision : manager
    data {
        DATE manager
        TEXT carry
        VARCHAR(50) candidate
    }
    decision ||--o{ you : already
    decision {
        VARCHAR(50) already
        DATE back
    }
    you ||--o{ find : six
    you {
        DATE six
        TEXT area
        VARCHAR(50) really
    }
    find ||--o{ would : former
    find {
        VARCHAR(50) former
        DATE produce
    }