erDiagram
    interview ||--o{ fire : relate
    interview {
        DATE relate
        TEXT discover
        VARCHAR(50) consider
    }
    fire ||--o{ bring : use
    fire {
        VARCHAR(50) use
        DATE standard
    }
    bring ||--o{ left : project
    bring {
        DATE project
        TEXT rule
        VARCHAR(50) billion
    }
    left ||--o{ stage : however
    left {
        VARCHAR(50) however
        DATE pass
    }
    stage ||--o{ husband : staff
    stage {
        DATE staff
        TEXT sign
        VARCHAR(50) hospital
    }
    husband ||--o{ box : floor
    husband {
        VARCHAR(50) floor
        DATE PM
    }
    box ||--o{ interview : military
    box {
        DATE military
        TEXT across
        VARCHAR(50) rock
    }