erDiagram
    perform ||--o{ send : their
    perform {
        DATE their
        TEXT garden
        VARCHAR(50) government
    }
    send ||--o{ third : development
    send {
        VARCHAR(50) development
        DATE college
    }
    third ||--o{ recent : audience
    third {
        DATE audience
        TEXT part
        VARCHAR(50) draw
    }
    recent ||--o{ pick : reality
    recent {
        VARCHAR(50) reality
        DATE go
    }
    pick ||--o{ around : cut
    pick {
        DATE cut
        TEXT store
        VARCHAR(50) machine
    }
    around ||--o{ hit : cultural
    around {
        VARCHAR(50) cultural
        DATE prepare
    }
    hit ||--o{ character : first
    hit {
        DATE first
        TEXT mother
        VARCHAR(50) amount
    }
    character ||--o{ government : response
    character {
        VARCHAR(50) response
        DATE peace
    }
    government ||--o{ use : lot
    government {
        DATE lot
        TEXT southern
        VARCHAR(50) you
    }
    use ||--o{ spring : either
    use {
        VARCHAR(50) either
        DATE sea
    }
    spring ||--o{ avoid : exactly
    spring {
        DATE exactly
        TEXT bring
        VARCHAR(50) environmental
    }
    avoid ||--o{ perform : country
    avoid {
        VARCHAR(50) country
        DATE message
    }