erDiagram
    form ||--o{ sound : attack
    form {
        DATE attack
        TEXT even
        VARCHAR(50) mention
    }
    sound ||--o{ poor : expect
    sound {
        VARCHAR(50) expect
        DATE perhaps
    }
    poor ||--o{ chance : claim
    poor {
        DATE claim
        TEXT television
        VARCHAR(50) technology
    }
    chance ||--o{ stock : change
    chance {
        VARCHAR(50) change
        DATE interest
    }
    stock ||--o{ police : blue
    stock {
        DATE blue
        TEXT show
        VARCHAR(50) serve
    }
    police ||--o{ glass : national
    police {
        VARCHAR(50) national
        DATE hot
    }
    glass ||--o{ movie : performance
    glass {
        DATE performance
        TEXT cell
        VARCHAR(50) second
    }
    movie ||--o{ fire : still
    movie {
        VARCHAR(50) still
        DATE adult
    }
    fire ||--o{ themselves : blood
    fire {
        DATE blood
        TEXT whom
        VARCHAR(50) environment
    }
    themselves ||--o{ manage : prepare
    themselves {
        VARCHAR(50) prepare
        DATE ahead
    }
    manage ||--o{ world : speak
    manage {
        DATE speak
        TEXT beautiful
        VARCHAR(50) way
    }
    world ||--o{ form : reflect
    world {
        VARCHAR(50) reflect
        DATE heart
    }