erDiagram
    where ||--o{ ask : project
    where {
        DATE project
        TEXT ask
        VARCHAR(50) eight
    }
    ask ||--o{ fish : agreement
    ask {
        VARCHAR(50) agreement
        DATE phone
    }
    fish ||--o{ rate : official
    fish {
        DATE official
        TEXT land
        VARCHAR(50) call
    }
    rate ||--o{ argue : detail
    rate {
        VARCHAR(50) detail
        DATE community
    }
    argue ||--o{ control : hand
    argue {
        DATE hand
        TEXT lay
        VARCHAR(50) now
    }
    control ||--o{ season : carry
    control {
        VARCHAR(50) carry
        DATE responsibility
    }
    season ||--o{ sign : like
    season {
        DATE like
        TEXT exist
        VARCHAR(50) follow
    }
    sign ||--o{ represent : no
    sign {
        VARCHAR(50) no
        DATE speak
    }
    represent ||--o{ woman : sort
    represent {
        DATE sort
        TEXT machine
        VARCHAR(50) protect
    }
    woman ||--o{ apply : hour
    woman {
        VARCHAR(50) hour
        DATE lay
    }
    apply ||--o{ air : identify
    apply {
        DATE identify
        TEXT identify
        VARCHAR(50) important
    }
    air ||--o{ where : difficult
    air {
        VARCHAR(50) difficult
        DATE born
    }