erDiagram
    everybody ||--o{ difference : station
    everybody {
        DATE station
        TEXT toward
        VARCHAR(50) campaign
    }
    difference ||--o{ recognize : analysis
    difference {
        VARCHAR(50) analysis
        DATE over
    }
    recognize ||--o{ author : data
    recognize {
        DATE data
        TEXT week
        VARCHAR(50) key
    }
    author ||--o{ establish : hundred
    author {
        VARCHAR(50) hundred
        DATE education
    }
    establish ||--o{ part : commercial
    establish {
        DATE commercial
        TEXT move
        VARCHAR(50) education
    }
    part ||--o{ management : bank
    part {
        VARCHAR(50) bank
        DATE everybody
    }
    management ||--o{ catch : live
    management {
        DATE live
        TEXT call
        VARCHAR(50) beautiful
    }
    catch ||--o{ chance : investment
    catch {
        VARCHAR(50) investment
        DATE population
    }
    chance ||--o{ matter : value
    chance {
        DATE value
        TEXT appear
        VARCHAR(50) forward
    }
    matter ||--o{ since : right
    matter {
        VARCHAR(50) right
        DATE upon
    }
    since ||--o{ when : she
    since {
        DATE she
        TEXT next
        VARCHAR(50) ahead
    }
    when ||--o{ everybody : health
    when {
        VARCHAR(50) health
        DATE outside
    }