erDiagram
    take ||--o{ million : agent
    take {
        DATE agent
        TEXT street
        VARCHAR(50) toward
    }
    million ||--o{ answer : along
    million {
        VARCHAR(50) along
        DATE this
    }
    answer ||--o{ its : man
    answer {
        DATE man
        TEXT nor
        VARCHAR(50) let
    }
    its ||--o{ space : employee
    its {
        VARCHAR(50) employee
        DATE build
    }
    space ||--o{ join : include
    space {
        DATE include
        TEXT Mrs
        VARCHAR(50) movie
    }
    join ||--o{ or : one
    join {
        VARCHAR(50) one
        DATE rise
    }
    or ||--o{ enough : fine
    or {
        DATE fine
        TEXT oil
        VARCHAR(50) catch
    }
    enough ||--o{ early : stop
    enough {
        VARCHAR(50) stop
        DATE eye
    }
    early ||--o{ face : hotel
    early {
        DATE hotel
        TEXT clearly
        VARCHAR(50) within
    }
    face ||--o{ mission : big
    face {
        VARCHAR(50) big
        DATE price
    }
    mission ||--o{ take : article
    mission {
        DATE article
        TEXT share
        VARCHAR(50) election
    }