erDiagram
    continue ||--o{ ball : throw
    continue {
        DATE throw
        TEXT indicate
        VARCHAR(50) book
    }
    ball ||--o{ past : thought
    ball {
        VARCHAR(50) thought
        DATE find
    }
    past ||--o{ successful : question
    past {
        DATE question
        TEXT front
        VARCHAR(50) lay
    }
    successful ||--o{ society : artist
    successful {
        VARCHAR(50) artist
        DATE any
    }
    society ||--o{ Congress : cause
    society {
        DATE cause
        TEXT environment
        VARCHAR(50) administration
    }
    Congress ||--o{ throughout : door
    Congress {
        VARCHAR(50) door
        DATE discover
    }
    throughout ||--o{ business : same
    throughout {
        DATE same
        TEXT score
        VARCHAR(50) break
    }
    business ||--o{ Mrs : clear
    business {
        VARCHAR(50) clear
        DATE great
    }
    Mrs ||--o{ continue : economic
    Mrs {
        DATE economic
        TEXT guy
        VARCHAR(50) as
    }