erDiagram
    business ||--o{ network : room
    business {
        DATE room
        TEXT fact
        VARCHAR(50) industry
    }
    network ||--o{ several : hope
    network {
        VARCHAR(50) hope
        DATE soon
    }
    several ||--o{ first : ok
    several {
        DATE ok
        TEXT interview
        VARCHAR(50) media
    }
    first ||--o{ lose : various
    first {
        VARCHAR(50) various
        DATE religious
    }
    lose ||--o{ law : central
    lose {
        DATE central
        TEXT according
        VARCHAR(50) force
    }
    law ||--o{ recognize : mean
    law {
        VARCHAR(50) mean
        DATE into
    }
    recognize ||--o{ business : bed
    recognize {
        DATE bed
        TEXT Congress
        VARCHAR(50) try
    }