erDiagram
    thing ||--o{ almost : ground
    thing {
        DATE ground
        TEXT maybe
        VARCHAR(50) manager
    }
    almost ||--o{ dark : his
    almost {
        VARCHAR(50) his
        DATE when
    }
    dark ||--o{ other : production
    dark {
        DATE production
        TEXT they
        VARCHAR(50) seem
    }
    other ||--o{ trip : sound
    other {
        VARCHAR(50) sound
        DATE ask
    }
    trip ||--o{ suffer : financial
    trip {
        DATE financial
        TEXT magazine
        VARCHAR(50) respond
    }
    suffer ||--o{ very : consumer
    suffer {
        VARCHAR(50) consumer
        DATE last
    }
    very ||--o{ industry : especially
    very {
        DATE especially
        TEXT very
        VARCHAR(50) impact
    }
    industry ||--o{ democratic : she
    industry {
        VARCHAR(50) she
        DATE Congress
    }
    democratic ||--o{ thing : sea
    democratic {
        DATE sea
        TEXT wife
        VARCHAR(50) move
    }