erDiagram
    study ||--o{ some : up
    study {
        DATE up
        TEXT above
        VARCHAR(50) food
    }
    some ||--o{ amount : power
    some {
        VARCHAR(50) power
        DATE herself
    }
    amount ||--o{ theory : past
    amount {
        DATE past
        TEXT law
        VARCHAR(50) something
    }
    theory ||--o{ ready : no
    theory {
        VARCHAR(50) no
        DATE pick
    }
    ready ||--o{ on : tough
    ready {
        DATE tough
        TEXT company
        VARCHAR(50) opportunity
    }
    on ||--o{ within : stop
    on {
        VARCHAR(50) stop
        DATE true
    }
    within ||--o{ recent : Democrat
    within {
        DATE Democrat
        TEXT natural
        VARCHAR(50) ten
    }
    recent ||--o{ face : agent
    recent {
        VARCHAR(50) agent
        DATE treatment
    }
    face ||--o{ while : should
    face {
        DATE should
        TEXT trial
        VARCHAR(50) spring
    }
    while ||--o{ study : box
    while {
        VARCHAR(50) box
        DATE him
    }