erDiagram
    mind ||--o{ main : instead
    mind {
        DATE instead
        TEXT meet
        VARCHAR(50) some
    }
    main ||--o{ never : these
    main {
        VARCHAR(50) these
        DATE future
    }
    never ||--o{ early : space
    never {
        DATE space
        TEXT body
        VARCHAR(50) card
    }
    early ||--o{ of : action
    early {
        VARCHAR(50) action
        DATE expert
    }
    of ||--o{ way : star
    of {
        DATE star
        TEXT toward
        VARCHAR(50) talk
    }
    way ||--o{ place : gas
    way {
        VARCHAR(50) gas
        DATE her
    }
    place ||--o{ pass : material
    place {
        DATE material
        TEXT case
        VARCHAR(50) drive
    }
    pass ||--o{ mind : visit
    pass {
        VARCHAR(50) visit
        DATE everything
    }