erDiagram
    next ||--o{ bed : bit
    next {
        DATE bit
        TEXT usually
        VARCHAR(50) ok
    }
    bed ||--o{ theory : almost
    bed {
        VARCHAR(50) almost
        DATE line
    }
    theory ||--o{ ready : speech
    theory {
        DATE speech
        TEXT knowledge
        VARCHAR(50) out
    }
    ready ||--o{ usually : threat
    ready {
        VARCHAR(50) threat
        DATE laugh
    }
    usually ||--o{ traditional : mind
    usually {
        DATE mind
        TEXT around
        VARCHAR(50) approach
    }
    traditional ||--o{ field : measure
    traditional {
        VARCHAR(50) measure
        DATE truth
    }
    field ||--o{ first : material
    field {
        DATE material
        TEXT late
        VARCHAR(50) others
    }
    first ||--o{ leader : approach
    first {
        VARCHAR(50) approach
        DATE carry
    }
    leader ||--o{ sound : forward
    leader {
        DATE forward
        TEXT conference
        VARCHAR(50) author
    }
    sound ||--o{ good : experience
    sound {
        VARCHAR(50) experience
        DATE employee
    }
    good ||--o{ next : expert
    good {
        DATE expert
        TEXT still
        VARCHAR(50) billion
    }