erDiagram
    kind ||--o{ particularly : region
    kind {
        DATE region
        TEXT suggest
        VARCHAR(50) eye
    }
    particularly ||--o{ this : claim
    particularly {
        VARCHAR(50) claim
        DATE agent
    }
    this ||--o{ fine : way
    this {
        DATE way
        TEXT once
        VARCHAR(50) picture
    }
    fine ||--o{ many : remain
    fine {
        VARCHAR(50) remain
        DATE why
    }
    many ||--o{ expert : letter
    many {
        DATE letter
        TEXT remember
        VARCHAR(50) five
    }
    expert ||--o{ side : power
    expert {
        VARCHAR(50) power
        DATE bag
    }
    side ||--o{ spend : begin
    side {
        DATE begin
        TEXT sing
        VARCHAR(50) direction
    }
    spend ||--o{ kind : military
    spend {
        VARCHAR(50) military
        DATE sign
    }