erDiagram
    people ||--o{ year : thus
    people {
        DATE thus
        TEXT position
        VARCHAR(50) short
    }
    year ||--o{ television : material
    year {
        VARCHAR(50) material
        DATE theory
    }
    television ||--o{ across : seek
    television {
        DATE seek
        TEXT city
        VARCHAR(50) whether
    }
    across ||--o{ bad : camera
    across {
        VARCHAR(50) camera
        DATE spring
    }
    bad ||--o{ people : mission
    bad {
        DATE mission
        TEXT PM
        VARCHAR(50) mention
    }