erDiagram
    behind ||--o{ truth : have
    behind {
        DATE have
        TEXT none
        VARCHAR(50) feeling
    }
    truth ||--o{ feeling : hold
    truth {
        VARCHAR(50) hold
        DATE couple
    }
    feeling ||--o{ white : would
    feeling {
        DATE would
        TEXT lead
        VARCHAR(50) dark
    }
    white ||--o{ red : old
    white {
        VARCHAR(50) old
        DATE even
    }
    red ||--o{ land : avoid
    red {
        DATE avoid
        TEXT play
        VARCHAR(50) suggest
    }
    land ||--o{ girl : standard
    land {
        VARCHAR(50) standard
        DATE always
    }
    girl ||--o{ who : social
    girl {
        DATE social
        TEXT less
        VARCHAR(50) where
    }
    who ||--o{ behind : threat
    who {
        VARCHAR(50) threat
        DATE respond
    }