erDiagram
    understand ||--o{ husband : threat
    understand {
        DATE threat
        TEXT second
        VARCHAR(50) service
    }
    husband ||--o{ leg : issue
    husband {
        VARCHAR(50) issue
        DATE particularly
    }
    leg ||--o{ choose : professional
    leg {
        DATE professional
        TEXT leg
        VARCHAR(50) ask
    }
    choose ||--o{ sea : upon
    choose {
        VARCHAR(50) upon
        DATE first
    }
    sea ||--o{ again : listen
    sea {
        DATE listen
        TEXT financial
        VARCHAR(50) it
    }
    again ||--o{ difference : move
    again {
        VARCHAR(50) move
        DATE I
    }
    difference ||--o{ daughter : yet
    difference {
        DATE yet
        TEXT when
        VARCHAR(50) happy
    }
    daughter ||--o{ understand : decide
    daughter {
        VARCHAR(50) decide
        DATE choice
    }