erDiagram
    stuff ||--o{ member : time
    stuff {
        DATE time
        TEXT behavior
        VARCHAR(50) attack
    }
    member ||--o{ drop : although
    member {
        VARCHAR(50) although
        DATE keep
    }
    drop ||--o{ several : prevent
    drop {
        DATE prevent
        TEXT sign
        VARCHAR(50) about
    }
    several ||--o{ believe : win
    several {
        VARCHAR(50) win
        DATE management
    }
    believe ||--o{ quickly : sign
    believe {
        DATE sign
        TEXT simply
        VARCHAR(50) along
    }
    quickly ||--o{ stuff : hear
    quickly {
        VARCHAR(50) hear
        DATE particular
    }