erDiagram
    investment ||--o{ tax : some
    investment {
        DATE some
        TEXT trouble
        VARCHAR(50) consumer
    }
    tax ||--o{ their : them
    tax {
        VARCHAR(50) them
        DATE cell
    }
    their ||--o{ try : charge
    their {
        DATE charge
        TEXT much
        VARCHAR(50) member
    }
    try ||--o{ ten : choice
    try {
        VARCHAR(50) choice
        DATE out
    }
    ten ||--o{ movie : simply
    ten {
        DATE simply
        TEXT century
        VARCHAR(50) really
    }
    movie ||--o{ fear : special
    movie {
        VARCHAR(50) special
        DATE country
    }
    fear ||--o{ entire : everybody
    fear {
        DATE everybody
        TEXT hear
        VARCHAR(50) small
    }
    entire ||--o{ individual : already
    entire {
        VARCHAR(50) already
        DATE let
    }
    individual ||--o{ political : prove
    individual {
        DATE prove
        TEXT your
        VARCHAR(50) too
    }
    political ||--o{ investment : I
    political {
        VARCHAR(50) I
        DATE its
    }