erDiagram
    name ||--o{ really : six
    name {
        DATE six
        TEXT from
        VARCHAR(50) couple
    }
    really ||--o{ degree : manager
    really {
        VARCHAR(50) manager
        DATE yeah
    }
    degree ||--o{ finally : nature
    degree {
        DATE nature
        TEXT thought
        VARCHAR(50) your
    }
    finally ||--o{ marriage : son
    finally {
        VARCHAR(50) son
        DATE while
    }
    marriage ||--o{ perform : former
    marriage {
        DATE former
        TEXT skill
        VARCHAR(50) and
    }
    perform ||--o{ seven : physical
    perform {
        VARCHAR(50) physical
        DATE end
    }
    seven ||--o{ expect : western
    seven {
        DATE western
        TEXT form
        VARCHAR(50) represent
    }
    expect ||--o{ group : win
    expect {
        VARCHAR(50) win
        DATE watch
    }
    group ||--o{ name : right
    group {
        DATE right
        TEXT suffer
        VARCHAR(50) serious
    }