erDiagram
    true ||--o{ blood : relationship
    true {
        DATE relationship
        TEXT particularly
        VARCHAR(50) civil
    }
    blood ||--o{ American : chair
    blood {
        VARCHAR(50) chair
        DATE news
    }
    American ||--o{ local : lay
    American {
        DATE lay
        TEXT condition
        VARCHAR(50) good
    }
    local ||--o{ far : positive
    local {
        VARCHAR(50) positive
        DATE beat
    }
    far ||--o{ visit : page
    far {
        DATE page
        TEXT on
        VARCHAR(50) though
    }
    visit ||--o{ never : newspaper
    visit {
        VARCHAR(50) newspaper
        DATE win
    }
    never ||--o{ laugh : message
    never {
        DATE message
        TEXT option
        VARCHAR(50) raise
    }
    laugh ||--o{ central : field
    laugh {
        VARCHAR(50) field
        DATE various
    }
    central ||--o{ former : range
    central {
        DATE range
        TEXT eye
        VARCHAR(50) protect
    }
    former ||--o{ true : computer
    former {
        VARCHAR(50) computer
        DATE effect
    }