erDiagram
    Mr ||--o{ radio : little
    Mr {
        DATE little
        TEXT fact
        VARCHAR(50) red
    }
    radio ||--o{ manager : eye
    radio {
        VARCHAR(50) eye
        DATE child
    }
    manager ||--o{ probably : goal
    manager {
        DATE goal
        TEXT call
        VARCHAR(50) space
    }
    probably ||--o{ society : need
    probably {
        VARCHAR(50) need
        DATE president
    }
    society ||--o{ street : perhaps
    society {
        DATE perhaps
        TEXT doctor
        VARCHAR(50) old
    }
    street ||--o{ happy : phone
    street {
        VARCHAR(50) phone
        DATE including
    }
    happy ||--o{ Mr : upon
    happy {
        DATE upon
        TEXT nice
        VARCHAR(50) miss
    }