erDiagram
    main ||--o{ behind : appear
    main {
        DATE appear
        TEXT degree
        VARCHAR(50) police
    }
    behind ||--o{ break : small
    behind {
        VARCHAR(50) small
        DATE have
    }
    break ||--o{ budget : very
    break {
        DATE very
        TEXT pretty
        VARCHAR(50) rest
    }
    budget ||--o{ clearly : serve
    budget {
        VARCHAR(50) serve
        DATE culture
    }
    clearly ||--o{ conference : five
    clearly {
        DATE five
        TEXT shoulder
        VARCHAR(50) decision
    }
    conference ||--o{ partner : debate
    conference {
        VARCHAR(50) debate
        DATE change
    }
    partner ||--o{ such : project
    partner {
        DATE project
        TEXT give
        VARCHAR(50) animal
    }
    such ||--o{ main : contain
    such {
        VARCHAR(50) contain
        DATE security
    }