erDiagram
    room ||--o{ lot : test
    room {
        DATE test
        TEXT other
        VARCHAR(50) run
    }
    lot ||--o{ yet : test
    lot {
        VARCHAR(50) test
        DATE prove
    }
    yet ||--o{ special : middle
    yet {
        DATE middle
        TEXT market
        VARCHAR(50) through
    }
    special ||--o{ concern : reveal
    special {
        VARCHAR(50) reveal
        DATE gas
    }
    concern ||--o{ make : suggest
    concern {
        DATE suggest
        TEXT save
        VARCHAR(50) leader
    }
    make ||--o{ end : east
    make {
        VARCHAR(50) east
        DATE sell
    }
    end ||--o{ too : toward
    end {
        DATE toward
        TEXT will
        VARCHAR(50) million
    }
    too ||--o{ fact : suddenly
    too {
        VARCHAR(50) suddenly
        DATE he
    }
    fact ||--o{ room : inside
    fact {
        DATE inside
        TEXT believe
        VARCHAR(50) either
    }