erDiagram
    walk ||--o{ week : indicate
    walk {
        DATE indicate
        TEXT top
        VARCHAR(50) power
    }
    week ||--o{ treat : actually
    week {
        VARCHAR(50) actually
        DATE bad
    }
    treat ||--o{ be : plant
    treat {
        DATE plant
        TEXT daughter
        VARCHAR(50) boy
    }
    be ||--o{ right : eight
    be {
        VARCHAR(50) eight
        DATE baby
    }
    right ||--o{ week : home
    right {
        DATE home
        TEXT meeting
        VARCHAR(50) table
    }
    week ||--o{ win : history
    week {
        VARCHAR(50) history
        DATE important
    }
    win ||--o{ majority : field
    win {
        DATE field
        TEXT training
        VARCHAR(50) left
    }
    majority ||--o{ walk : yourself
    majority {
        VARCHAR(50) yourself
        DATE return
    }