erDiagram
    job ||--o{ although : sit
    job {
        DATE sit
        TEXT off
        VARCHAR(50) middle
    }
    although ||--o{ morning : particular
    although {
        VARCHAR(50) particular
        DATE resource
    }
    morning ||--o{ how : vote
    morning {
        DATE vote
        TEXT their
        VARCHAR(50) data
    }
    how ||--o{ wide : available
    how {
        VARCHAR(50) available
        DATE trouble
    }
    wide ||--o{ prove : rise
    wide {
        DATE rise
        TEXT medical
        VARCHAR(50) break
    }
    prove ||--o{ whole : fine
    prove {
        VARCHAR(50) fine
        DATE while
    }
    whole ||--o{ keep : debate
    whole {
        DATE debate
        TEXT may
        VARCHAR(50) southern
    }
    keep ||--o{ build : difference
    keep {
        VARCHAR(50) difference
        DATE per
    }
    build ||--o{ job : student
    build {
        DATE student
        TEXT before
        VARCHAR(50) conference
    }