erDiagram
    imagine ||--o{ miss : toward
    imagine {
        DATE toward
        TEXT much
        VARCHAR(50) east
    }
    miss ||--o{ camera : that
    miss {
        VARCHAR(50) that
        DATE himself
    }
    camera ||--o{ book : indicate
    camera {
        DATE indicate
        TEXT agreement
        VARCHAR(50) say
    }
    book ||--o{ interesting : fund
    book {
        VARCHAR(50) fund
        DATE operation
    }
    interesting ||--o{ history : past
    interesting {
        DATE past
        TEXT situation
        VARCHAR(50) manage
    }
    history ||--o{ spend : member
    history {
        VARCHAR(50) member
        DATE you
    }
    spend ||--o{ increase : range
    spend {
        DATE range
        TEXT current
        VARCHAR(50) security
    }
    increase ||--o{ sea : eight
    increase {
        VARCHAR(50) eight
        DATE instead
    }
    sea ||--o{ imagine : country
    sea {
        DATE country
        TEXT challenge
        VARCHAR(50) health
    }