erDiagram
    listen ||--o{ four : relate
    listen {
        DATE relate
        TEXT city
        VARCHAR(50) friend
    }
    four ||--o{ mean : hot
    four {
        VARCHAR(50) hot
        DATE still
    }
    mean ||--o{ natural : politics
    mean {
        DATE politics
        TEXT beyond
        VARCHAR(50) she
    }
    natural ||--o{ look : class
    natural {
        VARCHAR(50) class
        DATE worker
    }
    look ||--o{ help : friend
    look {
        DATE friend
        TEXT democratic
        VARCHAR(50) speech
    }
    help ||--o{ half : development
    help {
        VARCHAR(50) development
        DATE total
    }
    half ||--o{ theory : wait
    half {
        DATE wait
        TEXT major
        VARCHAR(50) high
    }
    theory ||--o{ here : action
    theory {
        VARCHAR(50) action
        DATE edge
    }
    here ||--o{ can : food
    here {
        DATE food
        TEXT often
        VARCHAR(50) sound
    }
    can ||--o{ listen : order
    can {
        VARCHAR(50) order
        DATE able
    }