erDiagram
    different ||--o{ morning : somebody
    different {
        DATE somebody
        TEXT beat
        VARCHAR(50) she
    }
    morning ||--o{ until : either
    morning {
        VARCHAR(50) either
        DATE receive
    }
    until ||--o{ investment : arm
    until {
        DATE arm
        TEXT check
        VARCHAR(50) science
    }
    investment ||--o{ involve : official
    investment {
        VARCHAR(50) official
        DATE million
    }
    involve ||--o{ away : attention
    involve {
        DATE attention
        TEXT attack
        VARCHAR(50) husband
    }
    away ||--o{ husband : her
    away {
        VARCHAR(50) her
        DATE station
    }
    husband ||--o{ different : either
    husband {
        DATE either
        TEXT beautiful
        VARCHAR(50) serious
    }