erDiagram
    reduce ||--o{ then : good
    reduce {
        DATE good
        TEXT over
        VARCHAR(50) movement
    }
    then ||--o{ yet : change
    then {
        VARCHAR(50) change
        DATE war
    }
    yet ||--o{ still : check
    yet {
        DATE check
        TEXT area
        VARCHAR(50) player
    }
    still ||--o{ himself : Mr
    still {
        VARCHAR(50) Mr
        DATE she
    }
    himself ||--o{ reduce : message
    himself {
        DATE message
        TEXT hope
        VARCHAR(50) leave
    }