erDiagram
    lead ||--o{ security : push
    lead {
        DATE push
        TEXT play
        VARCHAR(50) three
    }
    security ||--o{ style : raise
    security {
        VARCHAR(50) raise
        DATE feeling
    }
    style ||--o{ possible : once
    style {
        DATE once
        TEXT item
        VARCHAR(50) practice
    }
    possible ||--o{ among : scene
    possible {
        VARCHAR(50) scene
        DATE send
    }
    among ||--o{ let : identify
    among {
        DATE identify
        TEXT card
        VARCHAR(50) collection
    }
    let ||--o{ miss : event
    let {
        VARCHAR(50) event
        DATE wonder
    }
    miss ||--o{ them : writer
    miss {
        DATE writer
        TEXT once
        VARCHAR(50) range
    }
    them ||--o{ lead : small
    them {
        VARCHAR(50) small
        DATE level
    }