erDiagram
    high ||--o{ heart : ever
    high {
        DATE ever
        TEXT stand
        VARCHAR(50) question
    }
    heart ||--o{ understand : line
    heart {
        VARCHAR(50) line
        DATE billion
    }
    understand ||--o{ hospital : time
    understand {
        DATE time
        TEXT seven
        VARCHAR(50) decision
    }
    hospital ||--o{ possible : class
    hospital {
        VARCHAR(50) class
        DATE campaign
    }
    possible ||--o{ station : almost
    possible {
        DATE almost
        TEXT blue
        VARCHAR(50) either
    }
    station ||--o{ important : thank
    station {
        VARCHAR(50) thank
        DATE arm
    }
    important ||--o{ available : them
    important {
        DATE them
        TEXT lead
        VARCHAR(50) can
    }
    available ||--o{ line : buy
    available {
        VARCHAR(50) buy
        DATE around
    }
    line ||--o{ hair : outside
    line {
        DATE outside
        TEXT recently
        VARCHAR(50) democratic
    }
    hair ||--o{ contain : sign
    hair {
        VARCHAR(50) sign
        DATE beautiful
    }
    contain ||--o{ several : education
    contain {
        DATE education
        TEXT American
        VARCHAR(50) girl
    }
    several ||--o{ high : environment
    several {
        VARCHAR(50) environment
        DATE sense
    }