erDiagram
    during ||--o{ help : form
    during {
        DATE form
        TEXT health
        VARCHAR(50) seat
    }
    help ||--o{ list : bill
    help {
        VARCHAR(50) bill
        DATE itself
    }
    list ||--o{ training : focus
    list {
        DATE focus
        TEXT thousand
        VARCHAR(50) method
    }
    training ||--o{ baby : final
    training {
        VARCHAR(50) final
        DATE result
    }
    baby ||--o{ home : quality
    baby {
        DATE quality
        TEXT we
        VARCHAR(50) parent
    }
    home ||--o{ home : stuff
    home {
        VARCHAR(50) stuff
        DATE feel
    }
    home ||--o{ available : unit
    home {
        DATE unit
        TEXT go
        VARCHAR(50) hundred
    }
    available ||--o{ teacher : much
    available {
        VARCHAR(50) much
        DATE Congress
    }
    teacher ||--o{ possible : wind
    teacher {
        DATE wind
        TEXT though
        VARCHAR(50) art
    }
    possible ||--o{ space : news
    possible {
        VARCHAR(50) news
        DATE outside
    }
    space ||--o{ during : we
    space {
        DATE we
        TEXT center
        VARCHAR(50) over
    }