erDiagram
    white ||--o{ total : somebody
    white {
        DATE somebody
        TEXT yourself
        VARCHAR(50) ever
    }
    total ||--o{ beat : quickly
    total {
        VARCHAR(50) quickly
        DATE spring
    }
    beat ||--o{ admit : politics
    beat {
        DATE politics
        TEXT every
        VARCHAR(50) clear
    }
    admit ||--o{ side : would
    admit {
        VARCHAR(50) would
        DATE light
    }
    side ||--o{ value : fear
    side {
        DATE fear
        TEXT way
        VARCHAR(50) leg
    }
    value ||--o{ name : mouth
    value {
        VARCHAR(50) mouth
        DATE anything
    }
    name ||--o{ group : enjoy
    name {
        DATE enjoy
        TEXT fact
        VARCHAR(50) stage
    }
    group ||--o{ know : ok
    group {
        VARCHAR(50) ok
        DATE pick
    }
    know ||--o{ white : example
    know {
        DATE example
        TEXT school
        VARCHAR(50) fill
    }