erDiagram
    few ||--o{ number : age
    few {
        DATE age
        TEXT low
        VARCHAR(50) candidate
    }
    number ||--o{ investment : necessary
    number {
        VARCHAR(50) necessary
        DATE ago
    }
    investment ||--o{ personal : place
    investment {
        DATE place
        TEXT side
        VARCHAR(50) activity
    }
    personal ||--o{ organization : international
    personal {
        VARCHAR(50) international
        DATE left
    }
    organization ||--o{ can : blue
    organization {
        DATE blue
        TEXT front
        VARCHAR(50) enjoy
    }
    can ||--o{ opportunity : open
    can {
        VARCHAR(50) open
        DATE commercial
    }
    opportunity ||--o{ reason : serious
    opportunity {
        DATE serious
        TEXT meeting
        VARCHAR(50) ready
    }
    reason ||--o{ evidence : coach
    reason {
        VARCHAR(50) coach
        DATE whose
    }
    evidence ||--o{ organization : institution
    evidence {
        DATE institution
        TEXT short
        VARCHAR(50) level
    }
    organization ||--o{ total : past
    organization {
        VARCHAR(50) past
        DATE trial
    }
    total ||--o{ few : instead
    total {
        DATE instead
        TEXT employee
        VARCHAR(50) also
    }