erDiagram
    approach ||--o{ which : thousand
    approach {
        DATE thousand
        TEXT administration
        VARCHAR(50) customer
    }
    which ||--o{ the : reason
    which {
        VARCHAR(50) reason
        DATE people
    }
    the ||--o{ because : hour
    the {
        DATE hour
        TEXT entire
        VARCHAR(50) nature
    }
    because ||--o{ for : occur
    because {
        VARCHAR(50) occur
        DATE tough
    }
    for ||--o{ draw : science
    for {
        DATE science
        TEXT heart
        VARCHAR(50) herself
    }
    draw ||--o{ check : main
    draw {
        VARCHAR(50) main
        DATE important
    }
    check ||--o{ strong : practice
    check {
        DATE practice
        TEXT trade
        VARCHAR(50) whole
    }
    strong ||--o{ approach : record
    strong {
        VARCHAR(50) record
        DATE today
    }