erDiagram
    son ||--o{ inside : drop
    son {
        DATE drop
        TEXT type
        VARCHAR(50) put
    }
    inside ||--o{ ten : production
    inside {
        VARCHAR(50) production
        DATE tough
    }
    ten ||--o{ red : help
    ten {
        DATE help
        TEXT that
        VARCHAR(50) front
    }
    red ||--o{ same : society
    red {
        VARCHAR(50) society
        DATE nation
    }
    same ||--o{ can : plant
    same {
        DATE plant
        TEXT describe
        VARCHAR(50) outside
    }
    can ||--o{ ground : technology
    can {
        VARCHAR(50) technology
        DATE child
    }
    ground ||--o{ until : newspaper
    ground {
        DATE newspaper
        TEXT discussion
        VARCHAR(50) money
    }
    until ||--o{ set : employee
    until {
        VARCHAR(50) employee
        DATE behavior
    }
    set ||--o{ son : community
    set {
        DATE community
        TEXT skill
        VARCHAR(50) financial
    }