erDiagram
    prevent ||--o{ actually : down
    prevent {
        DATE down
        TEXT treat
        VARCHAR(50) parent
    }
    actually ||--o{ bit : church
    actually {
        VARCHAR(50) church
        DATE agent
    }
    bit ||--o{ central : degree
    bit {
        DATE degree
        TEXT argue
        VARCHAR(50) later
    }
    central ||--o{ agency : simple
    central {
        VARCHAR(50) simple
        DATE cold
    }
    agency ||--o{ father : thousand
    agency {
        DATE thousand
        TEXT fly
        VARCHAR(50) large
    }
    father ||--o{ especially : military
    father {
        VARCHAR(50) military
        DATE smile
    }
    especially ||--o{ similar : really
    especially {
        DATE really
        TEXT become
        VARCHAR(50) mind
    }
    similar ||--o{ leader : nature
    similar {
        VARCHAR(50) nature
        DATE investment
    }
    leader ||--o{ free : memory
    leader {
        DATE memory
        TEXT nor
        VARCHAR(50) question
    }
    free ||--o{ collection : left
    free {
        VARCHAR(50) left
        DATE say
    }
    collection ||--o{ husband : campaign
    collection {
        DATE campaign
        TEXT have
        VARCHAR(50) easy
    }
    husband ||--o{ prevent : team
    husband {
        VARCHAR(50) team
        DATE Mrs
    }