erDiagram
    everybody ||--o{ way : as
    everybody {
        DATE as
        TEXT recent
        VARCHAR(50) safe
    }
    way ||--o{ media : two
    way {
        VARCHAR(50) two
        DATE reveal
    }
    media ||--o{ person : yes
    media {
        DATE yes
        TEXT former
        VARCHAR(50) control
    }
    person ||--o{ consider : approach
    person {
        VARCHAR(50) approach
        DATE yeah
    }
    consider ||--o{ everybody : tough
    consider {
        DATE tough
        TEXT admit
        VARCHAR(50) political
    }