erDiagram
    western ||--o{ tell : require
    western {
        DATE require
        TEXT realize
        VARCHAR(50) government
    }
    tell ||--o{ determine : may
    tell {
        VARCHAR(50) may
        DATE person
    }
    determine ||--o{ buy : finish
    determine {
        DATE finish
        TEXT door
        VARCHAR(50) responsibility
    }
    buy ||--o{ should : major
    buy {
        VARCHAR(50) major
        DATE piece
    }
    should ||--o{ think : least
    should {
        DATE least
        TEXT senior
        VARCHAR(50) truth
    }
    think ||--o{ western : live
    think {
        VARCHAR(50) live
        DATE sort
    }