erDiagram
    enjoy ||--o{ debate : around
    enjoy {
        DATE around
        TEXT suddenly
        VARCHAR(50) team
    }
    debate ||--o{ present : local
    debate {
        VARCHAR(50) local
        DATE view
    }
    present ||--o{ imagine : risk
    present {
        DATE risk
        TEXT decide
        VARCHAR(50) best
    }
    imagine ||--o{ physical : animal
    imagine {
        VARCHAR(50) animal
        DATE own
    }
    physical ||--o{ standard : rich
    physical {
        DATE rich
        TEXT culture
        VARCHAR(50) future
    }
    standard ||--o{ let : above
    standard {
        VARCHAR(50) above
        DATE account
    }
    let ||--o{ response : act
    let {
        DATE act
        TEXT again
        VARCHAR(50) coach
    }
    response ||--o{ huge : ball
    response {
        VARCHAR(50) ball
        DATE glass
    }
    huge ||--o{ especially : line
    huge {
        DATE line
        TEXT yourself
        VARCHAR(50) whole
    }
    especially ||--o{ enjoy : senior
    especially {
        VARCHAR(50) senior
        DATE without
    }