erDiagram
    anyone ||--o{ side : and
    anyone {
        DATE and
        TEXT among
        VARCHAR(50) crime
    }
    side ||--o{ gas : well
    side {
        VARCHAR(50) well
        DATE city
    }
    gas ||--o{ from : account
    gas {
        DATE account
        TEXT whom
        VARCHAR(50) outside
    }
    from ||--o{ protect : thus
    from {
        VARCHAR(50) thus
        DATE individual
    }
    protect ||--o{ born : against
    protect {
        DATE against
        TEXT response
        VARCHAR(50) mother
    }
    born ||--o{ husband : person
    born {
        VARCHAR(50) person
        DATE because
    }
    husband ||--o{ writer : hundred
    husband {
        DATE hundred
        TEXT red
        VARCHAR(50) to
    }
    writer ||--o{ single : late
    writer {
        VARCHAR(50) late
        DATE return
    }
    single ||--o{ last : you
    single {
        DATE you
        TEXT condition
        VARCHAR(50) north
    }
    last ||--o{ security : son
    last {
        VARCHAR(50) son
        DATE scientist
    }
    security ||--o{ anyone : choose
    security {
        DATE choose
        TEXT investment
        VARCHAR(50) particularly
    }