erDiagram
    protect ||--o{ character : mouth
    protect {
        DATE mouth
        TEXT difference
        VARCHAR(50) between
    }
    character ||--o{ far : serve
    character {
        VARCHAR(50) serve
        DATE job
    }
    far ||--o{ animal : budget
    far {
        DATE budget
        TEXT card
        VARCHAR(50) worry
    }
    animal ||--o{ toward : four
    animal {
        VARCHAR(50) four
        DATE market
    }
    toward ||--o{ spend : activity
    toward {
        DATE activity
        TEXT without
        VARCHAR(50) along
    }
    spend ||--o{ bad : table
    spend {
        VARCHAR(50) table
        DATE identify
    }
    bad ||--o{ player : training
    bad {
        DATE training
        TEXT big
        VARCHAR(50) senior
    }
    player ||--o{ house : those
    player {
        VARCHAR(50) those
        DATE high
    }
    house ||--o{ military : she
    house {
        DATE she
        TEXT dog
        VARCHAR(50) firm
    }
    military ||--o{ cut : election
    military {
        VARCHAR(50) election
        DATE nearly
    }
    cut ||--o{ protect : image
    cut {
        DATE image
        TEXT house
        VARCHAR(50) rate
    }