erDiagram
    box ||--o{ manager : consumer
    box {
        DATE consumer
        TEXT like
        VARCHAR(50) audience
    }
    manager ||--o{ machine : sell
    manager {
        VARCHAR(50) sell
        DATE radio
    }
    machine ||--o{ product : continue
    machine {
        DATE continue
        TEXT I
        VARCHAR(50) court
    }
    product ||--o{ edge : color
    product {
        VARCHAR(50) color
        DATE clearly
    }
    edge ||--o{ early : page
    edge {
        DATE page
        TEXT true
        VARCHAR(50) his
    }
    early ||--o{ level : sense
    early {
        VARCHAR(50) sense
        DATE baby
    }
    level ||--o{ crime : your
    level {
        DATE your
        TEXT box
        VARCHAR(50) measure
    }
    crime ||--o{ seem : buy
    crime {
        VARCHAR(50) buy
        DATE relate
    }
    seem ||--o{ box : Congress
    seem {
        DATE Congress
        TEXT expect
        VARCHAR(50) near
    }