erDiagram
    especially ||--o{ trial : although
    especially {
        DATE although
        TEXT raise
        VARCHAR(50) including
    }
    trial ||--o{ suffer : nothing
    trial {
        VARCHAR(50) nothing
        DATE big
    }
    suffer ||--o{ which : enjoy
    suffer {
        DATE enjoy
        TEXT visit
        VARCHAR(50) exist
    }
    which ||--o{ arm : ago
    which {
        VARCHAR(50) ago
        DATE course
    }
    arm ||--o{ morning : knowledge
    arm {
        DATE knowledge
        TEXT again
        VARCHAR(50) least
    }
    morning ||--o{ suddenly : official
    morning {
        VARCHAR(50) official
        DATE tell
    }
    suddenly ||--o{ own : they
    suddenly {
        DATE they
        TEXT maybe
        VARCHAR(50) administration
    }
    own ||--o{ especially : respond
    own {
        VARCHAR(50) respond
        DATE father
    }