erDiagram
    box ||--o{ experience : break
    box {
        DATE break
        TEXT third
        VARCHAR(50) administration
    }
    experience ||--o{ many : start
    experience {
        VARCHAR(50) start
        DATE network
    }
    many ||--o{ work : like
    many {
        DATE like
        TEXT sell
    }
    work ||--o{ will : must
    work {
        VARCHAR(50) must
        DATE people
    }
    will ||--o{ almost : the
    will {
        DATE the
        TEXT indicate
        VARCHAR(50) energy
    }
    almost ||--o{ finally : body
    almost {
        VARCHAR(50) body
        DATE here
    }
    finally ||--o{ main : week
    finally {
        DATE week
        TEXT scientist
        VARCHAR(50) adult
    }
    main ||--o{ box : lead
    main {
        VARCHAR(50) lead
        DATE future
    }