erDiagram
    could ||--o{ daughter : bed
    could {
        DATE bed
        TEXT far
        VARCHAR(50) section
    }
    daughter ||--o{ box : evening
    daughter {
        VARCHAR(50) evening
        DATE than
    }
    box ||--o{ down : so
    box {
        DATE so
        TEXT particularly
        VARCHAR(50) threat
    }
    down ||--o{ at : record
    down {
        VARCHAR(50) record
        DATE right
    }
    at ||--o{ lose : out
    at {
        DATE out
        TEXT matter
        VARCHAR(50) budget
    }
    lose ||--o{ statement : collection
    lose {
        VARCHAR(50) collection
        DATE their
    }
    statement ||--o{ account : thing
    statement {
        DATE thing
        TEXT main
        VARCHAR(50) professor
    }
    account ||--o{ could : spend
    account {
        VARCHAR(50) spend
        DATE modern
    }