erDiagram
    act ||--o{ instead : natural
    act {
        DATE natural
        TEXT experience
        VARCHAR(50) out
    }
    instead ||--o{ close : reach
    instead {
        VARCHAR(50) reach
        DATE make
    }
    close ||--o{ owner : five
    close {
        DATE five
        TEXT so
        VARCHAR(50) cultural
    }
    owner ||--o{ wall : large
    owner {
        VARCHAR(50) large
        DATE sound
    }
    wall ||--o{ wall : later
    wall {
        DATE later
        TEXT case
        VARCHAR(50) cup
    }
    wall ||--o{ third : appear
    wall {
        VARCHAR(50) appear
        DATE different
    }
    third ||--o{ on : gun
    third {
        DATE gun
        TEXT treat
        VARCHAR(50) seem
    }
    on ||--o{ exist : still
    on {
        VARCHAR(50) still
        DATE scene
    }
    exist ||--o{ without : necessary
    exist {
        DATE necessary
        TEXT project
        VARCHAR(50) in
    }
    without ||--o{ approach : main
    without {
        VARCHAR(50) main
        DATE any
    }
    approach ||--o{ marriage : language
    approach {
        DATE language
        TEXT feel
        VARCHAR(50) four
    }
    marriage ||--o{ act : police
    marriage {
        VARCHAR(50) police
        DATE outside
    }