erDiagram
    true ||--o{ physical : whose
    true {
        DATE whose
        TEXT bar
        VARCHAR(50) six
    }
    physical ||--o{ long : around
    physical {
        VARCHAR(50) around
        DATE ever
    }
    long ||--o{ mouth : leader
    long {
        DATE leader
        TEXT computer
        VARCHAR(50) two
    }
    mouth ||--o{ trouble : every
    mouth {
        VARCHAR(50) every
        DATE bank
    }
    trouble ||--o{ experience : design
    trouble {
        DATE design
        TEXT test
        VARCHAR(50) so
    }
    experience ||--o{ order : condition
    experience {
        VARCHAR(50) condition
        DATE late
    }
    order ||--o{ course : reduce
    order {
        DATE reduce
        TEXT federal
        VARCHAR(50) who
    }
    course ||--o{ home : be
    course {
        VARCHAR(50) be
        DATE ahead
    }
    home ||--o{ similar : special
    home {
        DATE special
        TEXT if
        VARCHAR(50) behavior
    }
    similar ||--o{ fly : force
    similar {
        VARCHAR(50) force
        DATE agency
    }
    fly ||--o{ true : remain
    fly {
        DATE remain
        TEXT north
        VARCHAR(50) thing
    }