erDiagram
    traditional ||--o{ teach : mean
    traditional {
        DATE mean
        TEXT political
        VARCHAR(50) condition
    }
    teach ||--o{ return : form
    teach {
        VARCHAR(50) form
        DATE page
    }
    return ||--o{ they : everything
    return {
        DATE everything
        TEXT include
        VARCHAR(50) gun
    }
    they ||--o{ election : senior
    they {
        VARCHAR(50) senior
        DATE response
    }
    election ||--o{ program : according
    election {
        DATE according
        TEXT year
        VARCHAR(50) why
    }
    program ||--o{ time : state
    program {
        VARCHAR(50) state
        DATE hear
    }
    time ||--o{ nothing : million
    time {
        DATE million
        TEXT act
        VARCHAR(50) father
    }
    nothing ||--o{ your : body
    nothing {
        VARCHAR(50) body
        DATE wind
    }
    your ||--o{ debate : lay
    your {
        DATE lay
        TEXT toward
        VARCHAR(50) general
    }
    debate ||--o{ traditional : hair
    debate {
        VARCHAR(50) hair
        DATE threat
    }