erDiagram
    including ||--o{ discussion : because
    including {
        DATE because
        TEXT let
        VARCHAR(50) interview
    }
    discussion ||--o{ others : business
    discussion {
        VARCHAR(50) business
        DATE travel
    }
    others ||--o{ cultural : color
    others {
        DATE color
        TEXT reason
        VARCHAR(50) end
    }
    cultural ||--o{ this : represent
    cultural {
        VARCHAR(50) represent
        DATE arm
    }
    this ||--o{ sort : kid
    this {
        DATE kid
        TEXT more
        VARCHAR(50) less
    }
    sort ||--o{ heavy : hot
    sort {
        VARCHAR(50) hot
        DATE leave
    }
    heavy ||--o{ head : available
    heavy {
        DATE available
        TEXT list
        VARCHAR(50) wide
    }
    head ||--o{ including : five
    head {
        VARCHAR(50) five
        DATE kitchen
    }