erDiagram
    glass ||--o{ most : trip
    glass {
        DATE trip
        TEXT citizen
        VARCHAR(50) your
    }
    most ||--o{ nature : order
    most {
        VARCHAR(50) order
        DATE student
    }
    nature ||--o{ but : woman
    nature {
        DATE woman
        TEXT mention
        VARCHAR(50) figure
    }
    but ||--o{ I : culture
    but {
        VARCHAR(50) culture
        DATE material
    }
    I ||--o{ measure : use
    I {
        DATE use
        TEXT four
        VARCHAR(50) successful
    }
    measure ||--o{ PM : hundred
    measure {
        VARCHAR(50) hundred
        DATE none
    }
    PM ||--o{ head : edge
    PM {
        DATE edge
        TEXT show
        VARCHAR(50) laugh
    }
    head ||--o{ glass : daughter
    head {
        VARCHAR(50) daughter
        DATE general
    }