erDiagram
    charge ||--o{ hour : message
    charge {
        DATE message
        TEXT simple
        VARCHAR(50) whom
    }
    hour ||--o{ five : no
    hour {
        VARCHAR(50) no
        DATE not
    }
    five ||--o{ up : majority
    five {
        DATE majority
        TEXT every
        VARCHAR(50) remember
    }
    up ||--o{ school : police
    up {
        VARCHAR(50) police
        DATE attorney
    }
    school ||--o{ certain : third
    school {
        DATE third
        TEXT man
        VARCHAR(50) sing
    }
    certain ||--o{ material : feeling
    certain {
        VARCHAR(50) feeling
        DATE alone
    }
    material ||--o{ foreign : account
    material {
        DATE account
        TEXT learn
        VARCHAR(50) modern
    }
    foreign ||--o{ show : seven
    foreign {
        VARCHAR(50) seven
        DATE class
    }
    show ||--o{ charge : resource
    show {
        DATE resource
        TEXT wide
        VARCHAR(50) tough
    }