erDiagram
    use ||--o{ must : represent
    use {
        DATE represent
        TEXT down
        VARCHAR(50) young
    }
    must ||--o{ listen : story
    must {
        VARCHAR(50) story
        DATE own
    }
    listen ||--o{ Democrat : big
    listen {
        DATE big
        TEXT place
        VARCHAR(50) threat
    }
    Democrat ||--o{ recognize : door
    Democrat {
        VARCHAR(50) door
        DATE capital
    }
    recognize ||--o{ television : price
    recognize {
        DATE price
        TEXT help
        VARCHAR(50) talk
    }
    television ||--o{ stand : sure
    television {
        VARCHAR(50) sure
        DATE generation
    }
    stand ||--o{ then : skill
    stand {
        DATE skill
        TEXT analysis
        VARCHAR(50) safe
    }
    then ||--o{ son : one
    then {
        VARCHAR(50) one
        DATE education
    }
    son ||--o{ image : prove
    son {
        DATE prove
        TEXT available
        VARCHAR(50) pick
    }
    image ||--o{ economy : trip
    image {
        VARCHAR(50) trip
        DATE clear
    }
    economy ||--o{ be : responsibility
    economy {
        DATE responsibility
        TEXT husband
        VARCHAR(50) defense
    }
    be ||--o{ use : tough
    be {
        VARCHAR(50) tough
        DATE able
    }