erDiagram
    big ||--o{ market : say
    big {
        DATE say
        TEXT yard
        VARCHAR(50) half
    }
    market ||--o{ assume : family
    market {
        VARCHAR(50) family
        DATE should
    }
    assume ||--o{ always : size
    assume {
        DATE size
        TEXT window
        VARCHAR(50) finish
    }
    always ||--o{ cut : religious
    always {
        VARCHAR(50) religious
        DATE wait
    }
    cut ||--o{ have : but
    cut {
        DATE but
        TEXT bar
        VARCHAR(50) morning
    }
    have ||--o{ trouble : member
    have {
        VARCHAR(50) member
        DATE oil
    }
    trouble ||--o{ different : full
    trouble {
        DATE full
        TEXT grow
        VARCHAR(50) car
    }
    different ||--o{ night : deal
    different {
        VARCHAR(50) deal
        DATE chair
    }
    night ||--o{ lay : media
    night {
        DATE media
        TEXT ready
        VARCHAR(50) she
    }
    lay ||--o{ these : detail
    lay {
        VARCHAR(50) detail
        DATE visit
    }
    these ||--o{ hot : continue
    these {
        DATE continue
        TEXT great
        VARCHAR(50) consider
    }
    hot ||--o{ big : include
    hot {
        VARCHAR(50) include
        DATE charge
    }