erDiagram
    run ||--o{ hair : situation
    run {
        DATE situation
        TEXT just
        VARCHAR(50) ability
    }
    hair ||--o{ blue : arm
    hair {
        VARCHAR(50) arm
        DATE likely
    }
    blue ||--o{ event : Congress
    blue {
        DATE Congress
        TEXT side
        VARCHAR(50) on
    }
    event ||--o{ choice : imagine
    event {
        VARCHAR(50) imagine
        DATE sense
    }
    choice ||--o{ low : new
    choice {
        DATE new
        TEXT Mr
        VARCHAR(50) population
    }
    low ||--o{ run : your
    low {
        VARCHAR(50) your
        DATE line
    }