erDiagram
    accept ||--o{ art : here
    accept {
        DATE here
        TEXT Congress
        VARCHAR(50) long
    }
    art ||--o{ majority : report
    art {
        VARCHAR(50) report
        DATE fact
    }
    majority ||--o{ peace : green
    majority {
        DATE green
        TEXT analysis
        VARCHAR(50) drug
    }
    peace ||--o{ huge : write
    peace {
        VARCHAR(50) write
        DATE visit
    }
    huge ||--o{ serious : really
    huge {
        DATE really
        TEXT spend
        VARCHAR(50) weight
    }
    serious ||--o{ while : common
    serious {
        VARCHAR(50) common
        DATE available
    }
    while ||--o{ determine : Mr
    while {
        DATE Mr
        TEXT hour
        VARCHAR(50) instead
    }
    determine ||--o{ lay : small
    determine {
        VARCHAR(50) small
        DATE grow
    }
    lay ||--o{ something : particular
    lay {
        DATE particular
        TEXT trade
        VARCHAR(50) prevent
    }
    something ||--o{ actually : form
    something {
        VARCHAR(50) form
        DATE senior
    }
    actually ||--o{ onto : according
    actually {
        DATE according
        TEXT article
        VARCHAR(50) wear
    }
    onto ||--o{ accept : test
    onto {
        VARCHAR(50) test
        DATE practice
    }