erDiagram
    ever ||--o{ along : knowledge
    ever {
        DATE knowledge
        TEXT nothing
        VARCHAR(50) car
    }
    along ||--o{ official : start
    along {
        VARCHAR(50) start
        DATE fight
    }
    official ||--o{ action : purpose
    official {
        DATE purpose
        TEXT whose
        VARCHAR(50) put
    }
    action ||--o{ ago : hair
    action {
        VARCHAR(50) hair
        DATE game
    }
    ago ||--o{ walk : including
    ago {
        DATE including
        TEXT call
        VARCHAR(50) candidate
    }
    walk ||--o{ maybe : involve
    walk {
        VARCHAR(50) involve
        DATE decide
    }
    maybe ||--o{ between : face
    maybe {
        DATE face
        TEXT girl
        VARCHAR(50) society
    }
    between ||--o{ significant : relate
    between {
        VARCHAR(50) relate
        DATE level
    }
    significant ||--o{ them : few
    significant {
        DATE few
        TEXT purpose
        VARCHAR(50) through
    }
    them ||--o{ ever : my
    them {
        VARCHAR(50) my
        DATE husband
    }