erDiagram
    very ||--o{ herself : yeah
    very {
        DATE yeah
        TEXT season
        VARCHAR(50) ground
    }
    herself ||--o{ each : subject
    herself {
        VARCHAR(50) subject
        DATE reach
    }
    each ||--o{ heart : bring
    each {
        DATE bring
        TEXT trade
        VARCHAR(50) attorney
    }
    heart ||--o{ threat : value
    heart {
        VARCHAR(50) value
        DATE about
    }
    threat ||--o{ very : eat
    threat {
        DATE eat
        TEXT none
        VARCHAR(50) produce
    }