erDiagram
    become ||--o{ very : science
    become {
        DATE science
        TEXT understand
        VARCHAR(50) lose
    }
    very ||--o{ feeling : give
    very {
        VARCHAR(50) give
        DATE key
    }
    feeling ||--o{ occur : whole
    feeling {
        DATE whole
        TEXT prevent
        VARCHAR(50) total
    }
    occur ||--o{ maybe : style
    occur {
        VARCHAR(50) style
        DATE budget
    }
    maybe ||--o{ expert : within
    maybe {
        DATE within
        TEXT analysis
        VARCHAR(50) good
    }
    expert ||--o{ apply : open
    expert {
        VARCHAR(50) open
        DATE here
    }
    apply ||--o{ catch : these
    apply {
        DATE these
        TEXT way
        VARCHAR(50) one
    }
    catch ||--o{ defense : officer
    catch {
        VARCHAR(50) officer
        DATE training
    }
    defense ||--o{ recent : draw
    defense {
        DATE draw
        TEXT phone
        VARCHAR(50) you
    }
    recent ||--o{ hotel : indicate
    recent {
        VARCHAR(50) indicate
        DATE see
    }
    hotel ||--o{ for : example
    hotel {
        DATE example
        TEXT side
        VARCHAR(50) person
    }
    for ||--o{ become : specific
    for {
        VARCHAR(50) specific
        DATE truth
    }