erDiagram
    happen ||--o{ war : maintain
    happen {
        DATE maintain
        TEXT newspaper
        VARCHAR(50) scene
    }
    war ||--o{ expect : senior
    war {
        VARCHAR(50) senior
        DATE case
    }
    expect ||--o{ fear : sing
    expect {
        DATE sing
        TEXT protect
        VARCHAR(50) job
    }
    fear ||--o{ admit : plan
    fear {
        VARCHAR(50) plan
        DATE can
    }
    admit ||--o{ down : stand
    admit {
        DATE stand
        TEXT specific
        VARCHAR(50) be
    }
    down ||--o{ happen : nice
    down {
        VARCHAR(50) nice
        DATE scene
    }