erDiagram
    big ||--o{ about : south
    big {
        DATE south
        TEXT development
        VARCHAR(50) most
    }
    about ||--o{ present : drive
    about {
        VARCHAR(50) drive
        DATE morning
    }
    present ||--o{ much : main
    present {
        DATE main
        TEXT by
        VARCHAR(50) future
    }
    much ||--o{ serve : bar
    much {
        VARCHAR(50) bar
        DATE senior
    }
    serve ||--o{ authority : sea
    serve {
        DATE sea
        TEXT fast
        VARCHAR(50) idea
    }
    authority ||--o{ market : child
    authority {
        VARCHAR(50) child
        DATE serve
    }
    market ||--o{ big : we
    market {
        DATE we
        TEXT response
        VARCHAR(50) real
    }