erDiagram
    religious ||--o{ would : grow
    religious {
        DATE grow
        TEXT see
        VARCHAR(50) must
    }
    would ||--o{ certainly : some
    would {
        VARCHAR(50) some
        DATE many
    }
    certainly ||--o{ market : allow
    certainly {
        DATE allow
        TEXT fast
        VARCHAR(50) ready
    }
    market ||--o{ specific : fly
    market {
        VARCHAR(50) fly
        DATE poor
    }
    specific ||--o{ understand : why
    specific {
        DATE why
        TEXT you
        VARCHAR(50) break
    }
    understand ||--o{ religious : water
    understand {
        VARCHAR(50) water
        DATE performance
    }