erDiagram
    level ||--o{ international : more
    level {
        DATE more
        TEXT officer
        VARCHAR(50) key
    }
    international ||--o{ challenge : write
    international {
        VARCHAR(50) write
        DATE hit
    }
    challenge ||--o{ perform : three
    challenge {
        DATE three
        TEXT white
        VARCHAR(50) marriage
    }
    perform ||--o{ how : example
    perform {
        VARCHAR(50) example
        DATE increase
    }
    how ||--o{ ready : week
    how {
        DATE week
        TEXT various
        VARCHAR(50) chance
    }
    ready ||--o{ level : evening
    ready {
        VARCHAR(50) evening
        DATE commercial
    }