erDiagram
    direction ||--o{ particularly : material
    direction {
        DATE material
        TEXT threat
        VARCHAR(50) represent
    }
    particularly ||--o{ practice : foot
    particularly {
        VARCHAR(50) foot
        DATE by
    }
    practice ||--o{ able : everyone
    practice {
        DATE everyone
        TEXT least
        VARCHAR(50) PM
    }
    able ||--o{ among : interview
    able {
        VARCHAR(50) interview
        DATE clearly
    }
    among ||--o{ dinner : down
    among {
        DATE down
        TEXT different
        VARCHAR(50) trade
    }
    dinner ||--o{ guess : reflect
    dinner {
        VARCHAR(50) reflect
        DATE protect
    }
    guess ||--o{ his : show
    guess {
        DATE show
        TEXT control
        VARCHAR(50) our
    }
    his ||--o{ agency : really
    his {
        VARCHAR(50) really
        DATE strong
    }
    agency ||--o{ wait : available
    agency {
        DATE available
        TEXT yet
        VARCHAR(50) section
    }
    wait ||--o{ direction : true
    wait {
        VARCHAR(50) true
        DATE avoid
    }