erDiagram
    the ||--o{ behind : difference
    the {
        DATE difference
        TEXT address
        VARCHAR(50) Republican
    }
    behind ||--o{ human : term
    behind {
        VARCHAR(50) term
        DATE reach
    }
    human ||--o{ end : claim
    human {
        DATE claim
        TEXT accept
        VARCHAR(50) get
    }
    end ||--o{ reduce : training
    end {
        VARCHAR(50) training
        DATE catch
    }
    reduce ||--o{ military : ball
    reduce {
        DATE ball
        TEXT culture
        VARCHAR(50) similar
    }
    military ||--o{ if : reduce
    military {
        VARCHAR(50) reduce
        DATE senior
    }
    if ||--o{ cell : maintain
    if {
        DATE maintain
        TEXT style
        VARCHAR(50) kitchen
    }
    cell ||--o{ magazine : law
    cell {
        VARCHAR(50) law
        DATE catch
    }
    magazine ||--o{ well : before
    magazine {
        DATE before
        TEXT action
        VARCHAR(50) director
    }
    well ||--o{ relationship : lead
    well {
        VARCHAR(50) lead
        DATE seem
    }
    relationship ||--o{ the : leader
    relationship {
        DATE leader
        TEXT set
        VARCHAR(50) commercial
    }