erDiagram
    consumer ||--o{ throw : friend
    consumer {
        DATE friend
        TEXT certainly
        VARCHAR(50) garden
    }
    throw ||--o{ effect : loss
    throw {
        VARCHAR(50) loss
        DATE performance
    }
    effect ||--o{ star : plant
    effect {
        DATE plant
        TEXT vote
        VARCHAR(50) no
    }
    star ||--o{ she : clear
    star {
        VARCHAR(50) clear
        DATE office
    }
    she ||--o{ voice : year
    she {
        DATE year
        TEXT look
        VARCHAR(50) new
    }
    voice ||--o{ section : between
    voice {
        VARCHAR(50) between
        DATE both
    }
    section ||--o{ consumer : read
    section {
        DATE read
        TEXT use
        VARCHAR(50) down
    }