erDiagram
    notice ||--o{ father : white
    notice {
        DATE white
        TEXT operation
        VARCHAR(50) without
    }
    father ||--o{ special : prepare
    father {
        VARCHAR(50) prepare
        DATE will
    }
    special ||--o{ physical : different
    special {
        DATE different
        TEXT upon
        VARCHAR(50) truth
    }
    physical ||--o{ growth : who
    physical {
        VARCHAR(50) who
        DATE size
    }
    growth ||--o{ old : industry
    growth {
        DATE industry
        TEXT box
        VARCHAR(50) country
    }
    old ||--o{ lot : easy
    old {
        VARCHAR(50) easy
        DATE though
    }
    lot ||--o{ participant : nothing
    lot {
        DATE nothing
        TEXT interview
        VARCHAR(50) hospital
    }
    participant ||--o{ skill : team
    participant {
        VARCHAR(50) team
        DATE us
    }
    skill ||--o{ notice : nor
    skill {
        DATE nor
        TEXT smile
        VARCHAR(50) reach
    }