erDiagram
    phone ||--o{ image : no
    phone {
        DATE no
        TEXT central
        VARCHAR(50) every
    }
    image ||--o{ any : under
    image {
        VARCHAR(50) under
        DATE budget
    }
    any ||--o{ happen : film
    any {
        DATE film
        TEXT whom
        VARCHAR(50) impact
    }
    happen ||--o{ ok : fish
    happen {
        VARCHAR(50) fish
        DATE his
    }
    ok ||--o{ speech : though
    ok {
        DATE though
        TEXT may
        VARCHAR(50) leg
    }
    speech ||--o{ next : democratic
    speech {
        VARCHAR(50) democratic
        DATE within
    }
    next ||--o{ door : main
    next {
        DATE main
        TEXT sister
        VARCHAR(50) like
    }
    door ||--o{ fight : hundred
    door {
        VARCHAR(50) hundred
        DATE tax
    }
    fight ||--o{ accept : available
    fight {
        DATE available
        TEXT five
        VARCHAR(50) education
    }
    accept ||--o{ whom : reveal
    accept {
        VARCHAR(50) reveal
        DATE consumer
    }
    whom ||--o{ suddenly : sit
    whom {
        DATE sit
        TEXT simple
        VARCHAR(50) check
    }
    suddenly ||--o{ phone : simply
    suddenly {
        VARCHAR(50) simply
        DATE cup
    }