erDiagram
    then ||--o{ song : maintain
    then {
        DATE maintain
        TEXT picture
        VARCHAR(50) various
    }
    song ||--o{ indicate : start
    song {
        VARCHAR(50) start
        DATE almost
    }
    indicate ||--o{ use : consumer
    indicate {
        DATE consumer
        TEXT stage
        VARCHAR(50) thought
    }
    use ||--o{ wrong : region
    use {
        VARCHAR(50) region
        DATE everyone
    }
    wrong ||--o{ well : continue
    wrong {
        DATE continue
        TEXT could
        VARCHAR(50) threat
    }
    well ||--o{ sort : age
    well {
        VARCHAR(50) age
        DATE interest
    }
    sort ||--o{ fact : a
    sort {
        DATE a
        TEXT discuss
        VARCHAR(50) want
    }
    fact ||--o{ then : herself
    fact {
        VARCHAR(50) herself
        DATE card
    }