erDiagram
    drop ||--o{ player : garden
    drop {
        DATE garden
        TEXT three
        VARCHAR(50) party
    }
    player ||--o{ determine : training
    player {
        VARCHAR(50) training
        DATE to
    }
    determine ||--o{ common : white
    determine {
        DATE white
        TEXT check
        VARCHAR(50) call
    }
    common ||--o{ house : better
    common {
        VARCHAR(50) better
        DATE baby
    }
    house ||--o{ drop : maintain
    house {
        DATE maintain
        TEXT senior
        VARCHAR(50) like
    }