erDiagram
    national ||--o{ agreement : less
    national {
        DATE less
        TEXT region
        VARCHAR(50) certainly
    }
    agreement ||--o{ military : loss
    agreement {
        VARCHAR(50) loss
        DATE four
    }
    military ||--o{ west : trade
    military {
        DATE trade
        TEXT bank
        VARCHAR(50) understand
    }
    west ||--o{ follow : guy
    west {
        VARCHAR(50) guy
        DATE evidence
    }
    follow ||--o{ present : adult
    follow {
        DATE adult
        TEXT product
        VARCHAR(50) writer
    }
    present ||--o{ fear : discover
    present {
        VARCHAR(50) discover
        DATE any
    }
    fear ||--o{ Mrs : without
    fear {
        DATE without
        TEXT expect
        VARCHAR(50) worker
    }
    Mrs ||--o{ strategy : game
    Mrs {
        VARCHAR(50) game
        DATE half
    }
    strategy ||--o{ force : know
    strategy {
        DATE know
        TEXT want
        VARCHAR(50) father
    }
    force ||--o{ discussion : fill
    force {
        VARCHAR(50) fill
        DATE serious
    }
    discussion ||--o{ national : worry
    discussion {
        DATE worry
        TEXT surface
        VARCHAR(50) other
    }