erDiagram
    idea ||--o{ care : ten
    idea {
        DATE ten
        TEXT rich
        VARCHAR(50) help
    }
    care ||--o{ reason : suggest
    care {
        VARCHAR(50) suggest
        DATE fish
    }
    reason ||--o{ his : social
    reason {
        DATE social
        TEXT maintain
        VARCHAR(50) population
    }
    his ||--o{ continue : international
    his {
        VARCHAR(50) international
        DATE type
    }
    continue ||--o{ test : low
    continue {
        DATE low
        TEXT politics
        VARCHAR(50) back
    }
    test ||--o{ change : deep
    test {
        VARCHAR(50) deep
        DATE mouth
    }
    change ||--o{ idea : level
    change {
        DATE level
        TEXT new
        VARCHAR(50) what
    }