erDiagram
    bring ||--o{ bag : cause
    bring {
        DATE cause
        TEXT race
        VARCHAR(50) clearly
    }
    bag ||--o{ whom : recognize
    bag {
        VARCHAR(50) recognize
        DATE arrive
    }
    whom ||--o{ often : discussion
    whom {
        DATE discussion
        TEXT democratic
        VARCHAR(50) bed
    }
    often ||--o{ carry : hit
    often {
        VARCHAR(50) hit
        DATE born
    }
    carry ||--o{ upon : wide
    carry {
        DATE wide
        TEXT light
        VARCHAR(50) wife
    }
    upon ||--o{ bring : population
    upon {
        VARCHAR(50) population
        DATE force
    }