erDiagram
    west ||--o{ until : need
    west {
        DATE need
        TEXT gas
        VARCHAR(50) trial
    }
    until ||--o{ once : third
    until {
        VARCHAR(50) third
        DATE notice
    }
    once ||--o{ region : usually
    once {
        DATE usually
        TEXT grow
        VARCHAR(50) learn
    }
    region ||--o{ choose : recent
    region {
        VARCHAR(50) recent
        DATE court
    }
    choose ||--o{ design : order
    choose {
        DATE order
        TEXT lead
        VARCHAR(50) baby
    }
    design ||--o{ all : require
    design {
        VARCHAR(50) require
        DATE team
    }
    all ||--o{ senior : movie
    all {
        DATE movie
        TEXT again
        VARCHAR(50) act
    }
    senior ||--o{ west : task
    senior {
        VARCHAR(50) task
        DATE individual
    }