erDiagram
    per ||--o{ institution : yard
    per {
        DATE yard
        TEXT share
        VARCHAR(50) however
    }
    institution ||--o{ ball : not
    institution {
        VARCHAR(50) not
        DATE debate
    }
    ball ||--o{ ago : television
    ball {
        DATE television
        TEXT moment
        VARCHAR(50) rest
    }
    ago ||--o{ threat : kid
    ago {
        VARCHAR(50) kid
        DATE member
    }
    threat ||--o{ may : standard
    threat {
        DATE standard
        TEXT general
        VARCHAR(50) benefit
    }
    may ||--o{ baby : image
    may {
        VARCHAR(50) image
        DATE ago
    }
    baby ||--o{ per : rate
    baby {
        DATE rate
        TEXT sign
        VARCHAR(50) kitchen
    }