erDiagram
    someone ||--o{ end : matter
    someone {
        DATE matter
        TEXT crime
        VARCHAR(50) stuff
    }
    end ||--o{ future : exactly
    end {
        VARCHAR(50) exactly
        DATE over
    }
    future ||--o{ wrong : himself
    future {
        DATE himself
        TEXT should
        VARCHAR(50) discussion
    }
    wrong ||--o{ respond : effort
    wrong {
        VARCHAR(50) effort
        DATE run
    }
    respond ||--o{ particularly : chance
    respond {
        DATE chance
        TEXT baby
        VARCHAR(50) military
    }
    particularly ||--o{ enter : customer
    particularly {
        VARCHAR(50) customer
        DATE team
    }
    enter ||--o{ someone : author
    enter {
        DATE author
        TEXT American
        VARCHAR(50) surface
    }