erDiagram
    second ||--o{ star : school
    second {
        DATE school
        TEXT order
        VARCHAR(50) pay
    }
    star ||--o{ enjoy : price
    star {
        VARCHAR(50) price
        DATE concern
    }
    enjoy ||--o{ next : method
    enjoy {
        DATE method
        TEXT four
        VARCHAR(50) soldier
    }
    next ||--o{ affect : mention
    next {
        VARCHAR(50) mention
        DATE might
    }
    affect ||--o{ ok : bar
    affect {
        DATE bar
        TEXT want
        VARCHAR(50) price
    }
    ok ||--o{ concern : word
    ok {
        VARCHAR(50) word
        DATE per
    }
    concern ||--o{ power : successful
    concern {
        DATE successful
        TEXT pay
        VARCHAR(50) worry
    }
    power ||--o{ skin : blue
    power {
        VARCHAR(50) blue
        DATE beyond
    }
    skin ||--o{ second : activity
    skin {
        DATE activity
        TEXT worry
        VARCHAR(50) actually
    }