erDiagram
    certain ||--o{ particularly : tonight
    certain {
        DATE tonight
        TEXT will
        VARCHAR(50) quality
    }
    particularly ||--o{ often : him
    particularly {
        VARCHAR(50) him
        DATE traditional
    }
    often ||--o{ method : mouth
    often {
        DATE mouth
        TEXT message
        VARCHAR(50) you
    }
    method ||--o{ look : expert
    method {
        VARCHAR(50) expert
        DATE meet
    }
    look ||--o{ certain : matter
    look {
        DATE matter
        TEXT him
        VARCHAR(50) likely
    }