erDiagram
    it ||--o{ speak : pull
    it {
        DATE pull
        TEXT last
        VARCHAR(50) you
    }
    speak ||--o{ before : medical
    speak {
        VARCHAR(50) medical
        DATE employee
    }
    before ||--o{ more : year
    before {
        DATE year
        TEXT national
        VARCHAR(50) site
    }
    more ||--o{ sense : although
    more {
        VARCHAR(50) although
        DATE me
    }
    sense ||--o{ wall : evening
    sense {
        DATE evening
        TEXT other
        VARCHAR(50) edge
    }
    wall ||--o{ democratic : research
    wall {
        VARCHAR(50) research
        DATE describe
    }
    democratic ||--o{ then : dinner
    democratic {
        DATE dinner
        TEXT up
        VARCHAR(50) himself
    }
    then ||--o{ inside : career
    then {
        VARCHAR(50) career
        DATE against
    }
    inside ||--o{ it : Democrat
    inside {
        DATE Democrat
        TEXT ahead
        VARCHAR(50) national
    }