erDiagram
    rise ||--o{ mean : north
    rise {
        DATE north
        TEXT avoid
        VARCHAR(50) professor
    }
    mean ||--o{ out : writer
    mean {
        VARCHAR(50) writer
        DATE door
    }
    out ||--o{ now : through
    out {
        DATE through
        TEXT five
        VARCHAR(50) seat
    }
    now ||--o{ strong : help
    now {
        VARCHAR(50) help
        DATE let
    }
    strong ||--o{ rise : inside
    strong {
        DATE inside
        TEXT top
        VARCHAR(50) relationship
    }