erDiagram
    represent ||--o{ send : country
    represent {
        DATE country
        TEXT account
        VARCHAR(50) once
    }
    send ||--o{ poor : treat
    send {
        VARCHAR(50) treat
        DATE character
    }
    poor ||--o{ behavior : major
    poor {
        DATE major
        TEXT agreement
        VARCHAR(50) song
    }
    behavior ||--o{ television : carry
    behavior {
        VARCHAR(50) carry
        DATE put
    }
    television ||--o{ foreign : audience
    television {
        DATE audience
        TEXT reflect
        VARCHAR(50) five
    }
    foreign ||--o{ score : when
    foreign {
        VARCHAR(50) when
        DATE apply
    }
    score ||--o{ boy : may
    score {
        DATE may
        TEXT during
        VARCHAR(50) writer
    }
    boy ||--o{ card : effort
    boy {
        VARCHAR(50) effort
        DATE rock
    }
    card ||--o{ represent : improve
    card {
        DATE improve
        TEXT matter
        VARCHAR(50) find
    }