erDiagram
    stand ||--o{ outside : read
    stand {
        DATE read
        TEXT maintain
        VARCHAR(50) reflect
    }
    outside ||--o{ north : threat
    outside {
        VARCHAR(50) threat
        DATE require
    }
    north ||--o{ sea : white
    north {
        DATE white
        TEXT institution
        VARCHAR(50) else
    }
    sea ||--o{ morning : minute
    sea {
        VARCHAR(50) minute
        DATE treat
    }
    morning ||--o{ perhaps : several
    morning {
        DATE several
        TEXT front
        VARCHAR(50) speak
    }
    perhaps ||--o{ market : represent
    perhaps {
        VARCHAR(50) represent
        DATE plant
    }
    market ||--o{ stand : hold
    market {
        DATE hold
        TEXT according
        VARCHAR(50) politics
    }