erDiagram
    skill ||--o{ head : trip
    skill {
        DATE trip
        TEXT fill
        VARCHAR(50) continue
    }
    head ||--o{ house : after
    head {
        VARCHAR(50) after
        DATE economic
    }
    house ||--o{ least : argue
    house {
        DATE argue
        TEXT democratic
        VARCHAR(50) long
    }
    least ||--o{ community : office
    least {
        VARCHAR(50) office
        DATE once
    }
    community ||--o{ woman : thing
    community {
        DATE thing
        TEXT minute
        VARCHAR(50) develop
    }
    woman ||--o{ fly : little
    woman {
        VARCHAR(50) little
        DATE type
    }
    fly ||--o{ how : themselves
    fly {
        DATE themselves
        TEXT society
        VARCHAR(50) group
    }
    how ||--o{ third : positive
    how {
        VARCHAR(50) positive
        DATE understand
    }
    third ||--o{ key : theory
    third {
        DATE theory
        TEXT personal
        VARCHAR(50) side
    }
    key ||--o{ skill : report
    key {
        VARCHAR(50) report
        DATE save
    }