erDiagram
    bank ||--o{ gun : bad
    bank {
        DATE bad
        TEXT accept
        VARCHAR(50) effort
    }
    gun ||--o{ after : blue
    gun {
        VARCHAR(50) blue
        DATE moment
    }
    after ||--o{ billion : technology
    after {
        DATE technology
        TEXT real
        VARCHAR(50) home
    }
    billion ||--o{ speech : down
    billion {
        VARCHAR(50) down
        DATE drug
    }
    speech ||--o{ bank : word
    speech {
        DATE word
        TEXT station
        VARCHAR(50) sign
    }