erDiagram
    choice ||--o{ call : no
    choice {
        DATE no
        TEXT decade
        VARCHAR(50) story
    }
    call ||--o{ never : might
    call {
        VARCHAR(50) might
        DATE win
    }
    never ||--o{ card : degree
    never {
        DATE degree
        TEXT material
        VARCHAR(50) future
    }
    card ||--o{ those : student
    card {
        VARCHAR(50) student
        DATE throughout
    }
    those ||--o{ success : page
    those {
        DATE page
        TEXT movie
        VARCHAR(50) sometimes
    }
    success ||--o{ old : during
    success {
        VARCHAR(50) during
        DATE ready
    }
    old ||--o{ try : less
    old {
        DATE less
        TEXT experience
        VARCHAR(50) college
    }
    try ||--o{ ask : week
    try {
        VARCHAR(50) week
        DATE probably
    }
    ask ||--o{ to : story
    ask {
        DATE story
        TEXT government
        VARCHAR(50) machine
    }
    to ||--o{ picture : successful
    to {
        VARCHAR(50) successful
        DATE treat
    }
    picture ||--o{ whatever : newspaper
    picture {
        DATE newspaper
        TEXT finally
        VARCHAR(50) medical
    }
    whatever ||--o{ choice : tell
    whatever {
        VARCHAR(50) tell
        DATE just
    }