erDiagram
    own ||--o{ success : stop
    own {
        DATE stop
        TEXT every
        VARCHAR(50) start
    }
    success ||--o{ bit : force
    success {
        VARCHAR(50) force
        DATE many
    }
    bit ||--o{ father : citizen
    bit {
        DATE citizen
        TEXT clear
        VARCHAR(50) fast
    }
    father ||--o{ page : throw
    father {
        VARCHAR(50) throw
        DATE western
    }
    page ||--o{ scene : country
    page {
        DATE country
        TEXT score
        VARCHAR(50) move
    }
    scene ||--o{ own : report
    scene {
        VARCHAR(50) report
        DATE simple
    }