erDiagram
    fund ||--o{ yard : majority
    fund {
        DATE majority
        TEXT some
        VARCHAR(50) rise
    }
    yard ||--o{ prevent : six
    yard {
        VARCHAR(50) six
        DATE article
    }
    prevent ||--o{ member : major
    prevent {
        DATE major
        TEXT medical
        VARCHAR(50) itself
    }
    member ||--o{ cell : study
    member {
        VARCHAR(50) study
        DATE employee
    }
    cell ||--o{ shoulder : resource
    cell {
        DATE resource
        TEXT term
        VARCHAR(50) thus
    }
    shoulder ||--o{ figure : data
    shoulder {
        VARCHAR(50) data
        DATE international
    }
    figure ||--o{ read : then
    figure {
        DATE then
        TEXT effort
        VARCHAR(50) bill
    }
    read ||--o{ have : us
    read {
        VARCHAR(50) us
        DATE memory
    }
    have ||--o{ last : practice
    have {
        DATE practice
        TEXT all
        VARCHAR(50) PM
    }
    last ||--o{ fund : budget
    last {
        VARCHAR(50) budget
        DATE poor
    }