erDiagram
    include ||--o{ trade : fill
    include {
        DATE fill
        TEXT modern
        VARCHAR(50) store
    }
    trade ||--o{ hospital : open
    trade {
        VARCHAR(50) open
        DATE away
    }
    hospital ||--o{ southern : young
    hospital {
        DATE young
        TEXT then
        VARCHAR(50) small
    }
    southern ||--o{ camera : TV
    southern {
        VARCHAR(50) TV
        DATE as
    }
    camera ||--o{ charge : east
    camera {
        DATE east
        TEXT good
        VARCHAR(50) even
    }
    charge ||--o{ back : forward
    charge {
        VARCHAR(50) forward
        DATE affect
    }
    back ||--o{ project : measure
    back {
        DATE measure
        TEXT question
        VARCHAR(50) occur
    }
    project ||--o{ include : senior
    project {
        VARCHAR(50) senior
        DATE state
    }