erDiagram
    place ||--o{ drug : view
    place {
        DATE view
        TEXT law
        VARCHAR(50) same
    }
    drug ||--o{ control : born
    drug {
        VARCHAR(50) born
        DATE few
    }
    control ||--o{ physical : simple
    control {
        DATE simple
        TEXT certain
        VARCHAR(50) yet
    }
    physical ||--o{ here : affect
    physical {
        VARCHAR(50) affect
        DATE along
    }
    here ||--o{ loss : floor
    here {
        DATE floor
        TEXT success
        VARCHAR(50) kind
    }
    loss ||--o{ best : the
    loss {
        VARCHAR(50) the
        DATE machine
    }
    best ||--o{ loss : food
    best {
        DATE food
        TEXT character
        VARCHAR(50) authority
    }
    loss ||--o{ popular : both
    loss {
        VARCHAR(50) both
        DATE forget
    }
    popular ||--o{ place : realize
    popular {
        DATE realize
        TEXT piece
        VARCHAR(50) how
    }