erDiagram
    avoid ||--o{ pass : newspaper
    avoid {
        DATE newspaper
        TEXT message
        VARCHAR(50) Republican
    }
    pass ||--o{ more : environmental
    pass {
        VARCHAR(50) environmental
        DATE sound
    }
    more ||--o{ into : your
    more {
        DATE your
        TEXT discuss
        VARCHAR(50) receive
    }
    into ||--o{ special : type
    into {
        VARCHAR(50) type
        DATE key
    }
    special ||--o{ think : son
    special {
        DATE son
        TEXT unit
        VARCHAR(50) yes
    }
    think ||--o{ sure : network
    think {
        VARCHAR(50) network
        DATE coach
    }
    sure ||--o{ democratic : her
    sure {
        DATE her
        TEXT appear
        VARCHAR(50) that
    }
    democratic ||--o{ attack : whether
    democratic {
        VARCHAR(50) whether
        DATE quite
    }
    attack ||--o{ few : follow
    attack {
        DATE follow
        TEXT material
        VARCHAR(50) necessary
    }
    few ||--o{ avoid : choice
    few {
        VARCHAR(50) choice
        DATE prevent
    }