erDiagram
    idea ||--o{ attention : type
    idea {
        DATE type
        TEXT good
        VARCHAR(50) most
    }
    attention ||--o{ method : benefit
    attention {
        VARCHAR(50) benefit
        DATE culture
    }
    method ||--o{ skill : total
    method {
        DATE total
        TEXT card
        VARCHAR(50) break
    }
    skill ||--o{ hour : who
    skill {
        VARCHAR(50) who
        DATE respond
    }
    hour ||--o{ member : government
    hour {
        DATE government
        TEXT act
        VARCHAR(50) agent
    }
    member ||--o{ court : west
    member {
        VARCHAR(50) west
        DATE so
    }
    court ||--o{ idea : beyond
    court {
        DATE beyond
        TEXT job
        VARCHAR(50) later
    }