erDiagram
    news ||--o{ south : high
    news {
        DATE high
        TEXT blood
        VARCHAR(50) worry
    }
    south ||--o{ wish : art
    south {
        VARCHAR(50) art
        DATE in
    }
    wish ||--o{ than : manage
    wish {
        DATE manage
        TEXT more
        VARCHAR(50) necessary
    }
    than ||--o{ stop : son
    than {
        VARCHAR(50) son
        DATE such
    }
    stop ||--o{ west : wall
    stop {
        DATE wall
        TEXT as
        VARCHAR(50) difficult
    }
    west ||--o{ ability : here
    west {
        VARCHAR(50) here
        DATE want
    }
    ability ||--o{ owner : staff
    ability {
        DATE staff
        TEXT everything
        VARCHAR(50) water
    }
    owner ||--o{ be : recent
    owner {
        VARCHAR(50) recent
        DATE civil
    }
    be ||--o{ activity : goal
    be {
        DATE goal
        TEXT picture
        VARCHAR(50) member
    }
    activity ||--o{ born : may
    activity {
        VARCHAR(50) may
        DATE from
    }
    born ||--o{ rock : offer
    born {
        DATE offer
        TEXT positive
        VARCHAR(50) money
    }
    rock ||--o{ news : computer
    rock {
        VARCHAR(50) computer
        DATE image
    }