erDiagram
    compare ||--o{ poor : material
    compare {
        DATE material
        TEXT cover
        VARCHAR(50) push
    }
    poor ||--o{ establish : president
    poor {
        VARCHAR(50) president
        DATE deal
    }
    establish ||--o{ bag : remain
    establish {
        DATE remain
        TEXT through
        VARCHAR(50) since
    }
    bag ||--o{ up : reduce
    bag {
        VARCHAR(50) reduce
        DATE down
    }
    up ||--o{ around : when
    up {
        DATE when
        TEXT score
        VARCHAR(50) population
    }
    around ||--o{ wall : leave
    around {
        VARCHAR(50) leave
        DATE pass
    }
    wall ||--o{ set : choice
    wall {
        DATE choice
        TEXT toward
        VARCHAR(50) media
    }
    set ||--o{ compare : forward
    set {
        VARCHAR(50) forward
        DATE statement
    }