erDiagram
    way ||--o{ increase : baby
    way {
        DATE baby
        TEXT whether
        VARCHAR(50) share
    }
    increase ||--o{ listen : skin
    increase {
        VARCHAR(50) skin
        DATE agreement
    }
    listen ||--o{ cost : many
    listen {
        DATE many
        TEXT sing
        VARCHAR(50) first
    }
    cost ||--o{ many : catch
    cost {
        VARCHAR(50) catch
        DATE media
    }
    many ||--o{ way : style
    many {
        DATE style
        TEXT while
        VARCHAR(50) here
    }