erDiagram
    apply ||--o{ hold : reach
    apply {
        DATE reach
        TEXT part
        VARCHAR(50) summer
    }
    hold ||--o{ matter : table
    hold {
        VARCHAR(50) table
        DATE television
    }
    matter ||--o{ question : will
    matter {
        DATE will
        TEXT sport
        VARCHAR(50) something
    }
    question ||--o{ establish : majority
    question {
        VARCHAR(50) majority
        DATE amount
    }
    establish ||--o{ he : air
    establish {
        DATE air
        TEXT since
        VARCHAR(50) land
    }
    he ||--o{ organization : chance
    he {
        VARCHAR(50) chance
        DATE tough
    }
    organization ||--o{ cover : fear
    organization {
        DATE fear
        TEXT over
        VARCHAR(50) relationship
    }
    cover ||--o{ for : it
    cover {
        VARCHAR(50) it
        DATE force
    }
    for ||--o{ attention : far
    for {
        DATE far
        TEXT sell
        VARCHAR(50) way
    }
    attention ||--o{ apply : hospital
    attention {
        VARCHAR(50) hospital
        DATE light
    }