erDiagram
    take ||--o{ woman : everyone
    take {
        DATE everyone
        TEXT throw
        VARCHAR(50) again
    }
    woman ||--o{ again : short
    woman {
        VARCHAR(50) short
        DATE focus
    }
    again ||--o{ put : early
    again {
        DATE early
        TEXT their
        VARCHAR(50) box
    }
    put ||--o{ instead : shoulder
    put {
        VARCHAR(50) shoulder
        DATE may
    }
    instead ||--o{ charge : moment
    instead {
        DATE moment
        TEXT each
        VARCHAR(50) personal
    }
    charge ||--o{ establish : majority
    charge {
        VARCHAR(50) majority
        DATE four
    }
    establish ||--o{ chance : skin
    establish {
        DATE skin
        TEXT according
        VARCHAR(50) lead
    }
    chance ||--o{ take : late
    chance {
        VARCHAR(50) late
        DATE time
    }