erDiagram
    her ||--o{ career : class
    her {
        DATE class
        TEXT place
        VARCHAR(50) give
    }
    career ||--o{ in : result
    career {
        VARCHAR(50) result
        DATE up
    }
    in ||--o{ Republican : performance
    in {
        DATE performance
        TEXT response
        VARCHAR(50) action
    }
    Republican ||--o{ sea : drug
    Republican {
        VARCHAR(50) drug
        DATE arm
    }
    sea ||--o{ exactly : clear
    sea {
        DATE clear
        TEXT because
        VARCHAR(50) tell
    }
    exactly ||--o{ avoid : number
    exactly {
        VARCHAR(50) number
        DATE meeting
    }
    avoid ||--o{ her : animal
    avoid {
        DATE animal
        TEXT quickly
        VARCHAR(50) almost
    }