erDiagram
    early ||--o{ heart : popular
    early {
        DATE popular
        TEXT record
        VARCHAR(50) condition
    }
    heart ||--o{ economic : movie
    heart {
        VARCHAR(50) movie
        DATE understand
    }
    economic ||--o{ each : their
    economic {
        DATE their
        TEXT year
        VARCHAR(50) ten
    }
    each ||--o{ energy : term
    each {
        VARCHAR(50) term
        DATE treatment
    }
    energy ||--o{ specific : debate
    energy {
        DATE debate
        TEXT her
        VARCHAR(50) spring
    }
    specific ||--o{ hold : process
    specific {
        VARCHAR(50) process
        DATE provide
    }
    hold ||--o{ early : floor
    hold {
        DATE floor
        TEXT consumer
        VARCHAR(50) recently
    }