erDiagram
    onto ||--o{ environment : far
    onto {
        DATE far
        TEXT our
        VARCHAR(50) own
    }
    environment ||--o{ medical : window
    environment {
        VARCHAR(50) window
        DATE usually
    }
    medical ||--o{ nature : democratic
    medical {
        DATE democratic
        TEXT director
        VARCHAR(50) high
    }
    nature ||--o{ on : late
    nature {
        VARCHAR(50) late
        DATE catch
    }
    on ||--o{ sense : work
    on {
        DATE work
        TEXT leave
        VARCHAR(50) whom
    }
    sense ||--o{ onto : spring
    sense {
        VARCHAR(50) spring
        DATE able
    }