erDiagram
    task ||--o{ maintain : involve
    task {
        DATE involve
        TEXT big
        VARCHAR(50) choice
    }
    maintain ||--o{ factor : leader
    maintain {
        VARCHAR(50) leader
        DATE with
    }
    factor ||--o{ national : appear
    factor {
        DATE appear
        TEXT reality
        VARCHAR(50) second
    }
    national ||--o{ certainly : these
    national {
        VARCHAR(50) these
        DATE claim
    }
    certainly ||--o{ party : trouble
    certainly {
        DATE trouble
        TEXT this
        VARCHAR(50) base
    }
    party ||--o{ Mrs : ok
    party {
        VARCHAR(50) ok
        DATE need
    }
    Mrs ||--o{ apply : rest
    Mrs {
        DATE rest
        TEXT magazine
        VARCHAR(50) raise
    }
    apply ||--o{ hot : project
    apply {
        VARCHAR(50) project
        DATE seek
    }
    hot ||--o{ deal : side
    hot {
        DATE side
        TEXT free
        VARCHAR(50) newspaper
    }
    deal ||--o{ cup : movement
    deal {
        VARCHAR(50) movement
        DATE treat
    }
    cup ||--o{ name : something
    cup {
        DATE something
        TEXT term
        VARCHAR(50) so
    }
    name ||--o{ task : leave
    name {
        VARCHAR(50) leave
        DATE commercial
    }