erDiagram
    simply ||--o{ not : head
    simply {
        DATE head
        TEXT not
        VARCHAR(50) heavy
    }
    not ||--o{ start : it
    not {
        VARCHAR(50) it
        DATE to
    }
    start ||--o{ treat : score
    start {
        DATE score
        TEXT first
        VARCHAR(50) huge
    }
    treat ||--o{ land : address
    treat {
        VARCHAR(50) address
        DATE he
    }
    land ||--o{ able : activity
    land {
        DATE activity
        TEXT middle
        VARCHAR(50) size
    }
    able ||--o{ majority : board
    able {
        VARCHAR(50) board
        DATE energy
    }
    majority ||--o{ simply : resource
    majority {
        DATE resource
        TEXT natural
        VARCHAR(50) very
    }