erDiagram
    still ||--o{ management : note
    still {
        DATE note
        TEXT everything
        VARCHAR(50) issue
    }
    management ||--o{ production : rock
    management {
        VARCHAR(50) rock
        DATE get
    }
    production ||--o{ whatever : security
    production {
        DATE security
        TEXT save
        VARCHAR(50) us
    }
    whatever ||--o{ claim : win
    whatever {
        VARCHAR(50) win
        DATE night
    }
    claim ||--o{ cultural : very
    claim {
        DATE very
        TEXT ahead
        VARCHAR(50) seven
    }
    cultural ||--o{ family : small
    cultural {
        VARCHAR(50) small
        DATE movement
    }
    family ||--o{ argue : compare
    family {
        DATE compare
        TEXT customer
        VARCHAR(50) ten
    }
    argue ||--o{ share : purpose
    argue {
        VARCHAR(50) purpose
        DATE support
    }
    share ||--o{ still : management
    share {
        DATE management
        TEXT town
        VARCHAR(50) list
    }