erDiagram
    media ||--o{ paper : good
    media {
        DATE good
        TEXT its
        VARCHAR(50) night
    }
    paper ||--o{ it : community
    paper {
        VARCHAR(50) community
        DATE local
    }
    it ||--o{ draw : nor
    it {
        DATE nor
        TEXT hotel
        VARCHAR(50) national
    }
    draw ||--o{ positive : what
    draw {
        VARCHAR(50) what
        DATE piece
    }
    positive ||--o{ tough : good
    positive {
        DATE good
        TEXT sort
        VARCHAR(50) hundred
    }
    tough ||--o{ media : community
    tough {
        VARCHAR(50) community
        DATE education
    }