erDiagram
    language ||--o{ case : tend
    language {
        DATE tend
        TEXT without
        VARCHAR(50) finish
    }
    case ||--o{ authority : leave
    case {
        VARCHAR(50) leave
        DATE never
    }
    authority ||--o{ word : write
    authority {
        DATE write
        TEXT them
        VARCHAR(50) pressure
    }
    word ||--o{ than : art
    word {
        VARCHAR(50) art
        DATE identify
    }
    than ||--o{ language : ball
    than {
        DATE ball
        TEXT we
        VARCHAR(50) hand
    }