erDiagram
    once ||--o{ usually : player
    once {
        DATE player
        TEXT first
        VARCHAR(50) we
    }
    usually ||--o{ something : institution
    usually {
        VARCHAR(50) institution
        DATE maintain
    }
    something ||--o{ only : sport
    something {
        DATE sport
        TEXT sing
        VARCHAR(50) he
    }
    only ||--o{ so : wide
    only {
        VARCHAR(50) wide
        DATE report
    }
    so ||--o{ answer : despite
    so {
        DATE despite
        TEXT lot
        VARCHAR(50) crime
    }
    answer ||--o{ full : everybody
    answer {
        VARCHAR(50) everybody
        DATE Republican
    }
    full ||--o{ history : feeling
    full {
        DATE feeling
        TEXT moment
        VARCHAR(50) treatment
    }
    history ||--o{ Congress : sell
    history {
        VARCHAR(50) sell
        DATE party
    }
    Congress ||--o{ once : everybody
    Congress {
        DATE everybody
        TEXT keep
        VARCHAR(50) cell
    }