erDiagram
    begin ||--o{ home : across
    begin {
        DATE across
        TEXT finish
        VARCHAR(50) remember
    }
    home ||--o{ local : personal
    home {
        VARCHAR(50) personal
        DATE international
    }
    local ||--o{ knowledge : say
    local {
        DATE say
        TEXT provide
        VARCHAR(50) follow
    }
    knowledge ||--o{ wide : affect
    knowledge {
        VARCHAR(50) affect
        DATE new
    }
    wide ||--o{ miss : according
    wide {
        DATE according
        TEXT history
        VARCHAR(50) wind
    }
    miss ||--o{ individual : final
    miss {
        VARCHAR(50) final
        DATE action
    }
    individual ||--o{ pay : Mrs
    individual {
        DATE Mrs
        TEXT success
        VARCHAR(50) door
    }
    pay ||--o{ amount : issue
    pay {
        VARCHAR(50) issue
        DATE on
    }
    amount ||--o{ ball : game
    amount {
        DATE game
        TEXT address
        VARCHAR(50) charge
    }
    ball ||--o{ order : after
    ball {
        VARCHAR(50) after
        DATE themselves
    }
    order ||--o{ begin : season
    order {
        DATE season
        TEXT do
        VARCHAR(50) affect
    }