erDiagram
    approach ||--o{ radio : first
    approach {
        DATE first
        TEXT long
        VARCHAR(50) maintain
    }
    radio ||--o{ husband : everything
    radio {
        VARCHAR(50) everything
        DATE it
    }
    husband ||--o{ leader : in
    husband {
        DATE in
        TEXT analysis
        VARCHAR(50) guy
    }
    leader ||--o{ report : blood
    leader {
        VARCHAR(50) blood
        DATE necessary
    }
    report ||--o{ live : step
    report {
        DATE step
        TEXT strong
        VARCHAR(50) bank
    }
    live ||--o{ leg : mean
    live {
        VARCHAR(50) mean
        DATE like
    }
    leg ||--o{ who : someone
    leg {
        DATE someone
        TEXT also
        VARCHAR(50) computer
    }
    who ||--o{ account : wonder
    who {
        VARCHAR(50) wonder
        DATE team
    }
    account ||--o{ friend : sense
    account {
        DATE sense
        TEXT pressure
        VARCHAR(50) should
    }
    friend ||--o{ condition : add
    friend {
        VARCHAR(50) add
        DATE debate
    }
    condition ||--o{ approach : moment
    condition {
        DATE moment
        TEXT bank
        VARCHAR(50) nor
    }