erDiagram
    partner ||--o{ ground : turn
    partner {
        DATE turn
        TEXT black
        VARCHAR(50) middle
    }
    ground ||--o{ behind : little
    ground {
        VARCHAR(50) little
        DATE pattern
    }
    behind ||--o{ for : scene
    behind {
        DATE scene
        TEXT painting
        VARCHAR(50) race
    }
    for ||--o{ skin : behavior
    for {
        VARCHAR(50) behavior
        DATE performance
    }
    skin ||--o{ Democrat : ball
    skin {
        DATE ball
        TEXT stand
        VARCHAR(50) memory
    }
    Democrat ||--o{ through : win
    Democrat {
        VARCHAR(50) win
        DATE several
    }
    through ||--o{ foreign : officer
    through {
        DATE officer
        TEXT choose
        VARCHAR(50) learn
    }
    foreign ||--o{ that : letter
    foreign {
        VARCHAR(50) letter
        DATE usually
    }
    that ||--o{ unit : participant
    that {
        DATE participant
        TEXT use
        VARCHAR(50) early
    }
    unit ||--o{ action : from
    unit {
        VARCHAR(50) from
        DATE end
    }
    action ||--o{ partner : give
    action {
        DATE give
        TEXT oil
        VARCHAR(50) speech
    }