erDiagram
    thus ||--o{ almost : move
    thus {
        DATE move
        TEXT present
        VARCHAR(50) perhaps
    }
    almost ||--o{ risk : police
    almost {
        VARCHAR(50) police
        DATE other
    }
    risk ||--o{ everything : appear
    risk {
        DATE appear
        TEXT down
        VARCHAR(50) lay
    }
    everything ||--o{ teach : seem
    everything {
        VARCHAR(50) seem
        DATE wife
    }
    teach ||--o{ thus : course
    teach {
        DATE course
        TEXT story
        VARCHAR(50) travel
    }