erDiagram
    because ||--o{ purpose : parent
    because {
        DATE parent
        TEXT environmental
        VARCHAR(50) report
    }
    purpose ||--o{ arm : fly
    purpose {
        VARCHAR(50) fly
        DATE analysis
    }
    arm ||--o{ benefit : I
    arm {
        DATE I
        TEXT buy
        VARCHAR(50) focus
    }
    benefit ||--o{ think : college
    benefit {
        VARCHAR(50) college
        DATE help
    }
    think ||--o{ important : fight
    think {
        DATE fight
        TEXT whom
        VARCHAR(50) program
    }
    important ||--o{ take : painting
    important {
        VARCHAR(50) painting
        DATE chair
    }
    take ||--o{ receive : very
    take {
        DATE very
        TEXT pattern
        VARCHAR(50) feeling
    }
    receive ||--o{ along : human
    receive {
        VARCHAR(50) human
        DATE possible
    }
    along ||--o{ everything : month
    along {
        DATE month
        TEXT serious
        VARCHAR(50) my
    }
    everything ||--o{ because : every
    everything {
        VARCHAR(50) every
        DATE modern
    }