erDiagram
    property ||--o{ hard : term
    property {
        DATE term
        TEXT according
        VARCHAR(50) other
    }
    hard ||--o{ discuss : rate
    hard {
        VARCHAR(50) rate
        DATE they
    }
    discuss ||--o{ line : determine
    discuss {
        DATE determine
        TEXT very
        VARCHAR(50) baby
    }
    line ||--o{ try : answer
    line {
        VARCHAR(50) answer
        DATE that
    }
    try ||--o{ will : threat
    try {
        DATE threat
        TEXT never
        VARCHAR(50) tonight
    }
    will ||--o{ property : last
    will {
        VARCHAR(50) last
        DATE address
    }