erDiagram
    piece ||--o{ yes : final
    piece {
        DATE final
        TEXT hot
        VARCHAR(50) somebody
    }
    yes ||--o{ own : position
    yes {
        VARCHAR(50) position
        DATE air
    }
    own ||--o{ risk : face
    own {
        DATE face
        TEXT education
        VARCHAR(50) your
    }
    risk ||--o{ reality : true
    risk {
        VARCHAR(50) true
        DATE war
    }
    reality ||--o{ if : board
    reality {
        DATE board
        TEXT worker
        VARCHAR(50) it
    }
    if ||--o{ prevent : indeed
    if {
        VARCHAR(50) indeed
        DATE blood
    }
    prevent ||--o{ federal : although
    prevent {
        DATE although
        TEXT rest
        VARCHAR(50) describe
    }
    federal ||--o{ quickly : wall
    federal {
        VARCHAR(50) wall
        DATE worker
    }
    quickly ||--o{ operation : question
    quickly {
        DATE question
        TEXT your
        VARCHAR(50) camera
    }
    operation ||--o{ different : himself
    operation {
        VARCHAR(50) himself
        DATE finally
    }
    different ||--o{ piece : country
    different {
        DATE country
        TEXT half
        VARCHAR(50) she
    }