erDiagram
    everything ||--o{ analysis : recent
    everything {
        DATE recent
        TEXT tonight
        VARCHAR(50) politics
    }
    analysis ||--o{ nation : bit
    analysis {
        VARCHAR(50) bit
        DATE mind
    }
    nation ||--o{ visit : rich
    nation {
        DATE rich
        TEXT letter
        VARCHAR(50) minute
    }
    visit ||--o{ new : since
    visit {
        VARCHAR(50) since
        DATE protect
    }
    new ||--o{ approach : allow
    new {
        DATE allow
        TEXT decide
        VARCHAR(50) third
    }
    approach ||--o{ recently : employee
    approach {
        VARCHAR(50) employee
        DATE school
    }
    recently ||--o{ everything : onto
    recently {
        DATE onto
        TEXT court
        VARCHAR(50) market
    }