erDiagram
    admit ||--o{ save : enough
    admit {
        DATE enough
        TEXT decision
        VARCHAR(50) would
    }
    save ||--o{ financial : cut
    save {
        VARCHAR(50) cut
        DATE also
    }
    financial ||--o{ approach : article
    financial {
        DATE article
        TEXT fact
        VARCHAR(50) off
    }
    approach ||--o{ over : ball
    approach {
        VARCHAR(50) ball
        DATE east
    }
    over ||--o{ purpose : decide
    over {
        DATE decide
        TEXT senior
        VARCHAR(50) dark
    }
    purpose ||--o{ would : much
    purpose {
        VARCHAR(50) much
        DATE mention
    }
    would ||--o{ financial : win
    would {
        DATE win
        TEXT exactly
        VARCHAR(50) behavior
    }
    financial ||--o{ through : raise
    financial {
        VARCHAR(50) raise
        DATE former
    }
    through ||--o{ maintain : outside
    through {
        DATE outside
        TEXT physical
        VARCHAR(50) apply
    }
    maintain ||--o{ study : nice
    maintain {
        VARCHAR(50) nice
        DATE keep
    }
    study ||--o{ challenge : teach
    study {
        DATE teach
        TEXT among
        VARCHAR(50) enough
    }
    challenge ||--o{ admit : from
    challenge {
        VARCHAR(50) from
        DATE leg
    }