erDiagram
    act ||--o{ bed : growth
    act {
        DATE growth
        TEXT guy
        VARCHAR(50) area
    }
    bed ||--o{ dark : girl
    bed {
        VARCHAR(50) girl
        DATE wall
    }
    dark ||--o{ lay : huge
    dark {
        DATE huge
        TEXT increase
        VARCHAR(50) civil
    }
    lay ||--o{ political : prepare
    lay {
        VARCHAR(50) prepare
        DATE measure
    }
    political ||--o{ name : matter
    political {
        DATE matter
        TEXT nearly
        VARCHAR(50) board
    }
    name ||--o{ factor : history
    name {
        VARCHAR(50) history
        DATE wait
    }
    factor ||--o{ act : so
    factor {
        DATE so
        TEXT fish
        VARCHAR(50) partner
    }