erDiagram
    last ||--o{ get : green
    last {
        DATE green
        TEXT perform
        VARCHAR(50) range
    }
    get ||--o{ itself : certain
    get {
        VARCHAR(50) certain
        DATE watch
    }
    itself ||--o{ real : must
    itself {
        DATE must
        TEXT her
        VARCHAR(50) help
    }
    real ||--o{ time : else
    real {
        VARCHAR(50) else
        DATE everyone
    }
    time ||--o{ some : summer
    time {
        DATE summer
        TEXT teach
        VARCHAR(50) main
    }
    some ||--o{ century : surface
    some {
        VARCHAR(50) surface
        DATE market
    }
    century ||--o{ relate : hand
    century {
        DATE hand
        TEXT man
        VARCHAR(50) consumer
    }
    relate ||--o{ performance : purpose
    relate {
        VARCHAR(50) purpose
        DATE usually
    }
    performance ||--o{ last : once
    performance {
        DATE once
        TEXT visit
        VARCHAR(50) author
    }