erDiagram
    tax ||--o{ remain : maintain
    tax {
        DATE maintain
        TEXT give
        VARCHAR(50) language
    }
    remain ||--o{ activity : yourself
    remain {
        VARCHAR(50) yourself
        DATE beautiful
    }
    activity ||--o{ exist : watch
    activity {
        DATE watch
        TEXT establish
        VARCHAR(50) take
    }
    exist ||--o{ play : low
    exist {
        VARCHAR(50) low
        DATE throw
    }
    play ||--o{ tax : almost
    play {
        DATE almost
        TEXT magazine
        VARCHAR(50) sign
    }