erDiagram
    end ||--o{ simple : nor
    end {
        DATE nor
        TEXT focus
        VARCHAR(50) voice
    }
    simple ||--o{ seat : increase
    simple {
        VARCHAR(50) increase
        DATE design
    }
    seat ||--o{ individual : able
    seat {
        DATE able
        TEXT threat
        VARCHAR(50) truth
    }
    individual ||--o{ hold : total
    individual {
        VARCHAR(50) total
        DATE down
    }
    hold ||--o{ work : operation
    hold {
        DATE operation
        TEXT inside
        VARCHAR(50) company
    }
    work ||--o{ yourself : more
    work {
        VARCHAR(50) more
        DATE effort
    }
    yourself ||--o{ black : trade
    yourself {
        DATE trade
        TEXT positive
        VARCHAR(50) student
    }
    black ||--o{ likely : all
    black {
        VARCHAR(50) all
        DATE nice
    }
    likely ||--o{ record : hotel
    likely {
        DATE hotel
        TEXT seek
        VARCHAR(50) beautiful
    }
    record ||--o{ end : information
    record {
        VARCHAR(50) information
        DATE partner
    }