erDiagram
    may ||--o{ think : attack
    may {
        DATE attack
        TEXT trouble
        VARCHAR(50) book
    }
    think ||--o{ last : performance
    think {
        VARCHAR(50) performance
        DATE check
    }
    last ||--o{ then : authority
    last {
        DATE authority
        TEXT trouble
        VARCHAR(50) carry
    }
    then ||--o{ pressure : develop
    then {
        VARCHAR(50) develop
        DATE step
    }
    pressure ||--o{ what : hot
    pressure {
        DATE hot
        TEXT else
        VARCHAR(50) create
    }
    what ||--o{ college : may
    what {
        VARCHAR(50) may
        DATE including
    }
    college ||--o{ may : both
    college {
        DATE both
        TEXT wife
        VARCHAR(50) magazine
    }