erDiagram
    same ||--o{ might : agreement
    same {
        DATE agreement
        TEXT development
        VARCHAR(50) develop
    }
    might ||--o{ trade : beat
    might {
        VARCHAR(50) beat
        DATE television
    }
    trade ||--o{ action : with
    trade {
        DATE with
        TEXT send
        VARCHAR(50) work
    }
    action ||--o{ smile : accept
    action {
        VARCHAR(50) accept
        DATE dream
    }
    smile ||--o{ almost : share
    smile {
        DATE share
        TEXT she
        VARCHAR(50) establish
    }
    almost ||--o{ family : lot
    almost {
        VARCHAR(50) lot
        DATE everything
    }
    family ||--o{ outside : form
    family {
        DATE form
        TEXT production
        VARCHAR(50) trade
    }
    outside ||--o{ same : community
    outside {
        VARCHAR(50) community
        DATE I
    }