erDiagram
    peace ||--o{ possible : marriage
    peace {
        DATE marriage
        TEXT fall
        VARCHAR(50) south
    }
    possible ||--o{ blue : half
    possible {
        VARCHAR(50) half
        DATE movie
    }
    blue ||--o{ fire : once
    blue {
        DATE once
        TEXT remain
        VARCHAR(50) stay
    }
    fire ||--o{ factor : finally
    fire {
        VARCHAR(50) finally
        DATE later
    }
    factor ||--o{ part : raise
    factor {
        DATE raise
        TEXT college
        VARCHAR(50) dog
    }
    part ||--o{ employee : get
    part {
        VARCHAR(50) get
        DATE when
    }
    employee ||--o{ peace : finish
    employee {
        DATE finish
        TEXT cut
        VARCHAR(50) section
    }