erDiagram
    condition ||--o{ wife : ever
    condition {
        DATE ever
        TEXT computer
        VARCHAR(50) artist
    }
    wife ||--o{ appear : term
    wife {
        VARCHAR(50) term
        DATE house
    }
    appear ||--o{ floor : risk
    appear {
        DATE risk
        TEXT middle
        VARCHAR(50) though
    }
    floor ||--o{ real : business
    floor {
        VARCHAR(50) business
        DATE live
    }
    real ||--o{ sea : Democrat
    real {
        DATE Democrat
        TEXT matter
        VARCHAR(50) also
    }
    sea ||--o{ condition : lead
    sea {
        VARCHAR(50) lead
        DATE account
    }