erDiagram
    itself ||--o{ thank : able
    itself {
        DATE able
        TEXT event
        VARCHAR(50) heavy
    }
    thank ||--o{ office : scientist
    thank {
        VARCHAR(50) scientist
        DATE modern
    }
    office ||--o{ loss : race
    office {
        DATE race
        TEXT southern
        VARCHAR(50) receive
    }
    loss ||--o{ about : character
    loss {
        VARCHAR(50) character
        DATE than
    }
    about ||--o{ nor : goal
    about {
        DATE goal
        TEXT top
        VARCHAR(50) his
    }
    nor ||--o{ election : radio
    nor {
        VARCHAR(50) radio
        DATE reflect
    }
    election ||--o{ success : leave
    election {
        DATE leave
        TEXT grow
        VARCHAR(50) natural
    }
    success ||--o{ policy : institution
    success {
        VARCHAR(50) institution
        DATE notice
    }
    policy ||--o{ challenge : life
    policy {
        DATE life
        TEXT leg
        VARCHAR(50) without
    }
    challenge ||--o{ itself : before
    challenge {
        VARCHAR(50) before
        DATE one
    }