erDiagram
    environmental ||--o{ lose : authority
    environmental {
        DATE authority
        TEXT around
        VARCHAR(50) suddenly
    }
    lose ||--o{ science : professional
    lose {
        VARCHAR(50) professional
        DATE trouble
    }
    science ||--o{ really : simply
    science {
        DATE simply
        TEXT range
        VARCHAR(50) computer
    }
    really ||--o{ determine : enough
    really {
        VARCHAR(50) enough
        DATE capital
    }
    determine ||--o{ catch : talk
    determine {
        DATE talk
        TEXT while
        VARCHAR(50) source
    }
    catch ||--o{ character : great
    catch {
        VARCHAR(50) great
        DATE son
    }
    character ||--o{ stuff : us
    character {
        DATE us
        TEXT full
        VARCHAR(50) young
    }
    stuff ||--o{ test : arrive
    stuff {
        VARCHAR(50) arrive
        DATE item
    }
    test ||--o{ environmental : owner
    test {
        DATE owner
        TEXT word
        VARCHAR(50) sell
    }