erDiagram
    source ||--o{ ball : big
    source {
        DATE big
        TEXT throw
        VARCHAR(50) usually
    }
    ball ||--o{ sell : however
    ball {
        VARCHAR(50) however
        DATE form
    }
    sell ||--o{ drop : dinner
    sell {
        DATE dinner
        TEXT subject
        VARCHAR(50) fill
    }
    drop ||--o{ while : girl
    drop {
        VARCHAR(50) girl
        DATE space
    }
    while ||--o{ line : mention
    while {
        DATE mention
        TEXT front
        VARCHAR(50) deal
    }
    line ||--o{ forward : lot
    line {
        VARCHAR(50) lot
        DATE center
    }
    forward ||--o{ realize : bit
    forward {
        DATE bit
        TEXT need
        VARCHAR(50) physical
    }
    realize ||--o{ section : two
    realize {
        VARCHAR(50) two
        DATE send
    }
    section ||--o{ source : water
    section {
        DATE water
        TEXT tend
        VARCHAR(50) require
    }