erDiagram
    increase ||--o{ month : compare
    increase {
        DATE compare
        TEXT carry
        VARCHAR(50) draw
    }
    month ||--o{ while : role
    month {
        VARCHAR(50) role
        DATE education
    }
    while ||--o{ really : senior
    while {
        DATE senior
        TEXT also
        VARCHAR(50) much
    }
    really ||--o{ very : there
    really {
        VARCHAR(50) there
        DATE difference
    }
    very ||--o{ suggest : coach
    very {
        DATE coach
        TEXT call
        VARCHAR(50) director
    }
    suggest ||--o{ drop : change
    suggest {
        VARCHAR(50) change
        DATE audience
    }
    drop ||--o{ increase : so
    drop {
        DATE so
        TEXT indicate
        VARCHAR(50) government
    }