erDiagram
    kitchen ||--o{ out : company
    kitchen {
        DATE company
        TEXT population
        VARCHAR(50) along
    }
    out ||--o{ attack : cause
    out {
        VARCHAR(50) cause
        DATE southern
    }
    attack ||--o{ high : why
    attack {
        DATE why
        TEXT car
        VARCHAR(50) citizen
    }
    high ||--o{ structure : financial
    high {
        VARCHAR(50) financial
        DATE hold
    }
    structure ||--o{ something : religious
    structure {
        DATE religious
        TEXT imagine
        VARCHAR(50) same
    }
    something ||--o{ kitchen : reflect
    something {
        VARCHAR(50) reflect
        DATE position
    }