erDiagram
    nearly ||--o{ entire : range
    nearly {
        DATE range
        TEXT nice
        VARCHAR(50) partner
    }
    entire ||--o{ always : hand
    entire {
        VARCHAR(50) hand
        DATE southern
    }
    always ||--o{ bill : person
    always {
        DATE person
        TEXT degree
        VARCHAR(50) order
    }
    bill ||--o{ experience : attention
    bill {
        VARCHAR(50) attention
        DATE me
    }
    experience ||--o{ issue : event
    experience {
        DATE event
        TEXT second
        VARCHAR(50) finish
    }
    issue ||--o{ also : space
    issue {
        VARCHAR(50) space
        DATE local
    }
    also ||--o{ nearly : treatment
    also {
        DATE treatment
        TEXT owner
        VARCHAR(50) him
    }