erDiagram
    decision ||--o{ page : hour
    decision {
        DATE hour
        TEXT shoulder
        VARCHAR(50) run
    }
    page ||--o{ community : admit
    page {
        VARCHAR(50) admit
        DATE mission
    }
    community ||--o{ hand : position
    community {
        DATE position
        TEXT poor
        VARCHAR(50) research
    }
    hand ||--o{ Mr : model
    hand {
        VARCHAR(50) model
        DATE outside
    }
    Mr ||--o{ decision : rule
    Mr {
        DATE rule
        TEXT feeling
        VARCHAR(50) inside
    }