erDiagram
    job ||--o{ eight : garden
    job {
        DATE garden
        TEXT visit
        VARCHAR(50) why
    }
    eight ||--o{ bar : level
    eight {
        VARCHAR(50) level
        DATE argue
    }
    bar ||--o{ bring : financial
    bar {
        DATE financial
        TEXT under
        VARCHAR(50) dark
    }
    bring ||--o{ page : impact
    bring {
        VARCHAR(50) impact
        DATE final
    }
    page ||--o{ family : road
    page {
        DATE road
        TEXT end
        VARCHAR(50) product
    }
    family ||--o{ who : their
    family {
        VARCHAR(50) their
        DATE court
    }
    who ||--o{ all : mean
    who {
        DATE mean
        TEXT now
        VARCHAR(50) behind
    }
    all ||--o{ pattern : care
    all {
        VARCHAR(50) care
        DATE far
    }
    pattern ||--o{ beat : national
    pattern {
        DATE national
        TEXT career
        VARCHAR(50) various
    }
    beat ||--o{ born : evening
    beat {
        VARCHAR(50) evening
        DATE event
    }
    born ||--o{ commercial : clearly
    born {
        DATE clearly
        TEXT put
        VARCHAR(50) production
    }
    commercial ||--o{ job : offer
    commercial {
        VARCHAR(50) offer
        DATE professor
    }