erDiagram
    sign ||--o{ factor : look
    sign {
        DATE look
        TEXT sit
        VARCHAR(50) senior
    }
    factor ||--o{ son : seem
    factor {
        VARCHAR(50) seem
        DATE condition
    }
    son ||--o{ create : let
    son {
        DATE let
        TEXT some
        VARCHAR(50) alone
    }
    create ||--o{ throughout : simply
    create {
        VARCHAR(50) simply
        DATE from
    }
    throughout ||--o{ relate : ability
    throughout {
        DATE ability
        TEXT identify
        VARCHAR(50) town
    }
    relate ||--o{ sign : no
    relate {
        VARCHAR(50) no
        DATE important
    }