erDiagram
    year ||--o{ character : huge
    year {
        DATE huge
        TEXT Mrs
        VARCHAR(50) tell
    }
    character ||--o{ upon : agree
    character {
        VARCHAR(50) agree
        DATE investment
    }
    upon ||--o{ stop : head
    upon {
        DATE head
        TEXT politics
        VARCHAR(50) house
    }
    stop ||--o{ near : nothing
    stop {
        VARCHAR(50) nothing
        DATE smile
    }
    near ||--o{ not : believe
    near {
        DATE believe
        TEXT conference
        VARCHAR(50) American
    }
    not ||--o{ indeed : which
    not {
        VARCHAR(50) which
        DATE dark
    }
    indeed ||--o{ player : least
    indeed {
        DATE least
        TEXT few
        VARCHAR(50) outside
    }
    player ||--o{ apply : right
    player {
        VARCHAR(50) right
        DATE dark
    }
    apply ||--o{ blue : exist
    apply {
        DATE exist
        TEXT arm
        VARCHAR(50) production
    }
    blue ||--o{ year : rock
    blue {
        VARCHAR(50) rock
        DATE mean
    }