erDiagram
    foot ||--o{ hour : yeah
    foot {
        DATE yeah
        TEXT education
        VARCHAR(50) hundred
    }
    hour ||--o{ author : baby
    hour {
        VARCHAR(50) baby
        DATE law
    }
    author ||--o{ which : leg
    author {
        DATE leg
        TEXT fall
        VARCHAR(50) stage
    }
    which ||--o{ such : build
    which {
        VARCHAR(50) build
        DATE wear
    }
    such ||--o{ each : customer
    such {
        DATE customer
        TEXT report
        VARCHAR(50) total
    }
    each ||--o{ tonight : with
    each {
        VARCHAR(50) with
        DATE short
    }
    tonight ||--o{ purpose : stand
    tonight {
        DATE stand
        TEXT address
        VARCHAR(50) ago
    }
    purpose ||--o{ training : bit
    purpose {
        VARCHAR(50) bit
        DATE type
    }
    training ||--o{ store : candidate
    training {
        DATE candidate
        TEXT good
        VARCHAR(50) exactly
    }
    store ||--o{ for : between
    store {
        VARCHAR(50) between
        DATE address
    }
    for ||--o{ foot : positive
    for {
        DATE positive
        TEXT Mr
        VARCHAR(50) place
    }