erDiagram
    model ||--o{ spend : teacher
    model {
        DATE teacher
        TEXT occur
        VARCHAR(50) discover
    }
    spend ||--o{ be : both
    spend {
        VARCHAR(50) both
        DATE play
    }
    be ||--o{ floor : kid
    be {
        DATE kid
        TEXT movement
        VARCHAR(50) former
    }
    floor ||--o{ economy : economy
    floor {
        VARCHAR(50) economy
        DATE task
    }
    economy ||--o{ law : easy
    economy {
        DATE easy
        TEXT finally
        VARCHAR(50) year
    }
    law ||--o{ green : movie
    law {
        VARCHAR(50) movie
        DATE image
    }
    green ||--o{ third : speech
    green {
        DATE speech
        TEXT good
        VARCHAR(50) interesting
    }
    third ||--o{ condition : stay
    third {
        VARCHAR(50) stay
        DATE soon
    }
    condition ||--o{ sport : expert
    condition {
        DATE expert
        TEXT decide
        VARCHAR(50) well
    }
    sport ||--o{ everybody : film
    sport {
        VARCHAR(50) film
        DATE population
    }
    everybody ||--o{ model : truth
    everybody {
        DATE truth
        TEXT bill
        VARCHAR(50) others
    }