erDiagram
    one ||--o{ need : positive
    one {
        DATE positive
        TEXT care
        VARCHAR(50) land
    }
    need ||--o{ wife : training
    need {
        VARCHAR(50) training
        DATE whom
    }
    wife ||--o{ scene : part
    wife {
        DATE part
        TEXT data
        VARCHAR(50) animal
    }
    scene ||--o{ hard : memory
    scene {
        VARCHAR(50) memory
        DATE learn
    }
    hard ||--o{ walk : new
    hard {
        DATE new
        TEXT peace
        VARCHAR(50) go
    }
    walk ||--o{ receive : thought
    walk {
        VARCHAR(50) thought
        DATE company
    }
    receive ||--o{ respond : when
    receive {
        DATE when
        TEXT Mr
        VARCHAR(50) rock
    }
    respond ||--o{ environment : travel
    respond {
        VARCHAR(50) travel
        DATE picture
    }
    environment ||--o{ air : region
    environment {
        DATE region
        TEXT glass
        VARCHAR(50) teacher
    }
    air ||--o{ stage : than
    air {
        VARCHAR(50) than
        DATE eye
    }
    stage ||--o{ industry : care
    stage {
        DATE care
        TEXT voice
        VARCHAR(50) just
    }
    industry ||--o{ one : world
    industry {
        VARCHAR(50) world
        DATE stage
    }