erDiagram
    record ||--o{ debate : well
    record {
        DATE well
        TEXT trip
        VARCHAR(50) garden
    }
    debate ||--o{ herself : last
    debate {
        VARCHAR(50) last
        DATE including
    }
    herself ||--o{ take : action
    herself {
        DATE action
        TEXT house
        VARCHAR(50) kind
    }
    take ||--o{ since : street
    take {
        VARCHAR(50) street
        DATE animal
    }
    since ||--o{ fire : thought
    since {
        DATE thought
        TEXT list
        VARCHAR(50) country
    }
    fire ||--o{ player : huge
    fire {
        VARCHAR(50) huge
        DATE career
    }
    player ||--o{ forget : week
    player {
        DATE week
        TEXT whole
        VARCHAR(50) conference
    }
    forget ||--o{ especially : him
    forget {
        VARCHAR(50) him
        DATE owner
    }
    especially ||--o{ during : late
    especially {
        DATE late
        TEXT affect
        VARCHAR(50) generation
    }
    during ||--o{ record : make
    during {
        VARCHAR(50) make
        DATE goal
    }