erDiagram
    fall ||--o{ food : truth
    fall {
        DATE truth
        TEXT sport
        VARCHAR(50) part
    }
    food ||--o{ laugh : per
    food {
        VARCHAR(50) per
        DATE this
    }
    laugh ||--o{ strong : not
    laugh {
        DATE not
        TEXT time
        VARCHAR(50) father
    }
    strong ||--o{ according : why
    strong {
        VARCHAR(50) why
        DATE rate
    }
    according ||--o{ picture : skill
    according {
        DATE skill
        TEXT range
        VARCHAR(50) over
    }
    picture ||--o{ executive : voice
    picture {
        VARCHAR(50) voice
        DATE election
    }
    executive ||--o{ bar : guy
    executive {
        DATE guy
        TEXT experience
        VARCHAR(50) arm
    }
    bar ||--o{ finish : collection
    bar {
        VARCHAR(50) collection
        DATE soon
    }
    finish ||--o{ respond : start
    finish {
        DATE start
        TEXT our
        VARCHAR(50) enough
    }
    respond ||--o{ difference : recent
    respond {
        VARCHAR(50) recent
        DATE those
    }
    difference ||--o{ challenge : service
    difference {
        DATE service
        TEXT reflect
        VARCHAR(50) design
    }
    challenge ||--o{ fall : community
    challenge {
        VARCHAR(50) community
        DATE market
    }