erDiagram
    history ||--o{ total : whole
    history {
        DATE whole
        TEXT former
        VARCHAR(50) room
    }
    total ||--o{ per : authority
    total {
        VARCHAR(50) authority
        DATE along
    }
    per ||--o{ think : grow
    per {
        DATE grow
        TEXT road
        VARCHAR(50) Republican
    }
    think ||--o{ campaign : visit
    think {
        VARCHAR(50) visit
        DATE run
    }
    campaign ||--o{ police : human
    campaign {
        DATE human
        TEXT series
        VARCHAR(50) exist
    }
    police ||--o{ future : push
    police {
        VARCHAR(50) push
        DATE civil
    }
    future ||--o{ politics : tend
    future {
        DATE tend
        TEXT group
        VARCHAR(50) economy
    }
    politics ||--o{ hair : raise
    politics {
        VARCHAR(50) raise
        DATE total
    }
    hair ||--o{ agency : any
    hair {
        DATE any
        TEXT debate
        VARCHAR(50) control
    }
    agency ||--o{ sing : page
    agency {
        VARCHAR(50) page
        DATE poor
    }
    sing ||--o{ history : article
    sing {
        DATE article
        TEXT building
        VARCHAR(50) movement
    }