erDiagram
    carry ||--o{ training : direction
    carry {
        DATE direction
        TEXT left
        VARCHAR(50) fish
    }
    training ||--o{ dinner : along
    training {
        VARCHAR(50) along
        DATE lose
    }
    dinner ||--o{ both : hard
    dinner {
        DATE hard
        TEXT along
        VARCHAR(50) realize
    }
    both ||--o{ hospital : rise
    both {
        VARCHAR(50) rise
        DATE already
    }
    hospital ||--o{ he : matter
    hospital {
        DATE matter
        TEXT fire
        VARCHAR(50) full
    }
    he ||--o{ beat : drop
    he {
        VARCHAR(50) drop
        DATE experience
    }
    beat ||--o{ safe : run
    beat {
        DATE run
        TEXT month
        VARCHAR(50) or
    }
    safe ||--o{ rock : measure
    safe {
        VARCHAR(50) measure
        DATE into
    }
    rock ||--o{ support : return
    rock {
        DATE return
        TEXT team
        VARCHAR(50) office
    }
    support ||--o{ pretty : important
    support {
        VARCHAR(50) important
        DATE everybody
    }
    pretty ||--o{ arrive : prepare
    pretty {
        DATE prepare
        TEXT town
        VARCHAR(50) activity
    }
    arrive ||--o{ carry : cause
    arrive {
        VARCHAR(50) cause
        DATE off
    }