erDiagram
    evidence ||--o{ when : hot
    evidence {
        DATE hot
        TEXT million
        VARCHAR(50) week
    }
    when ||--o{ science : plan
    when {
        VARCHAR(50) plan
        DATE together
    }
    science ||--o{ tree : they
    science {
        DATE they
        TEXT kitchen
        VARCHAR(50) lead
    }
    tree ||--o{ parent : child
    tree {
        VARCHAR(50) child
        DATE middle
    }
    parent ||--o{ red : various
    parent {
        DATE various
        TEXT book
        VARCHAR(50) fear
    }
    red ||--o{ concern : itself
    red {
        VARCHAR(50) itself
        DATE girl
    }
    concern ||--o{ tree : agent
    concern {
        DATE agent
        TEXT star
        VARCHAR(50) better
    }
    tree ||--o{ every : call
    tree {
        VARCHAR(50) call
        DATE local
    }
    every ||--o{ evidence : economy
    every {
        DATE economy
        TEXT expect
        VARCHAR(50) political
    }