erDiagram
    guy ||--o{ always : box
    guy {
        DATE box
        TEXT policy
        VARCHAR(50) like
    }
    always ||--o{ mean : discover
    always {
        VARCHAR(50) discover
        DATE process
    }
    mean ||--o{ both : nor
    mean {
        DATE nor
        TEXT debate
        VARCHAR(50) note
    }
    both ||--o{ fear : tree
    both {
        VARCHAR(50) tree
        DATE traditional
    }
    fear ||--o{ part : six
    fear {
        DATE six
        TEXT suffer
        VARCHAR(50) despite
    }
    part ||--o{ pick : operation
    part {
        VARCHAR(50) operation
        DATE soon
    }
    pick ||--o{ network : chance
    pick {
        DATE chance
        TEXT recognize
        VARCHAR(50) parent
    }
    network ||--o{ American : training
    network {
        VARCHAR(50) training
        DATE near
    }
    American ||--o{ option : hour
    American {
        DATE hour
        TEXT else
        VARCHAR(50) east
    }
    option ||--o{ plant : ground
    option {
        VARCHAR(50) ground
        DATE size
    }
    plant ||--o{ guy : official
    plant {
        DATE official
        TEXT my
        VARCHAR(50) all
    }