erDiagram
    card ||--o{ want : wrong
    card {
        DATE wrong
        TEXT color
        VARCHAR(50) total
    }
    want ||--o{ always : group
    want {
        VARCHAR(50) group
        DATE finish
    }
    always ||--o{ with : market
    always {
        DATE market
        TEXT imagine
        VARCHAR(50) something
    }
    with ||--o{ computer : however
    with {
        VARCHAR(50) however
        DATE picture
    }
    computer ||--o{ avoid : letter
    computer {
        DATE letter
        TEXT who
        VARCHAR(50) them
    }
    avoid ||--o{ mind : market
    avoid {
        VARCHAR(50) market
        DATE second
    }
    mind ||--o{ degree : enough
    mind {
        DATE enough
        TEXT always
        VARCHAR(50) deal
    }
    degree ||--o{ skin : receive
    degree {
        VARCHAR(50) receive
        DATE try
    }
    skin ||--o{ different : able
    skin {
        DATE able
        TEXT later
        VARCHAR(50) often
    }
    different ||--o{ become : manager
    different {
        VARCHAR(50) manager
        DATE serious
    }
    become ||--o{ card : business
    become {
        DATE business
        TEXT market
        VARCHAR(50) building
    }