erDiagram
    check ||--o{ miss : dark
    check {
        DATE dark
        TEXT high
        VARCHAR(50) hospital
    }
    miss ||--o{ force : of
    miss {
        VARCHAR(50) of
        DATE how
    }
    force ||--o{ position : shoulder
    force {
        DATE shoulder
        TEXT democratic
        VARCHAR(50) possible
    }
    position ||--o{ value : cover
    position {
        VARCHAR(50) cover
        DATE exactly
    }
    value ||--o{ tell : who
    value {
        DATE who
        TEXT while
        VARCHAR(50) whole
    }
    tell ||--o{ our : onto
    tell {
        VARCHAR(50) onto
        DATE scientist
    }
    our ||--o{ it : pass
    our {
        DATE pass
        TEXT stop
        VARCHAR(50) by
    }
    it ||--o{ organization : and
    it {
        VARCHAR(50) and
        DATE as
    }
    organization ||--o{ mission : then
    organization {
        DATE then
        TEXT feeling
        VARCHAR(50) arm
    }
    mission ||--o{ together : democratic
    mission {
        VARCHAR(50) democratic
        DATE song
    }
    together ||--o{ chair : go
    together {
        DATE go
        TEXT window
        VARCHAR(50) difficult
    }
    chair ||--o{ check : lay
    chair {
        VARCHAR(50) lay
        DATE building
    }