erDiagram
    poor ||--o{ guy : successful
    poor {
        DATE successful
        TEXT machine
        VARCHAR(50) like
    }
    guy ||--o{ book : you
    guy {
        VARCHAR(50) you
        DATE should
    }
    book ||--o{ necessary : show
    book {
        DATE show
        TEXT bit
        VARCHAR(50) indeed
    }
    necessary ||--o{ student : along
    necessary {
        VARCHAR(50) along
        DATE worry
    }
    student ||--o{ race : cover
    student {
        DATE cover
        TEXT drop
        VARCHAR(50) nearly
    }
    race ||--o{ audience : administration
    race {
        VARCHAR(50) administration
        DATE future
    }
    audience ||--o{ natural : hundred
    audience {
        DATE hundred
        TEXT support
        VARCHAR(50) painting
    }
    natural ||--o{ poor : season
    natural {
        VARCHAR(50) season
        DATE study
    }