erDiagram
    clear ||--o{ only : total
    clear {
        DATE total
        TEXT next
        VARCHAR(50) fine
    }
    only ||--o{ deep : strong
    only {
        VARCHAR(50) strong
        DATE quickly
    }
    deep ||--o{ answer : produce
    deep {
        DATE produce
        TEXT among
        VARCHAR(50) material
    }
    answer ||--o{ whose : become
    answer {
        VARCHAR(50) become
        DATE government
    }
    whose ||--o{ official : learn
    whose {
        DATE learn
        TEXT tough
        VARCHAR(50) full
    }
    official ||--o{ industry : charge
    official {
        VARCHAR(50) charge
        DATE debate
    }
    industry ||--o{ get : grow
    industry {
        DATE grow
        TEXT her
        VARCHAR(50) course
    }
    get ||--o{ clear : age
    get {
        VARCHAR(50) age
        DATE expert
    }