erDiagram
    air ||--o{ among : similar
    air {
        DATE similar
        TEXT summer
        VARCHAR(50) all
    }
    among ||--o{ support : week
    among {
        VARCHAR(50) week
        DATE it
    }
    support ||--o{ data : together
    support {
        DATE together
        TEXT free
        VARCHAR(50) film
    }
    data ||--o{ officer : question
    data {
        VARCHAR(50) question
        DATE determine
    }
    officer ||--o{ peace : step
    officer {
        DATE step
        TEXT statement
        VARCHAR(50) expect
    }
    peace ||--o{ wind : against
    peace {
        VARCHAR(50) against
        DATE recent
    }
    wind ||--o{ air : small
    wind {
        DATE small
        TEXT lose
        VARCHAR(50) still
    }