erDiagram
    pattern ||--o{ affect : public
    pattern {
        DATE public
        TEXT during
        VARCHAR(50) any
    }
    affect ||--o{ guess : audience
    affect {
        VARCHAR(50) audience
        DATE almost
    }
    guess ||--o{ rich : own
    guess {
        DATE own
        TEXT many
        VARCHAR(50) world
    }
    rich ||--o{ much : ten
    rich {
        VARCHAR(50) ten
        DATE red
    }
    much ||--o{ former : perform
    much {
        DATE perform
        TEXT reveal
        VARCHAR(50) behavior
    }
    former ||--o{ produce : loss
    former {
        VARCHAR(50) loss
        DATE reduce
    }
    produce ||--o{ everybody : evening
    produce {
        DATE evening
        TEXT through
        VARCHAR(50) TV
    }
    everybody ||--o{ level : make
    everybody {
        VARCHAR(50) make
        DATE either
    }
    level ||--o{ pattern : reflect
    level {
        DATE reflect
        TEXT situation
        VARCHAR(50) respond
    }