erDiagram
    news ||--o{ vote : dream
    news {
        DATE dream
        TEXT still
        VARCHAR(50) body
    }
    vote ||--o{ others : enough
    vote {
        VARCHAR(50) enough
        DATE city
    }
    others ||--o{ none : production
    others {
        DATE production
        TEXT why
        VARCHAR(50) sea
    }
    none ||--o{ upon : tree
    none {
        VARCHAR(50) tree
        DATE production
    }
    upon ||--o{ blood : prepare
    upon {
        DATE prepare
        TEXT price
        VARCHAR(50) partner
    }
    blood ||--o{ name : enough
    blood {
        VARCHAR(50) enough
        DATE break
    }
    name ||--o{ send : attorney
    name {
        DATE attorney
        TEXT Mr
        VARCHAR(50) difficult
    }
    send ||--o{ miss : probably
    send {
        VARCHAR(50) probably
        DATE her
    }
    miss ||--o{ news : quality
    miss {
        DATE quality
        TEXT several
        VARCHAR(50) television
    }