erDiagram
    pay ||--o{ while : line
    pay {
        DATE line
        TEXT there
        VARCHAR(50) century
    }
    while ||--o{ light : cold
    while {
        VARCHAR(50) cold
        DATE recent
    }
    light ||--o{ discussion : ten
    light {
        DATE ten
        TEXT sure
        VARCHAR(50) course
    }
    discussion ||--o{ direction : red
    discussion {
        VARCHAR(50) red
        DATE executive
    }
    direction ||--o{ pay : size
    direction {
        DATE size
        TEXT character
        VARCHAR(50) offer
    }