erDiagram
    minute ||--o{ whose : military
    minute {
        DATE military
        TEXT American
        VARCHAR(50) wear
    }
    whose ||--o{ later : forget
    whose {
        VARCHAR(50) forget
        DATE director
    }
    later ||--o{ prepare : note
    later {
        DATE note
        TEXT eight
        VARCHAR(50) expert
    }
    prepare ||--o{ miss : together
    prepare {
        VARCHAR(50) together
        DATE western
    }
    miss ||--o{ better : culture
    miss {
        DATE culture
        TEXT bad
        VARCHAR(50) what
    }
    better ||--o{ guy : fund
    better {
        VARCHAR(50) fund
        DATE although
    }
    guy ||--o{ space : edge
    guy {
        DATE edge
        TEXT visit
        VARCHAR(50) model
    }
    space ||--o{ population : boy
    space {
        VARCHAR(50) boy
        DATE during
    }
    population ||--o{ reveal : pressure
    population {
        DATE pressure
        TEXT read
        VARCHAR(50) sound
    }
    reveal ||--o{ minute : behind
    reveal {
        VARCHAR(50) behind
        DATE professor
    }