erDiagram
    almost ||--o{ effect : leader
    almost {
        DATE leader
        TEXT cover
        VARCHAR(50) economy
    }
    effect ||--o{ treat : share
    effect {
        VARCHAR(50) share
        DATE sense
    }
    treat ||--o{ artist : environment
    treat {
        DATE environment
        TEXT back
        VARCHAR(50) save
    }
    artist ||--o{ huge : together
    artist {
        VARCHAR(50) together
        DATE a
    }
    huge ||--o{ chair : her
    huge {
        DATE her
        TEXT degree
        VARCHAR(50) girl
    }
    chair ||--o{ big : thought
    chair {
        VARCHAR(50) thought
        DATE sometimes
    }
    big ||--o{ form : particularly
    big {
        DATE particularly
        TEXT in
        VARCHAR(50) affect
    }
    form ||--o{ country : magazine
    form {
        VARCHAR(50) magazine
        DATE soldier
    }
    country ||--o{ almost : training
    country {
        DATE training
        TEXT total
        VARCHAR(50) drug
    }