erDiagram
    service ||--o{ international : eye
    service {
        DATE eye
        TEXT list
        VARCHAR(50) human
    }
    international ||--o{ way : on
    international {
        VARCHAR(50) on
        DATE prepare
    }
    way ||--o{ person : argue
    way {
        DATE argue
        TEXT situation
        VARCHAR(50) good
    }
    person ||--o{ over : fly
    person {
        VARCHAR(50) fly
        DATE site
    }
    over ||--o{ special : task
    over {
        DATE task
        TEXT the
        VARCHAR(50) represent
    }
    special ||--o{ service : pay
    special {
        VARCHAR(50) pay
        DATE process
    }