erDiagram
    raise ||--o{ for : or
    raise {
        DATE or
        TEXT church
        VARCHAR(50) north
    }
    for ||--o{ serve : lawyer
    for {
        VARCHAR(50) lawyer
        DATE away
    }
    serve ||--o{ push : social
    serve {
        DATE social
        TEXT garden
        VARCHAR(50) go
    }
    push ||--o{ where : perhaps
    push {
        VARCHAR(50) perhaps
        DATE front
    }
    where ||--o{ hour : age
    where {
        DATE age
        TEXT operation
        VARCHAR(50) interesting
    }
    hour ||--o{ people : right
    hour {
        VARCHAR(50) right
        DATE radio
    }
    people ||--o{ perhaps : hear
    people {
        DATE hear
        TEXT guy
        VARCHAR(50) light
    }
    perhaps ||--o{ guy : important
    perhaps {
        VARCHAR(50) important
        DATE dog
    }
    guy ||--o{ east : prevent
    guy {
        DATE prevent
        TEXT purpose
        VARCHAR(50) trial
    }
    east ||--o{ raise : girl
    east {
        VARCHAR(50) girl
        DATE sell
    }