erDiagram
    second ||--o{ interest : least
    second {
        DATE least
        TEXT would
        VARCHAR(50) night
    }
    interest ||--o{ then : science
    interest {
        VARCHAR(50) science
        DATE room
    }
    then ||--o{ forward : I
    then {
        DATE I
        TEXT smile
        VARCHAR(50) wall
    }
    forward ||--o{ arrive : sometimes
    forward {
        VARCHAR(50) sometimes
        DATE into
    }
    arrive ||--o{ everyone : meeting
    arrive {
        DATE meeting
        TEXT over
        VARCHAR(50) at
    }
    everyone ||--o{ second : save
    everyone {
        VARCHAR(50) save
        DATE create
    }