erDiagram
    difficult ||--o{ lose : election
    difficult {
        DATE election
        TEXT size
        VARCHAR(50) election
    }
    lose ||--o{ fact : as
    lose {
        VARCHAR(50) as
        DATE bit
    }
    fact ||--o{ senior : teacher
    fact {
        DATE teacher
        TEXT case
        VARCHAR(50) require
    }
    senior ||--o{ street : moment
    senior {
        VARCHAR(50) moment
        DATE type
    }
    street ||--o{ board : perhaps
    street {
        DATE perhaps
        TEXT yard
        VARCHAR(50) beyond
    }
    board ||--o{ difficult : culture
    board {
        VARCHAR(50) culture
        DATE level
    }