erDiagram
    miss ||--o{ boy : yard
    miss {
        DATE yard
        TEXT card
        VARCHAR(50) mention
    }
    boy ||--o{ bill : age
    boy {
        VARCHAR(50) age
        DATE need
    }
    bill ||--o{ writer : member
    bill {
        DATE member
        TEXT campaign
        VARCHAR(50) event
    }
    writer ||--o{ actually : simple
    writer {
        VARCHAR(50) simple
        DATE move
    }
    actually ||--o{ large : agency
    actually {
        DATE agency
        TEXT often
        VARCHAR(50) financial
    }
    large ||--o{ five : mean
    large {
        VARCHAR(50) mean
        DATE carry
    }
    five ||--o{ idea : school
    five {
        DATE school
        TEXT often
        VARCHAR(50) major
    }
    idea ||--o{ throughout : anyone
    idea {
        VARCHAR(50) anyone
        DATE daughter
    }
    throughout ||--o{ miss : citizen
    throughout {
        DATE citizen
        TEXT reduce
        VARCHAR(50) yet
    }