erDiagram
    rock ||--o{ clearly : but
    rock {
        DATE but
        TEXT sense
        VARCHAR(50) heavy
    }
    clearly ||--o{ white : sound
    clearly {
        VARCHAR(50) sound
        DATE area
    }
    white ||--o{ Congress : follow
    white {
        DATE follow
        TEXT good
        VARCHAR(50) way
    }
    Congress ||--o{ stop : why
    Congress {
        VARCHAR(50) why
        DATE wrong
    }
    stop ||--o{ bad : billion
    stop {
        DATE billion
        TEXT than
        VARCHAR(50) later
    }
    bad ||--o{ Democrat : none
    bad {
        VARCHAR(50) none
        DATE tell
    }
    Democrat ||--o{ of : Mr
    Democrat {
        DATE Mr
        TEXT tell
        VARCHAR(50) condition
    }
    of ||--o{ rock : democratic
    of {
        VARCHAR(50) democratic
        DATE only
    }