erDiagram
    despite ||--o{ tend : less
    despite {
        DATE less
        TEXT special
        VARCHAR(50) debate
    }
    tend ||--o{ ok : unit
    tend {
        VARCHAR(50) unit
        DATE bed
    }
    ok ||--o{ easy : class
    ok {
        DATE class
        TEXT participant
        VARCHAR(50) bed
    }
    easy ||--o{ particularly : check
    easy {
        VARCHAR(50) check
        DATE audience
    }
    particularly ||--o{ building : participant
    particularly {
        DATE participant
        TEXT among
        VARCHAR(50) relate
    }
    building ||--o{ entire : available
    building {
        VARCHAR(50) available
        DATE positive
    }
    entire ||--o{ call : team
    entire {
        DATE team
        TEXT put
        VARCHAR(50) manage
    }
    call ||--o{ despite : person
    call {
        VARCHAR(50) person
        DATE same
    }