erDiagram
    either ||--o{ sure : want
    either {
        DATE want
        TEXT stuff
        VARCHAR(50) green
    }
    sure ||--o{ base : do
    sure {
        VARCHAR(50) do
        DATE wide
    }
    base ||--o{ road : white
    base {
        DATE white
        TEXT music
        VARCHAR(50) history
    }
    road ||--o{ wall : less
    road {
        VARCHAR(50) less
        DATE simple
    }
    wall ||--o{ data : full
    wall {
        DATE full
        TEXT smile
        VARCHAR(50) now
    }
    data ||--o{ financial : these
    data {
        VARCHAR(50) these
        DATE kind
    }
    financial ||--o{ can : but
    financial {
        DATE but
        TEXT figure
        VARCHAR(50) story
    }
    can ||--o{ discussion : candidate
    can {
        VARCHAR(50) candidate
        DATE sport
    }
    discussion ||--o{ right : model
    discussion {
        DATE model
        TEXT under
        VARCHAR(50) approach
    }
    right ||--o{ evening : participant
    right {
        VARCHAR(50) participant
        DATE cup
    }
    evening ||--o{ water : speech
    evening {
        DATE speech
        TEXT star
        VARCHAR(50) onto
    }
    water ||--o{ either : put
    water {
        VARCHAR(50) put
        DATE raise
    }