erDiagram
    site ||--o{ relationship : image
    site {
        DATE image
        TEXT others
        VARCHAR(50) any
    }
    relationship ||--o{ suffer : positive
    relationship {
        VARCHAR(50) positive
        DATE good
    }
    suffer ||--o{ large : next
    suffer {
        DATE next
        TEXT color
        VARCHAR(50) society
    }
    large ||--o{ suddenly : able
    large {
        VARCHAR(50) able
        DATE industry
    }
    suddenly ||--o{ site : not
    suddenly {
        DATE not
        TEXT song
        VARCHAR(50) wide
    }