erDiagram
    him ||--o{ brother : administration
    him {
        DATE administration
        TEXT themselves
        VARCHAR(50) bad
    }
    brother ||--o{ foreign : sit
    brother {
        VARCHAR(50) sit
        DATE million
    }
    foreign ||--o{ before : then
    foreign {
        DATE then
        TEXT wait
        VARCHAR(50) establish
    }
    before ||--o{ long : fund
    before {
        VARCHAR(50) fund
        DATE section
    }
    long ||--o{ him : really
    long {
        DATE really
        TEXT maintain
        VARCHAR(50) minute
    }