erDiagram
    deep ||--o{ wait : floor
    deep {
        DATE floor
        TEXT international
        VARCHAR(50) design
    }
    wait ||--o{ sign : after
    wait {
        VARCHAR(50) after
        DATE beyond
    }
    sign ||--o{ smile : past
    sign {
        DATE past
        TEXT probably
        VARCHAR(50) may
    }
    smile ||--o{ skill : bed
    smile {
        VARCHAR(50) bed
        DATE talk
    }
    skill ||--o{ allow : left
    skill {
        DATE left
        TEXT garden
        VARCHAR(50) item
    }
    allow ||--o{ film : computer
    allow {
        VARCHAR(50) computer
        DATE southern
    }
    film ||--o{ up : federal
    film {
        DATE federal
        TEXT keep
        VARCHAR(50) computer
    }
    up ||--o{ visit : parent
    up {
        VARCHAR(50) parent
        DATE necessary
    }
    visit ||--o{ ok : consider
    visit {
        DATE consider
        TEXT level
        VARCHAR(50) front
    }
    ok ||--o{ perform : build
    ok {
        VARCHAR(50) build
        DATE year
    }
    perform ||--o{ deep : month
    perform {
        DATE month
        TEXT threat
        VARCHAR(50) will
    }