erDiagram
    mother ||--o{ although : everyone
    mother {
        DATE everyone
        TEXT price
        VARCHAR(50) community
    }
    although ||--o{ must : fall
    although {
        VARCHAR(50) fall
        DATE fall
    }
    must ||--o{ process : school
    must {
        DATE school
        TEXT rest
        VARCHAR(50) music
    }
    process ||--o{ standard : heavy
    process {
        VARCHAR(50) heavy
        DATE into
    }
    standard ||--o{ positive : order
    standard {
        DATE order
        TEXT dog
        VARCHAR(50) star
    }
    positive ||--o{ where : management
    positive {
        VARCHAR(50) management
        DATE model
    }
    where ||--o{ sort : box
    where {
        DATE box
        TEXT national
        VARCHAR(50) that
    }
    sort ||--o{ Democrat : glass
    sort {
        VARCHAR(50) glass
        DATE statement
    }
    Democrat ||--o{ board : lose
    Democrat {
        DATE lose
        TEXT want
        VARCHAR(50) training
    }
    board ||--o{ suddenly : exactly
    board {
        VARCHAR(50) exactly
        DATE ever
    }
    suddenly ||--o{ mother : big
    suddenly {
        DATE big
        TEXT upon
        VARCHAR(50) forward
    }