erDiagram
    wind ||--o{ skill : be
    wind {
        DATE be
        TEXT turn
        VARCHAR(50) imagine
    }
    skill ||--o{ always : piece
    skill {
        VARCHAR(50) piece
        DATE character
    }
    always ||--o{ major : group
    always {
        DATE group
        TEXT weight
        VARCHAR(50) market
    }
    major ||--o{ college : however
    major {
        VARCHAR(50) however
        DATE history
    }
    college ||--o{ senior : including
    college {
        DATE including
        TEXT board
        VARCHAR(50) view
    }
    senior ||--o{ person : medical
    senior {
        VARCHAR(50) medical
        DATE outside
    }
    person ||--o{ wind : our
    person {
        DATE our
        TEXT special
        VARCHAR(50) answer
    }