erDiagram
    purpose ||--o{ Mr : in
    purpose {
        DATE in
        TEXT friend
        VARCHAR(50) capital
    }
    Mr ||--o{ enter : operation
    Mr {
        VARCHAR(50) operation
        DATE play
    }
    enter ||--o{ lawyer : employee
    enter {
        DATE employee
        TEXT crime
        VARCHAR(50) despite
    }
    lawyer ||--o{ tax : discussion
    lawyer {
        VARCHAR(50) discussion
        DATE program
    }
    tax ||--o{ kind : run
    tax {
        DATE run
        TEXT somebody
        VARCHAR(50) rate
    }
    kind ||--o{ perhaps : determine
    kind {
        VARCHAR(50) determine
        DATE process
    }
    perhaps ||--o{ talk : right
    perhaps {
        DATE right
        TEXT him
        VARCHAR(50) thing
    }
    talk ||--o{ Mrs : institution
    talk {
        VARCHAR(50) institution
        DATE approach
    }
    Mrs ||--o{ term : father
    Mrs {
        DATE father
        TEXT growth
        VARCHAR(50) feel
    }
    term ||--o{ determine : travel
    term {
        VARCHAR(50) travel
        DATE this
    }
    determine ||--o{ sure : decide
    determine {
        DATE decide
        TEXT building
        VARCHAR(50) guess
    }
    sure ||--o{ purpose : land
    sure {
        VARCHAR(50) land
        DATE enter
    }