erDiagram
    head ||--o{ me : part
    head {
        DATE part
        TEXT reach
        VARCHAR(50) other
    }
    me ||--o{ image : for
    me {
        VARCHAR(50) for
        DATE seem
    }
    image ||--o{ street : share
    image {
        DATE share
        TEXT peace
        VARCHAR(50) clearly
    }
    street ||--o{ responsibility : newspaper
    street {
        VARCHAR(50) newspaper
        DATE quickly
    }
    responsibility ||--o{ run : industry
    responsibility {
        DATE industry
        TEXT thank
        VARCHAR(50) cup
    }
    run ||--o{ tree : culture
    run {
        VARCHAR(50) culture
        DATE say
    }
    tree ||--o{ strong : pretty
    tree {
        DATE pretty
        TEXT country
        VARCHAR(50) allow
    }
    strong ||--o{ put : measure
    strong {
        VARCHAR(50) measure
        DATE sister
    }
    put ||--o{ you : anyone
    put {
        DATE anyone
        TEXT world
        VARCHAR(50) newspaper
    }
    you ||--o{ prove : gas
    you {
        VARCHAR(50) gas
        DATE process
    }
    prove ||--o{ dark : produce
    prove {
        DATE produce
        TEXT effort
        VARCHAR(50) radio
    }
    dark ||--o{ head : happen
    dark {
        VARCHAR(50) happen
        DATE nature
    }