erDiagram
    language ||--o{ resource : kid
    language {
        DATE kid
        TEXT many
        VARCHAR(50) wind
    }
    resource ||--o{ leader : fight
    resource {
        VARCHAR(50) fight
        DATE song
    }
    leader ||--o{ cold : catch
    leader {
        DATE catch
        TEXT bag
        VARCHAR(50) study
    }
    cold ||--o{ imagine : benefit
    cold {
        VARCHAR(50) benefit
        DATE stay
    }
    imagine ||--o{ next : improve
    imagine {
        DATE improve
        TEXT investment
        VARCHAR(50) already
    }
    next ||--o{ economy : gas
    next {
        VARCHAR(50) gas
        DATE similar
    }
    economy ||--o{ policy : purpose
    economy {
        DATE purpose
        TEXT about
        VARCHAR(50) customer
    }
    policy ||--o{ foot : land
    policy {
        VARCHAR(50) land
        DATE important
    }
    foot ||--o{ scene : work
    foot {
        DATE work
        TEXT enter
        VARCHAR(50) professional
    }
    scene ||--o{ develop : situation
    scene {
        VARCHAR(50) situation
        DATE senior
    }
    develop ||--o{ feeling : thousand
    develop {
        DATE thousand
        TEXT manage
        VARCHAR(50) charge
    }
    feeling ||--o{ language : detail
    feeling {
        VARCHAR(50) detail
        DATE another
    }