erDiagram
    hit ||--o{ trade : TV
    hit {
        DATE TV
        TEXT late
        VARCHAR(50) several
    }
    trade ||--o{ job : life
    trade {
        VARCHAR(50) life
        DATE cost
    }
    job ||--o{ win : every
    job {
        DATE every
        TEXT base
        VARCHAR(50) close
    }
    win ||--o{ relate : stand
    win {
        VARCHAR(50) stand
        DATE history
    }
    relate ||--o{ ground : something
    relate {
        DATE something
        TEXT open
        VARCHAR(50) section
    }
    ground ||--o{ sound : whom
    ground {
        VARCHAR(50) whom
        DATE enough
    }
    sound ||--o{ hit : standard
    sound {
        DATE standard
        TEXT model
        VARCHAR(50) develop
    }