erDiagram
    job ||--o{ mean : beyond
    job {
        DATE beyond
        TEXT us
        VARCHAR(50) indicate
    }
    mean ||--o{ suddenly : ago
    mean {
        VARCHAR(50) ago
        DATE end
    }
    suddenly ||--o{ then : performance
    suddenly {
        DATE performance
        TEXT listen
        VARCHAR(50) hit
    }
    then ||--o{ sing : drug
    then {
        VARCHAR(50) drug
        DATE relate
    }
    sing ||--o{ too : sing
    sing {
        DATE sing
        TEXT goal
        VARCHAR(50) identify
    }
    too ||--o{ do : memory
    too {
        VARCHAR(50) memory
        DATE my
    }
    do ||--o{ attorney : toward
    do {
        DATE toward
        TEXT them
        VARCHAR(50) sell
    }
    attorney ||--o{ society : wait
    attorney {
        VARCHAR(50) wait
        DATE over
    }
    society ||--o{ job : cost
    society {
        DATE cost
        TEXT include
        VARCHAR(50) enter
    }