erDiagram
    watch ||--o{ identify : friend
    watch {
        DATE friend
        TEXT meet
        VARCHAR(50) radio
    }
    identify ||--o{ happy : never
    identify {
        VARCHAR(50) never
        DATE person
    }
    happy ||--o{ out : rather
    happy {
        DATE rather
        TEXT speech
        VARCHAR(50) where
    }
    out ||--o{ forward : course
    out {
        VARCHAR(50) course
        DATE manager
    }
    forward ||--o{ hit : recent
    forward {
        DATE recent
        TEXT weight
        VARCHAR(50) information
    }
    hit ||--o{ arm : south
    hit {
        VARCHAR(50) south
        DATE high
    }
    arm ||--o{ investment : employee
    arm {
        DATE employee
        TEXT PM
        VARCHAR(50) mean
    }
    investment ||--o{ watch : but
    investment {
        VARCHAR(50) but
        DATE Congress
    }