erDiagram
    best ||--o{ however : table
    best {
        DATE table
        TEXT too
        VARCHAR(50) after
    }
    however ||--o{ onto : continue
    however {
        VARCHAR(50) continue
        DATE something
    }
    onto ||--o{ care : candidate
    onto {
        DATE candidate
        TEXT third
        VARCHAR(50) include
    }
    care ||--o{ career : face
    care {
        VARCHAR(50) face
        DATE so
    }
    career ||--o{ notice : Republican
    career {
        DATE Republican
        TEXT charge
        VARCHAR(50) decide
    }
    notice ||--o{ usually : so
    notice {
        VARCHAR(50) so
        DATE watch
    }
    usually ||--o{ stage : must
    usually {
        DATE must
        TEXT financial
        VARCHAR(50) art
    }
    stage ||--o{ reveal : exactly
    stage {
        VARCHAR(50) exactly
        DATE seven
    }
    reveal ||--o{ character : star
    reveal {
        DATE star
        TEXT size
        VARCHAR(50) future
    }
    character ||--o{ best : food
    character {
        VARCHAR(50) food
        DATE current
    }