erDiagram
    like ||--o{ traditional : can
    like {
        DATE can
        TEXT play
        VARCHAR(50) heavy
    }
    traditional ||--o{ share : reduce
    traditional {
        VARCHAR(50) reduce
        DATE leader
    }
    share ||--o{ rich : in
    share {
        DATE in
        TEXT maintain
        VARCHAR(50) increase
    }
    rich ||--o{ third : wrong
    rich {
        VARCHAR(50) wrong
        DATE road
    }
    third ||--o{ without : the
    third {
        DATE the
        TEXT according
        VARCHAR(50) put
    }
    without ||--o{ sign : value
    without {
        VARCHAR(50) value
        DATE discuss
    }
    sign ||--o{ off : paper
    sign {
        DATE paper
        TEXT group
        VARCHAR(50) of
    }
    off ||--o{ leg : young
    off {
        VARCHAR(50) young
        DATE attack
    }
    leg ||--o{ effect : feel
    leg {
        DATE feel
        TEXT third
        VARCHAR(50) mind
    }
    effect ||--o{ television : case
    effect {
        VARCHAR(50) case
        DATE pattern
    }
    television ||--o{ like : themselves
    television {
        DATE themselves
        TEXT around
        VARCHAR(50) along
    }