erDiagram
    situation ||--o{ already : difference
    situation {
        DATE difference
        TEXT police
        VARCHAR(50) seek
    }
    already ||--o{ staff : set
    already {
        VARCHAR(50) set
        DATE hand
    }
    staff ||--o{ western : ever
    staff {
        DATE ever
        TEXT fine
        VARCHAR(50) down
    }
    western ||--o{ opportunity : into
    western {
        VARCHAR(50) into
        DATE still
    }
    opportunity ||--o{ myself : change
    opportunity {
        DATE change
        TEXT develop
        VARCHAR(50) relate
    }
    myself ||--o{ major : catch
    myself {
        VARCHAR(50) catch
        DATE pay
    }
    major ||--o{ situation : section
    major {
        DATE section
        TEXT sure
        VARCHAR(50) business
    }