erDiagram
    quickly ||--o{ mother : compare
    quickly {
        DATE compare
        TEXT already
        VARCHAR(50) care
    }
    mother ||--o{ argue : every
    mother {
        VARCHAR(50) every
        DATE determine
    }
    argue ||--o{ professor : threat
    argue {
        DATE threat
        TEXT son
        VARCHAR(50) themselves
    }
    professor ||--o{ generation : front
    professor {
        VARCHAR(50) front
        DATE whom
    }
    generation ||--o{ court : artist
    generation {
        DATE artist
        TEXT positive
        VARCHAR(50) church
    }
    court ||--o{ game : total
    court {
        VARCHAR(50) total
        DATE end
    }
    game ||--o{ quickly : strategy
    game {
        DATE strategy
        TEXT develop
        VARCHAR(50) early
    }