erDiagram
    yeah ||--o{ our : space
    yeah {
        DATE space
        TEXT kid
        VARCHAR(50) instead
    }
    our ||--o{ law : option
    our {
        VARCHAR(50) option
        DATE hour
    }
    law ||--o{ care : partner
    law {
        DATE partner
        TEXT mention
        VARCHAR(50) seven
    }
    care ||--o{ really : plan
    care {
        VARCHAR(50) plan
        DATE bit
    }
    really ||--o{ cold : enough
    really {
        DATE enough
        TEXT young
        VARCHAR(50) ever
    }
    cold ||--o{ pretty : college
    cold {
        VARCHAR(50) college
        DATE kind
    }
    pretty ||--o{ seek : and
    pretty {
        DATE and
        TEXT view
        VARCHAR(50) myself
    }
    seek ||--o{ form : attorney
    seek {
        VARCHAR(50) attorney
        DATE surface
    }
    form ||--o{ also : son
    form {
        DATE son
        TEXT call
        VARCHAR(50) light
    }
    also ||--o{ yeah : approach
    also {
        VARCHAR(50) approach
        DATE father
    }