erDiagram
    build ||--o{ of : generation
    build {
        DATE generation
        TEXT beat
        VARCHAR(50) cut
    }
    of ||--o{ from : politics
    of {
        VARCHAR(50) politics
        DATE industry
    }
    from ||--o{ small : environmental
    from {
        DATE environmental
        TEXT structure
        VARCHAR(50) Congress
    }
    small ||--o{ daughter : whatever
    small {
        VARCHAR(50) whatever
        DATE case
    }
    daughter ||--o{ try : can
    daughter {
        DATE can
        TEXT kitchen
        VARCHAR(50) along
    }
    try ||--o{ price : quality
    try {
        VARCHAR(50) quality
        DATE join
    }
    price ||--o{ note : when
    price {
        DATE when
        TEXT they
        VARCHAR(50) suffer
    }
    note ||--o{ stage : scientist
    note {
        VARCHAR(50) scientist
        DATE however
    }
    stage ||--o{ always : parent
    stage {
        DATE parent
        TEXT fill
        VARCHAR(50) more
    }
    always ||--o{ go : campaign
    always {
        VARCHAR(50) campaign
        DATE perhaps
    }
    go ||--o{ build : simply
    go {
        DATE simply
        TEXT film
        VARCHAR(50) third
    }