erDiagram
    space ||--o{ suddenly : entire
    space {
        DATE entire
        TEXT spend
        VARCHAR(50) home
    }
    suddenly ||--o{ she : democratic
    suddenly {
        VARCHAR(50) democratic
        DATE evening
    }
    she ||--o{ section : decide
    she {
        DATE decide
        TEXT number
        VARCHAR(50) forget
    }
    section ||--o{ raise : radio
    section {
        VARCHAR(50) radio
        DATE glass
    }
    raise ||--o{ often : meet
    raise {
        DATE meet
        TEXT remember
        VARCHAR(50) military
    }
    often ||--o{ action : positive
    often {
        VARCHAR(50) positive
        DATE experience
    }
    action ||--o{ be : special
    action {
        DATE special
        TEXT statement
        VARCHAR(50) million
    }
    be ||--o{ space : any
    be {
        VARCHAR(50) any
    }