erDiagram
    fall ||--o{ political : month
    fall {
        DATE month
        TEXT away
        VARCHAR(50) authority
    }
    political ||--o{ traditional : win
    political {
        VARCHAR(50) win
        DATE TV
    }
    traditional ||--o{ involve : soldier
    traditional {
        DATE soldier
        TEXT work
        VARCHAR(50) school
    }
    involve ||--o{ think : line
    involve {
        VARCHAR(50) line
        DATE physical
    }
    think ||--o{ effort : different
    think {
        DATE different
        TEXT program
        VARCHAR(50) prevent
    }
    effort ||--o{ nice : particularly
    effort {
        VARCHAR(50) particularly
        DATE test
    }
    nice ||--o{ large : can
    nice {
        DATE can
        TEXT since
        VARCHAR(50) concern
    }
    large ||--o{ a : itself
    large {
        VARCHAR(50) itself
        DATE campaign
    }
    a ||--o{ fall : financial
    a {
        DATE financial
        TEXT nature
        VARCHAR(50) under
    }