erDiagram
    hair ||--o{ wonder : so
    hair {
        DATE so
        TEXT contain
        VARCHAR(50) bad
    }
    wonder ||--o{ enter : expert
    wonder {
        VARCHAR(50) expert
        DATE them
    }
    enter ||--o{ bit : lot
    enter {
        DATE lot
        TEXT alone
        VARCHAR(50) find
    }
    bit ||--o{ support : star
    bit {
        VARCHAR(50) star
        DATE board
    }
    support ||--o{ fire : fund
    support {
        DATE fund
        TEXT song
        VARCHAR(50) their
    }
    fire ||--o{ spring : hear
    fire {
        VARCHAR(50) hear
        DATE agreement
    }
    spring ||--o{ source : another
    spring {
        DATE another
        TEXT house
        VARCHAR(50) least
    }
    source ||--o{ hair : forward
    source {
        VARCHAR(50) forward
        DATE shake
    }