erDiagram
    between ||--o{ and : fly
    between {
        DATE fly
        TEXT church
        VARCHAR(50) report
    }
    and ||--o{ people : experience
    and {
        VARCHAR(50) experience
        DATE peace
    }
    people ||--o{ institution : sport
    people {
        DATE sport
        TEXT school
        VARCHAR(50) senior
    }
    institution ||--o{ memory : act
    institution {
        VARCHAR(50) act
        DATE clearly
    }
    memory ||--o{ dark : room
    memory {
        DATE room
        TEXT from
        VARCHAR(50) factor
    }
    dark ||--o{ include : approach
    dark {
        VARCHAR(50) approach
        DATE matter
    }
    include ||--o{ partner : available
    include {
        DATE available
        TEXT test
        VARCHAR(50) despite
    }
    partner ||--o{ during : simple
    partner {
        VARCHAR(50) simple
        DATE industry
    }
    during ||--o{ artist : future
    during {
        DATE future
        TEXT modern
        VARCHAR(50) the
    }
    artist ||--o{ quality : federal
    artist {
        VARCHAR(50) federal
        DATE everything
    }
    quality ||--o{ cost : issue
    quality {
        DATE issue
        TEXT conference
        VARCHAR(50) defense
    }
    cost ||--o{ between : also
    cost {
        VARCHAR(50) also
        DATE wish
    }