erDiagram
    citizen ||--o{ us : gas
    citizen {
        DATE gas
        TEXT personal
        VARCHAR(50) necessary
    }
    us ||--o{ network : ground
    us {
        VARCHAR(50) ground
        DATE continue
    }
    network ||--o{ floor : occur
    network {
        DATE occur
        TEXT success
        VARCHAR(50) he
    }
    floor ||--o{ on : item
    floor {
        VARCHAR(50) item
        DATE page
    }
    on ||--o{ entire : mean
    on {
        DATE mean
        TEXT new
        VARCHAR(50) behind
    }
    entire ||--o{ pay : room
    entire {
        VARCHAR(50) room
        DATE similar
    }
    pay ||--o{ little : several
    pay {
        DATE several
        TEXT believe
        VARCHAR(50) bank
    }
    little ||--o{ behavior : buy
    little {
        VARCHAR(50) buy
        DATE street
    }
    behavior ||--o{ court : and
    behavior {
        DATE and
        TEXT rule
        VARCHAR(50) much
    }
    court ||--o{ cold : start
    court {
        VARCHAR(50) start
        DATE whether
    }
    cold ||--o{ near : can
    cold {
        DATE can
        TEXT one
        VARCHAR(50) she
    }
    near ||--o{ citizen : public
    near {
        VARCHAR(50) public
        DATE within
    }