erDiagram
    wish ||--o{ image : hold
    wish {
        DATE hold
        TEXT determine
        VARCHAR(50) office
    }
    image ||--o{ safe : store
    image {
        VARCHAR(50) store
        DATE whom
    }
    safe ||--o{ military : finally
    safe {
        DATE finally
        TEXT nothing
        VARCHAR(50) write
    }
    military ||--o{ near : order
    military {
        VARCHAR(50) order
        DATE see
    }
    near ||--o{ wish : property
    near {
        DATE property
        TEXT role
        VARCHAR(50) past
    }