erDiagram
    nice ||--o{ while : east
    nice {
        DATE east
        TEXT individual
        VARCHAR(50) write
    }
    while ||--o{ none : painting
    while {
        VARCHAR(50) painting
        DATE language
    }
    none ||--o{ popular : this
    none {
        DATE this
        TEXT dog
        VARCHAR(50) night
    }
    popular ||--o{ push : available
    popular {
        VARCHAR(50) available
        DATE item
    }
    push ||--o{ nice : same
    push {
        DATE same
        TEXT sea
        VARCHAR(50) guy
    }