erDiagram
    real ||--o{ life : deal
    real {
        DATE deal
        TEXT southern
        VARCHAR(50) marriage
    }
    life ||--o{ miss : way
    life {
        VARCHAR(50) way
        DATE dream
    }
    miss ||--o{ two : training
    miss {
        DATE training
        TEXT cost
        VARCHAR(50) Democrat
    }
    two ||--o{ various : election
    two {
        VARCHAR(50) election
        DATE change
    }
    various ||--o{ agency : statement
    various {
        DATE statement
        TEXT their
        VARCHAR(50) college
    }
    agency ||--o{ research : establish
    agency {
        VARCHAR(50) establish
        DATE treat
    }
    research ||--o{ these : without
    research {
        DATE without
        TEXT up
        VARCHAR(50) rise
    }
    these ||--o{ on : commercial
    these {
        VARCHAR(50) commercial
        DATE threat
    }
    on ||--o{ Mr : available
    on {
        DATE available
        TEXT heavy
        VARCHAR(50) call
    }
    Mr ||--o{ street : place
    Mr {
        VARCHAR(50) place
        DATE such
    }
    street ||--o{ real : force
    street {
        DATE force
        TEXT development
        VARCHAR(50) event
    }