erDiagram
    listen ||--o{ join : yes
    listen {
        DATE yes
        TEXT well
        VARCHAR(50) information
    }
    join ||--o{ sign : show
    join {
        VARCHAR(50) show
    }
    sign ||--o{ choice : fill
    sign {
        DATE fill
        TEXT record
        VARCHAR(50) seem
    }
    choice ||--o{ commercial : surface
    choice {
        VARCHAR(50) surface
        DATE sit
    }
    commercial ||--o{ college : require
    commercial {
        DATE require
        TEXT system
        VARCHAR(50) hand
    }
    college ||--o{ away : nature
    college {
        VARCHAR(50) nature
        DATE growth
    }
    away ||--o{ beautiful : tough
    away {
        DATE tough
        TEXT begin
        VARCHAR(50) three
    }
    beautiful ||--o{ campaign : order
    beautiful {
        VARCHAR(50) order
        DATE paper
    }
    campaign ||--o{ listen : your
    campaign {
        DATE your
        TEXT pressure
        VARCHAR(50) good
    }