erDiagram
    camera ||--o{ himself : third
    camera {
        DATE third
        TEXT others
        VARCHAR(50) capital
    }
    himself ||--o{ difficult : movement
    himself {
        VARCHAR(50) movement
        DATE television
    }
    difficult ||--o{ run : do
    difficult {
        DATE do
        TEXT wall
        VARCHAR(50) happen
    }
    run ||--o{ sort : stay
    run {
        VARCHAR(50) stay
        DATE music
    }
    sort ||--o{ become : local
    sort {
        DATE local
        TEXT understand
        VARCHAR(50) eye
    }
    become ||--o{ order : determine
    become {
        VARCHAR(50) determine
        DATE professor
    }
    order ||--o{ investment : factor
    order {
        DATE factor
        TEXT effort
        VARCHAR(50) concern
    }
    investment ||--o{ political : suffer
    investment {
        VARCHAR(50) suffer
        DATE down
    }
    political ||--o{ camera : have
    political {
        DATE have
        TEXT particularly
        VARCHAR(50) trip
    }