erDiagram
    consider ||--o{ food : hard
    consider {
        DATE hard
        TEXT girl
        VARCHAR(50) bag
    }
    food ||--o{ blood : have
    food {
        VARCHAR(50) have
        DATE should
    }
    blood ||--o{ stuff : late
    blood {
        DATE late
        TEXT father
        VARCHAR(50) school
    }
    stuff ||--o{ shake : machine
    stuff {
        VARCHAR(50) machine
        DATE enjoy
    }
    shake ||--o{ high : also
    shake {
        DATE also
        TEXT close
        VARCHAR(50) draw
    }
    high ||--o{ personal : night
    high {
        VARCHAR(50) night
        DATE series
    }
    personal ||--o{ wall : light
    personal {
        DATE light
        TEXT resource
        VARCHAR(50) address
    }
    wall ||--o{ consider : music
    wall {
        VARCHAR(50) music
        DATE account
    }