erDiagram
    part ||--o{ save : clearly
    part {
        DATE clearly
        TEXT brother
        VARCHAR(50) front
    }
    save ||--o{ information : together
    save {
        VARCHAR(50) together
        DATE rich
    }
    information ||--o{ fish : thought
    information {
        DATE thought
        TEXT send
        VARCHAR(50) manager
    }
    fish ||--o{ me : evening
    fish {
        VARCHAR(50) evening
        DATE industry
    }
    me ||--o{ recognize : church
    me {
        DATE church
        TEXT crime
        VARCHAR(50) light
    }
    recognize ||--o{ carry : page
    recognize {
        VARCHAR(50) page
        DATE trade
    }
    carry ||--o{ trial : husband
    carry {
        DATE husband
        TEXT support
        VARCHAR(50) share
    }
    trial ||--o{ economic : behind
    trial {
        VARCHAR(50) behind
        DATE story
    }
    economic ||--o{ most : southern
    economic {
        DATE southern
        TEXT far
        VARCHAR(50) civil
    }
    most ||--o{ party : PM
    most {
        VARCHAR(50) PM
        DATE research
    }
    party ||--o{ part : leave
    party {
        DATE leave
        TEXT official
        VARCHAR(50) structure
    }