erDiagram
    develop ||--o{ event : central
    develop {
        DATE central
        TEXT better
        VARCHAR(50) actually
    }
    event ||--o{ continue : staff
    event {
        VARCHAR(50) staff
        DATE mother
    }
    continue ||--o{ sell : away
    continue {
        DATE away
        TEXT stuff
        VARCHAR(50) perform
    }
    sell ||--o{ follow : above
    sell {
        VARCHAR(50) above
        DATE prepare
    }
    follow ||--o{ and : ability
    follow {
        DATE ability
        TEXT score
        VARCHAR(50) carry
    }
    and ||--o{ church : above
    and {
        VARCHAR(50) above
        DATE listen
    }
    church ||--o{ rest : expert
    church {
        DATE expert
        TEXT send
        VARCHAR(50) draw
    }
    rest ||--o{ eight : example
    rest {
        VARCHAR(50) example
        DATE yourself
    }
    eight ||--o{ significant : weight
    eight {
        DATE weight
        TEXT avoid
        VARCHAR(50) happy
    }
    significant ||--o{ develop : we
    significant {
        VARCHAR(50) we
        DATE people
    }