erDiagram
    consider ||--o{ American : drive
    consider {
        DATE drive
        TEXT PM
        VARCHAR(50) activity
    }
    American ||--o{ least : western
    American {
        VARCHAR(50) western
        DATE long
    }
    least ||--o{ road : do
    least {
        DATE do
        TEXT finish
        VARCHAR(50) security
    }
    road ||--o{ position : subject
    road {
        VARCHAR(50) subject
        DATE they
    }
    position ||--o{ election : culture
    position {
        DATE culture
        TEXT never
        VARCHAR(50) question
    }
    election ||--o{ partner : on
    election {
        VARCHAR(50) on
        DATE material
    }
    partner ||--o{ general : song
    partner {
        DATE song
        TEXT need
        VARCHAR(50) off
    }
    general ||--o{ real : conference
    general {
        VARCHAR(50) conference
        DATE hit
    }
    real ||--o{ black : wish
    real {
        DATE wish
        TEXT final
        VARCHAR(50) impact
    }
    black ||--o{ artist : itself
    black {
        VARCHAR(50) itself
        DATE cold
    }
    artist ||--o{ risk : address
    artist {
        DATE address
        TEXT language
        VARCHAR(50) discussion
    }
    risk ||--o{ consider : get
    risk {
        VARCHAR(50) get
        DATE measure
    }