erDiagram
    husband ||--o{ degree : improve
    husband {
        DATE improve
        TEXT art
        VARCHAR(50) nor
    }
    degree ||--o{ expect : threat
    degree {
        VARCHAR(50) threat
        DATE law
    }
    expect ||--o{ author : game
    expect {
        DATE game
        TEXT throughout
        VARCHAR(50) quite
    }
    author ||--o{ size : want
    author {
        VARCHAR(50) want
        DATE state
    }
    size ||--o{ adult : family
    size {
        DATE family
        TEXT direction
        VARCHAR(50) sort
    }
    adult ||--o{ put : position
    adult {
        VARCHAR(50) position
        DATE home
    }
    put ||--o{ husband : knowledge
    put {
        DATE knowledge
        TEXT bag
        VARCHAR(50) education
    }