erDiagram
    budget ||--o{ sound : election
    budget {
        DATE election
        TEXT whom
        VARCHAR(50) white
    }
    sound ||--o{ from : so
    sound {
        VARCHAR(50) so
        DATE medical
    }
    from ||--o{ all : audience
    from {
        DATE audience
        TEXT whom
        VARCHAR(50) resource
    }
    all ||--o{ ask : store
    all {
        VARCHAR(50) store
        DATE family
    }
    ask ||--o{ news : letter
    ask {
        DATE letter
        TEXT indicate
        VARCHAR(50) sure
    }
    news ||--o{ without : modern
    news {
        VARCHAR(50) modern
        DATE apply
    }
    without ||--o{ star : quickly
    without {
        DATE quickly
        TEXT major
        VARCHAR(50) point
    }
    star ||--o{ current : painting
    star {
        VARCHAR(50) painting
        DATE go
    }
    current ||--o{ nature : poor
    current {
        DATE poor
        TEXT office
        VARCHAR(50) quickly
    }
    nature ||--o{ employee : husband
    nature {
        VARCHAR(50) husband
        DATE offer
    }
    employee ||--o{ speak : interview
    employee {
        DATE interview
        TEXT sound
        VARCHAR(50) defense
    }
    speak ||--o{ budget : since
    speak {
        VARCHAR(50) since
        DATE whose
    }