erDiagram
    different ||--o{ want : gas
    different {
        DATE gas
        TEXT turn
        VARCHAR(50) nation
    }
    want ||--o{ recently : would
    want {
        VARCHAR(50) would
        DATE network
    }
    recently ||--o{ wrong : road
    recently {
        DATE road
        TEXT more
        VARCHAR(50) room
    }
    wrong ||--o{ newspaper : road
    wrong {
        VARCHAR(50) road
        DATE several
    }
    newspaper ||--o{ scientist : do
    newspaper {
        DATE do
        TEXT necessary
        VARCHAR(50) lead
    }
    scientist ||--o{ late : far
    scientist {
        VARCHAR(50) far
        DATE cell
    }
    late ||--o{ different : attorney
    late {
        DATE attorney
        TEXT travel
        VARCHAR(50) since
    }