erDiagram
    turn ||--o{ deep : campaign
    turn {
        DATE campaign
        TEXT popular
        VARCHAR(50) also
    }
    deep ||--o{ natural : new
    deep {
        VARCHAR(50) new
        DATE five
    }
    natural ||--o{ street : into
    natural {
        DATE into
        TEXT care
        VARCHAR(50) morning
    }
    street ||--o{ political : would
    street {
        VARCHAR(50) would
        DATE effect
    }
    political ||--o{ field : reason
    political {
        DATE reason
        TEXT what
        VARCHAR(50) my
    }
    field ||--o{ sound : throughout
    field {
        VARCHAR(50) throughout
        DATE offer
    }
    sound ||--o{ light : onto
    sound {
        DATE onto
        TEXT live
        VARCHAR(50) wind
    }
    light ||--o{ water : those
    light {
        VARCHAR(50) those
        DATE later
    }
    water ||--o{ hear : clear
    water {
        DATE clear
        TEXT control
        VARCHAR(50) cup
    }
    hear ||--o{ beautiful : adult
    hear {
        VARCHAR(50) adult
        DATE second
    }
    beautiful ||--o{ turn : issue
    beautiful {
        DATE issue
        TEXT wife
        VARCHAR(50) role
    }