erDiagram
    decision ||--o{ popular : probably
    decision {
        DATE probably
        TEXT direction
        VARCHAR(50) major
    }
    popular ||--o{ simply : certain
    popular {
        VARCHAR(50) certain
        DATE politics
    }
    simply ||--o{ work : nature
    simply {
        DATE nature
        TEXT likely
        VARCHAR(50) measure
    }
    work ||--o{ stand : sea
    work {
        VARCHAR(50) sea
        DATE study
    }
    stand ||--o{ tell : second
    stand {
        DATE second
        TEXT direction
        VARCHAR(50) professor
    }
    tell ||--o{ author : firm
    tell {
        VARCHAR(50) firm
        DATE girl
    }
    author ||--o{ subject : son
    author {
        DATE son
        TEXT surface
        VARCHAR(50) while
    }
    subject ||--o{ send : political
    subject {
        VARCHAR(50) political
        DATE manage
    }
    send ||--o{ check : per
    send {
        DATE per
        TEXT avoid
        VARCHAR(50) member
    }
    check ||--o{ carry : feeling
    check {
        VARCHAR(50) feeling
        DATE according
    }
    carry ||--o{ decision : second
    carry {
        DATE second
        TEXT size
        VARCHAR(50) summer
    }