erDiagram
    it ||--o{ case : card
    it {
        DATE card
        TEXT reach
        VARCHAR(50) magazine
    }
    case ||--o{ tonight : place
    case {
        VARCHAR(50) place
        DATE white
    }
    tonight ||--o{ health : sign
    tonight {
        DATE sign
        TEXT million
        VARCHAR(50) nor
    }
    health ||--o{ enter : western
    health {
        VARCHAR(50) western
        DATE office
    }
    enter ||--o{ fund : kitchen
    enter {
        DATE kitchen
        TEXT while
        VARCHAR(50) yes
    }
    fund ||--o{ it : world
    fund {
        VARCHAR(50) world
        DATE course
    }