erDiagram
    see ||--o{ manager : baby
    see {
        DATE baby
        TEXT least
        VARCHAR(50) somebody
    }
    manager ||--o{ create : first
    manager {
        VARCHAR(50) first
        DATE land
    }
    create ||--o{ which : this
    create {
        DATE this
        TEXT white
        VARCHAR(50) really
    }
    which ||--o{ let : data
    which {
        VARCHAR(50) data
        DATE year
    }
    let ||--o{ trial : according
    let {
        DATE according
        TEXT clear
        VARCHAR(50) step
    }
    trial ||--o{ air : who
    trial {
        VARCHAR(50) who
        DATE may
    }
    air ||--o{ out : yet
    air {
        DATE yet
        TEXT tell
        VARCHAR(50) ahead
    }
    out ||--o{ process : ok
    out {
        VARCHAR(50) ok
        DATE involve
    }
    process ||--o{ building : back
    process {
        DATE back
        TEXT education
        VARCHAR(50) nor
    }
    building ||--o{ see : fire
    building {
        VARCHAR(50) fire
        DATE help
    }