erDiagram
    consumer ||--o{ foreign : lay
    consumer {
        DATE lay
        TEXT inside
        VARCHAR(50) put
    }
    foreign ||--o{ force : resource
    foreign {
        VARCHAR(50) resource
        DATE picture
    }
    force ||--o{ six : once
    force {
        DATE once
        TEXT build
        VARCHAR(50) stock
    }
    six ||--o{ us : change
    six {
        VARCHAR(50) change
        DATE call
    }
    us ||--o{ condition : especially
    us {
        DATE especially
        TEXT model
        VARCHAR(50) ball
    }
    condition ||--o{ some : across
    condition {
        VARCHAR(50) across
        DATE PM
    }
    some ||--o{ child : prepare
    some {
        DATE prepare
        TEXT back
        VARCHAR(50) amount
    }
    child ||--o{ business : century
    child {
        VARCHAR(50) century
        DATE friend
    }
    business ||--o{ entire : success
    business {
        DATE success
        TEXT glass
        VARCHAR(50) current
    }
    entire ||--o{ information : them
    entire {
        VARCHAR(50) them
        DATE develop
    }
    information ||--o{ far : stock
    information {
        DATE stock
        TEXT medical
        VARCHAR(50) traditional
    }
    far ||--o{ consumer : issue
    far {
        VARCHAR(50) issue
        DATE accept
    }