erDiagram
    somebody ||--o{ space : factor
    somebody {
        DATE factor
        TEXT fill
        VARCHAR(50) beyond
    }
    space ||--o{ lead : shake
    space {
        VARCHAR(50) shake
        DATE quickly
    }
    lead ||--o{ all : join
    lead {
        DATE join
        TEXT live
        VARCHAR(50) there
    }
    all ||--o{ feeling : mother
    all {
        VARCHAR(50) mother
        DATE case
    }
    feeling ||--o{ somebody : goal
    feeling {
        DATE goal
        TEXT by
        VARCHAR(50) pattern
    }