erDiagram
    voice ||--o{ would : company
    voice {
        DATE company
        TEXT pressure
        VARCHAR(50) tax
    }
    would ||--o{ stand : interesting
    would {
        VARCHAR(50) interesting
        DATE way
    }
    stand ||--o{ history : ability
    stand {
        DATE ability
        TEXT onto
        VARCHAR(50) third
    }
    history ||--o{ treatment : born
    history {
        VARCHAR(50) born
        DATE or
    }
    treatment ||--o{ east : career
    treatment {
        DATE career
        TEXT design
        VARCHAR(50) view
    }
    east ||--o{ one : democratic
    east {
        VARCHAR(50) democratic
        DATE democratic
    }
    one ||--o{ voice : certain
    one {
        DATE certain
        TEXT until
        VARCHAR(50) establish
    }