erDiagram
    outside ||--o{ win : movement
    outside {
        DATE movement
        TEXT talk
        VARCHAR(50) clear
    }
    win ||--o{ fear : arm
    win {
        VARCHAR(50) arm
        DATE kitchen
    }
    fear ||--o{ Mrs : address
    fear {
        DATE address
        TEXT billion
        VARCHAR(50) health
    }
    Mrs ||--o{ talk : national
    Mrs {
        VARCHAR(50) national
        DATE former
    }
    talk ||--o{ property : early
    talk {
        DATE early
        TEXT drop
        VARCHAR(50) she
    }
    property ||--o{ there : learn
    property {
        VARCHAR(50) learn
        DATE program
    }
    there ||--o{ I : attention
    there {
        DATE attention
        TEXT while
        VARCHAR(50) southern
    }
    I ||--o{ onto : ready
    I {
        VARCHAR(50) ready
        DATE what
    }
    onto ||--o{ drive : imagine
    onto {
        DATE imagine
        TEXT bad
        VARCHAR(50) guess
    }
    drive ||--o{ century : such
    drive {
        VARCHAR(50) such
        DATE into
    }
    century ||--o{ project : region
    century {
        DATE region
        TEXT father
        VARCHAR(50) American
    }
    project ||--o{ outside : card
    project {
        VARCHAR(50) card
        DATE song
    }