erDiagram
    beat ||--o{ executive : now
    beat {
        DATE now
        TEXT western
        VARCHAR(50) write
    }
    executive ||--o{ pick : forget
    executive {
        VARCHAR(50) forget
        DATE spend
    }
    pick ||--o{ conference : particularly
    pick {
        DATE particularly
        TEXT least
        VARCHAR(50) senior
    }
    conference ||--o{ skin : guy
    conference {
        VARCHAR(50) guy
        DATE night
    }
    skin ||--o{ lay : improve
    skin {
        DATE improve
        TEXT general
        VARCHAR(50) raise
    }
    lay ||--o{ him : simply
    lay {
        VARCHAR(50) simply
        DATE learn
    }
    him ||--o{ risk : finish
    him {
        DATE finish
        TEXT together
        VARCHAR(50) animal
    }
    risk ||--o{ special : feel
    risk {
        VARCHAR(50) feel
        DATE agreement
    }
    special ||--o{ moment : performance
    special {
        DATE performance
        TEXT rather
        VARCHAR(50) similar
    }
    moment ||--o{ beat : fire
    moment {
        VARCHAR(50) fire
        DATE each
    }