erDiagram
    team ||--o{ face : leave
    team {
        DATE leave
        TEXT tonight
        VARCHAR(50) above
    }
    face ||--o{ walk : design
    face {
        VARCHAR(50) design
        DATE hard
    }
    walk ||--o{ adult : blood
    walk {
        DATE blood
        TEXT yet
        VARCHAR(50) future
    }
    adult ||--o{ cover : save
    adult {
        VARCHAR(50) save
        DATE resource
    }
    cover ||--o{ bit : police
    cover {
        DATE police
        TEXT partner
        VARCHAR(50) scientist
    }
    bit ||--o{ the : measure
    bit {
        VARCHAR(50) measure
        DATE business
    }
    the ||--o{ material : most
    the {
        DATE most
        TEXT western
        VARCHAR(50) practice
    }
    material ||--o{ role : it
    material {
        VARCHAR(50) it
        DATE worry
    }
    role ||--o{ main : large
    role {
        DATE large
        TEXT five
        VARCHAR(50) collection
    }
    main ||--o{ team : trial
    main {
        VARCHAR(50) trial
        DATE Congress
    }