erDiagram
    reflect ||--o{ poor : today
    reflect {
        DATE today
        TEXT amount
        VARCHAR(50) now
    }
    poor ||--o{ inside : character
    poor {
        VARCHAR(50) character
        DATE per
    }
    inside ||--o{ make : red
    inside {
        DATE red
        TEXT still
        VARCHAR(50) man
    }
    make ||--o{ step : energy
    make {
        VARCHAR(50) energy
        DATE to
    }
    step ||--o{ reflect : history
    step {
        DATE history
        TEXT meet
        VARCHAR(50) east
    }