erDiagram
    serious ||--o{ box : imagine
    serious {
        DATE imagine
        TEXT forward
        VARCHAR(50) approach
    }
    box ||--o{ growth : couple
    box {
        VARCHAR(50) couple
        DATE evening
    }
    growth ||--o{ total : continue
    growth {
        DATE continue
        TEXT although
        VARCHAR(50) base
    }
    total ||--o{ street : grow
    total {
        VARCHAR(50) grow
        DATE news
    }
    street ||--o{ within : edge
    street {
        DATE edge
        TEXT similar
        VARCHAR(50) wall
    }
    within ||--o{ economy : floor
    within {
        VARCHAR(50) floor
        DATE point
    }
    economy ||--o{ anything : glass
    economy {
        DATE glass
        TEXT board
        VARCHAR(50) spend
    }
    anything ||--o{ purpose : thus
    anything {
        VARCHAR(50) thus
        DATE take
    }
    purpose ||--o{ best : space
    purpose {
        DATE space
        TEXT effort
        VARCHAR(50) her
    }
    best ||--o{ serious : painting
    best {
        VARCHAR(50) painting
        DATE film
    }