erDiagram
    might ||--o{ near : author
    might {
        DATE author
        TEXT save
        VARCHAR(50) ever
    }
    near ||--o{ why : feel
    near {
        VARCHAR(50) feel
        DATE seem
    }
    why ||--o{ heavy : pull
    why {
        DATE pull
        TEXT school
        VARCHAR(50) when
    }
    heavy ||--o{ mean : thought
    heavy {
        VARCHAR(50) thought
        DATE table
    }
    mean ||--o{ might : night
    mean {
        DATE night
        TEXT safe
        VARCHAR(50) mission
    }