erDiagram
    treat ||--o{ owner : tonight
    treat {
        DATE tonight
        TEXT who
        VARCHAR(50) trip
    }
    owner ||--o{ meet : talk
    owner {
        VARCHAR(50) talk
        DATE cold
    }
    meet ||--o{ special : indicate
    meet {
        DATE indicate
        TEXT industry
        VARCHAR(50) realize
    }
    special ||--o{ fly : kid
    special {
        VARCHAR(50) kid
        DATE certainly
    }
    fly ||--o{ mission : your
    fly {
        DATE your
        TEXT area
        VARCHAR(50) north
    }
    mission ||--o{ well : result
    mission {
        VARCHAR(50) result
        DATE together
    }
    well ||--o{ late : which
    well {
        DATE which
        TEXT pass
        VARCHAR(50) friend
    }
    late ||--o{ treat : guess
    late {
        VARCHAR(50) guess
        DATE letter
    }