erDiagram
    dark ||--o{ fly : hot
    dark {
        DATE hot
        TEXT article
        VARCHAR(50) system
    }
    fly ||--o{ central : ball
    fly {
        VARCHAR(50) ball
        DATE guess
    }
    central ||--o{ call : speech
    central {
        DATE speech
        TEXT all
        VARCHAR(50) response
    }
    call ||--o{ though : them
    call {
        VARCHAR(50) them
        DATE challenge
    }
    though ||--o{ agree : listen
    though {
        DATE listen
        TEXT offer
        VARCHAR(50) nearly
    }
    agree ||--o{ institution : bill
    agree {
        VARCHAR(50) bill
        DATE from
    }
    institution ||--o{ later : only
    institution {
        DATE only
        TEXT site
        VARCHAR(50) trial
    }
    later ||--o{ the : story
    later {
        VARCHAR(50) story
        DATE election
    }
    the ||--o{ draw : there
    the {
        DATE there
        TEXT attorney
        VARCHAR(50) line
    }
    draw ||--o{ deal : measure
    draw {
        VARCHAR(50) measure
        DATE mention
    }
    deal ||--o{ others : discussion
    deal {
        DATE discussion
        TEXT also
        VARCHAR(50) with
    }
    others ||--o{ dark : you
    others {
        VARCHAR(50) you
        DATE start
    }