erDiagram
    east ||--o{ foot : type
    east {
        DATE type
        TEXT southern
        VARCHAR(50) garden
    }
    foot ||--o{ hotel : institution
    foot {
        VARCHAR(50) institution
        DATE few
    }
    hotel ||--o{ old : try
    hotel {
        DATE try
        TEXT always
        VARCHAR(50) law
    }
    old ||--o{ make : dinner
    old {
        VARCHAR(50) dinner
        DATE simple
    }
    make ||--o{ run : court
    make {
        DATE court
        TEXT especially
        VARCHAR(50) want
    }
    run ||--o{ product : want
    run {
        VARCHAR(50) want
        DATE family
    }
    product ||--o{ share : yeah
    product {
        DATE yeah
        TEXT impact
        VARCHAR(50) answer
    }
    share ||--o{ mouth : main
    share {
        VARCHAR(50) main
        DATE life
    }
    mouth ||--o{ rate : none
    mouth {
        DATE none
        TEXT do
        VARCHAR(50) south
    }
    rate ||--o{ into : sit
    rate {
        VARCHAR(50) sit
        DATE minute
    }
    into ||--o{ east : certainly
    into {
        DATE certainly
        TEXT window
        VARCHAR(50) receive
    }