erDiagram
    first ||--o{ ago : his
    first {
        DATE his
        TEXT safe
        VARCHAR(50) born
    }
    ago ||--o{ PM : his
    ago {
        VARCHAR(50) his
        DATE mission
    }
    PM ||--o{ college : might
    PM {
        DATE might
        TEXT whether
        VARCHAR(50) end
    }
    college ||--o{ room : serious
    college {
        VARCHAR(50) serious
        DATE fine
    }
    room ||--o{ government : consider
    room {
        DATE consider
        TEXT have
        VARCHAR(50) deal
    }
    government ||--o{ enjoy : leave
    government {
        VARCHAR(50) leave
        DATE house
    }
    enjoy ||--o{ learn : right
    enjoy {
        DATE right
        TEXT we
        VARCHAR(50) candidate
    }
    learn ||--o{ first : model
    learn {
        VARCHAR(50) model
        DATE economy
    }