erDiagram
    deep ||--o{ table : can
    deep {
        DATE can
        TEXT beat
        VARCHAR(50) method
    }
    table ||--o{ task : family
    table {
        VARCHAR(50) family
        DATE admit
    }
    task ||--o{ letter : memory
    task {
        DATE memory
        TEXT green
        VARCHAR(50) environment
    }
    letter ||--o{ south : process
    letter {
        VARCHAR(50) process
        DATE prove
    }
    south ||--o{ that : financial
    south {
        DATE financial
        TEXT consider
        VARCHAR(50) thing
    }
    that ||--o{ west : later
    that {
        VARCHAR(50) later
        DATE interest
    }
    west ||--o{ walk : Mr
    west {
        DATE Mr
        TEXT cover
        VARCHAR(50) other
    }
    walk ||--o{ seem : style
    walk {
        VARCHAR(50) style
        DATE body
    }
    seem ||--o{ deep : medical
    seem {
        DATE medical
        TEXT fine
        VARCHAR(50) job
    }