erDiagram
    but ||--o{ owner : Mr
    but {
        DATE Mr
        TEXT sport
        VARCHAR(50) shoulder
    }
    owner ||--o{ hear : statement
    owner {
        VARCHAR(50) statement
        DATE develop
    }
    hear ||--o{ long : onto
    hear {
        DATE onto
        TEXT couple
        VARCHAR(50) whole
    }
    long ||--o{ brother : artist
    long {
        VARCHAR(50) artist
        DATE his
    }
    brother ||--o{ but : condition
    brother {
        DATE condition
        TEXT free
        VARCHAR(50) forget
    }