erDiagram
    that ||--o{ race : have
    that {
        DATE have
        TEXT party
        VARCHAR(50) huge
    }
    race ||--o{ smile : turn
    race {
        VARCHAR(50) turn
        DATE manage
    }
    smile ||--o{ say : hit
    smile {
        DATE hit
        TEXT wind
        VARCHAR(50) develop
    }
    say ||--o{ girl : professor
    say {
        VARCHAR(50) professor
        DATE buy
    }
    girl ||--o{ space : thus
    girl {
        DATE thus
        TEXT analysis
        VARCHAR(50) front
    }
    space ||--o{ before : rise
    space {
        VARCHAR(50) rise
        DATE middle
    }
    before ||--o{ yes : indicate
    before {
        DATE indicate
        TEXT also
        VARCHAR(50) serious
    }
    yes ||--o{ TV : today
    yes {
        VARCHAR(50) today
        DATE position
    }
    TV ||--o{ that : without
    TV {
        DATE without
        TEXT after
        VARCHAR(50) arm
    }