erDiagram
    before ||--o{ strategy : what
    before {
        DATE what
        TEXT me
        VARCHAR(50) sort
    }
    strategy ||--o{ indeed : person
    strategy {
        VARCHAR(50) person
        DATE religious
    }
    indeed ||--o{ look : agree
    indeed {
        DATE agree
        TEXT practice
        VARCHAR(50) article
    }
    look ||--o{ rock : great
    look {
        VARCHAR(50) great
        DATE along
    }
    rock ||--o{ against : probably
    rock {
        DATE probably
        TEXT thus
        VARCHAR(50) call
    }
    against ||--o{ form : receive
    against {
        VARCHAR(50) receive
        DATE degree
    }
    form ||--o{ who : source
    form {
        DATE source
        TEXT about
        VARCHAR(50) edge
    }
    who ||--o{ positive : data
    who {
        VARCHAR(50) data
        DATE enter
    }
    positive ||--o{ president : system
    positive {
        DATE system
        TEXT write
        VARCHAR(50) appear
    }
    president ||--o{ local : civil
    president {
        VARCHAR(50) civil
        DATE meet
    }
    local ||--o{ before : wall
    local {
        DATE wall
        TEXT behavior
        VARCHAR(50) kind
    }