erDiagram
    space ||--o{ respond : believe
    space {
        DATE believe
        TEXT clear
        VARCHAR(50) bring
    }
    respond ||--o{ billion : Mr
    respond {
        VARCHAR(50) Mr
        DATE campaign
    }
    billion ||--o{ significant : test
    billion {
        DATE test
        TEXT human
        VARCHAR(50) exist
    }
    significant ||--o{ both : international
    significant {
        VARCHAR(50) international
        DATE if
    }
    both ||--o{ organization : back
    both {
        DATE back
        TEXT win
        VARCHAR(50) he
    }
    organization ||--o{ black : movie
    organization {
        VARCHAR(50) movie
        DATE class
    }
    black ||--o{ space : so
    black {
        DATE so
        TEXT south
        VARCHAR(50) movie
    }