erDiagram
    degree ||--o{ almost : store
    degree {
        DATE store
        TEXT respond
        VARCHAR(50) onto
    }
    almost ||--o{ successful : military
    almost {
        VARCHAR(50) military
        DATE money
    }
    successful ||--o{ focus : yourself
    successful {
        DATE yourself
        TEXT message
        VARCHAR(50) where
    }
    focus ||--o{ crime : city
    focus {
        VARCHAR(50) city
        DATE always
    }
    crime ||--o{ shake : sea
    crime {
        DATE sea
        TEXT test
        VARCHAR(50) box
    }
    shake ||--o{ certain : left
    shake {
        VARCHAR(50) left
        DATE worker
    }
    certain ||--o{ military : during
    certain {
        DATE during
        TEXT hair
        VARCHAR(50) indicate
    }
    military ||--o{ environment : challenge
    military {
        VARCHAR(50) challenge
        DATE prevent
    }
    environment ||--o{ thought : room
    environment {
        DATE room
        TEXT child
        VARCHAR(50) real
    }
    thought ||--o{ as : people
    thought {
        VARCHAR(50) people
        DATE draw
    }
    as ||--o{ degree : up
    as {
        DATE up
        TEXT section
        VARCHAR(50) home
    }