erDiagram
    color ||--o{ push : only
    color {
        DATE only
        TEXT situation
        VARCHAR(50) citizen
    }
    push ||--o{ all : five
    push {
        VARCHAR(50) five
        DATE science
    }
    all ||--o{ child : ahead
    all {
        DATE ahead
        TEXT learn
        VARCHAR(50) mission
    }
    child ||--o{ discussion : certain
    child {
        VARCHAR(50) certain
        DATE nearly
    }
    discussion ||--o{ outside : deal
    discussion {
        DATE deal
        TEXT home
        VARCHAR(50) throughout
    }
    outside ||--o{ born : resource
    outside {
        VARCHAR(50) resource
        DATE administration
    }
    born ||--o{ century : without
    born {
        DATE without
        TEXT you
        VARCHAR(50) treatment
    }
    century ||--o{ it : example
    century {
        VARCHAR(50) example
        DATE financial
    }
    it ||--o{ town : hundred
    it {
        DATE hundred
        TEXT other
        VARCHAR(50) risk
    }
    town ||--o{ evening : first
    town {
        VARCHAR(50) first
        DATE full
    }
    evening ||--o{ sometimes : enjoy
    evening {
        DATE enjoy
        TEXT well
        VARCHAR(50) exactly
    }
    sometimes ||--o{ color : live
    sometimes {
        VARCHAR(50) live
        DATE today
    }