erDiagram
    site ||--o{ thank : social
    site {
        DATE social
        TEXT possible
        VARCHAR(50) candidate
    }
    thank ||--o{ arrive : military
    thank {
        VARCHAR(50) military
        DATE one
    }
    arrive ||--o{ your : too
    arrive {
        DATE too
        TEXT voice
        VARCHAR(50) agent
    }
    your ||--o{ few : see
    your {
        VARCHAR(50) see
        DATE message
    }
    few ||--o{ drive : concern
    few {
        DATE concern
        TEXT campaign
        VARCHAR(50) avoid
    }
    drive ||--o{ ten : defense
    drive {
        VARCHAR(50) defense
        DATE gas
    }
    ten ||--o{ site : different
    ten {
        DATE different
        TEXT Mrs
        VARCHAR(50) rate
    }