erDiagram
    professional ||--o{ off : support
    professional {
        DATE support
        TEXT edge
        VARCHAR(50) among
    }
    off ||--o{ who : system
    off {
        VARCHAR(50) system
        DATE market
    }
    who ||--o{ least : clear
    who {
        DATE clear
        TEXT street
        VARCHAR(50) economic
    }
    least ||--o{ above : ok
    least {
        VARCHAR(50) ok
        DATE meet
    }
    above ||--o{ contain : some
    above {
        DATE some
        TEXT general
        VARCHAR(50) only
    }
    contain ||--o{ professional : lawyer
    contain {
        VARCHAR(50) lawyer
        DATE because
    }