erDiagram
    social ||--o{ need : cut
    social {
        DATE cut
        TEXT international
        VARCHAR(50) possible
    }
    need ||--o{ develop : environment
    need {
        VARCHAR(50) environment
        DATE media
    }
    develop ||--o{ main : according
    develop {
        DATE according
        TEXT east
        VARCHAR(50) short
    }
    main ||--o{ upon : up
    main {
        VARCHAR(50) up
        DATE own
    }
    upon ||--o{ social : letter
    upon {
        DATE letter
        TEXT buy
        VARCHAR(50) pattern
    }