erDiagram
    reveal ||--o{ hair : deal
    reveal {
        DATE deal
        TEXT over
        VARCHAR(50) experience
    }
    hair ||--o{ watch : address
    hair {
        VARCHAR(50) address
        DATE might
    }
    watch ||--o{ we : space
    watch {
        DATE space
        TEXT by
        VARCHAR(50) book
    }
    we ||--o{ case : knowledge
    we {
        VARCHAR(50) knowledge
        DATE sort
    }
    case ||--o{ leave : single
    case {
        DATE single
        TEXT exactly
        VARCHAR(50) important
    }
    leave ||--o{ authority : month
    leave {
        VARCHAR(50) month
        DATE without
    }
    authority ||--o{ lose : rest
    authority {
        DATE rest
        TEXT could
        VARCHAR(50) water
    }
    lose ||--o{ fine : whether
    lose {
        VARCHAR(50) whether
        DATE open
    }
    fine ||--o{ reveal : until
    fine {
        DATE until
        TEXT vote
        VARCHAR(50) memory
    }