erDiagram
    social ||--o{ today : letter
    social {
        DATE letter
        TEXT season
        VARCHAR(50) car
    }
    today ||--o{ also : hot
    today {
        VARCHAR(50) hot
    }
    also ||--o{ blood : pattern
    also {
        DATE pattern
        TEXT himself
        VARCHAR(50) find
    }
    blood ||--o{ hope : debate
    blood {
        VARCHAR(50) debate
        DATE group
    }
    hope ||--o{ woman : lot
    hope {
        DATE lot
        TEXT already
        VARCHAR(50) various
    }
    woman ||--o{ blue : floor
    woman {
        VARCHAR(50) floor
        DATE set
    }
    blue ||--o{ sport : continue
    blue {
        DATE continue
        TEXT nearly
        VARCHAR(50) catch
    }
    sport ||--o{ marriage : animal
    sport {
        VARCHAR(50) animal
        DATE religious
    }
    marriage ||--o{ outside : itself
    marriage {
        DATE itself
        TEXT unit
        VARCHAR(50) people
    }
    outside ||--o{ social : assume
    outside {
        VARCHAR(50) assume
        DATE feeling
    }