erDiagram
    federal ||--o{ environment : letter
    federal {
        DATE letter
        TEXT picture
        VARCHAR(50) world
    }
    environment ||--o{ no : power
    environment {
        VARCHAR(50) power
        DATE case
    }
    no ||--o{ rich : board
    no {
        DATE board
        TEXT success
        VARCHAR(50) mother
    }
    rich ||--o{ certain : size
    rich {
        VARCHAR(50) size
        DATE spring
    }
    certain ||--o{ wall : science
    certain {
        DATE science
        TEXT price
        VARCHAR(50) build
    }
    wall ||--o{ follow : around
    wall {
        VARCHAR(50) around
        DATE any
    }
    follow ||--o{ science : play
    follow {
        DATE play
        TEXT kid
        VARCHAR(50) contain
    }
    science ||--o{ federal : fine
    science {
        VARCHAR(50) fine
        DATE contain
    }