erDiagram
    keep ||--o{ win : certain
    keep {
        DATE certain
        TEXT recently
        VARCHAR(50) think
    }
    win ||--o{ condition : wife
    win {
        VARCHAR(50) wife
        DATE stand
    }
    condition ||--o{ most : rest
    condition {
        DATE rest
        TEXT number
        VARCHAR(50) conference
    }
    most ||--o{ imagine : be
    most {
        VARCHAR(50) be
        DATE sit
    }
    imagine ||--o{ somebody : goal
    imagine {
        DATE goal
        TEXT little
        VARCHAR(50) prevent
    }
    somebody ||--o{ mouth : nation
    somebody {
        VARCHAR(50) nation
        DATE increase
    }
    mouth ||--o{ little : interesting
    mouth {
        DATE interesting
        TEXT pressure
        VARCHAR(50) today
    }
    little ||--o{ easy : produce
    little {
        VARCHAR(50) produce
        DATE young
    }
    easy ||--o{ keep : professional
    easy {
        DATE professional
        TEXT for
        VARCHAR(50) large
    }