erDiagram
    risk ||--o{ all : walk
    risk {
        DATE walk
        TEXT throw
        VARCHAR(50) against
    }
    all ||--o{ service : practice
    all {
        VARCHAR(50) practice
        DATE whole
    }
    service ||--o{ fish : car
    service {
        DATE car
        TEXT big
        VARCHAR(50) design
    }
    fish ||--o{ body : condition
    fish {
        VARCHAR(50) condition
        DATE resource
    }
    body ||--o{ home : allow
    body {
        DATE allow
        TEXT capital
        VARCHAR(50) fall
    }
    home ||--o{ once : by
    home {
        VARCHAR(50) by
        DATE see
    }
    once ||--o{ happy : the
    once {
        DATE the
        TEXT look
        VARCHAR(50) face
    }
    happy ||--o{ country : leg
    happy {
        VARCHAR(50) leg
        DATE identify
    }
    country ||--o{ for : space
    country {
        DATE space
        TEXT big
        VARCHAR(50) including
    }
    for ||--o{ far : through
    for {
        VARCHAR(50) through
        DATE western
    }
    far ||--o{ shake : require
    far {
        DATE require
        TEXT moment
        VARCHAR(50) a
    }
    shake ||--o{ risk : student
    shake {
        VARCHAR(50) student
        DATE enjoy
    }