erDiagram
    somebody ||--o{ send : current
    somebody {
        DATE current
        TEXT course
        VARCHAR(50) than
    }
    send ||--o{ sea : product
    send {
        VARCHAR(50) product
        DATE appear
    }
    sea ||--o{ feel : despite
    sea {
        DATE despite
        TEXT suggest
        VARCHAR(50) new
    }
    feel ||--o{ fish : role
    feel {
        VARCHAR(50) role
        DATE watch
    }
    fish ||--o{ somebody : describe
    fish {
        DATE describe
        TEXT well
        VARCHAR(50) land
    }