erDiagram
    morning ||--o{ watch : high
    morning {
        DATE high
        TEXT whose
        VARCHAR(50) beautiful
    }
    watch ||--o{ author : crime
    watch {
        VARCHAR(50) crime
        DATE stage
    }
    author ||--o{ thousand : point
    author {
        DATE point
        TEXT anyone
        VARCHAR(50) might
    }
    thousand ||--o{ media : lawyer
    thousand {
        VARCHAR(50) lawyer
        DATE yet
    }
    media ||--o{ speak : north
    media {
        DATE north
        TEXT deep
        VARCHAR(50) sign
    }
    speak ||--o{ different : executive
    speak {
        VARCHAR(50) executive
        DATE single
    }
    different ||--o{ this : next
    different {
        DATE next
        TEXT build
        VARCHAR(50) assume
    }
    this ||--o{ morning : place
    this {
        VARCHAR(50) place
        DATE treatment
    }