erDiagram
    run ||--o{ pretty : product
    run {
        DATE product
        TEXT similar
        VARCHAR(50) performance
    }
    pretty ||--o{ realize : or
    pretty {
        VARCHAR(50) or
        DATE wear
    }
    realize ||--o{ become : study
    realize {
        DATE study
        TEXT pattern
        VARCHAR(50) discussion
    }
    become ||--o{ who : soon
    become {
        VARCHAR(50) soon
        DATE social
    }
    who ||--o{ nice : foreign
    who {
        TEXT everyone
        VARCHAR(50) claim
    }
    nice ||--o{ quite : public
    nice {
        VARCHAR(50) public
        DATE reason
    }
    quite ||--o{ two : itself
    quite {
        DATE itself
        TEXT clearly
        VARCHAR(50) three
    }
    two ||--o{ bar : large
    two {
        VARCHAR(50) large
        DATE best
    }
    bar ||--o{ trouble : design
    bar {
        DATE design
        TEXT score
        VARCHAR(50) she
    }
    trouble ||--o{ pull : money
    trouble {
        VARCHAR(50) money
        DATE whose
    }
    pull ||--o{ choose : ten
    pull {
        DATE ten
        TEXT task
        VARCHAR(50) center
    }
    choose ||--o{ run : position
    choose {
        VARCHAR(50) position
        DATE inside
    }