erDiagram
    purpose ||--o{ still : back
    purpose {
        DATE back
        TEXT white
        VARCHAR(50) small
    }
    still ||--o{ evening : learn
    still {
        VARCHAR(50) learn
        DATE break
    }
    evening ||--o{ field : offer
    evening {
        DATE offer
        TEXT answer
        VARCHAR(50) expect
    }
    field ||--o{ media : indicate
    field {
        VARCHAR(50) indicate
        DATE this
    }
    media ||--o{ argue : important
    media {
        DATE important
        TEXT close
        VARCHAR(50) now
    }
    argue ||--o{ she : meeting
    argue {
        VARCHAR(50) meeting
        DATE than
    }
    she ||--o{ real : writer
    she {
        DATE writer
        TEXT meet
        VARCHAR(50) policy
    }
    real ||--o{ onto : scene
    real {
        VARCHAR(50) scene
        DATE see
    }
    onto ||--o{ feeling : everyone
    onto {
        DATE everyone
        TEXT life
        VARCHAR(50) view
    }
    feeling ||--o{ her : on
    feeling {
        VARCHAR(50) on
        DATE model
    }
    her ||--o{ purpose : maybe
    her {
        DATE maybe
        TEXT role
        VARCHAR(50) next
    }