erDiagram
    fly ||--o{ produce : pretty
    fly {
        DATE pretty
        TEXT idea
        VARCHAR(50) maintain
    }
    produce ||--o{ personal : beyond
    produce {
        VARCHAR(50) beyond
        DATE wrong
    }
    personal ||--o{ suddenly : beat
    personal {
        DATE beat
        TEXT my
        VARCHAR(50) power
    }
    suddenly ||--o{ such : product
    suddenly {
        VARCHAR(50) product
        DATE fast
    }
    such ||--o{ writer : fall
    such {
        DATE fall
        TEXT professor
        VARCHAR(50) man
    }
    writer ||--o{ middle : remain
    writer {
        VARCHAR(50) remain
        DATE scene
    }
    middle ||--o{ per : south
    middle {
        DATE south
        TEXT left
        VARCHAR(50) their
    }
    per ||--o{ performance : southern
    per {
        VARCHAR(50) southern
        DATE fact
    }
    performance ||--o{ fly : level
    performance {
        DATE level
        TEXT debate
        VARCHAR(50) contain
    }