erDiagram
    staff ||--o{ everything : learn
    staff {
        DATE learn
        TEXT usually
        VARCHAR(50) rock
    }
    everything ||--o{ meet : answer
    everything {
        VARCHAR(50) answer
        DATE however
    }
    meet ||--o{ power : game
    meet {
        DATE game
        TEXT south
        VARCHAR(50) dream
    }
    power ||--o{ gun : save
    power {
        VARCHAR(50) save
        DATE listen
    }
    gun ||--o{ somebody : reason
    gun {
        DATE reason
        TEXT minute
        VARCHAR(50) many
    }
    somebody ||--o{ rule : our
    somebody {
        VARCHAR(50) our
        DATE war
    }
    rule ||--o{ cell : under
    rule {
        DATE under
        TEXT politics
        VARCHAR(50) huge
    }
    cell ||--o{ inside : dinner
    cell {
        VARCHAR(50) dinner
        DATE rich
    }
    inside ||--o{ measure : trouble
    inside {
        DATE trouble
        TEXT country
        VARCHAR(50) outside
    }
    measure ||--o{ staff : social
    measure {
        VARCHAR(50) social
        DATE although
    }