erDiagram
    relationship ||--o{ international : try
    relationship {
        DATE try
        TEXT white
        VARCHAR(50) often
    }
    international ||--o{ project : song
    international {
        VARCHAR(50) song
        DATE forget
    }
    project ||--o{ college : by
    project {
        DATE by
        TEXT idea
        VARCHAR(50) others
    }
    college ||--o{ drug : early
    college {
        VARCHAR(50) early
        DATE authority
    }
    drug ||--o{ garden : off
    drug {
        DATE off
        TEXT such
        VARCHAR(50) court
    }
    garden ||--o{ box : within
    garden {
        VARCHAR(50) within
        DATE exactly
    }
    box ||--o{ relationship : analysis
    box {
        DATE analysis
        TEXT professor
        VARCHAR(50) PM
    }