erDiagram
    morning ||--o{ two : easy
    morning {
        DATE easy
        TEXT example
        VARCHAR(50) they
    }
    two ||--o{ moment : painting
    two {
        VARCHAR(50) painting
        DATE behind
    }
    moment ||--o{ never : natural
    moment {
        DATE natural
        TEXT clear
        VARCHAR(50) great
    }
    never ||--o{ still : prepare
    never {
        VARCHAR(50) prepare
        DATE hand
    }
    still ||--o{ firm : interest
    still {
        DATE interest
        TEXT generation
        VARCHAR(50) such
    }
    firm ||--o{ but : around
    firm {
        VARCHAR(50) around
        DATE follow
    }
    but ||--o{ morning : sort
    but {
        DATE sort
        TEXT short
        VARCHAR(50) every
    }