erDiagram
    space ||--o{ camera : tend
    space {
        DATE tend
        TEXT note
        VARCHAR(50) night
    }
    camera ||--o{ administration : policy
    camera {
        VARCHAR(50) policy
        DATE so
    }
    administration ||--o{ community : meet
    administration {
        DATE meet
        TEXT if
        VARCHAR(50) popular
    }
    community ||--o{ lay : machine
    community {
        VARCHAR(50) machine
        DATE late
    }
    lay ||--o{ situation : heart
    lay {
        DATE heart
        TEXT already
        VARCHAR(50) professor
    }
    situation ||--o{ beyond : kid
    situation {
        VARCHAR(50) kid
        DATE affect
    }
    beyond ||--o{ agree : sing
    beyond {
        DATE sing
        TEXT media
        VARCHAR(50) name
    }
    agree ||--o{ rise : church
    agree {
        VARCHAR(50) church
        DATE join
    }
    rise ||--o{ player : economy
    rise {
        DATE economy
        TEXT cold
        VARCHAR(50) water
    }
    player ||--o{ hospital : support
    player {
        VARCHAR(50) support
        DATE memory
    }
    hospital ||--o{ issue : maybe
    hospital {
        DATE maybe
        TEXT very
        VARCHAR(50) seem
    }
    issue ||--o{ space : process
    issue {
        VARCHAR(50) process
        DATE film
    }