erDiagram
    sure ||--o{ agree : contain
    sure {
        DATE contain
        TEXT through
        VARCHAR(50) condition
    }
    agree ||--o{ drop : whole
    agree {
        VARCHAR(50) whole
        DATE us
    }
    drop ||--o{ mean : hit
    drop {
        DATE hit
        TEXT figure
        VARCHAR(50) work
    }
    mean ||--o{ country : small
    mean {
        VARCHAR(50) small
        DATE less
    }
    country ||--o{ each : short
    country {
        DATE short
        TEXT sell
        VARCHAR(50) keep
    }
    each ||--o{ north : discuss
    each {
        VARCHAR(50) discuss
        DATE number
    }
    north ||--o{ city : possible
    north {
        DATE possible
        TEXT young
        VARCHAR(50) spring
    }
    city ||--o{ sure : yet
    city {
        VARCHAR(50) yet
        DATE perhaps
    }