erDiagram
    show ||--o{ better : consider
    show {
        DATE consider
        TEXT value
        VARCHAR(50) artist
    }
    better ||--o{ author : culture
    better {
        VARCHAR(50) culture
        DATE suggest
    }
    author ||--o{ light : from
    author {
        DATE from
        TEXT board
        VARCHAR(50) side
    }
    light ||--o{ measure : under
    light {
        VARCHAR(50) under
        DATE citizen
    }
    measure ||--o{ yard : save
    measure {
        DATE save
        TEXT already
        VARCHAR(50) whose
    }
    yard ||--o{ company : position
    yard {
        VARCHAR(50) position
        DATE reduce
    }
    company ||--o{ way : I
    company {
        DATE I
        TEXT property
        VARCHAR(50) available
    }
    way ||--o{ not : even
    way {
        VARCHAR(50) even
        DATE quickly
    }
    not ||--o{ show : city
    not {
        DATE city
        TEXT election
        VARCHAR(50) research
    }