erDiagram
    center ||--o{ machine : education
    center {
        DATE education
        TEXT western
        VARCHAR(50) indeed
    }
    machine ||--o{ leg : take
    machine {
        VARCHAR(50) take
        DATE serious
    }
    leg ||--o{ five : cup
    leg {
        DATE cup
        TEXT industry
        VARCHAR(50) side
    }
    five ||--o{ fight : somebody
    five {
        VARCHAR(50) somebody
        DATE lawyer
    }
    fight ||--o{ structure : close
    fight {
        DATE close
        TEXT accept
        VARCHAR(50) base
    }
    structure ||--o{ center : interesting
    structure {
        VARCHAR(50) interesting
        DATE themselves
    }