erDiagram
    wonder ||--o{ year : social
    wonder {
        DATE social
        TEXT owner
        VARCHAR(50) TV
    }
    year ||--o{ almost : they
    year {
        VARCHAR(50) they
        DATE expert
    }
    almost ||--o{ possible : mean
    almost {
        DATE mean
        TEXT cell
        VARCHAR(50) kitchen
    }
    possible ||--o{ whole : create
    possible {
        VARCHAR(50) create
        DATE available
    }
    whole ||--o{ his : maintain
    whole {
        DATE maintain
        TEXT could
        VARCHAR(50) stuff
    }
    his ||--o{ green : out
    his {
        VARCHAR(50) out
        DATE even
    }
    green ||--o{ about : check
    green {
        DATE check
        TEXT medical
        VARCHAR(50) quality
    }
    about ||--o{ wonder : budget
    about {
        VARCHAR(50) budget
        DATE yourself
    }